'use client'

// The Lumio starter resource library — drills, technique work, plans, fitness,
// mental worksheets and reading, tagged to the racket system.
//
// Written to the Lumio Coach standard (see src/lib/coach/agent-persona.ts): every
// description DIAGNOSES rather than describes. It names the fault the resource
// fixes, why that fault matters and what it costs the player — not "work on your
// forehand". If a description would be true of any player at any stage, it is
// wrong and should be rewritten.
//
// Coverage is deliberate: at least 10 resources per racket colour AND at least 10
// per category, so no filter in the Resource Centre ever lands on an empty grid.
//
// Formats are weighted towards printable material (PDF / Plan / Worksheet) rather
// than Video. A video card with no video is a promise the product does not keep;
// a drill card prints and goes on court. `url: 'lumio:<slug>'` marks a resource
// with real printable content — see resource-printables.ts. External http(s) URLs
// still open in a new tab as before.
//
// Columns match coach_resources: title, category, format, level, duration,
// racket, tags, url, notes(description).

import { sb, currentCoachId } from './coach-db'

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`
const p = (slug: string) => `lumio:${slug}`

export const LUMIO_RESOURCES: Record<string, any>[] = [
  // ─── WHITE — first racket. Contact, tracking, and simply making the ball. ───
  { title: 'Split-step & first-move reaction', category: 'Drill', level: 'Beginner', format: 'Video', duration: '4 min', racket: 'white', tags: 'movement, warm-up', notes: 'Players who arrive late to the ball are usually late leaving the last one. Trains the split-step to land as the opponent strikes.', url: yt('J1UhPl1UrYs') },
  { title: 'Catch, drop, hit — contact point card', category: 'Drill', level: 'Beginner', format: 'PDF', duration: '12 min', racket: 'white', tags: 'contact, foundation', notes: 'Beginners meet the ball behind the hip, so the racket face closes and the ball dumps into the net. Fixes contact point out in front.', url: p('white-catch-drop-hit') },
  { title: 'Ten-in-a-row rally ladder', category: 'Drill', level: 'Beginner', format: 'PDF', duration: '15 min', racket: 'white', tags: 'consistency, rally', notes: 'Rallies end at two or three shots because the player plays every ball as a winner. Builds tolerance before power.', url: p('white-rally-ladder') },
  { title: 'Ready position & racket carry', category: 'Technique', level: 'Beginner', format: 'PDF', duration: '10 min', racket: 'white', tags: 'ready, foundation', notes: 'A racket carried low and one-handed costs the unit turn before the ball has bounced. Sets the hands, height and grip that make everything else possible.', url: p('white-ready-position') },
  { title: 'Continental grip: the one grip that lasts', category: 'Technique', level: 'Beginner', format: 'PDF', duration: '8 min', racket: 'white', tags: 'grip, serve, volley', notes: 'A frying-pan grip works for six months and then blocks the serve and every volley. Establish continental now and it never has to be unlearned.', url: p('white-continental-grip') },
  { title: 'First 6 weeks — White racket block', category: 'Training plan', level: 'Beginner', format: 'Plan', duration: '6 weeks', racket: 'white', tags: 'periodisation, foundation', notes: 'Six sessions that take a complete beginner from feeding to a ten-ball rally, with the White racket criteria as the exit test.', url: p('white-6-week-block') },
  { title: 'Balance & landing basics', category: 'Fitness', level: 'Beginner', format: 'PDF', duration: '10 min', racket: 'white', tags: 'balance, movement', notes: 'Players who fall away from the shot cannot recover for the next one. Off-court landing and balance work that transfers straight to the baseline.', url: p('white-balance-basics') },
  { title: 'I can do this now — confidence card', category: 'Mental', level: 'Beginner', format: 'Worksheet', duration: null, racket: 'white', tags: 'confidence, juniors', notes: 'Beginners quit when they only notice misses. A weekly card that makes progress visible to the player and to the parent reading it.', url: p('white-confidence-card') },
  { title: 'Parent guide: the ball-colour pathway', category: 'Books', level: 'Beginner', format: 'PDF', duration: null, racket: 'white', tags: 'parents, red-orange-green', notes: 'Parents push to yellow ball too early because nobody explained why the balls are different. Explains the pathway in plain language.', url: p('parent-ball-pathway') },
  { title: 'Mini-tennis games pack', category: 'Drill', level: 'Beginner', format: 'PDF', duration: '20 min', racket: 'white', tags: 'games, juniors', notes: 'Beginners lose focus when a session is all feeding. Eight scoring games that teach tracking and contact while looking like play.', url: p('white-mini-games') },

  // ─── YELLOW — the rally starts to hold. Depth, direction, and shape. ───
  { title: 'Two-handed backhand fundamentals', category: 'Technique', level: 'Beginner', format: 'PDF', duration: '12 min', racket: 'yellow', tags: 'backhand, technique', notes: 'A backhand steered with the arms alone has no margin and no depth. Builds grip, unit turn and a contact point in front of the front hip.', url: p('yellow-two-hander') },
  { title: 'Cross-court rally targets', category: 'Drill', level: 'All levels', format: 'PDF', duration: '20 min', racket: 'yellow', tags: 'consistency, rally', notes: 'Balls land short and central, which invites the opponent in. Printable court targets that force depth and cross-court shape.', url: p('yellow-crosscourt-targets') },
  { title: 'Net clearance & the one-metre window', category: 'Drill', level: 'Beginner', format: 'PDF', duration: '15 min', racket: 'yellow', tags: 'margin, consistency', notes: 'Most unforced errors at this stage are net errors, not long ones. Trains a metre of clearance as the default, not a safety option.', url: p('yellow-net-clearance') },
  { title: 'Recover to the middle — the T drill', category: 'Drill', level: 'Beginner', format: 'PDF', duration: '15 min', racket: 'yellow', tags: 'movement, recovery', notes: 'Players admire the shot they just hit and get wrong-footed by the reply. Makes recovery automatic rather than an afterthought.', url: p('yellow-recovery-t') },
  { title: 'Adult improver — 8-session plan', category: 'Training plan', level: 'Intermediate', format: 'Plan', duration: '8 weeks', racket: 'yellow', tags: 'adults, technique', notes: 'Returning adults have a serviceable forehand and nothing else. Eight sessions that build a backhand, a serve and a reason to come back.', url: p('yellow-adult-8-session') },
  { title: 'Serve: throw the racket, not the ball', category: 'Technique', level: 'Beginner', format: 'PDF', duration: '12 min', racket: 'yellow', tags: 'serve, technique', notes: 'A serve pushed with a stiff arm caps out and hurts the shoulder. Builds the throwing action first and the toss around it.', url: p('yellow-serve-throw') },
  { title: 'Dynamic warm-up routine', category: 'Fitness', level: 'All levels', format: 'PDF', duration: '10 min', racket: 'yellow', tags: 'warm-up, mobility', notes: 'Cold players hit late for the first twenty minutes and call it a bad day. A ten-minute on-court warm-up that makes minute one usable.', url: p('warmup-dynamic') },
  { title: 'Between-points routine — starter card', category: 'Mental', level: 'Beginner', format: 'Worksheet', duration: null, racket: 'yellow', tags: 'routines, focus', notes: 'One bad point becomes three because nothing separates them. A four-step routine simple enough for a junior to actually use.', url: p('yellow-between-points') },
  { title: 'Scoring & etiquette cheat sheet', category: 'Books', level: 'Beginner', format: 'PDF', duration: null, racket: 'yellow', tags: 'rules, parents', notes: 'Players avoid entering competitions because they are unsure of scoring or calls. One page that removes the excuse.', url: p('yellow-scoring-sheet') },
  { title: 'First competition — what to expect', category: 'Mental', level: 'Beginner', format: 'Worksheet', duration: null, racket: 'yellow', tags: 'competition, parents', notes: 'A first match is lost in the car park, not on court. Prepares player and parent for the day so nerves are normal rather than a surprise.', url: p('yellow-first-comp') },

  // ─── ORANGE — patterns begin. Playing to a plan rather than to the ball. ───
  { title: 'Net play & volley progression', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '18 min', racket: 'orange', tags: 'volley, net', notes: 'Players swing at volleys because they treat them as short groundstrokes. A feed sequence from block volley to closing the net.', url: p('orange-volley-progression') },
  { title: '6-week Orange-racket block', category: 'Training plan', level: 'Beginner', format: 'Plan', duration: '6 weeks', racket: 'orange', tags: 'periodisation, beginner', notes: 'Structured block against the Orange racket criteria, so the award is earned on evidence rather than time served.', url: p('orange-6-week-block') },
  { title: 'Two-shot patterns: wide then middle', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '20 min', racket: 'orange', tags: 'patterns, tactics', notes: 'Players hit good shots in no particular order and wonder why points do not go anywhere. Introduces the first deliberate pattern.', url: p('orange-two-shot-patterns') },
  { title: 'Approach & first volley', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '18 min', racket: 'orange', tags: 'transition, net', notes: 'Approaches float and get passed because the player stops running. Links the approach, the split and the first volley into one movement.', url: p('orange-approach-volley') },
  { title: 'Forehand: unit turn before the bounce', category: 'Technique', level: 'Beginner', format: 'PDF', duration: '12 min', racket: 'orange', tags: 'forehand, preparation', notes: 'Late preparation shows up as a jammed contact point and an arm-only swing. Trains the turn to happen before the ball bounces.', url: p('orange-unit-turn') },
  { title: 'Serve targets: body, wide, T', category: 'Technique', level: 'Intermediate', format: 'PDF', duration: '15 min', racket: 'orange', tags: 'serve, placement', notes: 'A serve aimed only at the box is a serve the returner never fears. Three targets and how to practise them under a score.', url: p('orange-serve-targets') },
  { title: 'Speed & agility ladder set', category: 'Fitness', level: 'All levels', format: 'PDF', duration: '15 min', racket: 'orange', tags: 'movement, warm-up', notes: 'Split-steps are late because feet are slow, not because the player is unfit. Off-court ladder routine for first-step speed.', url: p('orange-agility-ladder') },
  { title: 'Effort over outcome — scoring card', category: 'Mental', level: 'Beginner', format: 'Worksheet', duration: null, racket: 'orange', tags: 'mindset, juniors', notes: 'Juniors judge a match only by the result and learn nothing from a good loss. Scores the things the player controls.', url: p('orange-effort-card') },
  { title: 'Practice at home — 15 minutes a day', category: 'Books', level: 'Beginner', format: 'PDF', duration: null, racket: 'orange', tags: 'parents, practice', notes: 'Parents ask what to do between lessons and get told "keep practising". Fifteen minutes of specific work needing a wall and a ball.', url: p('orange-home-practice') },
  { title: 'Doubles basics: who covers what', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '20 min', racket: 'orange', tags: 'doubles, positioning', notes: 'Club doubles is two players watching one ball. Establishes starting positions and whose ball it is before anything tactical.', url: p('orange-doubles-basics') },

  // ─── GREEN — the transition to the full court. Shape, spin and depth. ───
  { title: 'Low-to-high topspin forehand', category: 'Technique', level: 'Intermediate', format: 'Video', duration: '7 min', racket: 'green', tags: 'forehand, spin', notes: 'Flat hitting that works on a green ball starts flying long on a yellow one. Builds the swing path that turns pace into margin.', url: yt('KV9DTSNkLAg') },
  { title: 'Flat serve mechanics & toss', category: 'Technique', level: 'Intermediate', format: 'PDF', duration: '15 min', racket: 'green', tags: 'serve, technique', notes: 'An inconsistent toss forces a different serve every time and no fault is ever fixable. Trophy position, toss window and racket-drop timing.', url: p('green-serve-mechanics') },
  { title: '8-week Green-racket block', category: 'Training plan', level: 'Intermediate', format: 'Plan', duration: '8 weeks', racket: 'green', tags: 'serve, periodisation', notes: 'Periodised block against the Green racket serve criteria, with a measurable exit test rather than a coach\u2019s impression.', url: p('green-8-week-block') },
  { title: 'Depth control: the three-zone drill', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '20 min', racket: 'green', tags: 'depth, consistency', notes: 'Short balls invite attack, and at this stage opponents finally punish them. Trains landing zones the player can name and hit on demand.', url: p('green-three-zone') },
  { title: 'Rally tolerance: play to twelve', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '20 min', racket: 'green', tags: 'consistency, tolerance', notes: 'Players go for the winner on ball four because they have never been asked to hit ball twelve. Extends tolerance under a score.', url: p('green-play-to-twelve') },
  { title: 'Return of serve: two positions', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '18 min', racket: 'green', tags: 'return, positioning', notes: 'Returners stand in one spot and let the server dictate. Teaches a deep position and a stepped-in position, and when to use each.', url: p('green-return-positions') },
  { title: 'Endurance intervals for match play', category: 'Fitness', level: 'Intermediate', format: 'PDF', duration: '20 min', racket: 'green', tags: 'conditioning, speed', notes: 'Level drops in the third set because training never went past twenty minutes. Tennis-specific intervals matched to point length.', url: p('green-endurance-intervals') },
  { title: 'Goal-setting & review sheet', category: 'Mental', level: 'All levels', format: 'Worksheet', duration: null, racket: 'green', tags: 'goals, review', notes: 'Players train hard with no idea what they are training towards. Termly goals split into technical, tactical, physical and mental.', url: p('green-goal-setting') },
  { title: 'Understanding the LTA Youth pathway', category: 'Books', level: 'Intermediate', format: 'PDF', duration: null, racket: 'green', tags: 'pathway, parents', notes: 'Families make decisions about competition and coaching without knowing how the pathway fits together. Explains it in one read.', url: p('green-lta-pathway') },
  { title: 'Serve+1: the first pattern', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '18 min', racket: 'green', tags: 'patterns, serve', notes: 'A good serve is wasted when the next ball has no plan. Links the serve to a pre-decided first groundstroke.', url: p('green-serve-plus-one') },

  // ─── BLUE — the full court and a game style beginning to show. ───
  { title: 'Slice backhand: stay low & carve', category: 'Technique', level: 'Intermediate', format: 'PDF', duration: '14 min', racket: 'blue', tags: 'backhand, slice', notes: 'Players with one backhand have one answer to every ball. Adds a slice that defends, approaches and changes rhythm.', url: p('blue-slice-backhand') },
  { title: 'Inside-out forehand set-up', category: 'Technique', level: 'Intermediate', format: 'PDF', duration: '15 min', racket: 'blue', tags: 'forehand, patterns', notes: 'Running around the backhand achieves nothing if the forehand then goes cross-court. Trains the footwork and the target together.', url: p('blue-inside-out') },
  { title: 'Neutral, attack, defend — ball reading', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '22 min', racket: 'blue', tags: 'tactics, decisions', notes: 'Errors here are decision errors, not stroke errors: attacking a defensive ball. Trains reading the ball before choosing the shot.', url: p('blue-ball-reading') },
  { title: 'Second serve under pressure', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '18 min', racket: 'blue', tags: 'serve, pressure', notes: 'A second serve practised without consequence collapses at 30-40. Adds spin, target and a score so the pressure is real.', url: p('blue-second-serve') },
  { title: 'Passing shots & the low first ball', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '18 min', racket: 'blue', tags: 'passing, transition', notes: 'Players panic when an opponent comes in and go for a winner from a poor position. Builds the dipping ball at the feet as the default.', url: p('blue-passing-shots') },
  { title: '10-week Blue-racket development block', category: 'Training plan', level: 'Intermediate', format: 'Plan', duration: '10 weeks', racket: 'blue', tags: 'periodisation, tactics', notes: 'Ten weeks that move a player from hitting well to competing well, with tactical outcomes as the exit test.', url: p('blue-10-week-block') },
  { title: 'Core & rotational power circuit', category: 'Fitness', level: 'Advanced', format: 'PDF', duration: '25 min', racket: 'blue', tags: 'strength, power', notes: 'Racket-head speed generated by the arm alone stalls and injures. Med-ball and core work that builds it from the ground up.', url: p('blue-core-power') },
  { title: 'Pre-match focus routine', category: 'Mental', level: 'Intermediate', format: 'Worksheet', duration: null, racket: 'blue', tags: 'routines, focus', notes: 'Players arrive on court still thinking about the journey and lose the first three games. A routine that starts before the warm-up.', url: p('blue-prematch-routine') },
  { title: 'The Inner Game of Tennis — reading notes', category: 'Books', level: 'All levels', format: 'PDF', duration: null, racket: 'blue', tags: 'mental, reading', notes: 'The foundational text on the mental side, condensed into what a coach can actually use on court this week.', url: p('blue-inner-game-notes') },
  { title: 'Playing the big points — patterns card', category: 'Mental', level: 'Intermediate', format: 'Worksheet', duration: null, racket: 'blue', tags: 'pressure, tactics', notes: 'Under pressure players either freeze or over-hit. Pre-decides the pattern for 30-30, break point and set point.', url: p('blue-big-points') },

  // ─── PURPLE — variety and specialty. Beating opponents who match you. ───
  { title: 'Drop shot & touch session', category: 'Technique', level: 'Intermediate', format: 'PDF', duration: '15 min', racket: 'purple', tags: 'touch, specialty', notes: 'Drop shots sit up because the hand tightens at contact. Builds disguise, grip pressure and the recovery step that follows.', url: p('purple-drop-shot') },
  { title: 'Lob & overhead exchange', category: 'Drill', level: 'Intermediate', format: 'PDF', duration: '18 min', racket: 'purple', tags: 'lob, overhead', notes: 'Players lob only in desperation and smash only badly. Trains both ends of the exchange as a deliberate tactic.', url: p('purple-lob-overhead') },
  { title: 'Changing the height of the ball', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '20 min', racket: 'purple', tags: 'variety, tactics', notes: 'One-speed players are read by ball three. Trains heavy, flat and low as choices rather than accidents.', url: p('purple-height-variety') },
  { title: 'Kick serve in 5 steps', category: 'Technique', level: 'Advanced', format: 'PDF', duration: '18 min', racket: 'purple', tags: 'serve, spin', notes: 'A flat second serve is a liability against a good returner. Builds a kick from toss position through to pronation.', url: p('purple-kick-serve') },
  { title: 'Serve & volley — the classic pattern', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '20 min', racket: 'purple', tags: 'net, patterns', notes: 'Players reach the net having stopped moving and volley from their shoelaces. Times the split to the return, not to the serve.', url: p('purple-serve-volley') },
  { title: 'Building a game style — audit', category: 'Training plan', level: 'Advanced', format: 'Plan', duration: '6 weeks', racket: 'purple', tags: 'game style, identity', notes: 'Players at this level plateau because they train everything equally. Audits strengths and commits to a way of winning.', url: p('purple-game-style') },
  { title: 'Change-of-direction speed work', category: 'Fitness', level: 'Advanced', format: 'PDF', duration: '20 min', racket: 'purple', tags: 'agility, speed', notes: 'Straight-line speed is not tennis speed. Deceleration and re-acceleration work for the shapes points actually make.', url: p('purple-cod-speed') },
  { title: 'Reading your opponent — scouting card', category: 'Mental', level: 'Advanced', format: 'Worksheet', duration: null, racket: 'purple', tags: 'scouting, tactics', notes: 'Players plan for their own game and never for the opponent in front of them. Five things to identify inside two service games.', url: p('purple-scouting-card') },
  { title: 'Winning Ugly — reading notes', category: 'Books', level: 'All levels', format: 'PDF', duration: null, racket: 'purple', tags: 'tactics, reading', notes: 'The classic on match-craft, reduced to the handful of ideas that change how a club player competes on Saturday.', url: p('purple-winning-ugly') },
  { title: 'Doubles: poaching and switching', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '20 min', racket: 'purple', tags: 'doubles, tactics', notes: 'Net players who never move are a spectator their partner has to cover for. Trains the poach, the fake and the switch behind it.', url: p('purple-poaching') },

  // ─── BROWN — competitive tennis. Winning matches, not just rallies. ───
  { title: 'Serve under scoreboard pressure', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '20 min', racket: 'brown', tags: 'serve, pressure', notes: 'First-serve percentage collapses at 4-5 because it has only ever been measured in baskets. Practises serving from real scores.', url: p('brown-serve-pressure') },
  { title: 'Return+1: neutralise then build', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '20 min', racket: 'brown', tags: 'return, patterns', notes: 'Returns go for too much and hand back the break point. Trains a deep neutral return and a planned second ball.', url: p('brown-return-plus-one') },
  { title: 'Closing out a set', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '25 min', racket: 'brown', tags: 'pressure, tactics', notes: 'Leads of 5-2 become 5-5 because the player stops doing what built the lead. Rehearses serving it out with a score on.', url: p('brown-closing-out') },
  { title: 'Defending and turning the point', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '22 min', racket: 'brown', tags: 'defence, transition', notes: 'Players defend by hitting harder and lose the point twice. Trains height, depth and the moment neutral becomes attack.', url: p('brown-defend-turn') },
  { title: 'Match-play tactics worksheet', category: 'Mental', level: 'Advanced', format: 'Worksheet', duration: null, racket: 'brown', tags: 'tactics, scouting', notes: 'A plan made in the warm-up is forgotten by 2-2. Written before, checked at changeovers, reviewed after.', url: p('brown-match-tactics') },
  { title: 'Tournament block — 8-week build', category: 'Training plan', level: 'Advanced', format: 'Plan', duration: '8 weeks', racket: 'brown', tags: 'periodisation, competition', notes: 'Players arrive at their target event flat or undercooked. Eight weeks that peak deliberately rather than by luck.', url: p('brown-tournament-block') },
  { title: 'Match-day fuelling & hydration', category: 'Fitness', level: 'Advanced', format: 'PDF', duration: null, racket: 'brown', tags: 'nutrition, recovery', notes: 'Cramp and fade in match two of a day are planning failures, not fitness failures. What to eat and drink, and when.', url: p('brown-fuelling') },
  { title: 'Recovery between matches', category: 'Fitness', level: 'Advanced', format: 'PDF', duration: '15 min', racket: 'brown', tags: 'recovery, mobility', notes: 'A won first round is lost in the ninety minutes after it. A structured cool-down, refuel and reset protocol.', url: p('brown-recovery-between') },
  { title: 'Periodisation for tennis — primer', category: 'Books', level: 'Advanced', format: 'PDF', duration: null, racket: 'brown', tags: 'planning, reading', notes: 'Coaches plan week to week and wonder why players peak in February. A short primer on planning a training year.', url: p('brown-periodisation') },
  { title: 'Dealing with nerves & tight points', category: 'Mental', level: 'Advanced', format: 'Worksheet', duration: null, racket: 'brown', tags: 'mental, pressure', notes: 'Tight arms at 30-40 are a breathing and routine problem before they are a technique problem. Tools to play big points freely.', url: p('brown-tight-points') },

  // ─── RED — performance. Margins, patterns and physical robustness. ───
  { title: 'Serve+1 forehand patterns', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '22 min', racket: 'red', tags: 'patterns, tactics', notes: 'At this level a serve without a pattern behind it is a neutral rally started on your own terms and then wasted. Three go-to patterns.', url: p('red-serve-plus-one-patterns') },
  { title: 'Open-stance forehand recovery', category: 'Technique', level: 'Advanced', format: 'PDF', duration: '15 min', racket: 'red', tags: 'forehand, footwork', notes: 'Players load well and then recover late, so the next ball is played on the run. Load, explode and recover as one action.', url: p('red-open-stance') },
  { title: 'Backhand down the line — the low-margin ball', category: 'Technique', level: 'Advanced', format: 'PDF', duration: '18 min', racket: 'red', tags: 'backhand, patterns', notes: 'The line backhand is attempted from the wrong ball and misses by inches. Defines the ball that earns it.', url: p('red-backhand-dtl') },
  { title: 'First-strike tennis — three-ball points', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '25 min', racket: 'red', tags: 'patterns, aggression', notes: 'Players are comfortable in long rallies and passive in short ones. Trains points to be won inside three balls.', url: p('red-first-strike') },
  { title: 'Pre-tournament 2-week taper', category: 'Training plan', level: 'Advanced', format: 'Plan', duration: '2 weeks', racket: 'red', tags: 'periodisation, competition', notes: 'Players train hardest the week before the event and arrive heavy. Sharpen and taper into the target week.', url: p('red-two-week-taper') },
  { title: 'Strength for tennis — off-court block', category: 'Fitness', level: 'Advanced', format: 'PDF', duration: '45 min', racket: 'red', tags: 'strength, robustness', notes: 'Volume rises and shoulders and hips give way first. A twice-weekly block built for robustness, not aesthetics.', url: p('red-strength-block') },
  { title: 'Injury-prevention: shoulder & hip', category: 'Fitness', level: 'Advanced', format: 'PDF', duration: '15 min', racket: 'red', tags: 'prehab, robustness', notes: 'The serve shoulder and lead hip take the load every session and are trained last. A prehab routine that fits before practice.', url: p('red-prehab') },
  { title: 'Competitive intent — the 100% card', category: 'Mental', level: 'Advanced', format: 'Worksheet', duration: null, racket: 'red', tags: 'intent, competing', notes: 'Talented players lose to lesser ones by conceding a few points a set. Makes intent measurable rather than assumed.', url: p('red-intent-card') },
  { title: 'Reviewing your own matches', category: 'Books', level: 'Advanced', format: 'PDF', duration: null, racket: 'red', tags: 'review, analysis', notes: 'Players remember the last two points and call it analysis. A framework for reviewing a match honestly.', url: p('red-match-review') },
  { title: 'Playing different opponents', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '25 min', racket: 'red', tags: 'tactics, adaptability', notes: 'A player with one game style is beaten by the first opponent who neutralises it. Drills against pusher, ball-basher and net-rusher.', url: p('red-opponent-types') },

  // ─── BLACK — mastery. Coaching yourself, and the mental game at the top. ───
  { title: 'Compete: reset routine card', category: 'Mental', level: 'Advanced', format: 'Worksheet', duration: null, racket: 'black', tags: 'mental, routines', notes: 'At this level matches turn on the twenty seconds after an error. A between-points reset and breathing routine.', url: p('black-reset-routine') },
  { title: 'Self-coaching: the changeover checklist', category: 'Mental', level: 'Advanced', format: 'Worksheet', duration: null, racket: 'black', tags: 'self-coaching, tactics', notes: 'Players wait for a coach who is not allowed to speak. Three questions at every changeover that produce a decision.', url: p('black-changeover-checklist') },
  { title: 'Owning your patterns under fatigue', category: 'Drill', level: 'Advanced', format: 'PDF', duration: '30 min', racket: 'black', tags: 'patterns, fatigue', notes: 'Patterns hold for a set and disappear in the third. Rehearses them when tired, which is when they are worth having.', url: p('black-patterns-fatigue') },
  { title: 'Serve variety: disguise and pattern', category: 'Technique', level: 'Advanced', format: 'PDF', duration: '20 min', racket: 'black', tags: 'serve, disguise', notes: 'A readable toss gives the return away before the ball is struck. One toss, three serves, and how to pattern them.', url: p('black-serve-disguise') },
  { title: 'Finishing at the net under pressure', category: 'Technique', level: 'Advanced', format: 'PDF', duration: '18 min', racket: 'black', tags: 'net, pressure', notes: 'The volley that decides the match is the one played tight and short. Trains the finish rather than the approach.', url: p('black-finishing-net') },
  { title: 'Season plan — building the year', category: 'Training plan', level: 'Advanced', format: 'Plan', duration: '12 months', racket: 'black', tags: 'periodisation, season', notes: 'Players and coaches plan the next block and never the year. Maps blocks, events, peaks and genuine off-weeks.', url: p('black-season-plan') },
  { title: 'Managing load across a season', category: 'Fitness', level: 'Advanced', format: 'PDF', duration: null, racket: 'black', tags: 'load, robustness', notes: 'Overuse injuries arrive after the best training month, not the worst. A simple way to track and moderate load.', url: p('black-load-management') },
  { title: 'Mental skills for the long game', category: 'Books', level: 'Advanced', format: 'PDF', duration: null, racket: 'black', tags: 'mental, reading', notes: 'Reading for the player whose limit is now psychological rather than technical, with what to practise from each idea.', url: p('black-mental-reading') },
  { title: 'Building a training week', category: 'Training plan', level: 'Advanced', format: 'Plan', duration: '1 week', racket: 'black', tags: 'planning, structure', notes: 'A week of hard sessions is not a hard week if none of them are easy. Lays out a week that balances load and quality.', url: p('black-training-week') },
  { title: 'Coaching yourself in practice', category: 'Books', level: 'Advanced', format: 'PDF', duration: null, racket: 'black', tags: 'self-coaching, practice', notes: 'Independent players improve between lessons; dependent ones only improve during them. How to run your own session.', url: p('black-self-coaching') },
]

// Insert the library for the current coach (skips titles they already have).
export async function seedLumioResources(): Promise<number> {
  const uid = await currentCoachId()
  if (!uid) return 0
  const existing = await sb().from('coach_resources').select('title').eq('coach_id', uid)
  const have = new Set((existing.data ?? []).map((r: any) => (r.title || '').toLowerCase()))
  const rows = LUMIO_RESOURCES.filter(r => !have.has(r.title.toLowerCase())).map(r => ({ ...r, coach_id: uid }))
  if (!rows.length) return 0
  const { error } = await sb().from('coach_resources').insert(rows)
  if (error) { console.error('[lumio-resources] seed', error.message); throw new Error(error.message) }
  return rows.length
}
