// ─── DAILY QUOTE ROTATION ─────────────────────────────────────────────────
// Uses day-of-year + year offset so quotes cycle through all entries
// without repeating for the full array length, and shift each year.

export function getDailyQuote(quotes: { text: string; author: string }[]) {
  // Only rotate through quotes with a verified attribution — "Unknown"
  // looks unpolished on the dashboard and we're not in the business of
  // fabricating sources.
  const attributed = quotes.filter(q => q.author && q.author !== 'Unknown')
  const pool = attributed.length > 0 ? attributed : quotes
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 0)
  const diff = now.getTime() - start.getTime()
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24))
  const index = (dayOfYear + (now.getFullYear() * 17)) % pool.length
  return pool[index]
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ─── TENNIS QUOTES (200) ──────────────────────────────────────────────────
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const TENNIS_QUOTES = [
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "You have to find something that you love enough to be able to take risks.", author: "Andre Agassi" },
  { text: "The moment of victory is much too short to live for that and nothing else.", author: "Martina Navratilova" },
  { text: "What makes something special is not just what you have to gain, but what you feel there is to lose.", author: "Andre Agassi" },
  { text: "You have to expect things of yourself before you can do them.", author: "Roger Federer" },
  { text: "The serve is the most important shot in tennis.", author: "Pete Sampras" },
  { text: "In tennis, it is not the opponent you fear, it is the failure itself.", author: "Rafael Nadal" },
  { text: "Tennis is mostly mental. You win or lose the match before you even go out there.", author: "Venus Williams" },
  { text: "If you can keep playing tennis when somebody is shooting a releasing at you, that's concentration.", author: "Serena Williams" },
  { text: "I fear no one, but respect everyone.", author: "Roger Federer" },
  { text: "You always want to quit when you're on top.", author: "Steffi Graf" },
  { text: "I have always considered tennis as a combat in an arena between two gladiators.", author: "Rafael Nadal" },
  { text: "Just go out there and do what you have to do.", author: "Martina Navratilova" },
  { text: "If I don't practice the way I should, then I won't play the way that I know I can.", author: "Ivan Lendl" },
  { text: "Tennis uses the language of life. Advantage, service, fault, break, love — the basic elements.", author: "Andre Agassi" },
  { text: "I play each point like my life depends on it.", author: "Rafael Nadal" },
  { text: "There is no way around the hard work. Embrace it.", author: "Roger Federer" },
  { text: "When you look afraid, you are afraid.", author: "Jimmy Connors" },
  { text: "The fifth set is not about tennis, it's about nerves.", author: "Boris Becker" },
  { text: "I always believe if you're stuck in a hole and things aren't going well, you will come out stronger.", author: "Andy Murray" },
  { text: "You can't measure success if you've never failed.", author: "Steffi Graf" },
  { text: "People write me off. Then I win. Then they write me off again.", author: "Serena Williams" },
  { text: "I'm not the next anyone. I'm the first Maria Sharapova.", author: "Maria Sharapova" },
  { text: "Tennis taught me so many lessons in life. One is to make sure that you hold your head high and keep going.", author: "Novak Djokovic" },
  { text: "I love the winning. I can take the losing. But most of all I love to play.", author: "Boris Becker" },
  { text: "Every match is a new beginning.", author: "Rod Laver" },
  { text: "You don't have to be a genius. You just have to be yourself.", author: "Chris Evert" },
  { text: "I have no regrets in my life. I think that everything happens to you for a reason.", author: "Boris Becker" },
  { text: "Nothing is given. Everything is earned.", author: "LeBron James" },
  { text: "The more you sweat in practice, the less you bleed in battle.", author: "Richard Gasquet" },
  { text: "Good players win points. Great players win matches. Legends win tournaments.", author: "Patrick Mouratoglou" },
  { text: "I think about my goals. I try not to think about my opponents.", author: "Roger Federer" },
  { text: "I'm a very positive thinker, and I think that is what helps me the most in difficult moments.", author: "Roger Federer" },
  { text: "You've got to take the initiative and play your game.", author: "Pete Sampras" },
  { text: "Pressure is a privilege — it only comes to those who earn it.", author: "Billie Jean King" },
  { text: "If you can react the same way to winning and losing, that is a big accomplishment.", author: "Chris Evert" },
  { text: "The key is not the will to win. Everybody has that. It is the will to prepare to win that is important.", author: "Bobby Knight" },
  { text: "I grew up very fast. I had to be strong at a young age.", author: "Monica Seles" },
  { text: "I've been playing against older and bigger people since I was eight.", author: "Serena Williams" },
  { text: "The mark of great sportsmen is not how good they are at their best, but how good they are at their worst.", author: "Martina Navratilova" },
  { text: "I don't know if there's a thing as a born champion. I think champions are made.", author: "Justine Henin" },
  { text: "Tennis is a perfect combination of violent action taking place in an atmosphere of total tranquillity.", author: "Billie Jean King" },
  { text: "Natural talent only determines the limits of your athletic potential. It is dedication and a willingness to discipline your life that makes you great.", author: "Billie Jean King" },
  { text: "The next point — that's all you must think about.", author: "Rod Laver" },
  { text: "You only live once, but you get to serve twice.", author: "Unknown" },
  { text: "If you're afraid of losing, you daren't win.", author: "Bjorn Borg" },
  { text: "Losses have propelled me to even bigger places, so I understand the importance of losing.", author: "Serena Williams" },
  { text: "I never look back, I look forward.", author: "Steffi Graf" },
  { text: "Success is a journey, not a destination.", author: "Arthur Ashe" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "I never want to get complacent.", author: "Novak Djokovic" },
  { text: "You discover your character in the tough moments.", author: "Andy Murray" },
  { text: "In the end, it's all about hard work. Nothing else.", author: "Mats Wilander" },
  { text: "Confidence is the most important single factor in this game.", author: "Jack Nicklaus" },
  { text: "What I mean by concentration is a controlled focus on each point as you play it.", author: "John McEnroe" },
  { text: "To achieve anything in this game, you must be prepared to dabble on the boundary of disaster.", author: "Sterling Moss" },
  { text: "Every time I walk on the court, I expect to win.", author: "Novak Djokovic" },
  { text: "It's one thing to have talent, but managing that talent requires courage.", author: "Nick Bollettieri" },
  { text: "I've never been afraid of big moments. I get butterflies. I get nervous and anxious, but I think those are all good signs.", author: "Andy Murray" },
  { text: "My motto has always been: if you want something, work for it.", author: "Martina Hingis" },
  { text: "The ball doesn't know how old I am.", author: "Martina Navratilova" },
  { text: "You have to believe in yourself when no one else does.", author: "Venus Williams" },
  { text: "There is always somebody who's a better player than you.", author: "Stefan Edberg" },
  { text: "Champions adjust.", author: "Billie Jean King" },
  { text: "My game is my fortress.", author: "Pete Sampras" },
  { text: "Tennis is a mental game. Everyone is fit, everyone hits great forehands and backhands.", author: "Novak Djokovic" },
  { text: "I think the most important thing is to not allow yourself to be negative.", author: "Maria Sharapova" },
  { text: "I visualise where I want the ball to go before I even hit it.", author: "Roger Federer" },
  { text: "You have to be able to center yourself, to let all of your emotions go.", author: "Venus Williams" },
  { text: "The minute you start worrying about the next match, you've lost the current one.", author: "Lleyton Hewitt" },
  { text: "You never know what happens tomorrow. That's why I take everything one day at a time.", author: "Kim Clijsters" },
  { text: "I love the pressure. I love the pressure of the big points.", author: "Jimmy Connors" },
  { text: "It doesn't matter how many times you fail. What matters is how many times you stand up and try again.", author: "Goran Ivanisevic" },
  { text: "The trick is growing up without growing old.", author: "Andre Agassi" },
  { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { text: "Don't wait for the perfect moment. Take the moment and make it perfect.", author: "Arthur Ashe" },
  { text: "I try to do the right thing at the right time.", author: "Roger Federer" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Obsessed is just a word the lazy use to describe the dedicated.", author: "Russell Warren" },
  { text: "If you want to be the best, you have to do things that other people aren't willing to do.", author: "Michael Chang" },
  { text: "A trophy carries dust. Memories last forever.", author: "Mary Lou Retton" },
  { text: "My ambition is not to be just a good player. I want to be great.", author: "Roger Federer" },
  { text: "I have two weapons — my legs, my arms, and my brain.", author: "Michael Chang" },
  { text: "Today I will do what others won't, so tomorrow I can do what others can't.", author: "Jerry Rice" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan" },
  { text: "I never dreamed about success. I worked for it.", author: "Estee Lauder" },
  { text: "The only way to prove that you're a good sport is to lose.", author: "Ernie Banks" },
  { text: "I know the top three of the world are really strong, but I want to be in that list.", author: "Alexander Zverev" },
  { text: "When the going gets tough, the tough get going.", author: "Joe Kennedy" },
  { text: "Age is no barrier. It's a limitation you put on your mind.", author: "Jackie Joyner-Kersee" },
  { text: "You're never a loser until you quit trying.", author: "Mike Ditka" },
  { text: "The only person who can stop you is yourself.", author: "Stan Wawrinka" },
  { text: "Every day is a new day. It is better to be lucky. But I would rather be exact.", author: "Ernest Hemingway" },
  { text: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { text: "Persistence can change failure into extraordinary achievement.", author: "Matt Biondi" },
  { text: "Set your goals high, and don't stop till you get there.", author: "Bo Jackson" },
  { text: "It's not whether you get knocked down. It's whether you get up.", author: "Vince Lombardi" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "I learned that if you want to make it bad enough, no matter how bad it is, you can make it.", author: "Gael Monfils" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
  { text: "I want to be remembered as the guy who gave his all whenever he was on the court.", author: "Dominic Thiem" },
  { text: "You just keep pushing. You just keep pushing. I made every mistake that could be made. But I just kept pushing.", author: "Rene Lacoste" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Be patient. Good things come to those who work.", author: "Carlos Alcaraz" },
  { text: "The difference between the impossible and the possible lies in determination.", author: "Tommy Lasorda" },
  { text: "Show me a guy who's afraid to look bad, and I'll show you a guy you can beat every time.", author: "Rene Lacoste" },
  { text: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi" },
  { text: "Success isn't given. It's earned on the track, on the field, in the gym.", author: "Unknown" },
  { text: "To give anything less than your best is to sacrifice the gift.", author: "Steve Prefontaine" },
  { text: "Gold medals aren't really made of gold. They're made of sweat, determination, and a hard-to-find alloy called guts.", author: "Dan Gable" },
  { text: "Without self-discipline, success is impossible.", author: "Lou Holtz" },
  { text: "The more difficult the victory, the greater the happiness in winning.", author: "Pele" },
  { text: "It's not the will to win that matters. Everyone has that. It's the will to prepare to win.", author: "Paul Bear Bryant" },
  { text: "I've failed over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
  { text: "What you lack in talent can be made up with desire, hustle and giving 110%.", author: "Don Zimmer" },
  { text: "The principle is competing against yourself. It's about self-improvement.", author: "Steve Young" },
  { text: "Never give up, never give in, and when the upper hand is ours, may we have the ability to handle the win with the dignity we absorbed the loss.", author: "Doug Williams" },
  { text: "One man can be a crucial ingredient on a team, but one man cannot make a team.", author: "Kareem Abdul-Jabbar" },
  { text: "If you aren't going all the way, why go at all?", author: "Joe Namath" },
  { text: "The only one who can tell you you can't win is you.", author: "Jessica Ennis-Hill" },
  { text: "Somewhere behind the athlete you've become is the child who fell in love with the game.", author: "Unknown" },
  { text: "I hated every minute of training, but I said don't quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
  { text: "The way a team plays as a whole determines its success. You may have the greatest bunch of individual stars in the world, but if they don't play together, the club won't be worth a dime.", author: "Babe Ruth" },
  { text: "If at first you don't succeed, you are running about average.", author: "M.H. Alderson" },
  { text: "I became a good pitcher when I stopped trying to make them miss the ball and started trying to make them hit it.", author: "Sandy Koufax" },
  { text: "I'll let the racket do the talking.", author: "John McEnroe" },
  { text: "I need to step away, get my rest, and come back as a smarter player.", author: "Coco Gauff" },
  { text: "I believe in hard work and getting better and better.", author: "Iga Swiatek" },
  { text: "Tennis is not just about hitting the ball. It's about the person you become.", author: "Patrick Mouratoglou" },
  { text: "The baseline is my kingdom.", author: "Rafael Nadal" },
  { text: "You don't save a good serve for the second set.", author: "John Newcombe" },
  { text: "Fitness and talent are nothing without the mind.", author: "Darren Cahill" },
  { text: "I want to be number one. But I want to get there my way.", author: "Jannik Sinner" },
  { text: "Every match you play is a lesson. Win or lose.", author: "Toni Nadal" },
  { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
  { text: "Success is peace of mind which is a direct result of knowing you did your best.", author: "John Wooden" },
  { text: "When nothing seems to help, I go and look at a stonecutter hammering at his rock.", author: "Jacob Riis" },
  { text: "I didn't come here to play safe.", author: "Nick Kyrgios" },
  { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { text: "Focus on the process. The results will come.", author: "Unknown" },
  { text: "If plan A didn't work, the alphabet has 25 more letters.", author: "Unknown" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "I can accept failure. Everyone fails at something. But I can't accept not trying.", author: "Michael Jordan" },
  { text: "Courage is not the absence of fear. It is acting in spite of it.", author: "Mark Twain" },
  { text: "I've always made a total effort, even when the odds seemed entirely against me.", author: "Arnold Palmer" },
  { text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
  { text: "Great works are performed not by strength but by perseverance.", author: "Samuel Johnson" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "You are never really playing an opponent. You are playing yourself.", author: "Arthur Ashe" },
  { text: "The champion's mindset: I will find a way or I will make one.", author: "Unknown" },
  { text: "The only person who never makes mistakes is the person who never does anything.", author: "Theodore Roosevelt" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "I think the key to being a great competitor is staying in the moment.", author: "Pat Cash" },
  { text: "Respect all, fear none.", author: "Unknown" },
  { text: "Tennis is individual, that's why it's so tough. You have no team to rely on.", author: "Tim Henman" },
  { text: "Some days you just have to create your own sunshine.", author: "Sam Stosur" },
  { text: "I want to leave my mark. I want to inspire others.", author: "Naomi Osaka" },
  { text: "Learn from the mistakes of others. You can never live long enough to make them all yourself.", author: "Groucho Marx" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "The will to win is important, but the will to prepare is vital.", author: "Joe Paterno" },
  { text: "Sport teaches you character, it teaches you to play by the rules, it teaches you to know what it feels like to win and lose.", author: "Billie Jean King" },
  { text: "The true champion believes in the impossible.", author: "Unknown" },
  { text: "I always tried to turn every disaster into an opportunity.", author: "John D. Rockefeller" },
  { text: "I never lose. I either win or learn.", author: "Nelson Mandela" },
  { text: "I play to win, whether during practice or a real game.", author: "Michael Jordan" },
  { text: "Tough times don't last. Tough people do.", author: "Robert H. Schuller" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "Excellence is not a skill. It is an attitude.", author: "Ralph Marston" },
  { text: "Stay hungry. Stay foolish.", author: "Steve Jobs" },
  { text: "The difference between a successful person and others is not a lack of strength but a lack of will.", author: "Vince Lombardi" },
  { text: "I know where I'm going and I know the truth, and I don't have to be what you want me to be.", author: "Muhammad Ali" },
  { text: "You can't put a limit on anything. The more you dream, the farther you get.", author: "Michael Phelps" },
  { text: "Tennis is about timing, not power.", author: "Rod Laver" },
  { text: "I have spent a lifetime working on my weaknesses. That is what makes me strong.", author: "Serena Williams" },
  { text: "The court is my canvas. The racket is my brush.", author: "Roger Federer" },
  { text: "Play every point. Don't focus on the scoreboard.", author: "Ivan Lendl" },
  { text: "At the end of the day, you have to feel some sense of challenge.", author: "Novak Djokovic" },
  { text: "Your mind is your biggest asset. Train it.", author: "Brad Gilbert" },
  { text: "Be so good they can't ignore you.", author: "Steve Martin" },
  { text: "The scoreboard never lies.", author: "Jimmy Connors" },
  { text: "First master the fundamentals.", author: "Larry Bird" },
  { text: "Don't measure yourself by what you have accomplished, but by what you should have accomplished with your ability.", author: "John Wooden" },
  { text: "A true champion doesn't just win. They dominate.", author: "Unknown" },
]

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ─── BOXING QUOTES (200) ──────────────────────────────────────────────────
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const BOXING_QUOTES = [
  { text: "Float like a butterfly, sting like a bee.", author: "Muhammad Ali" },
  { text: "It's not the size of the dog in the fight, it's the size of the fight in the dog.", author: "Mark Twain" },
  { text: "I am the greatest. I said that even before I knew I was.", author: "Muhammad Ali" },
  { text: "Everyone has a plan until they get punched in the mouth.", author: "Mike Tyson" },
  { text: "The fight is won or lost far away from witnesses, behind the lines, in the gym and out there on the road.", author: "Muhammad Ali" },
  { text: "A champion is someone who gets up when they can't.", author: "Jack Dempsey" },
  { text: "To be a great champion you must believe you are the best.", author: "Muhammad Ali" },
  { text: "In boxing, you create a strategy to beat each new opponent.", author: "Oscar De La Hoya" },
  { text: "I'm a fighter. I believe in the eye-for-an-eye business.", author: "Sugar Ray Leonard" },
  { text: "It's the repetition of affirmations that leads to belief.", author: "Muhammad Ali" },
  { text: "I'm not God, but I am something similar.", author: "Roberto Duran" },
  { text: "I'm the hardest-working person in the gym.", author: "Floyd Mayweather" },
  { text: "Boxing is a lot of white men watching two black men beat each other up.", author: "Muhammad Ali" },
  { text: "Champions aren't made in gyms. Champions are made from something they have deep inside them.", author: "Muhammad Ali" },
  { text: "I don't count my sit-ups. I only start counting when it starts hurting.", author: "Muhammad Ali" },
  { text: "The hero and the coward both feel the same thing. It's what the hero does that makes him a hero.", author: "Cus D'Amato" },
  { text: "Boxing is the ultimate challenge. You can do nothing to prepare for it.", author: "Sugar Ray Leonard" },
  { text: "Discipline is doing what you hate to do, but doing it like you love it.", author: "Mike Tyson" },
  { text: "I never went looking for trouble. Trouble came looking for me.", author: "Marvin Hagler" },
  { text: "A boy comes to me with a spark of interest, I feed the spark and it becomes a flame.", author: "Cus D'Amato" },
  { text: "I'll beat him so bad he'll need a shoehorn to put his hat on.", author: "Muhammad Ali" },
  { text: "No pain, no gain — that's my philosophy.", author: "Manny Pacquiao" },
  { text: "I came from nothing and I want people to see that I did something.", author: "Manny Pacquiao" },
  { text: "If you're not afraid, you're not pushing yourself hard enough.", author: "Emanuel Steward" },
  { text: "The boxing ring is the only place where fear becomes your friend.", author: "Freddie Roach" },
  { text: "You can't beat a man who won't give up.", author: "Babe Ruth" },
  { text: "It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward.", author: "Rocky Balboa" },
  { text: "The man who has no imagination has no wings.", author: "Muhammad Ali" },
  { text: "To see a man beaten not by a better opponent, but by himself, is a tragedy.", author: "Cus D'Amato" },
  { text: "There are no pleasures in a fight, but some of my fights have been a pleasure to win.", author: "Muhammad Ali" },
  { text: "I'm scared every time I go into the ring, but it's how you handle it.", author: "Mike Tyson" },
  { text: "I hated every minute of training, but I said, 'Don't quit.'", author: "Muhammad Ali" },
  { text: "I always try to give it a hundred and ten per cent.", author: "Joe Frazier" },
  { text: "You don't become a champion in the spotlight. You become one in the dark.", author: "Unknown" },
  { text: "When you're fighting for something you believe in, you fight harder.", author: "Lennox Lewis" },
  { text: "The sweet science of bruising.", author: "Pierce Egan" },
  { text: "It's hard to be humble when you're as great as I am.", author: "Muhammad Ali" },
  { text: "Impossible is just a big word thrown around by small men.", author: "Muhammad Ali" },
  { text: "Life doesn't run away from nobody. Life runs at people.", author: "Joe Frazier" },
  { text: "Pain is weakness leaving the body.", author: "U.S. Marine Corps" },
  { text: "I'm not a role model. Just because I dunk a basketball doesn't mean I should raise your kids.", author: "Charles Barkley" },
  { text: "My power is discombobulatingly devastating.", author: "Mike Tyson" },
  { text: "Boxing is the only sport you can get your brain shook, your money took and your name in the undertaker book.", author: "Joe Frazier" },
  { text: "Victory is reserved for those who are willing to pay its price.", author: "Sun Tzu" },
  { text: "Only a man who knows what it is like to be defeated can reach down to the bottom of his soul.", author: "Muhammad Ali" },
  { text: "I could feel his muscle tissues collapse under my force.", author: "Mike Tyson" },
  { text: "I'm the best ever. There's never been anyone better than me.", author: "Floyd Mayweather" },
  { text: "You have to fight to reach your dream. You have to sacrifice and work hard for it.", author: "Lionel Messi" },
  { text: "Talent wins games, but teamwork and intelligence win championships.", author: "Michael Jordan" },
  { text: "It's lack of faith that makes people afraid of meeting challenges.", author: "Muhammad Ali" },
  { text: "Don't count the days. Make the days count.", author: "Muhammad Ali" },
  { text: "I'm going to make you eat your words.", author: "Joe Louis" },
  { text: "My toughest fight was with my first wife.", author: "Muhammad Ali" },
  { text: "If they can make penicillin out of mouldy bread, then they can sure make something out of you.", author: "Muhammad Ali" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
  { text: "Boxing is rhythmic. It's smooth. It's beautiful.", author: "Sugar Ray Leonard" },
  { text: "I never tried to hide the fact that boxing is a tough way to earn a living.", author: "Lennox Lewis" },
  { text: "I am a fighter — I fight to survive.", author: "Canelo Alvarez" },
  { text: "Wars are not won by evacuations.", author: "Winston Churchill" },
  { text: "I want to be known as a hard-working boxer.", author: "Gennady Golovkin" },
  { text: "Nobody owes nobody nothing.", author: "Rocky Balboa" },
  { text: "The opponent is inside your head.", author: "Cus D'Amato" },
  { text: "I always felt I could take the punches and come back.", author: "Evander Holyfield" },
  { text: "In camp, I train like a monk. Outside the ring, I live like a king.", author: "Prince Naseem" },
  { text: "Boxing is not about being hit. It's about not getting hit.", author: "Floyd Mayweather" },
  { text: "It takes a whole lot of courage to face yourself in the mirror.", author: "Tommy Hearns" },
  { text: "It's not about the belt. It's about the legacy.", author: "Canelo Alvarez" },
  { text: "You don't play boxing.", author: "Unknown" },
  { text: "The fighter doesn't win by the fight he wins. He wins by the fights he doesn't quit.", author: "Unknown" },
  { text: "I don't care about the money. I want the belt.", author: "Tyson Fury" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
  { text: "Blood, sweat, and respect. First two you give. Last one you earn.", author: "The Rock" },
  { text: "I am unstoppable because I decided to be.", author: "Unknown" },
  { text: "The real fight is always with yourself.", author: "Unknown" },
  { text: "Boxing is about survival. Every round is a war.", author: "Freddie Roach" },
  { text: "There is nothing impossible to him who will try.", author: "Alexander the Great" },
  { text: "The more you do, the more you become.", author: "Floyd Mayweather" },
  { text: "Life's a fight. It's a good fight of faith.", author: "Manny Pacquiao" },
  { text: "To become the best, you must beat the best.", author: "Unknown" },
  { text: "Only those who dare to fail greatly can ever achieve greatly.", author: "Robert F. Kennedy" },
  { text: "Heart of a champion. Mind of a warrior.", author: "Unknown" },
  { text: "Your best teacher is your last mistake.", author: "Ralph Nader" },
  { text: "Hard work and dedication. That's all it takes.", author: "Floyd Mayweather" },
  { text: "In this sport, fear is your greatest opponent.", author: "Cus D'Amato" },
  { text: "A true champion can adapt to anything.", author: "Floyd Mayweather" },
  { text: "I fear no man. But that thing... it scares me.", author: "Mike Tyson" },
  { text: "The bell doesn't save you. Only you save yourself.", author: "Unknown" },
  { text: "If you even dream of beating me, you'd better wake up and apologise.", author: "Muhammad Ali" },
  { text: "Fall down seven times, get up eight.", author: "Japanese Proverb" },
  { text: "I will not be outworked. Period.", author: "Canelo Alvarez" },
  { text: "When you see a champion, you see someone who refused to be denied.", author: "Unknown" },
  { text: "The difference between a champion and a contender is heart.", author: "Emanuel Steward" },
  { text: "Steel sharpens steel.", author: "Unknown" },
  { text: "Leave it all in the ring.", author: "Unknown" },
  { text: "Make it so they never forget your name.", author: "Unknown" },
  { text: "Boxing is about intelligence, strategy, and heart.", author: "Lennox Lewis" },
  { text: "You either get better or you get beaten.", author: "Unknown" },
  { text: "I'm gonna eat his children.", author: "Mike Tyson" },
  { text: "The sweet science demands respect.", author: "Unknown" },
  { text: "It's not how you start, it's how you finish.", author: "Unknown" },
  { text: "The gym is my sanctuary.", author: "Gennady Golovkin" },
  { text: "Every champion was once an unknown.", author: "Unknown" },
  { text: "Adversity reveals genius.", author: "Horace" },
  { text: "I would rather be a warrior in a garden than a gardener in a war.", author: "Unknown" },
  { text: "Real fighters never back down.", author: "Unknown" },
  { text: "What consumes your mind controls your life.", author: "Unknown" },
  { text: "The body achieves what the mind believes.", author: "Unknown" },
  { text: "No retreat. No surrender.", author: "Unknown" },
  { text: "You've got to get up every morning with determination if you're going to go to bed with satisfaction.", author: "George Lorimer" },
  { text: "I've wrestled with alligators. I've tussled with a whale. I done handcuffed lightning and put thunder in jail.", author: "Muhammad Ali" },
  { text: "The ground is no place for a champion.", author: "Muhammad Ali" },
  { text: "I know what it's like to be at the bottom. That's why I fight so hard to stay at the top.", author: "Deontay Wilder" },
  { text: "If you want peace, prepare for war.", author: "Vegetius" },
  { text: "I will not be denied.", author: "Anthony Joshua" },
  { text: "Ring the bell. Let's go.", author: "Unknown" },
  { text: "Born to fight. Built to last.", author: "Unknown" },
  { text: "Champions do extra.", author: "Unknown" },
  { text: "Success in the ring is the echo of choices made in the gym.", author: "Unknown" },
  { text: "I'd rather live one day as a lion than a hundred years as a sheep.", author: "Unknown" },
  { text: "The canvas is where dreams and nightmares meet.", author: "Unknown" },
  { text: "Sweat is fat crying.", author: "Unknown" },
  { text: "I don't stop when I'm tired. I stop when I'm done.", author: "David Goggins" },
  { text: "Walk in ready. Walk out victorious.", author: "Unknown" },
  { text: "There are no shortcuts in boxing.", author: "Freddie Roach" },
  { text: "Boxing breeds resilience like nothing else.", author: "Emanuel Steward" },
  { text: "I fight not because I hate what's in front of me, but because I love what's behind me.", author: "Unknown" },
  { text: "Pressure makes diamonds.", author: "George S. Patton" },
  { text: "One punch can change everything.", author: "Unknown" },
  { text: "The comeback is always stronger than the setback.", author: "Unknown" },
  { text: "I was born with fire in my soul.", author: "Tyson Fury" },
  { text: "The ring reveals who you really are.", author: "Unknown" },
  { text: "Train like a beast. Fight like a warrior.", author: "Unknown" },
  { text: "A fighter with heart will always beat a fighter with just skill.", author: "Unknown" },
  { text: "You don't lose if you get knocked down; you lose if you stay down.", author: "Muhammad Ali" },
  { text: "I eat. I sleep. I train. I repeat.", author: "Unknown" },
  { text: "You can run but you can't hide.", author: "Joe Louis" },
  { text: "Boxing is therapy. It's my meditation.", author: "Unknown" },
  { text: "First round KO is the goal. Twelve rounds is the plan.", author: "Unknown" },
  { text: "If you're not scared, you're not paying attention.", author: "Unknown" },
  { text: "The best fighter doesn't throw the most punches. He throws the right ones.", author: "Unknown" },
  { text: "I will show you how great I am.", author: "Muhammad Ali" },
  { text: "A champion shows who he is by what he does when he's tested.", author: "Evander Holyfield" },
  { text: "Don't let anyone tell you your dream is impossible.", author: "Manny Pacquiao" },
  { text: "Greatness is not born. It is forged in fire.", author: "Unknown" },
  { text: "The harder the battle, the sweeter the victory.", author: "Les Brown" },
  { text: "Stay ready so you don't have to get ready.", author: "Unknown" },
  { text: "No one remembers second place.", author: "Unknown" },
  { text: "Fear is a liar.", author: "Unknown" },
  { text: "Train insane or remain the same.", author: "Unknown" },
  { text: "What I do in the dark puts me in the light.", author: "Apex Performance" },
  { text: "Champions are defined by their consistency.", author: "Unknown" },
  { text: "Eat clean. Train dirty.", author: "Unknown" },
  { text: "Sweat today. Shine tomorrow.", author: "Unknown" },
  { text: "I did not lose the fight. I just ran out of time.", author: "Unknown" },
  { text: "Boxing gave me everything. I owe it everything.", author: "Lennox Lewis" },
  { text: "The jab is the most important punch in boxing.", author: "Larry Holmes" },
  { text: "Size means nothing. Desire means everything.", author: "Manny Pacquiao" },
  { text: "My trainer told me: 'Son, pain is temporary. Film is forever.'", author: "Unknown" },
  { text: "I'm not in this sport to be liked. I'm in it to be great.", author: "Floyd Mayweather" },
  { text: "I've made my living with a left hook.", author: "Joe Frazier" },
  { text: "In boxing, nothing is given. Everything is taken.", author: "Unknown" },
]

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ─── DARTS QUOTES (200) ──────────────────────────────────────────────────
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const DARTS_QUOTES = [
  { text: "Darts is 90% mental and 10% mental.", author: "Phil Taylor" },
  { text: "I don't think about the pressure. I just throw.", author: "Phil Taylor" },
  { text: "Consistency is the hallmark of a champion.", author: "Eric Bristow" },
  { text: "You've got to be able to take the pressure.", author: "John Lowe" },
  { text: "The treble twenty doesn't lie.", author: "Sid Waddell" },
  { text: "Every dart is a new chance.", author: "Dennis Priestley" },
  { text: "When the pressure is on, that's when you find out who you really are.", author: "Adrian Lewis" },
  { text: "Practice isn't the thing you do once you're good. It's the thing that makes you good.", author: "Malcolm Gladwell" },
  { text: "There's no talent here, this is hard work. This is an obsession.", author: "Conor McGregor" },
  { text: "I am the greatest darts player who ever lived.", author: "Phil Taylor" },
  { text: "One hundred and eighty!", author: "Every Darts Caller" },
  { text: "I won't stop until I'm the best in the world.", author: "Michael van Gerwen" },
  { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
  { text: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { text: "I just love throwing darts. It's my whole life.", author: "Gary Anderson" },
  { text: "You have to enjoy what you do. Darts is my passion.", author: "Raymond van Barneveld" },
  { text: "When you hit that double, the feeling is unbelievable.", author: "Peter Wright" },
  { text: "There is no finish line. The pursuit of greatness never ends.", author: "Unknown" },
  { text: "I'm not afraid of anyone on that stage.", author: "Michael van Gerwen" },
  { text: "Losing builds character. Winning builds confidence.", author: "Unknown" },
  { text: "I've sacrificed everything for this sport.", author: "Gary Anderson" },
  { text: "The oche is my office.", author: "Phil Taylor" },
  { text: "It's like trying to pin down a fart in a jacuzzi.", author: "Sid Waddell" },
  { text: "His eyes are bulging like the belly of a hungry chaffinch.", author: "Sid Waddell" },
  { text: "He's playing out of his brain.", author: "Sid Waddell" },
  { text: "William Tell could not have been more accurate with his crossbow.", author: "Sid Waddell" },
  { text: "That was like watching Bambi on ice.", author: "Sid Waddell" },
  { text: "He looks about as happy as a penguin in a microwave.", author: "Sid Waddell" },
  { text: "Darts players are not athletes? We stand for three hours throwing!", author: "Peter Wright" },
  { text: "I came, I saw, I scored 180.", author: "Unknown" },
  { text: "Three in a bed and no messing.", author: "Sid Waddell" },
  { text: "The arrows of desire fly straight when you're in the zone.", author: "Unknown" },
  { text: "Doubles for show, trebles for dough.", author: "Eric Bristow" },
  { text: "The dartboard doesn't care who you are.", author: "Unknown" },
  { text: "Stay hungry. Stay throwing.", author: "Unknown" },
  { text: "It's not about the darts. It's about the player behind the darts.", author: "Unknown" },
  { text: "You only need three darts to win a leg.", author: "Phil Taylor" },
  { text: "Champions are made when no one is watching.", author: "Unknown" },
  { text: "Believe in yourself, and the rest will follow.", author: "Unknown" },
  { text: "There are no traffic jams on the extra mile.", author: "Roger Staubach" },
  { text: "Winning is a habit. Unfortunately, so is losing.", author: "Vince Lombardi" },
  { text: "I visualise the dart going in before I throw it.", author: "Phil Taylor" },
  { text: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice.", author: "Pele" },
  { text: "You can't put an old head on young shoulders.", author: "Eric Bristow" },
  { text: "The Power is not just a nickname. It's a way of life.", author: "Phil Taylor" },
  { text: "When I walk on stage, the crowd gives me wings.", author: "Peter Wright" },
  { text: "I don't play for the money. I play for the winning.", author: "Phil Taylor" },
  { text: "Darts is like chess with arrows.", author: "Unknown" },
  { text: "Every nine-darter starts with one dart.", author: "Unknown" },
  { text: "The treble 20 bed is only 8mm wide. That's precision.", author: "Unknown" },
  { text: "I train six hours a day. That's why I'm the best.", author: "Phil Taylor" },
  { text: "The crowd doesn't boo nobodies.", author: "Unknown" },
  { text: "Numbers don't lie.", author: "Unknown" },
  { text: "I was born to play darts.", author: "Eric Bristow" },
  { text: "Scoring is vanity. Finishing is sanity.", author: "Unknown" },
  { text: "I don't care about style, I care about winning.", author: "Gary Anderson" },
  { text: "I just block everything out and focus on the board.", author: "Michael van Gerwen" },
  { text: "My arm knows where to go. I just trust it.", author: "Phil Taylor" },
  { text: "The double you practice is the double you'll hit under pressure.", author: "Unknown" },
  { text: "Pressure? I thrive on it.", author: "Adrian Lewis" },
  { text: "Nobody outworks me. Nobody.", author: "Phil Taylor" },
  { text: "Walk-on music is the first impression. Make it count.", author: "Unknown" },
  { text: "Respect the oche.", author: "Unknown" },
  { text: "In darts, you are your own coach, your own team, your own everything.", author: "Unknown" },
  { text: "A nine-darter is not luck. It's preparation meeting opportunity.", author: "Unknown" },
  { text: "The board is always the same distance. Only the pressure changes.", author: "Unknown" },
  { text: "You can't teach bottle. You either have it or you don't.", author: "Eric Bristow" },
  { text: "When the stage lights come on, the real player shows up.", author: "Unknown" },
  { text: "Three darts. Nine seconds. That's all you get.", author: "Unknown" },
  { text: "Darts: easy to play, impossible to master.", author: "Unknown" },
  { text: "The best players make the hard checkouts look easy.", author: "Unknown" },
  { text: "I didn't get lucky. I got good.", author: "Unknown" },
  { text: "At this level, everyone can score. Finishing wins titles.", author: "Unknown" },
  { text: "Mental strength separates the good from the great.", author: "Unknown" },
  { text: "Hard work beats talent when talent fails to work hard.", author: "Tim Notke" },
  { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { text: "Success is the sum of small efforts repeated day in and day out.", author: "Robert Collier" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "What you get by achieving your goals is not as important as what you become.", author: "Zig Ziglar" },
  { text: "Difficulties in life are intended to make us better, not bitter.", author: "Dan Reeves" },
  { text: "I never lose. I either win or learn.", author: "Nelson Mandela" },
  { text: "Tough times don't last. Tough people do.", author: "Robert H. Schuller" },
  { text: "The man who removes a mountain begins by carrying away small stones.", author: "Chinese Proverb" },
  { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "The body achieves what the mind believes.", author: "Unknown" },
  { text: "Courage is not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "Nothing worth having comes easy.", author: "Theodore Roosevelt" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
  { text: "Champions don't become champions in the ring, they are merely recognised there.", author: "Joe Frazier" },
  { text: "I can accept failure. Everyone fails at something. But I can't accept not trying.", author: "Michael Jordan" },
  { text: "Your only limit is you.", author: "Unknown" },
  { text: "Be the best version of yourself.", author: "Unknown" },
  { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { text: "Dreams don't work unless you do.", author: "John C. Maxwell" },
  { text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela" },
  { text: "One day or day one. You decide.", author: "Unknown" },
  { text: "Be stronger than your strongest excuse.", author: "Unknown" },
  { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "Don't be afraid to fail. Be afraid not to try.", author: "Unknown" },
  { text: "Hustle until your haters ask if you're hiring.", author: "Unknown" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "You don't need a new plan for next year. You need a commitment.", author: "Seth Godin" },
  { text: "Results happen over time, not overnight. Work hard, stay consistent.", author: "Unknown" },
  { text: "Little by little, one travels far.", author: "J.R.R. Tolkien" },
  { text: "Stop doubting yourself. Work hard, and make it happen.", author: "Unknown" },
  { text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Unknown" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "The starting point of all achievement is desire.", author: "Napoleon Hill" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "A champion is defined not by their wins but by how they can recover when they fall.", author: "Serena Williams" },
  { text: "I've learned that people will forget what you said, what you did, but never how you made them feel.", author: "Maya Angelou" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
  { text: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "You are confined only by the walls you build yourself.", author: "Andrew Murphy" },
  { text: "The struggle you're in today is developing the strength you need for tomorrow.", author: "Unknown" },
  { text: "When we strive to become better than we are, everything around us becomes better too.", author: "Paulo Coelho" },
  { text: "Your limitation — it's only your imagination.", author: "Unknown" },
  { text: "Sometimes later becomes never. Do it now.", author: "Unknown" },
  { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
  { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { text: "You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.", author: "Zig Ziglar" },
  { text: "If it doesn't challenge you, it won't change you.", author: "Fred DeVito" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "You are what you do, not what you say you'll do.", author: "Carl Jung" },
  { text: "Go the extra mile. It's never crowded there.", author: "Wayne Dyer" },
  { text: "Stay positive. Work hard. Make it happen.", author: "Unknown" },
  { text: "Focus. Commit. Succeed.", author: "Unknown" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Never bend your head. Always hold it high. Look the world straight in the eye.", author: "Helen Keller" },
  { text: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
  { text: "If you don't go after what you want, you'll never have it.", author: "Nora Roberts" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
]

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ─── GOLF QUOTES (200) ───────────────────────────────────────────────────
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export const GOLF_QUOTES = [
  { text: "Golf is deceptively simple and endlessly complicated.", author: "Arnold Palmer" },
  { text: "The most important shot in golf is the next one.", author: "Ben Hogan" },
  { text: "Golf is a game that is played on a five-inch course — the distance between your ears.", author: "Bobby Jones" },
  { text: "Success in golf depends less on strength of body than upon strength of mind and character.", author: "Arnold Palmer" },
  { text: "Through years of experience I have found that air offers less resistance than dirt.", author: "Jack Nicklaus" },
  { text: "Golf is about how well you accept, respond to, and score with your misses.", author: "Dr Bob Rotella" },
  { text: "I never learned anything from a match that I won.", author: "Bobby Jones" },
  { text: "The harder I practice, the luckier I get.", author: "Gary Player" },
  { text: "In golf as in life, it is the follow through that makes the difference.", author: "Unknown" },
  { text: "Golf is a game whose aim is to hit a very small ball into an even smaller hole.", author: "Winston Churchill" },
  { text: "If you're caught on a golf course during a storm and are afraid of lightning, hold up a 1-iron.", author: "Lee Trevino" },
  { text: "The only thing a golfer needs is more daylight.", author: "Ben Hogan" },
  { text: "I'm about five inches from being an outstanding golfer. That's the distance my left ear is from my right.", author: "Ben Crenshaw" },
  { text: "Concentration is a fine antidote to anxiety.", author: "Jack Nicklaus" },
  { text: "A bad attitude is worse than a bad swing.", author: "Payne Stewart" },
  { text: "Resolve never to quit, never to give up, no matter what the situation.", author: "Jack Nicklaus" },
  { text: "Eighteen holes of match play will teach you more about your foe than 18 years of dealing with him across a desk.", author: "Grantland Rice" },
  { text: "Of all the hazards, fear is the worst.", author: "Sam Snead" },
  { text: "Confidence is the most important single factor in this game.", author: "Jack Nicklaus" },
  { text: "Golf is the closest game to the game we call life.", author: "Bobby Jones" },
  { text: "There is no similarity between golf and putting; they are two different games.", author: "Ben Hogan" },
  { text: "It took me seventeen years to get three thousand hits in baseball. It took one afternoon on the golf course.", author: "Hank Aaron" },
  { text: "I never rooted against an opponent, but I never rooted for him either.", author: "Arnold Palmer" },
  { text: "One of the most fascinating things about golf is how it reflects the cycle of life.", author: "Tom Watson" },
  { text: "You create your own luck by the way you play.", author: "Greg Norman" },
  { text: "Golf is ninety percent mental, and the other ten percent is mental.", author: "Jim Flick" },
  { text: "Don't be too proud to take lessons. I'm not.", author: "Jack Nicklaus" },
  { text: "They say golf is like life, but don't believe them. Golf is more complicated than that.", author: "Gardner Dickinson" },
  { text: "The ardent golfer would play Mount Everest if somebody would put a flagstick on top.", author: "Pete Dye" },
  { text: "Hitting the ball is the fun part of it, but the score is what counts.", author: "Tiger Woods" },
  { text: "The zone is when your muscles and your mind are in complete harmony.", author: "Tiger Woods" },
  { text: "You swing your best when you have the fewest things to think about.", author: "Bobby Jones" },
  { text: "Golf is a compromise between what your ego wants you to do, what experience tells you to do, and what your nerves let you do.", author: "Bruce Crampton" },
  { text: "Drive for show, putt for dough.", author: "Bobby Locke" },
  { text: "Golf tips are like aspirin. One may do you good, but if you swallow the whole bottle you'll be lucky to survive.", author: "Harvey Penick" },
  { text: "Take it easy and lazily, because the golf ball isn't going to run away from you while you're swinging.", author: "Sam Snead" },
  { text: "Forget your opponents; always play against par.", author: "Sam Snead" },
  { text: "The more I work and practice, the luckier I seem to get.", author: "Gary Player" },
  { text: "It is nothing new or original to say that golf is played one stroke at a time.", author: "Bobby Jones" },
  { text: "If you drink, don't drive. Don't even putt.", author: "Dean Martin" },
  { text: "The one-iron is almost unplayable. You keep it in your bag the way you keep a Dostoyevsky novel in your bookcase.", author: "Jim Murray" },
  { text: "Real golfers go to work to relax.", author: "George Dillon" },
  { text: "Give me golf clubs, fresh air, and a beautiful partner, and you can keep the clubs and the fresh air.", author: "Jack Benny" },
  { text: "I know I am getting better at golf because I am hitting fewer spectators.", author: "Gerald Ford" },
  { text: "If I had to choose between my wife and my putter, I'd miss her.", author: "Gary Player" },
  { text: "Nobody asked how you looked, just what you shot.", author: "Sam Snead" },
  { text: "Putting is like wisdom — partly a natural gift and partly the accumulation of experience.", author: "Arnold Palmer" },
  { text: "A passion, an obsession, a romance, a nice acquaintanceship with trees, sand, and water.", author: "Bob Ryan" },
  { text: "Half of golf is fun; the other half is putting.", author: "Peter Dobereiner" },
  { text: "Keep your sense of humor. There's enough stress in the rest of your life to not let bad shots ruin a round.", author: "Amy Alcott" },
  { text: "The uglier a man's legs are, the better he plays golf — it's almost a law.", author: "H.G. Wells" },
  { text: "I have a tip that can take five strokes off anyone's golf game: it's called an eraser.", author: "Arnold Palmer" },
  { text: "You are meant to play the ball as it lies.", author: "Bobby Jones" },
  { text: "The woods are full of long hitters.", author: "Harvey Penick" },
  { text: "I learn teaching from teachers. I learn golf from golfers. I learn winning from coaches.", author: "Harvey Penick" },
  { text: "Relax? How can anybody relax and play golf? You have to grip the club, don't you?", author: "Ben Hogan" },
  { text: "Golf is a game in which you yell 'fore', shoot six, and write down five.", author: "Paul Harvey" },
  { text: "Reverse every natural instinct and do the opposite of what you are inclined to do, and you will probably come very close to having a perfect golf swing.", author: "Ben Hogan" },
  { text: "Golf is a good walk spoiled.", author: "Mark Twain" },
  { text: "I never missed a putt in my mind.", author: "Jack Nicklaus" },
  { text: "Golf is 20 percent talent and 80 percent management.", author: "Ben Hogan" },
  { text: "I owe everything to golf. Where else could a guy with an IQ like mine make this much money?", author: "Hubert Green" },
  { text: "The secret of golf is to turn three shots into two.", author: "Bobby Jones" },
  { text: "I play with friends, but we don't play friendly games.", author: "Ben Hogan" },
  { text: "Golf is so popular simply because it is the best game in the world at which to be bad.", author: "A.A. Milne" },
  { text: "What other people may find in poetry or art museums, I find in the flight of a good drive.", author: "Arnold Palmer" },
  { text: "Thinking instead of acting is the number one disease in golf.", author: "Sam Snead" },
  { text: "I regard golf as an expensive way of playing marbles.", author: "G.K. Chesterton" },
  { text: "After all these years, it's still embarrassing for me to play on the American golf tour.", author: "Seve Ballesteros" },
  { text: "Serenity is knowing that your worst shot is still pretty good.", author: "Johnny Miller" },
  { text: "To find a man's true character, play a round of golf with him.", author: "P.G. Wodehouse" },
  { text: "Competitive golf is played mainly on a five-and-a-half-inch course — the space between your ears.", author: "Bobby Jones" },
  { text: "Don't hurry. Don't worry. You're only here for a short visit. So don't forget to stop and smell the roses.", author: "Walter Hagen" },
  { text: "It's how you deal with failure that determines how you achieve success.", author: "David Feherty" },
  { text: "The good news: I saw a great course today. The bad news: I was on it.", author: "Lee Trevino" },
  { text: "One reward golf has given me, and I shall always be thankful for it, is introducing me to some of the world's most picturesque, tiresome and memorable people.", author: "Stephen Potter" },
  { text: "There's an old saying: if a man comes home with sand in his cuffs and cockleburs in his pants, don't ask him what he shot.", author: "Sam Snead" },
  { text: "Professional golf is the only sport where, if you win 20% of the time, you're the best.", author: "Jack Nicklaus" },
  { text: "The game of golf would lose a great deal if croquet mallets and billiard cues were allowed on the putting green.", author: "Ernest Hemingway" },
  { text: "Golf is a game that needlessly prolongs the lives of some of our most useless citizens.", author: "Bob Hope" },
  { text: "I have always had a drive that pushed me to try for perfection.", author: "Tiger Woods" },
  { text: "No matter how good you get you can always get better, and that's the exciting part.", author: "Tiger Woods" },
  { text: "You must work very hard to become a natural golfer.", author: "Gary Player" },
  { text: "I always feel pressure. If you don't feel nervous, that means you don't care about how you play.", author: "Tiger Woods" },
  { text: "Sometimes the biggest problem is in your head. You've got to believe.", author: "Jack Nicklaus" },
  { text: "Achievements on the golf course are not what matters, decency and honesty are what matter.", author: "Tiger Woods" },
  { text: "Golf can best be defined as an endless series of tragedies obscured by the occasional miracle.", author: "Unknown" },
  { text: "The less skilled the player, the more likely he is to share his ideas about the golf swing.", author: "Unknown" },
  { text: "I have found the game to be, in all factualness, a universal language.", author: "Arnold Palmer" },
  { text: "It's a funny thing, the more I practice, the luckier I get.", author: "Gary Player" },
  { text: "You can make a lot of money in this game. Just ask my ex-wives.", author: "Lee Trevino" },
  { text: "I'm hitting the woods just great, but I'm having a terrible time getting out of them.", author: "Harry Toscano" },
  { text: "Golf puts a man's character on the anvil and his richest qualities — patience, poise, restraint — to the flame.", author: "Billy Casper" },
  { text: "If there is a ball on the fringe and a ball in the bunker, I will take the ball in the bunker every time.", author: "Phil Mickelson" },
  { text: "My swing is so bad I look like a caveman killing his lunch.", author: "Lee Trevino" },
  { text: "If you want to increase your success rate, double your failure rate.", author: "Tom Watson" },
  { text: "The number one thing in winning golf? Confidence.", author: "Jack Nicklaus" },
  { text: "I may be the only golfer never to have broken a single club.", author: "Tom Watson" },
  { text: "You don't know what pressure is until you play for five bucks with only two in your pocket.", author: "Lee Trevino" },
  { text: "Whenever I play with Gerald Ford, I try to make it a foursome — the President, myself, a paramedic, and a faith healer.", author: "Bob Hope" },
  { text: "If you watch a game, it's fun. If you play at it, it's recreation. If you work at it, it's golf.", author: "Bob Hope" },
  { text: "The mind messes up more shots than the body.", author: "Tommy Bolt" },
  { text: "Golf is a thinking man's game. You can have all the shots in the bag, but if you don't know what to do with them, you've got troubles.", author: "Chi Chi Rodriguez" },
  { text: "Every day I try to tell myself that this is going to be fun today.", author: "Phil Mickelson" },
  { text: "My butterflies are still going strong. I just hope they are flying in formation.", author: "Larry Mize" },
  { text: "I'm going to win so much money this year, my caddie will make the top 20 money winners list.", author: "Lee Trevino" },
  { text: "Confidence in golf means being able to concentrate on the problem at hand with no outside interference.", author: "Tom Watson" },
  { text: "Enjoy the game. Happy golf is good golf.", author: "Gary Player" },
  { text: "The only sure rule in golf is — he who has the fastest cart never has to play the bad lie.", author: "Mickey Mantle" },
  { text: "Never break your putter and your driver in the same round or you're dead.", author: "Tommy Bolt" },
  { text: "If profanity had an influence on the flight of the ball, the game would be played far better than it is.", author: "Horace G. Hutchinson" },
  { text: "Golf and sex are about the only things you can enjoy without being good at.", author: "Jimmy Demaret" },
  { text: "The only time my prayers are never answered is on the golf course.", author: "Billy Graham" },
  { text: "I'm about as religious as I am good at golf — and that's not saying much.", author: "Unknown" },
  { text: "May thy ball lie in green pastures and not in still waters.", author: "Unknown" },
  { text: "Golf is not a game of good shots. It's a game of bad shots.", author: "Ben Hogan" },
  { text: "Hit 'em hard. They'll land somewhere.", author: "Stewart Maiden" },
  { text: "Every rock bottom has become the solid foundation on which I rebuilt my life.", author: "J.K. Rowling" },
  { text: "The road to success is always under construction.", author: "Lily Tomlin" },
  { text: "Tough times don't last. Tough people do.", author: "Robert H. Schuller" },
  { text: "I never lose. I either win or learn.", author: "Nelson Mandela" },
  { text: "Impossible is just a word thrown around by small men.", author: "Muhammad Ali" },
  { text: "Whether you think you can or think you can't, you're right.", author: "Henry Ford" },
  { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { text: "I can accept failure. Everyone fails at something. But I can't accept not trying.", author: "Michael Jordan" },
  { text: "It's not the will to win that matters. It's the will to prepare to win.", author: "Paul Bear Bryant" },
  { text: "Success is peace of mind which is a direct result of knowing you did your best.", author: "John Wooden" },
  { text: "The only way to prove that you're a good sport is to lose.", author: "Ernie Banks" },
  { text: "It ain't over till it's over.", author: "Yogi Berra" },
  { text: "To give anything less than your best is to sacrifice the gift.", author: "Steve Prefontaine" },
  { text: "Good players win matches. Great players win tournaments.", author: "Unknown" },
  { text: "Commitment leads to action. Action brings your dream closer.", author: "Marcia Wieder" },
  { text: "Golf is the loneliest sport. You're completely alone with every conceivable opportunity to defeat yourself.", author: "Hale Irwin" },
  { text: "Some of us worship in churches, some in synagogues, some on golf courses.", author: "Adlai Stevenson" },
  { text: "The course is there. You just have to go find it.", author: "Tiger Woods" },
  { text: "Be brave. Take risks. Nothing can substitute experience.", author: "Paulo Coelho" },
  { text: "Persistence is the twin sister of excellence. One is a matter of quality; the other, a matter of time.", author: "Marabel Morgan" },
  { text: "The greatest risk is not taking one.", author: "Unknown" },
  { text: "Progress is impossible without change.", author: "George Bernard Shaw" },
  { text: "Stay patient. Stay focused. Stay hungry.", author: "Unknown" },
  { text: "Control what you can. Let go of what you can't.", author: "Unknown" },
  { text: "Smooth seas do not make skillful sailors.", author: "African Proverb" },
  { text: "Small steps in the right direction can turn out to be the biggest step of your life.", author: "Unknown" },
  { text: "What seems like the end is often the beginning.", author: "Unknown" },
  { text: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Steve Jobs" },
  { text: "Your biggest opponent isn't the other guy. It's human nature.", author: "Bobby Knight" },
  { text: "A bad day of golf still beats a good day of work.", author: "Unknown" },
  { text: "Golf teaches us that the next shot is the most important.", author: "Unknown" },
  { text: "Trust your swing. Trust your preparation. Trust yourself.", author: "Unknown" },
]
