'use client'

import Link from 'next/link'
import SportRoleTabs from '../components/SportRoleTabs'
import { RUGBY_ROLES } from '../components/sportRoles'

const PURPLE = '#7C3AED'
const PURPLE_DEEP = '#5B21B6'
const PURPLE_LIGHT = '#A78BFA'
const BG = '#07080F'
const CARD = '#0D1117'
const CARD_ALT = '#111827'
const BORDER = '#1E293B'
const BORDER_ALT = '#1F2937'
const TEXT = '#F9FAFB'
const MUTED = '#9CA3AF'

const STAT_PILLS = ['🏉 Championship Rugby', '⚖️ Salary Cap', '📡 GPS + AI', '🏆 Franchise Tracker', '🤖 Claude API']

const FEATURES: Array<{ icon: string; title: string; desc: string; badge?: string }> = [
  { icon: '⚖️', title: 'Salary Cap Intelligence', desc: 'Live three-zone cap indicator, player-by-player cap charge, academy credits, central contract discounts, and a scenario modeller that shows the exact cap impact of every signing before you make it.' },
  { icon: '🤖', title: 'AI Halftime Brief', desc: 'GPS first-half load data + FrameSports video tags (scrums, lineouts, rucks) + Claude API → structured coaching brief on the Head Coach\u2019s iPad within 4 minutes of the halftime whistle. Nothing like this exists in Championship Rugby.', badge: 'World first' },
  { icon: '📡', title: 'GPS & Player Heatmaps', desc: '28-day rolling ACWR for all 38 players. Green/amber/red zones. S&C coach alerted at 07:30 when any player enters amber. Position x/y heatmaps rendered on a pitch diagram — filterable by player, session, and match.' },
  { icon: '🏆', title: 'Franchise Readiness Tracker', desc: '6-criterion RFU readiness score with per-criterion evidence vault, Expression of Interest document builder, and gap analysis vs Premiership threshold. Automated alerts 30, 14, and 7 days before RFU submission deadlines.' },
  { icon: '📐', title: 'Set Piece Analytics', desc: 'Lineout win% by zone, call success rate per routine, scrum outcome breakdown, restart retention, and goal-kicking by angle — all auto-populated from FrameSports tagged video.' },
  { icon: '📊', title: '8 Role Dashboards', desc: 'Director of Rugby, Head Coach, Head of Medical, Head of Recruitment, Academy Director, Head of Analysis, Commercial Director, CEO/Chairman — each with their own tailored view.' },
  { icon: '🔁', title: 'Transfers + AI Researcher', desc: 'Unified transfer window tracker — incoming targets, outgoing risks, cap impact per signing. 4-step AI Transfer Researcher: input position + budget + playing style → Claude returns 5 Championship-market profiles filtered to your cap headroom.' },
  { icon: '🛡️', title: 'Welfare & Concussion Suite', desc: 'World Rugby HIA protocol tracker, Return to Play stage management, mental performance mood tracking, and a full welfare audit dashboard. GPS contact events feed HIA risk management.' },
]

const AI_FEATURES = [
  { icon: '🌅', title: 'AI DoR Briefing', body: 'Personalised 400-word Director of Rugby morning brief at 07:30. GPS ACWR flags, cap headroom, franchise score, match week context, welfare flags, and three priorities for the day — all generated by Claude in seconds.' },
  { icon: '🏉', title: 'AI Halftime Brief', body: 'GPS + FrameSports video tags → structured coaching brief in under 4 minutes. Physical load, set piece, contact & breakdown, 3 adjustments, substitution call, team talk. Delivered before the coach finishes their coffee.' },
  { icon: '🔁', title: 'AI Rotation Model', body: 'Input your fixture list, ACWR profiles, and injury flags → Claude generates a 6-week squad rotation plan to peak for your priority matches. Per-fixture selection notes, load targets, and academy opportunities.' },
]

const INTEGRATIONS = [
  { icon: '📡', name: 'Lumio GPS', desc: 'GPS vest load and position data' },
  { icon: '💗', name: 'Lumio Health', desc: 'Player readiness and welfare' },
  { icon: '🎬', name: 'Lumio Vision', desc: 'Video analysis and clips' },
  { icon: '📹', name: 'FrameSports', desc: 'Set piece and contact tagging' },
  { icon: '🏉', name: 'RFU Data API', desc: 'Franchise and compliance data' },
  { icon: '🤖', name: 'Claude API', desc: 'AI briefings and rotation' },
  { icon: '🎵', name: 'ElevenLabs', desc: 'Voice briefing delivery' },
]

const SIDEBAR_GROUPS = [
  { label: 'CLUB OVERVIEW', count: 5 }, { label: 'SALARY CAP', count: 4 },
  { label: 'FRANCHISE', count: 4 }, { label: 'SQUAD', count: 6 },
  { label: 'PERFORMANCE', count: 9 }, { label: 'RECRUITMENT', count: 5 },
  { label: 'WELFARE', count: 5 }, { label: 'COMMERCIAL', count: 6 },
  { label: "WOMEN'S RUGBY", count: 4 }, { label: 'INTELLIGENCE', count: 5 },
]

// ── Mockup chrome ───────────────────────────────────────────────────────────
function MockupFrame({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ backgroundColor: CARD_ALT, border: `1px solid ${BORDER_ALT}`, borderRadius: 12, overflow: 'hidden', boxShadow: `0 30px 80px ${PURPLE}22` }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 14px', borderBottom: `1px solid ${BORDER_ALT}`, backgroundColor: '#0B1020' }}>
        <div style={{ display: 'flex', gap: 6 }}>
          <div style={{ width: 10, height: 10, borderRadius: '50%', backgroundColor: '#EF4444' }} />
          <div style={{ width: 10, height: 10, borderRadius: '50%', backgroundColor: '#F59E0B' }} />
          <div style={{ width: 10, height: 10, borderRadius: '50%', backgroundColor: '#10B981' }} />
        </div>
        <div style={{ flex: 1, height: 18, borderRadius: 5, backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}` }} />
      </div>
      <div style={{ padding: 18 }}>{children}</div>
    </div>
  )
}

function Badge({ children, color, bg }: { children: React.ReactNode; color: string; bg: string }) {
  return <span style={{ fontSize: 9, fontWeight: 800, padding: '3px 8px', borderRadius: 999, color, backgroundColor: bg, border: `1px solid ${color}55`, letterSpacing: '0.05em', textTransform: 'uppercase' }}>{children}</span>
}

function KPI({ value, label, sub, color }: { value: string; label: string; sub?: string; color: string }) {
  return (
    <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${color}55`, borderRadius: 10, padding: 12 }}>
      <div style={{ fontSize: 18, fontWeight: 900, color }}>{value}</div>
      <div style={{ fontSize: 9, fontWeight: 700, color: TEXT, marginTop: 2, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{label}</div>
      {sub && <div style={{ fontSize: 9, color: MUTED, marginTop: 2 }}>{sub}</div>}
    </div>
  )
}

// ── Mockups ─────────────────────────────────────────────────────────────────
function DashboardMockup() {
  return (
    <MockupFrame>
      <div style={{ background: `linear-gradient(135deg, ${PURPLE}, ${PURPLE_LIGHT})`, borderRadius: 10, padding: 10, marginBottom: 10, color: '#fff' }}>
        <div style={{ fontSize: 10, fontWeight: 900 }}>Hartfield RFC — Director of Rugby Dashboard</div>
        <div style={{ fontSize: 8, marginTop: 4, opacity: 0.9 }}>Good morning, Steve. Match week — Jersey Reds (H) Saturday.</div>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6, marginBottom: 10 }}>
        <KPI value="£460k" label="Cap headroom" color={PURPLE} />
        <KPI value="71%" label="Franchise" sub="4 criteria met" color={PURPLE_LIGHT} />
        <KPI value="28/38" label="Fit" sub="Available" color="#10B981" />
        <KPI value="1.22" label="ACWR" sub="Team avg" color="#F59E0B" />
      </div>
      <div style={{ backgroundColor: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.45)', borderRadius: 10, padding: 10, marginBottom: 8 }}>
        <div style={{ fontSize: 10, color: '#EF4444', fontWeight: 800 }}>⚠ Danny Foster — HIA Protocol Day 8</div>
        <div style={{ fontSize: 9, color: MUTED, marginTop: 2 }}>Must NOT be named in matchday 23 until cleared</div>
      </div>
      <div style={{ backgroundColor: 'rgba(245,158,11,0.1)', border: '1px solid rgba(245,158,11,0.45)', borderRadius: 10, padding: 10, marginBottom: 10 }}>
        <div style={{ fontSize: 10, color: '#F59E0B', fontWeight: 800 }}>⚠ Luke Barnes ACWR 1.52</div>
        <div style={{ fontSize: 9, color: MUTED, marginTop: 2 }}>Overload zone — S&C recommends rest today</div>
      </div>
      <div style={{ display: 'flex', gap: 5, flexWrap: 'wrap' }}>
        {['Cap Model', 'Selection', 'GPS Load', 'Franchise'].map(a => (
          <span key={a} style={{ fontSize: 8, padding: '4px 8px', borderRadius: 999, backgroundColor: `${PURPLE}22`, color: PURPLE_LIGHT, border: `1px solid ${PURPLE}55` }}>{a}</span>
        ))}
      </div>
    </MockupFrame>
  )
}

function GPSMockup() {
  return (
    <MockupFrame>
      <div style={{ fontSize: 11, fontWeight: 800, color: TEXT, marginBottom: 2 }}>📡 GPS & Load — Squad Dashboard</div>
      <div style={{ fontSize: 9, color: MUTED, marginBottom: 12 }}>28-day rolling ACWR · All 38 players · Lumio GPS</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6, marginBottom: 10 }}>
        <KPI value="14" label="Ready" sub="Optimal" color="#10B981" />
        <KPI value="1" label="Manage" color="#F59E0B" />
        <KPI value="2" label="Rest" sub="Overload" color="#EF4444" />
        <KPI value="3" label="Build" sub="Underload" color="#3B82F6" />
      </div>
      <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}`, borderRadius: 10, padding: 10, marginBottom: 8 }}>
        <div style={{ fontSize: 9, fontWeight: 800, color: TEXT, marginBottom: 6 }}>Player Heatmap — Luke Barnes (Fullback)</div>
        <svg viewBox="0 0 200 120" style={{ width: '100%' }}>
          <rect width={200} height={120} fill="#0a1a0a" rx={4} />
          <line x1={0} y1={60} x2={200} y2={60} stroke="rgba(255,255,255,0.15)" strokeWidth={1} />
          <line x1={0} y1={26} x2={200} y2={26} stroke="rgba(255,255,255,0.1)" strokeWidth={0.5} strokeDasharray="3 2" />
          <line x1={0} y1={94} x2={200} y2={94} stroke="rgba(255,255,255,0.1)" strokeWidth={0.5} strokeDasharray="3 2" />
          <circle cx={100} cy={30} r={22} fill={PURPLE} opacity={0.5} />
          <circle cx={60} cy={50} r={14} fill={PURPLE} opacity={0.35} />
          <circle cx={140} cy={50} r={14} fill={PURPLE} opacity={0.35} />
          <circle cx={100} cy={70} r={10} fill="#3B82F6" opacity={0.3} />
          <text x={100} y={115} textAnchor="middle" fill="rgba(255,255,255,0.3)" fontSize={6}>OPP TRY LINE</text>
        </svg>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 6 }}>
        <KPI value="12.3 km" label="Distance" color={PURPLE} />
        <KPI value="1120 m" label="HI Running" color={PURPLE_LIGHT} />
        <KPI value="31.9" label="Max km/h" color="#3B82F6" />
      </div>
    </MockupFrame>
  )
}

function CapMockup() {
  return (
    <MockupFrame>
      <div style={{ fontSize: 11, fontWeight: 800, color: TEXT, marginBottom: 2 }}>⚖️ Salary Cap Dashboard</div>
      <div style={{ fontSize: 9, color: MUTED, marginBottom: 12 }}>Championship Rugby · 2025/26 Season</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 6, marginBottom: 10 }}>
        <KPI value="£2.8M" label="Cap Ceiling" color={PURPLE} />
        <KPI value="£2.34M" label="Current Spend" color={PURPLE_LIGHT} />
        <KPI value="£460k" label="Headroom" color="#10B981" />
      </div>
      <div style={{ marginBottom: 10 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 9, marginBottom: 3 }}>
          <span style={{ color: TEXT }}>Cap utilisation</span>
          <span style={{ color: PURPLE_LIGHT, fontWeight: 800 }}>84%</span>
        </div>
        <div style={{ height: 8, borderRadius: 4, backgroundColor: '#1F2937', overflow: 'hidden' }}>
          <div style={{ width: '84%', height: '100%', borderRadius: 4, background: `linear-gradient(90deg, ${PURPLE}, ${PURPLE_LIGHT})` }} />
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 8, color: MUTED, marginTop: 4 }}>
          <span>Green zone (&lt;80%)</span><span>Amber (80–90%)</span><span>Red (&gt;90%)</span>
        </div>
      </div>
      <div style={{ backgroundColor: 'rgba(245,158,11,0.1)', border: '1px solid rgba(245,158,11,0.45)', borderRadius: 10, padding: 10 }}>
        <div style={{ fontSize: 10, color: '#F59E0B', fontWeight: 800 }}>⚠ Amber zone — 84% utilised</div>
        <div style={{ fontSize: 9, color: MUTED, marginTop: 2 }}>Board notification triggered at 80%</div>
      </div>
    </MockupFrame>
  )
}

function BriefingMockup() {
  return (
    <MockupFrame>
      <div style={{ fontSize: 11, fontWeight: 800, color: TEXT, marginBottom: 2 }}>🤖 Lumio AI — Director of Rugby Briefing</div>
      <div style={{ fontSize: 9, color: MUTED, marginBottom: 10 }}>Generated 07:30 · Based on live squad, GPS &amp; cap data</div>
      <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${PURPLE}55`, borderRadius: 10, padding: 12, marginBottom: 10 }}>
        <p style={{ fontSize: 10, color: TEXT, lineHeight: 1.65, margin: 0, fontStyle: 'italic' }}>
          &ldquo;Good morning. Match week — Jersey Reds Saturday. Danny Foster still in HIA protocol, day 8. Luke Barnes in overload zone. Cap headroom is £460k — enough for the LHP signing. Franchise score at 71% — CoE inspection due September. Three priorities today.&rdquo;
        </p>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 6, marginBottom: 10 }}>
        <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}`, borderRadius: 8, padding: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 800, color: '#EF4444', marginBottom: 3 }}>⚠ WELFARE</div>
          <div style={{ fontSize: 9, color: MUTED }}>Foster HIA · Barnes overload · 2 amber ACWR</div>
        </div>
        <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}`, borderRadius: 8, padding: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 800, color: '#10B981', marginBottom: 3 }}>⚖️ CAP</div>
          <div style={{ fontSize: 9, color: MUTED }}>£460k headroom · LHP target: £78k/yr</div>
        </div>
        <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}`, borderRadius: 8, padding: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 800, color: PURPLE_LIGHT, marginBottom: 3 }}>🏆 FRANCHISE</div>
          <div style={{ fontSize: 9, color: MUTED }}>71% ready · CoE inspection Sep 2026</div>
        </div>
        <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}`, borderRadius: 8, padding: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 800, color: '#3B82F6', marginBottom: 3 }}>🏉 MATCH</div>
          <div style={{ fontSize: 9, color: MUTED }}>Jersey Reds (H) Sat · Selection Thu</div>
        </div>
      </div>
      <button style={{ width: '100%', fontSize: 10, fontWeight: 800, padding: '8px 12px', borderRadius: 8, backgroundColor: PURPLE, color: '#fff', border: 'none' }}>▶ Play voice briefing (3m 12s)</button>
    </MockupFrame>
  )
}

// ── Spotlight wrapper ────────────────────────────────────────────────────────
function Spotlight({ eyebrow, title, body, bullets, mockup, reverse, altBg }: {
  eyebrow: string; title: string; body: string; bullets: string[]; mockup: React.ReactNode; reverse?: boolean; altBg?: boolean
}) {
  return (
    <section style={{ padding: '96px 24px', backgroundColor: altBg ? '#0A0C14' : BG }}>
      <div style={{ maxWidth: 1200, margin: '0 auto', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 64, alignItems: 'center' }}>
        <div style={{ order: reverse ? 2 : 1 }}>
          <div style={{ fontSize: 12, fontWeight: 800, color: PURPLE_LIGHT, letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: 12 }}>{eyebrow}</div>
          <h2 style={{ fontSize: 40, fontWeight: 900, color: TEXT, marginBottom: 16, lineHeight: 1.1 }}>{title}</h2>
          <p style={{ fontSize: 16, color: MUTED, lineHeight: 1.6, marginBottom: 24 }}>{body}</p>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 10 }}>
            {bullets.map(b => (
              <li key={b} style={{ display: 'flex', alignItems: 'flex-start', gap: 10, fontSize: 15, color: TEXT }}>
                <span style={{ color: PURPLE_LIGHT, fontWeight: 900, flexShrink: 0 }}>✓</span>
                <span>{b}</span>
              </li>
            ))}
          </ul>
        </div>
        <div style={{ order: reverse ? 1 : 2 }}>{mockup}</div>
      </div>
    </section>
  )
}

// ── Page ─────────────────────────────────────────────────────────────────────
export default function RugbyLandingPage() {
  return (
    <div style={{ backgroundColor: BG, color: TEXT, minHeight: '100vh' }}>
      {/* ── HERO ── */}
      <section style={{ minHeight: '100vh', padding: '120px 24px 80px', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', inset: 0, background: `radial-gradient(circle at 20% 10%, ${PURPLE}33, transparent 50%), radial-gradient(circle at 80% 60%, ${PURPLE_LIGHT}22, transparent 55%)`, pointerEvents: 'none' }} />
        <div style={{ position: 'relative', maxWidth: 1200, margin: '0 auto', textAlign: 'center' }}>
          <div style={{ fontSize: 13, fontWeight: 800, letterSpacing: '0.2em', color: PURPLE_LIGHT, textTransform: 'uppercase', marginBottom: 24 }}>
            LUMIO RUGBY
          </div>
          <h1 style={{ fontSize: 'clamp(44px, 7vw, 80px)', fontWeight: 900, lineHeight: 1.05, color: TEXT, marginBottom: 24, maxWidth: 1000, marginLeft: 'auto', marginRight: 'auto' }}>
            The Championship Rugby Club OS.
          </h1>
          <p style={{ fontSize: 20, color: MUTED, lineHeight: 1.6, maxWidth: 860, margin: '0 auto 40px' }}>
            Salary cap intelligence. GPS-powered performance analytics. AI Halftime Brief. Franchise readiness tracking. Everything a Championship or Premiership club needs — in one platform.
          </p>
          <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap', marginBottom: 48 }}>
            <Link href="/rugby/hartfield" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '18px 32px', borderRadius: 12, backgroundColor: PURPLE, color: '#fff', fontSize: 16, fontWeight: 800, textDecoration: 'none', boxShadow: `0 20px 50px ${PURPLE}66` }}>
              View demo →
            </Link>
            <Link href="/contact" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '18px 32px', borderRadius: 12, backgroundColor: 'transparent', color: TEXT, fontSize: 16, fontWeight: 800, textDecoration: 'none', border: `1px solid ${BORDER}` }}>
              Book a club demo
            </Link>
          </div>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            {STAT_PILLS.map(p => (
              <span key={p} style={{ padding: '10px 18px', borderRadius: 999, backgroundColor: `${PURPLE}1A`, border: `1px solid ${PURPLE}66`, color: PURPLE_LIGHT, fontSize: 13, fontWeight: 700 }}>{p}</span>
            ))}
          </div>
        </div>
      </section>

      {/* ── PORTAL PREVIEW STRIP ── */}
      <section style={{ padding: '0 24px 64px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 12, backgroundColor: CARD, border: `1px solid ${PURPLE}44`, borderRadius: 16, padding: 20 }}>
            {[
              { value: '£460k', label: 'Cap Headroom' },
              { value: '71%', label: 'Franchise' },
              { value: '28', label: 'Squad Available' },
              { value: '1.22', label: 'ACWR' },
              { value: 'Sat', label: 'vs Jersey Reds' },
            ].map(s => (
              <div key={s.label} style={{ textAlign: 'center' }}>
                <div style={{ fontSize: 22, fontWeight: 900, color: PURPLE_LIGHT }}>{s.value}</div>
                <div style={{ fontSize: 11, color: MUTED, marginTop: 4 }}>{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── FEATURE GRID ── */}
      <section id="features" style={{ padding: '96px 24px', backgroundColor: '#0A0C14' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <h2 style={{ fontSize: 44, fontWeight: 900, color: TEXT, textAlign: 'center', marginBottom: 16, lineHeight: 1.1 }}>
            53 sections. One Club OS.
          </h2>
          <p style={{ fontSize: 16, color: MUTED, textAlign: 'center', marginBottom: 56 }}>
            Purpose-built for Championship and Premiership rugby clubs.
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 20 }}>
            {FEATURES.map(f => (
              <div key={f.title} style={{ backgroundColor: CARD, border: `1px solid ${BORDER}`, borderRadius: 16, padding: 24, position: 'relative' }}>
                {f.badge && <div style={{ position: 'absolute', top: 12, right: 12 }}><Badge color={PURPLE_LIGHT} bg={`${PURPLE}33`}>{f.badge}</Badge></div>}
                <div style={{ fontSize: 32, marginBottom: 12 }}>{f.icon}</div>
                <h3 style={{ fontSize: 18, fontWeight: 800, color: TEXT, marginBottom: 8 }}>{f.title}</h3>
                <p style={{ fontSize: 14, color: MUTED, lineHeight: 1.6 }}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <SportRoleTabs sport="rugby" demoHref="/rugby/hartfield" accentColor={PURPLE} accentColorDim={`${PURPLE}26`} roles={RUGBY_ROLES} />

      {/* ── SPOTLIGHTS ── */}
      <Spotlight
        eyebrow="SPOTLIGHT · CLUB DASHBOARD"
        title="Your entire club. One morning view."
        body="The Lumio Rugby dashboard gives your Director of Rugby salary cap status, GPS overload alerts, franchise score, welfare flags, and match week context — all before the first coffee."
        bullets={['Live cap headroom with three-zone indicator', 'GPS ACWR alerts for all 38 players', 'Franchise readiness score with gap analysis', 'HIA and welfare flags surfaced immediately']}
        mockup={<DashboardMockup />}
      />

      <Spotlight
        altBg reverse
        eyebrow="SPOTLIGHT · GPS & HEATMAPS"
        title="Know every player\u2019s load. Every session."
        body="28-day rolling ACWR for the full squad. Player heatmaps rendered on a pitch diagram. S&C coach alerted at 07:30 when any player enters amber or red — before you name the team."
        bullets={['28-day rolling ACWR with green/amber/red zones', 'Position x/y heatmaps filterable by player and session', 'Daily load bar chart with session-by-session breakdown', 'Lumio GPS vest integration — zero manual upload']}
        mockup={<GPSMockup />}
      />

      <Spotlight
        eyebrow="SPOTLIGHT · SALARY CAP"
        title="Cap intelligence. Not spreadsheets."
        body="Live three-zone cap indicator, player-by-player charge, academy credits, central contract discounts, and a scenario modeller that shows the exact cap impact of every signing before you make it."
        bullets={['Three-zone cap indicator: green / amber / red', 'Scenario modeller — test any signing before committing', 'Academy credit and central contract discount applied', 'Audit trail for every change — Championship Rugby compliant']}
        mockup={<CapMockup />}
      />

      <Spotlight
        altBg reverse
        eyebrow="SPOTLIGHT · AI MORNING BRIEFING"
        title="Briefed before the first session."
        body="Lumio reads your GPS load, cap position, franchise score, welfare flags, and fixture context — then generates a personalised Director of Rugby briefing. Every morning, before you arrive at the ground."
        bullets={['GPS ACWR flags for every player', 'Cap headroom and signing impact', 'Franchise readiness and RFU deadlines', 'HIA protocol status and welfare alerts']}
        mockup={<BriefingMockup />}
      />

      {/* ── AI FEATURES HIGHLIGHT ── */}
      <section style={{ padding: '96px 24px', backgroundColor: '#0A0C14' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <h2 style={{ fontSize: 40, fontWeight: 900, color: TEXT, textAlign: 'center', marginBottom: 56, lineHeight: 1.1 }}>
            AI that changes how clubs operate.
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 24 }}>
            {AI_FEATURES.map(f => (
              <div key={f.title} style={{ backgroundColor: CARD, border: `1px solid ${PURPLE}55`, borderRadius: 16, padding: 28 }}>
                <div style={{ fontSize: 36, marginBottom: 12 }}>{f.icon}</div>
                <h3 style={{ fontSize: 20, fontWeight: 800, color: TEXT, marginBottom: 10 }}>{f.title}</h3>
                <p style={{ fontSize: 14, color: MUTED, lineHeight: 1.6 }}>{f.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── INTEGRATIONS ── */}
      <section style={{ padding: '96px 24px', backgroundColor: BG }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <h2 style={{ fontSize: 40, fontWeight: 900, color: TEXT, textAlign: 'center', marginBottom: 16, lineHeight: 1.1 }}>
            Integrated with the tools Championship clubs already use.
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, marginTop: 48 }}>
            {INTEGRATIONS.map(i => (
              <div key={i.name} style={{ display: 'flex', alignItems: 'center', gap: 14, backgroundColor: CARD, border: `1px solid ${BORDER}`, borderRadius: 12, padding: 16 }}>
                <div style={{ fontSize: 26 }}>{i.icon}</div>
                <div>
                  <div style={{ fontSize: 14, fontWeight: 800, color: TEXT }}>{i.name}</div>
                  <div style={{ fontSize: 12, color: MUTED }}>{i.desc}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── SIDEBAR OVERVIEW ── */}
      <section style={{ padding: '96px 24px', backgroundColor: '#0A0C14' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <h2 style={{ fontSize: 40, fontWeight: 900, color: TEXT, textAlign: 'center', marginBottom: 16, lineHeight: 1.1 }}>
            53 sections across 10 departments.
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 12, marginTop: 48 }}>
            {SIDEBAR_GROUPS.map(g => (
              <div key={g.label} style={{ backgroundColor: CARD, border: `1px solid ${PURPLE}44`, borderRadius: 12, padding: 16, textAlign: 'center' }}>
                <div style={{ fontSize: 24, fontWeight: 900, color: PURPLE_LIGHT }}>{g.count}</div>
                <div style={{ fontSize: 11, fontWeight: 700, color: TEXT, marginTop: 4, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{g.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── DEMO CLUB CALLOUT ── */}
      <section style={{ padding: '96px 24px', backgroundColor: BG }}>
        <div style={{ maxWidth: 800, margin: '0 auto' }}>
          <div style={{ backgroundColor: CARD, border: `1px solid ${PURPLE}55`, borderRadius: 16, padding: 32, display: 'grid', gridTemplateColumns: '1fr auto', gap: 32, alignItems: 'center' }}>
            <div>
              <div style={{ fontSize: 12, fontWeight: 800, color: PURPLE_LIGHT, letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: 8 }}>DEMO CLUB</div>
              <h3 style={{ fontSize: 28, fontWeight: 900, color: TEXT, marginBottom: 8 }}>Hartfield RFC</h3>
              <div style={{ fontSize: 14, color: MUTED, lineHeight: 1.7 }}>
                Championship Rugby · Round 18 · #4 in league<br />
                The Grange · 4,800 capacity<br />
                Club Pro+ · £599/mo
              </div>
            </div>
            <Link href="/rugby/hartfield" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '16px 28px', borderRadius: 12, backgroundColor: PURPLE, color: '#fff', fontSize: 15, fontWeight: 800, textDecoration: 'none', boxShadow: `0 16px 40px ${PURPLE}55`, whiteSpace: 'nowrap' }}>
              Explore the live demo →
            </Link>
          </div>
        </div>
      </section>

      {/* ── PRICING ── */}
      <section style={{ padding: '96px 24px', backgroundColor: '#0A0C14' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <h2 style={{ fontSize: 40, fontWeight: 900, color: TEXT, textAlign: 'center', marginBottom: 56, lineHeight: 1.1 }}>
            Simple pricing for rugby clubs.
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 24, maxWidth: 900, margin: '0 auto' }}>
            {/* Club Pro+ */}
            <div style={{ backgroundColor: CARD, border: `1px solid ${PURPLE}55`, borderRadius: 16, padding: 32 }}>
              <div style={{ fontSize: 13, fontWeight: 800, color: PURPLE_LIGHT, letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: 8 }}>CLUB PRO+</div>
              <div style={{ fontSize: 40, fontWeight: 900, color: TEXT, marginBottom: 4 }}>£599<span style={{ fontSize: 16, color: MUTED }}>/mo</span></div>
              <div style={{ fontSize: 13, color: MUTED, marginBottom: 20 }}>Championship clubs</div>
              <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
                {['All 53 sections', 'GPS & Player Heatmaps', 'AI Halftime Brief', 'Salary cap dashboard', 'Franchise readiness tracker', 'Lumio Vision set-piece tagging', 'Lumio Health readiness sync', 'Claude API (DoR brief + rotation)', 'Up to 45 players'].map(f => (
                  <li key={f} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, color: TEXT }}>
                    <span style={{ color: PURPLE_LIGHT }}>✓</span>{f}
                  </li>
                ))}
              </ul>
              <Link href="/contact" style={{ display: 'block', textAlign: 'center', marginTop: 24, padding: '14px 24px', borderRadius: 10, backgroundColor: PURPLE, color: '#fff', fontSize: 14, fontWeight: 800, textDecoration: 'none' }}>Start free trial</Link>
            </div>
            {/* Club Elite */}
            <div style={{ backgroundColor: CARD, border: `2px solid ${PURPLE}`, borderRadius: 16, padding: 32, position: 'relative' }}>
              <div style={{ position: 'absolute', top: -12, right: 24 }}><Badge color="#fff" bg={PURPLE}>Most popular</Badge></div>
              <div style={{ fontSize: 13, fontWeight: 800, color: PURPLE_LIGHT, letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: 8 }}>CLUB ELITE</div>
              <div style={{ fontSize: 40, fontWeight: 900, color: TEXT, marginBottom: 4 }}>£799<span style={{ fontSize: 16, color: MUTED }}>/mo</span></div>
              <div style={{ fontSize: 13, color: MUTED, marginBottom: 20 }}>Premiership-track clubs</div>
              <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
                {['Everything in Pro+', 'GPS vest fleet (18 vests included)', 'Full FrameSports integration (all matches)', 'Advanced analytics suite', "Women's Rugby module", 'Academy GPS profiles', 'Multi-club parent access', 'Dedicated onboarding manager', 'SLA support'].map(f => (
                  <li key={f} style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, color: TEXT }}>
                    <span style={{ color: PURPLE_LIGHT }}>✓</span>{f}
                  </li>
                ))}
              </ul>
              <Link href="/contact" style={{ display: 'block', textAlign: 'center', marginTop: 24, padding: '14px 24px', borderRadius: 10, backgroundColor: PURPLE, color: '#fff', fontSize: 14, fontWeight: 800, textDecoration: 'none', boxShadow: `0 12px 32px ${PURPLE}55` }}>Book a demo</Link>
            </div>
          </div>
        </div>
      </section>

      {/* ── FINAL CTA ── */}
      <section style={{ padding: '120px 24px', backgroundColor: BG, borderTop: `1px solid ${BORDER}` }}>
        <div style={{ maxWidth: 900, margin: '0 auto', textAlign: 'center' }}>
          <h2 style={{ fontSize: 48, fontWeight: 900, color: TEXT, marginBottom: 20, lineHeight: 1.1 }}>
            The Championship Rugby Club OS that coaches actually use.
          </h2>
          <p style={{ fontSize: 17, color: MUTED, lineHeight: 1.6, marginBottom: 32 }}>
            Join the clubs using Lumio Rugby to manage salary cap, GPS performance, franchise readiness, and AI coaching intelligence from one platform.
          </p>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap', marginBottom: 40 }}>
            {['53 sections', 'AI powered', 'GPS integrated', 'Franchise ready'].map(p => (
              <span key={p} style={{ padding: '10px 18px', borderRadius: 999, backgroundColor: `${PURPLE}1A`, border: `1px solid ${PURPLE}66`, color: PURPLE_LIGHT, fontSize: 13, fontWeight: 700 }}>{p}</span>
            ))}
          </div>
          <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link href="/rugby/hartfield" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '18px 32px', borderRadius: 12, backgroundColor: PURPLE, color: '#fff', fontSize: 16, fontWeight: 800, textDecoration: 'none', boxShadow: `0 20px 50px ${PURPLE}66` }}>
              View Hartfield RFC demo →
            </Link>
            <Link href="/contact" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '18px 32px', borderRadius: 12, backgroundColor: 'transparent', color: TEXT, fontSize: 16, fontWeight: 800, textDecoration: 'none', border: `1px solid ${BORDER}` }}>
              Book a walkthrough
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}
