'use client'

// HQ Equipment & Kit — mapped from the tennis coach Equipment module:
// stat tiles, restock list with tick-to-order, grab-and-go kit checklists,
// and the full inventory by category. Ten Project twist: welcome-pack stock
// (T-shirts, balls, booklets, stickers, certificates) tracked like court kit.

import React, { useState } from 'react'
import { Package, Printer, ShoppingCart, CheckCircle } from 'lucide-react'
import { Card, SectionTitle, Pill } from './ui'
import { TP_RED, TP_DARK, TP_EQUIP_STATS, TP_RESTOCK, TP_KITS, TP_INVENTORY } from '@/data/tenproject/demo-data'
import { shell, brandHeader, esc, openDocWindow } from '../_lib/funder-docs'

const STATUS_PILL: Record<string, { tone: 'green' | 'amber' | 'red' | 'grey'; label: string }> = {
  'in-stock': { tone: 'green', label: 'IN STOCK' },
  'running-low': { tone: 'amber', label: 'RUNNING LOW' },
  'to-order': { tone: 'red', label: 'TO ORDER' },
  'repair': { tone: 'red', label: 'REPAIR' },
}

function printKitList() {
  const body = `
    ${brandHeader('KIT LIST')}
    <h1>Ten Project — kit checklists</h1>
    <div class="sub">Grab-and-go lists per session type · print one per kit bag</div>
    ${TP_KITS.map(k => `<h2>${esc(k.name.toUpperCase())}</h2><ul>${k.items.map(i => `<li style="margin-bottom:5px">☐&nbsp; ${esc(i)}</li>`).join('')}</ul>`).join('')}
    <div class="foot">Ten Project Ltd · Generated by the Ten Project Portal</div>
  `
  openDocWindow(shell('Ten Project — Kit List', body))
}

export default function EquipmentTab() {
  const [ticked, setTicked] = useState<string[]>(TP_RESTOCK.map(r => r.id))
  const [ordered, setOrdered] = useState(false)

  return (
    <div style={{ display: 'grid', gap: 16 }}>
      <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: -50, marginBottom: 4, position: 'relative', zIndex: 1 }}>
        <button onClick={printKitList} style={{ display: 'inline-flex', alignItems: 'center', gap: 7, background: TP_DARK, color: '#fff', border: 'none', borderRadius: 9, padding: '9px 14px', fontSize: 12.5, fontWeight: 800, cursor: 'pointer' }}>
          <Printer size={14} /> Print kit list
        </button>
      </div>

      {/* Stats */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: 12 }}>
        {TP_EQUIP_STATS.map(s => (
          <Card key={s.label} style={{ padding: '13px 16px' }}>
            <div style={{ fontSize: 10, fontWeight: 800, color: '#8A847E', letterSpacing: 0.8 }}>{s.label}</div>
            <div style={{ fontSize: 23, fontWeight: 900, color: s.label === 'NEED ATTENTION' ? TP_RED : TP_DARK, marginTop: 3 }}>{s.value}</div>
          </Card>
        ))}
      </div>

      {/* Restock list */}
      <Card>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10, flexWrap: 'wrap', marginBottom: 10 }}>
          <SectionTitle sub="Tick what you need, then Source & order — the portal finds the supplier and drafts the order email">
            Restock list — never miss anything
          </SectionTitle>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span style={{ fontSize: 11.5, color: '#8A847E', fontWeight: 700 }}>{ticked.length} selected</span>
            <button onClick={() => setOrdered(true)} disabled={ticked.length === 0} style={{ display: 'inline-flex', alignItems: 'center', gap: 7, background: ticked.length ? TP_RED : '#D9D3CC', color: '#fff', border: 'none', borderRadius: 9, padding: '9px 14px', fontSize: 12.5, fontWeight: 800, cursor: ticked.length ? 'pointer' : 'not-allowed' }}>
              <ShoppingCart size={14} /> Source & order
            </button>
          </div>
        </div>
        {ordered && (
          <div style={{ background: '#E5F5EA', borderRadius: 10, padding: '10px 13px', marginBottom: 10, fontSize: 12.5, color: '#187A3C', fontWeight: 700 }}>
            <CheckCircle size={14} style={{ verticalAlign: '-2px', marginRight: 6 }} />
            Order drafted for {ticked.length} items — Zsig quote requested for court kit, print order for booklets/stickers. Awaiting your approval in Comms.
          </div>
        )}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))', gap: 10 }}>
          {TP_RESTOCK.map(r => {
            const on = ticked.includes(r.id)
            return (
              <button key={r.id} onClick={() => setTicked(prev => on ? prev.filter(x => x !== r.id) : [...prev, r.id])}
                style={{ display: 'flex', gap: 10, alignItems: 'flex-start', background: on ? '#FDE8E8' : '#F7F5F2', border: on ? `1.5px solid ${TP_RED}55` : '1.5px solid transparent', borderRadius: 10, padding: '11px 12px', cursor: 'pointer', textAlign: 'left' }}>
                <div style={{ width: 17, height: 17, borderRadius: 5, flexShrink: 0, marginTop: 1, background: on ? TP_RED : '#fff', border: on ? 'none' : '1.5px solid #D9D3CC', color: '#fff', fontSize: 11, fontWeight: 900, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>{on ? '✓' : ''}</div>
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', gap: 6 }}>
                    <span style={{ fontSize: 12.5, fontWeight: 800, color: TP_DARK }}>{r.name}</span>
                    <Pill tone={STATUS_PILL[r.status].tone}>{STATUS_PILL[r.status].label}</Pill>
                  </div>
                  <div style={{ fontSize: 10.5, color: '#6B6560', marginTop: 3 }}>{r.where}</div>
                </div>
              </button>
            )
          })}
        </div>
      </Card>

      {/* Kits */}
      <Card>
        <SectionTitle sub="Grab-and-go checklists — one per session type">Kit for each session type</SectionTitle>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(210px, 1fr))', gap: 10 }}>
          {TP_KITS.map(k => (
            <div key={k.name} style={{ background: '#F7F5F2', borderRadius: 12, padding: '13px 14px' }}>
              <div style={{ fontSize: 12.5, fontWeight: 900, color: TP_DARK, marginBottom: 8 }}>
                <Package size={13} style={{ verticalAlign: '-2px', marginRight: 6, color: TP_RED }} />{k.name}
              </div>
              <div style={{ display: 'grid', gap: 4 }}>
                {k.items.map(i => <div key={i} style={{ fontSize: 11.5, color: '#5B554F' }}>• {i}</div>)}
              </div>
            </div>
          ))}
        </div>
      </Card>

      {/* Inventory */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 12 }}>
        {TP_INVENTORY.map(cat => (
          <Card key={cat.category}>
            <SectionTitle>{cat.category}</SectionTitle>
            <div style={{ display: 'grid', gap: 8 }}>
              {cat.items.map(i => (
                <div key={i.name} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, background: '#F7F5F2', borderRadius: 9, padding: '9px 11px' }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontSize: 12, fontWeight: 800, color: TP_DARK }}>{i.name}</div>
                    <div style={{ fontSize: 10, color: '#8A847E', marginTop: 2 }}>{i.where}</div>
                  </div>
                  <span style={{ fontSize: 11.5, fontWeight: 900, color: TP_DARK, flexShrink: 0 }}>{i.qty}</span>
                  <Pill tone={STATUS_PILL[i.status].tone}>{STATUS_PILL[i.status].label}</Pill>
                </div>
              ))}
            </div>
          </Card>
        ))}
      </div>
    </div>
  )
}
