import type { SportRole } from './SportRoleTabs'

export const FOOTBALL_ROLES: SportRole[] = [
  {
    id: 'chairman',
    label: 'Chairman / Owner',
    icon: '🏛️',
    description: 'The full financial and governance picture — PSR compliance, wage ratios, windfall deployment, and fan sentiment — before the board meeting.',
    modules: [
      { name: 'Directors Suite', detail: 'Board-level financial dashboard with PSR compliance tracker and EFL governance reporting.' },
      { name: 'Finance & PSR', detail: 'Wage-to-revenue ratio, budget vs actual, revenue by stream, spend by department.' },
      { name: 'Fan Engagement', detail: 'NPS score, attendance trends, season ticket trajectory, social sentiment.' },
      { name: 'Board Report PDF', detail: 'One-click branded board report — ready for the monthly meeting.' },
    ],
    integrations: ['Xero', 'FA Whole Game System', 'EFL Portal', 'Supabase'],
    whatYouGet: [
      'PSR compliance status — red/amber/green at a glance',
      'Wage-to-revenue ratio vs EFL ceiling',
      'One-click Board Report PDF',
      'Fan NPS and season ticket trajectory',
      'Transfer window PSR headroom calculator',
    ],
  },
  {
    id: 'ceo',
    label: 'CEO / General Manager',
    icon: '💼',
    description: 'Commercial pipeline, staff management, facilities, matchday operations, and the full club health score — everything across the business.',
    modules: [
      { name: 'Club Insights', detail: 'Department health scores across squad, medical, transfers, commercial, finance, and governance.' },
      { name: 'Commercial & Sponsorship', detail: 'Sponsor pipeline, activation tracking, renewal dates, and revenue vs targets.' },
      { name: 'Fan Hub', detail: 'Attendance, NPS, season tickets, social sentiment, matchday revenue.' },
      { name: 'Staff & Facilities', detail: 'Staff headcount, contracts, facilities management, and operational checklists.' },
    ],
    integrations: ['Xero', 'HubSpot', 'Slack', 'FA Whole Game System'],
    whatYouGet: [
      'Morning club health dashboard — all departments in one view',
      'Priority action feed ranked by urgency',
      'Commercial pipeline and sponsor activation tracker',
      'AI-generated department summaries every morning',
      'Matchday operations checklist and revenue tracking',
    ],
  },
  {
    id: 'dof',
    label: 'Director of Football',
    icon: '🎯',
    description: 'Transfers, squad planning, contracts, scouting, academy pathway, and GPS load — the complete football operations picture.',
    modules: [
      { name: 'Transfer Intelligence', detail: 'AI Transfer Researcher, 5-column Kanban pipeline, agent contacts, deadline tracker.' },
      { name: 'Squad Management', detail: 'Full squad register, contracts, availability, injury status, and form guide.' },
      { name: 'Scouting Database', detail: 'Scout targets, watchlist, reports, and Wyscout integration.' },
      { name: 'Academy', detail: 'Youth pathway tracker, development ratings, and progression monitoring.' },
      { name: 'GPS & Load', detail: 'ACWR monitoring, pitch heatmaps, training load planner, injury risk flags.' },
    ],
    integrations: ['Wyscout', 'Lumio GPS', 'STATSports', 'Catapult', 'FA Whole Game System'],
    whatYouGet: [
      'AI Transfer Researcher — 5 targets with Lumio Fit Score',
      'Transfer Kanban pipeline with deadline countdown',
      'Squad availability and contract expiry alerts',
      'GPS pitch heatmaps and ACWR risk monitoring',
      'Academy pathway tracker with progression milestones',
    ],
  },
  {
    id: 'manager',
    label: 'Head Coach',
    icon: '📋',
    description: 'Match prep, tactics, opposition reports, the AI half-time GPS brief, post-match analysis, and press conference tools — everything for matchday.',
    modules: [
      { name: 'AI Half-Time GPS Brief', detail: 'Upload first-half vest data → Claude returns fatigue alerts, sub recommendation, and second-half instruction in 10 seconds.' },
      { name: 'Match Prep & Tactics', detail: 'Formation builder, set piece planner, opposition analysis, and pre-match team sheet.' },
      { name: 'AI Opposition Report', detail: 'Full scouting report: formation, key threats, weaknesses, 3 tactical suggestions, predicted lineup.' },
      { name: 'AI Post-Match Analysis', detail: 'Input scoreline and formation → Claude generates headline, key moments, player ratings, and manager quote.' },
      { name: 'Press Conference', detail: 'AI-generated 5 questions + suggested responses based on last result and team news.' },
    ],
    integrations: ['Hudl', 'Wyscout', 'Lumio GPS', 'STATSports'],
    whatYouGet: [
      'World-first AI half-time GPS brief in under 10 seconds',
      'AI opposition report with tactical suggestions',
      'Post-match analysis with player ratings',
      'Press conference briefing — 5 questions pre-prepared',
      'Formation and set piece planning tools',
    ],
  },
  {
    id: 'analyst',
    label: 'Data Analyst',
    icon: '📡',
    description: 'GPS performance, ACWR load tracking, pitch heatmaps, match analytics, club comparison, and AI post-session analysis — the full data stack.',
    modules: [
      { name: 'GPS Performance', detail: 'ACWR monitoring, pitch heatmaps, per-player readiness, distance and HSR tracking.' },
      { name: 'Training Load Planner', detail: 'Weekly player × day calendar with ACWR risk flags auto-generated on session creation.' },
      { name: 'AI Post-Session Analysis', detail: "Claude reads full squad GPS data → session rating, rest/push/injury watch lists, tomorrow's recommendation." },
      { name: 'Match Analytics', detail: 'xG, possession, pressing stats, formation data, and club comparison tool.' },
      { name: 'Club Comparison', detail: 'Compare vs 3 rivals + division average across 13 metrics with AI analysis.' },
    ],
    integrations: ['Lumio GPS', 'Catapult', 'STATSports', 'Opta', 'StatsBomb'],
    whatYouGet: [
      'GPS pitch heatmaps per player or full squad',
      'ACWR 28-day rolling load monitoring with risk alerts',
      'AI post-session coaching recommendations',
      'Club comparison across 13 metrics vs division average',
      'Training Load Planner with injury risk flags',
    ],
  },
  {
    id: 'physio',
    label: 'Physio / Medical',
    icon: '🏥',
    description: 'Injury tracking, ACWR load monitoring, return-to-play pipeline, GPS readiness scores, and medical clearance workflow.',
    modules: [
      { name: 'Medical Hub', detail: 'Injury log, rehabilitation tracker, medical clearance workflow, and physio case notes.' },
      { name: 'GPS Load Monitoring', detail: 'Per-player ACWR, readiness scores, and GPS load history.' },
      { name: 'Return to Play', detail: 'Stage-by-stage RTP protocol with clearance sign-off and load caps.' },
      { name: 'Player Profile — Medical Tab', detail: 'Full injury timeline, severity badges, and season injury summary per player.' },
    ],
    integrations: ['Lumio GPS', 'Catapult', 'STATSports'],
    whatYouGet: [
      'ACWR risk flag before every training session',
      'GPS readiness scores — know who can go harder',
      'Return-to-play protocol with stage clearance',
      'Full injury timeline per player',
      'Medical clearance workflow with sign-off trail',
    ],
  },
]

export const CRICKET_ROLES: SportRole[] = [
  {
    id: 'chairman',
    label: 'Chairman',
    icon: '🏛️',
    description: 'Board Suite financials, ECB compliance status, Hundred windfall deployment, and commercial pipeline — the complete governance picture.',
    modules: [
      { name: 'Board Suite', detail: 'Revenue vs budget, wages ratio, ECB distribution, windfall tracker.' },
      { name: 'ECB Compliance', detail: 'CPA self-assessment progress, DBS register, safeguarding log, submission deadlines.' },
      { name: 'Commercial', detail: 'Sponsor pipeline, windfall deployment tracker, venue calendar.' },
    ],
    integrations: ['Xero', 'ECB Portal', 'Play-Cricket'],
    whatYouGet: [
      'ECB compliance status — 7-section CPA tracker',
      'Hundred windfall deployment dashboard',
      'Board Report PDF — one click',
      'Sponsor pipeline with activation tracking',
      'DBS expiry alerts for all staff',
    ],
  },
  {
    id: 'doc',
    label: 'Director of Cricket',
    icon: '🎯',
    description: 'Multi-format squad management, overseas player tracking, contracts, GPS bowling load, and ECB pathway — the full cricket operations picture.',
    modules: [
      { name: 'Multi-Format Squad Manager', detail: 'Format eligibility, overseas slots, GPS load scores, and format conflict detection.' },
      { name: 'Contract Hub', detail: 'All contracts with expiry alerts, agent contacts, and AI renewal summary.' },
      { name: 'Overseas Player Hub', detail: 'Visa tracking, format eligibility, ECB Category A/B/C, recruitment targets.' },
      { name: 'GPS Bowling Load', detail: 'Over-count + ACWR for seamers — injury prevention built in.' },
      { name: 'Signing Pipeline', detail: '5-column Kanban: Identified → Approached → Negotiating → Done → Failed.' },
    ],
    integrations: ['CricViz', 'Catapult GPS', 'Play-Cricket', 'ECB Portal'],
    whatYouGet: [
      'Format squad optimiser — Championship XI and T20 XI simultaneously',
      'AI contract renewal memo for expiring players',
      'Overseas recruitment hub with ECB eligibility checker',
      'GPS bowling load model — ACWR per seamer',
      'Signing Pipeline Kanban with 5 stages',
    ],
  },
  {
    id: 'coach',
    label: 'Head Coach',
    icon: '📋',
    description: 'Match prep, opposition dossiers, declaration planner, toss decision AI, net session planner, and match report generator.',
    modules: [
      { name: 'AI Opposition Scout', detail: 'Claude generates batting threats, bowling threats, weaknesses, game plan, and key matchup.' },
      { name: 'Declaration Planner', detail: 'Run rate calculator + risk model + AI declaration advice for Day 3/4.' },
      { name: 'AI Toss Decision', detail: 'Input weather, pitch, opposition → Claude returns BAT/FIELD with reasoning.' },
      { name: 'Net Session Planner', detail: '7-day session builder with bowling load limits and overuse flagging.' },
      { name: 'Match Report Generator', detail: 'Input scorecard → Claude generates 150-word match report for club comms.' },
    ],
    integrations: ['CricViz', 'Hawk-Eye', 'Play-Cricket'],
    whatYouGet: [
      'AI opposition dossier — batting threats, weaknesses, game plan',
      'Declaration planner with run rate risk model',
      'AI toss decision advisor with pitch and weather context',
      'Net session planner with bowler load caps',
      'AI match report ready for club website',
    ],
  },
  {
    id: 'analyst',
    label: 'Performance Analyst',
    icon: '📡',
    description: 'GPS tracking, bowling load model, batting analytics, D/L calculator, and format-split performance stats.',
    modules: [
      { name: 'GPS Tracking', detail: 'Fielding heatmap, distance by zone, speed profile, bowling load gauge per player.' },
      { name: 'Bowling Load Model', detail: 'Over-count + ACWR — 7-day delivery planner with dual-format cap warnings.' },
      { name: 'Batting Analytics', detail: 'Format-split averages, wagon wheel, run rate trends.' },
      { name: 'D/L Calculator', detail: 'Duckworth-Lewis-Stern par score tool for weather-interrupted matches.' },
    ],
    integrations: ['Catapult GPS', 'CricViz', 'Hawk-Eye'],
    whatYouGet: [
      'Cricket GPS heatmap — fielding zones and bowling runs',
      'ACWR bowling load with 7-day delivery planner',
      'Format-split batting and bowling analytics',
      'D/L par score calculator for limited overs',
      'Multi-session GPS overlay — visual progress over camp',
    ],
  },
  {
    id: 'commercial',
    label: 'Commercial Director',
    icon: '💼',
    description: 'Sponsorship pipeline, fan engagement dashboard, membership trends, Hundred windfall tracker, and matchday revenue.',
    modules: [
      { name: 'Sponsorship Pipeline', detail: 'Sponsor cards with activation progress bars, renewal dates, and obligation tracking.' },
      { name: 'Fan Engagement', detail: 'Membership renewals, attendance trends, NPS, social sentiment, season ticket trajectory.' },
      { name: 'Windfall Tracker', detail: 'Hundred windfall deployment — project by project vs ECB mandate.' },
      { name: 'Ticket & Match Day', detail: 'Gate management, pricing tiers, matchday checklist.' },
    ],
    integrations: ['Xero', 'Play-Cricket', 'ECB Portal'],
    whatYouGet: [
      'Fan NPS and membership renewal rate at a glance',
      'Season ticket trajectory vs target',
      'Sponsor activation tracking with obligation alerts',
      'Windfall deployment dashboard — allocated vs remaining',
      'Matchday revenue and attendance trends',
    ],
  },
]

export const TENNIS_ROLES: SportRole[] = [
  {
    id: 'player',
    label: 'Player',
    icon: '🎾',
    description: 'Live rankings, Race standings, points expiry countdowns, match prep, morning briefing, surface analytics, and GPS court heatmaps.',
    modules: [
      { name: 'Rankings & Race', detail: 'Live ATP/WTA ranking, Race to Finals, weekly movement, career high tracker.' },
      { name: 'AI Morning Briefing', detail: 'Claude generates a personalised daily briefing including GPS load, serve stats, points expiry, and opponent intel.' },
      { name: 'GPS & Court Heatmap', detail: 'Court positioning heatmaps, ACWR load monitoring, and match vs practice load comparison.' },
      { name: 'Match Prep', detail: 'Pre-match routine, opponent dossier, surface stats, and tactical notes.' },
      { name: 'Ace & Shot Tracker', detail: 'Career ace milestones, signature shot win rates, and pressure performance stats.' },
    ],
    integrations: ['ATP Infosys', 'WTA Live', 'Lumio GPS Vest', 'ElevenLabs'],
    whatYouGet: [
      'Live ranking with daily movement and career high',
      'Points expiry urgency strip — flagged automatically',
      'AI morning briefing before every session',
      'GPS court heatmap per session and surface',
      'Pressure analysis — win rate at 30-40, tiebreaks, deciding sets',
    ],
  },
  {
    id: 'coach',
    label: 'Coach',
    icon: '📋',
    description: 'Practice log, GPS load data, match reports, AI post-match debrief, double fault heatmap, and pressure analysis.',
    modules: [
      { name: 'Practice Log with AI', detail: 'Session tracking with Claude AI analysis — 3 observations, 2 focus areas, 1 tactical pattern per session.' },
      { name: 'AI Post-Match Debrief', detail: 'Input serve stats and GPS → Claude returns serve analysis, return analysis, GPS fatigue story, and next week focus.' },
      { name: 'Double Fault Heatmap', detail: 'Where serves miss under pressure (30-40) — court zone breakdown with fix recommendation.' },
      { name: 'Match Report PDF', detail: 'Fillable A4 match report with GPS summary, set notes, and tactical assessment.' },
      { name: 'String Tension Advisor', detail: 'Humidity slider → automated tension recommendation based on historical string log.' },
    ],
    integrations: ['SwingVision', 'Lumio GPS Vest', 'Hawk-Eye'],
    whatYouGet: [
      'AI practice session analysis after every session',
      'AI post-match debrief with GPS fatigue story',
      'Double fault heatmap — under pressure serve patterns',
      'Fillable match report PDF ready in one click',
      'String tension recommendation from humidity data',
    ],
  },
  {
    id: 'agent',
    label: 'Agent',
    icon: '💼',
    description: "Sponsorship pipeline, prize money forecaster, ranking trajectory, and AI-generated pitch emails — the commercial side of the player's career.",
    modules: [
      { name: 'Agent Pipeline', detail: 'Kanban deal pipeline with Prospect → Agreed stages, AI sponsor pitch generator.' },
      { name: 'Prize Money Forecaster', detail: '6-event scenario builder — result selectors update projected season earnings live.' },
      { name: 'AI Press Statement', detail: 'Input match result and 3 key moments → Claude generates press, Instagram, and X quotes.' },
      { name: 'Sponsorship Dashboard', detail: 'Active sponsors, activation progress, renewal dates, and obligation calendar.' },
    ],
    integrations: ['ATP Infosys', 'WTA Live', 'Xero'],
    whatYouGet: [
      'Live ranking and Race to Finals trajectory',
      'Prize money forecaster — model 6 events simultaneously',
      "AI sponsor pitch emails in your client's voice",
      'Deal pipeline with Kanban stages',
      'Sponsor obligation alerts — never miss a post deadline',
    ],
  },
  {
    id: 'physio',
    label: 'Physio',
    icon: '🏥',
    description: 'GPS ACWR load monitoring, three-month match load tracker, injury risk alerts, and return-to-play protocols.',
    modules: [
      { name: 'GPS Load Monitor', detail: 'ACWR 28-day rolling chart, session load by type, Sarah Okafor alert at 1.15 threshold.' },
      { name: 'Three-Month Match Load', detail: '90-day match count vs 20-match fatigue threshold — automatic withdrawal recommendation.' },
      { name: 'Physio Hub', detail: 'Injury log, treatment notes, return-to-play stages, and medical clearance.' },
    ],
    integrations: ['Lumio GPS Vest', 'Whoop', 'Polar'],
    whatYouGet: [
      'ACWR automated alert when load enters amber zone',
      '90-day match load vs ATP fatigue threshold',
      'Withdrawal recommendation when threshold exceeded',
      'Injury log with return-to-play stage tracker',
      'GPS load history per session and surface',
    ],
  },
]

export const GOLF_ROLES: SportRole[] = [
  {
    id: 'player',
    label: 'Player',
    icon: '🏌️',
    description: 'OWGR ranking, Race to Dubai, points expiry, strokes gained, schedule optimiser, scorecard entry, and morning briefing.',
    modules: [
      { name: 'OWGR & Race to Dubai', detail: 'Live ranking with 104-week rolling expiry calendar and Race to Dubai position.' },
      { name: 'AI Morning Briefing', detail: "Claude generates a daily briefing: OWGR context, today's course fit, sponsor obligations, weather." },
      { name: 'Strokes Gained', detail: 'SG profile across Off-the-Tee, Approach, Around-the-Green, Putting with trend charts.' },
      { name: 'Scorecard Entry', detail: '18-hole scorecard with GIR, fairways, putts — saves to localStorage, feeds performance trends.' },
      { name: 'Putting Heat Map', detail: '6-band × 3-direction grid with manual putt logger and Arccos integration hint.' },
    ],
    integrations: ['DP World Tour API', 'PGA Tour API', 'DataGolf', 'Arccos'],
    whatYouGet: [
      'Live OWGR with 104-week rolling expiry calendar',
      'Race to Dubai position and points gap',
      'AI morning briefing before every round',
      'Strokes gained profile across all 4 categories',
      'Putting heatmap with session putt logger',
    ],
  },
  {
    id: 'agent',
    label: 'Agent (ISM)',
    icon: '💼',
    description: 'Sponsorship pipeline, AI pitch generator, financial dashboard, and career earnings tracker — the complete commercial view.',
    modules: [
      { name: 'Agent Pipeline', detail: '4-column Kanban: Prospect → In Discussion → Offer Made → Agreed. AI pitch generator per brand.' },
      { name: 'Financial Dashboard', detail: 'Prize money ledger, earnings by category, tax jurisdiction tracker, annual expense breakdown.' },
      { name: 'AI Sponsor Pitch', detail: "Input brand, category, and value → Claude generates a formal pitch email in Sarah Mitchell's voice." },
    ],
    integrations: ['DP World Tour API', 'PGA Tour API', 'Xero'],
    whatYouGet: [
      'Kanban deal pipeline with 4 negotiation stages',
      'AI sponsor pitch email in your agency voice',
      'Prize money ledger with accountant PDF export',
      'Earnings by category — Majors, Meridian Series, DP World, Pro-Ams',
      'Tax jurisdiction tracker across multiple territories',
    ],
  },
  {
    id: 'coach',
    label: 'Coach / Caddie',
    icon: '📋',
    description: 'Round strategy, AI round prep, course fit, competitor tracker, caddie sheet PDF, and post-round debrief.',
    modules: [
      { name: 'AI Round Strategy', detail: 'Input conditions → Claude returns game plan, 3 tactical adjustments, putting strategy, mental anchor.' },
      { name: 'Caddie Sheet PDF', detail: 'A4 print-optimised: hole strategy table, pre-round checklist, key notes, conditions box.' },
      { name: 'AI Post-Round Debrief', detail: 'Scorecard input → Claude generates structured analytical debrief with next session priorities.' },
      { name: 'Course Fit', detail: 'Course characteristics vs SG profile — where James has an edge and where the risks are.' },
      { name: 'Competitor Tracker', detail: '6-peer watchlist with OWGR, Race to Dubai gap, last-5 results chips, and trend arrows.' },
    ],
    integrations: ['DP World Tour API', 'DataGolf', 'Arccos'],
    whatYouGet: [
      'AI round strategy before every competitive round',
      'Printable caddie sheet — one click from the portal',
      'AI post-round debrief with next priorities',
      'Course fit analysis vs your strokes gained profile',
      'Competitor tracker with Race to Dubai gap',
    ],
  },
]

export const BOXING_ROLES: SportRole[] = [
  {
    id: 'fighter',
    label: 'Fighter',
    icon: '🥊',
    description: 'Camp dashboard, weight tracker, world rankings, ACWR load monitoring, ring heatmaps, and AI morning briefing.',
    modules: [
      { name: 'Camp Dashboard', detail: 'Camp phase timeline, daily sessions, weight trajectory, GPS ring heatmap as hero.' },
      { name: 'Weight Tracker', detail: 'Daily weigh-ins, cut planner, GPS-adjusted daily target, nutritionist notes.' },
      { name: 'World Rankings', detail: 'WBC, WBA, WBO, IBF rankings, mandatory timelines, and undisputed tracker.' },
      { name: 'AI Morning Briefing', detail: 'Claude generates camp day briefing including GPS load, weight, sparring focus, and obligations.' },
    ],
    integrations: ['Lumio Fight GPS Vest', 'UWB Ring Beacons', 'ElevenLabs'],
    whatYouGet: [
      'Live ring GPS heatmap on the camp dashboard',
      'ACWR load monitoring — green/amber/red zones',
      'AI morning briefing with GPS session summary',
      'Weight cut tracker with GPS-adjusted daily target',
      'Undisputed tracker — path to all 4 belts mapped',
    ],
  },
  {
    id: 'trainer',
    label: 'Trainer',
    icon: '📋',
    description: 'GPS ring heatmap, AI footwork analyst, camp load report, corner sheet PDF, sparring planner, and multi-session overlay.',
    modules: [
      { name: 'GPS Ring Heatmap', detail: 'UWB ring positioning — centre/ropes/corners zone breakdown per sparring session.' },
      { name: 'AI Footwork Analyst', detail: 'Ring zone data → Claude generates 3 specific footwork drills to address weaknesses.' },
      { name: 'Camp Load Report PDF', detail: 'One-click: total distance, load by day, ACWR chart, ring zone gallery.' },
      { name: 'Corner Sheet PDF', detail: 'A4 with GPS zone targets, game plan, round notes grid, cutman notes.' },
      { name: 'Multi-Session Overlay', detail: 'Compare camp week 1 vs week 8 ring heatmaps — visual proof of footwork improvement.' },
    ],
    integrations: ['Lumio Fight GPS Vest', 'UWB Ring Beacons', 'CompuBox'],
    whatYouGet: [
      'Ring heatmap per sparring session — centre/ropes/corners',
      'AI footwork analyst — 3 drills from zone data',
      'Camp Load Report PDF in one click',
      'Printable corner sheet with GPS zone targets',
      'Multi-session heatmap comparison — week 1 vs week 8',
    ],
  },
  {
    id: 'manager',
    label: 'Manager',
    icon: '💼',
    description: 'World rankings, purse bid calculator, mandatory tracker, undisputed path, BBBofC compliance, and fight earnings.',
    modules: [
      { name: 'Purse Bid Calculator', detail: 'Live slider £500k–£20M, challenger/champion toggle, net breakdown after agent and camp costs.' },
      { name: 'Mandatory Tracker', detail: 'WBC/WBA/WBO/IBF mandatory proceedings with timelines and purse bid deadlines.' },
      { name: 'Undisputed Tracker', detail: '5-step path from current ranking to all 4 belts — estimated timeline per step.' },
      { name: 'Fight Earnings', detail: 'Earnings ledger, purse history, viewership growth, platform breakdown.' },
      { name: 'BBBofC Compliance', detail: 'Licence status, medical records, suspension log, pre-fight requirements checklist.' },
    ],
    integrations: ['BBBofC Portal', 'CompuBox', 'DAZN API'],
    whatYouGet: [
      'Purse bid floor calculated instantly from any total',
      'Mandatory proceedings tracker with deadline alerts',
      'Undisputed path — 5 steps mapped to a timeline',
      'BBBofC compliance checklist pre-fight',
      'Fight earnings ledger with viewership growth',
    ],
  },
  {
    id: 'physio',
    label: 'Physio / Medical',
    icon: '🏥',
    description: 'ACWR load monitoring, GPS camp load history, BBBofC medical requirements, shoulder monitoring, and return-to-training protocols.',
    modules: [
      { name: 'GPS ACWR Monitor', detail: 'Camp ACWR chart, daily load bars, alert when ratio exceeds 1.3.' },
      { name: 'Medical Record', detail: 'Injury log, scan results, treatment notes, BBBofC medical requirements tracker.' },
      { name: 'Recovery & HRV', detail: 'Sleep, HRV, soreness, energy — daily wellness tracking through camp.' },
    ],
    integrations: ['Lumio Fight GPS Vest', 'Whoop', 'BBBofC Portal'],
    whatYouGet: [
      'ACWR alert when load enters danger zone (>1.3)',
      'Camp load history — 70 days in one chart',
      'BBBofC pre-fight medical checklist',
      'Daily HRV and wellness dashboard',
      'GPS load trend alongside weight cut trajectory',
    ],
  },
]

export const DARTS_ROLES: SportRole[] = [
  {
    id: 'player',
    label: 'Player',
    icon: '🎯',
    description: 'Order of Merit, rankings, match prep, nine-dart tracker, tournament schedule, and AI morning briefing.',
    modules: [
      { name: 'Order of Merit', detail: 'Live PDC and WDF standings with prize money breakdown and ranking movement.' },
      { name: 'AI Morning Briefing', detail: "Claude generates a daily briefing: ranking context, today's opponent, travel, obligations." },
      { name: 'Nine-Dart Tracker', detail: 'Career nine-dart log with venue, date, broadcast — milestone celebration tracking.' },
      { name: 'Match Prep', detail: 'Opponent stats, H2H record, recent form, and venue context.' },
      { name: 'Pressure Analysis', detail: 'Checkout percentage under pressure, decider legs, final-set performance.' },
    ],
    integrations: ['PDC API', 'DartConnect', 'ElevenLabs'],
    whatYouGet: [
      'Live Order of Merit with prize money breakdown',
      'AI morning briefing before every session',
      'Nine-dart milestone tracker with career log',
      'Pressure performance stats — deciders and checkout %',
      'Tournament schedule with travel planning',
    ],
  },
  {
    id: 'manager',
    label: 'Manager / Agent',
    icon: '💼',
    description: 'Sponsorship pipeline, appearance fees, commercial pipeline, prize money tracker, and media obligations.',
    modules: [
      { name: 'Sponsorship Dashboard', detail: 'Active sponsors with activation tracking, renewal dates, and obligation calendar.' },
      { name: 'Appearance Fees', detail: 'Exhibition bookings, appearance fee tracker, availability calendar.' },
      { name: 'Prize Money', detail: 'Season prize money vs targets, career earnings, payment tracking.' },
      { name: 'Media Obligations', detail: 'Press requirements, social content calendar, broadcast commitments.' },
    ],
    integrations: ['PDC API', 'Xero'],
    whatYouGet: [
      'Sponsor activation tracking with obligation alerts',
      'Appearance fee and exhibition booking manager',
      'Season prize money vs target tracker',
      'Media obligation calendar with deadlines',
      'Commercial pipeline with deal stages',
    ],
  },
  {
    id: 'coach',
    label: 'Coach / Analyst',
    icon: '📊',
    description: 'Match statistics, checkout analysis, practice session tracking, opponent analysis, and performance trends.',
    modules: [
      { name: 'Performance Stats', detail: 'Three-dart average, checkout %, first-9 average, doubles rate by leg phase.' },
      { name: 'Practice Log', detail: 'Session logging with drill targets — checkout practice, scoring practice, match simulation.' },
      { name: 'Opponent Analysis', detail: 'Head-to-head records, opponent checkout %, and tactical notes.' },
    ],
    integrations: ['DartConnect', 'PDC API'],
    whatYouGet: [
      'Three-dart average trend over rolling 12 months',
      'Checkout percentage by score range',
      'Practice session log with drill performance',
      'Head-to-head database vs tour players',
      'Pressure performance — deciders and final sets',
    ],
  },
]

export const WOMENS_ROLES: SportRole[] = [
  {
    id: 'chairman',
    label: 'Chairman / Owner',
    icon: '🏛️',
    description: 'FSR compliance, board financials, Karen Carney welfare mandate compliance, and commercial overview.',
    modules: [
      { name: 'Board Suite', detail: 'Revenue vs budget, FSR compliance status, governance tracking.' },
      { name: 'FSR Compliance', detail: 'Financial Sustainability Rules tracker with submission deadlines and compliance status.' },
      { name: 'Welfare Mandate', detail: 'Karen Carney review compliance — player welfare, education, mental health provision.' },
    ],
    integrations: ['FA Whole Game System', 'Xero'],
    whatYouGet: [
      'FSR compliance status — automatic red/amber/green',
      'Karen Carney welfare mandate tracker',
      'Board Report PDF — one click',
      'Fan engagement and matchday revenue',
      'Commercial pipeline and sponsor tracking',
    ],
  },
  {
    id: 'dof',
    label: 'Director of Football',
    icon: '🎯',
    description: 'Squad management, transfers, contracts, Kitman Labs GPS integration, and player pathway across all tiers.',
    modules: [
      { name: 'Squad Manager', detail: 'Multi-format squad, fitness status, GPS load scores, welfare flags.' },
      { name: 'Transfer Hub', detail: 'Kanban pipeline, agent contacts, FSR headroom calculator, deadline tracker.' },
      { name: 'GPS & Load', detail: 'Kitman Labs integration, ACWR monitoring, injury risk flags.' },
      { name: 'Player Pathway', detail: 'Academy progression, dual-registration tracking, England pathway nominations.' },
    ],
    integrations: ['Kitman Labs', 'FA Whole Game System', 'Wyscout'],
    whatYouGet: [
      'GPS load monitoring via Kitman Labs integration',
      'FSR headroom calculator for transfer decisions',
      'Player pathway with dual-registration tracking',
      'England pathway nomination form generator',
      'Transfer Kanban with FSR compliance built in',
    ],
  },
  {
    id: 'manager',
    label: 'Head Coach',
    icon: '📋',
    description: 'Match prep, AI opposition report, GPS briefings, player welfare tracking, and post-match analysis.',
    modules: [
      { name: 'Match Prep', detail: 'Pre-match routine, opposition analysis, formation, and team sheet.' },
      { name: 'AI Opposition Report', detail: 'Formation, key threats, weaknesses, 3 tactical suggestions.' },
      { name: 'Player Welfare', detail: 'Welfare check-ins, mental health flags, education compliance tracking.' },
      { name: 'Post-Match Analysis', detail: 'AI-generated match report with player ratings and tactical analysis.' },
    ],
    integrations: ['Kitman Labs', 'Hudl', 'Wyscout'],
    whatYouGet: [
      'AI opposition report with tactical suggestions',
      'Player welfare dashboard with mental health flags',
      'Education compliance tracker per player',
      'Post-match AI analysis with player ratings',
      'GPS load briefing before every session',
    ],
  },
]

export const RUGBY_ROLES: SportRole[] = [
  {
    id: 'chairman',
    label: 'Chairman',
    icon: '🏛️',
    description: 'Club financials, RFU/Premiership compliance, commercial overview, and governance dashboard.',
    modules: [
      { name: 'Board Suite', detail: 'Revenue, salary cap compliance, RFU governance, Board Report PDF.' },
      { name: 'Salary Cap Tracker', detail: 'Live calculation against Premiership salary cap ceiling with headroom alerts.' },
    ],
    integrations: ['RFU Portal', 'Xero'],
    whatYouGet: [
      'Salary cap compliance status in real time',
      'Board Report PDF — one click',
      'RFU governance checklist',
      'Commercial and fan engagement dashboard',
    ],
  },
  {
    id: 'dor',
    label: 'Director of Rugby',
    icon: '🎯',
    description: 'Squad management, transfers, contracts, GPS load, salary cap headroom, and player pathway.',
    modules: [
      { name: 'Squad Manager', detail: 'Full squad, positions, availability, GPS load, and contract status.' },
      { name: 'GPS Load', detail: 'ACWR monitoring, contact load tracking, return-to-play protocol.' },
      { name: 'Transfer Pipeline', detail: 'Kanban pipeline with salary cap headroom per target.' },
    ],
    integrations: ['Catapult', 'STATSports', 'RFU Portal'],
    whatYouGet: [
      'GPS load with contact impact tracking',
      'ACWR injury risk flags before every session',
      'Salary cap headroom per transfer target',
      'Squad availability across all competitions',
      'Player pathway and dual-registration tracking',
    ],
  },
  {
    id: 'coach',
    label: 'Head Coach',
    icon: '📋',
    description: 'Match prep, lineout analysis, GPS briefing, opposition report, and post-match review.',
    modules: [
      { name: 'Match Prep', detail: 'Opposition analysis, lineout calls, set piece planner, team sheet.' },
      { name: 'AI Opposition Report', detail: 'Formation, key threats, set piece tendencies, 3 tactical suggestions.' },
      { name: 'GPS Match Brief', detail: 'First-half GPS data → AI half-time coaching brief.' },
    ],
    integrations: ['Catapult', 'Hudl', 'STATSports'],
    whatYouGet: [
      'AI opposition report with set piece analysis',
      'GPS half-time brief — fatigue alerts and sub recommendation',
      'Lineout analysis and set piece planner',
      'Post-match GPS load review per position',
      'Contact load monitoring for forwards',
    ],
  },
]
