import type { IntegrationConfig } from './integration-detail-view'

export const BOXING_INTEGRATIONS: Record<string, IntegrationConfig> = {
  boxrec: {
    icon: '📊',
    title: 'BoxRec Database',
    subtitle: 'The canonical record for professional boxers — fights, rankings, licences.',
    partnerBadge: 'BoxRec data-sharing · commercial tier · industry-standard',
    connectLabel: 'Connect BoxRec',
    summaryText: 'BoxRec is the definitive record for every licensed pro fight in history. Career record, opponent lookup, division rankings, and venue history all flow from this one connection. Every Fight Record, Career Stats, and Opposition Analysis view starts here.',
    connectedStats: [
      { label: 'API Status', value: '✓ Connected' },
      { label: 'Last Sync', value: '04:00 GMT' },
      { label: 'Fighters Indexed', value: '1.2M+' },
      { label: 'Fights Indexed', value: '21M+' },
    ],
    whyHeading: 'Why BoxRec is the highest-priority boxing integration',
    whyBody: 'Boxing has no single sanctioning body — so BoxRec is the closest thing to a canonical source. Career record, weight-class movement, venue history, and division ranking all live there. Without this integration, Lumio is a prettified spreadsheet. With it, every opponent lookup is live, career-stats recomputes nightly, and the Mandatory Tracker knows which challengers are eligible because BoxRec tracks sanctioning-body status for every fighter.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Fighter Record', desc: 'W/L/D, KOs, by-round breakdown, weight-class history.', status: 'Live' },
      { endpoint: 'Division Rankings', desc: 'Daily-updated division rankings across every weight class.', status: 'Live' },
      { endpoint: 'Opponent Lookup', desc: 'Full record, styles, venues, and recent-form data per fighter.', status: 'Live' },
      { endpoint: 'Fight History', desc: 'Every licensed bout with venue, judges, ref, and scorecard.', status: 'Live' },
      { endpoint: 'Venue Database', desc: 'Capacity, location, and hosting history per venue.', status: 'Live' },
      { endpoint: 'Promoter Activity', desc: 'Promoter-by-promoter event history and roster depth.', status: 'Live' },
      { endpoint: 'Licence Status', desc: 'Commission licence flags — active / expired / suspended.', status: 'Live' },
      { endpoint: 'Head-to-Head', desc: 'Common-opponent overlap and mutual-loss depth analysis.', status: 'Beta' },
      { endpoint: 'Historical Scorecards', desc: 'Round-by-round scorecards where available — sanctioning-era.', status: 'Beta' },
    ],
    coverage: {
      title: 'Coverage — BoxRec Database',
      columns: ['Tier', 'Fighters', 'Fight History', 'Rankings', 'Live Updates'],
      rows: [
        ['World-ranked (top 15 per division)', '✓ Full', '✓ Full', '✓ Daily', '✓'],
        ['National-ranked', '✓ Full', '✓ Full', '✓ Weekly', '✓'],
        ['Licensed pro (all commissions)', '✓ Full', '✓ Full', '✓', '✓'],
        ['Amateur (AIBA / World Boxing)', 'Partial', 'Partial', '—', '—'],
        ['Historical (pre-2000)', '✓ Full', 'Partial', 'N/A', 'N/A'],
      ],
    },
    pricing: 'BoxRec commercial-tier API access runs approximately $500–$1,500/month depending on call volume. Backend cost absorbed by Lumio, not charged to fighters. Public-facing fighter profiles remain free on boxrec.com.',
  },

  lumiopunchanalytics: {
    icon: '🥊',
    title: 'Lumio Punch Analytics',
    subtitle: 'Punch-by-punch statistics from televised bouts — Lumio-built reference data.',
    partnerBadge: 'Lumio-built punch analytics · per-event coverage · US + UK broadcasts',
    connectLabel: 'Connect Lumio Punch Analytics',
    summaryText: 'Every televised fight gets punch-level stats imported — jabs thrown, power shots landed, round-by-round accuracy. The ShotLink-equivalent for professional boxing.',
    connectedStats: [
      { label: 'Fights Covered', value: '14' },
      { label: 'Total Rounds', value: '148' },
      { label: 'Punch Events', value: '8,420' },
      { label: 'Accuracy Avg', value: '34.2%' },
    ],
    whyHeading: 'Why punch analytics is a performance-critical integration',
    whyBody: 'Punch-output data is the single most accurate indicator of how a fighter performed against elite opposition. Without it, post-fight analysis relies on memory + broadcast commentary. With it, the Career Stats view shows accuracy trends across every televised fight, the Opposition Analysis can pre-model punch output vs upcoming challengers, and training-camp targets (shots-per-round, power-shot %, body-shot ratio) are measurable instead of vibes-based.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Round-by-Round Punch Totals', desc: 'Thrown / landed per round, split jabs vs power shots.', status: 'Live' },
      { endpoint: 'Punch Accuracy', desc: 'Percentage landed across the fight, broken by round.', status: 'Live' },
      { endpoint: 'Body Shot Ratio', desc: 'Body vs head-shot distribution — key against high-guard opponents.', status: 'Live' },
      { endpoint: 'Punch Output by Minute', desc: 'Minute-by-minute punch-output curve — fatigue-detection proxy.', status: 'Live' },
      { endpoint: 'Opponent Comparative', desc: 'Your output vs opponent\'s in the same round — side-by-side.', status: 'Live' },
      { endpoint: 'Career Aggregates', desc: 'Career totals across all televised fights.', status: 'Beta' },
      { endpoint: 'Round-Outcome Correlation', desc: 'Judges\' scorecards mapped to punch totals — judging-lean indicator.', status: 'Beta' },
    ],
    pricing: 'Bundled with Lumio Tour Pro and Pro+ — no third-party data agreement required. Fighters see their own historical punch-analytics data in one consolidated view.',
  },

  sanctioning: {
    icon: '🏆',
    title: 'WBC / WBA / WBO / IBF',
    subtitle: 'Official rankings, mandatory tracking, and title-belt status across all four bodies.',
    partnerBadge: 'Sanctioning-body data agreements · quarterly ranking cycles',
    connectLabel: 'Connect Sanctioning Bodies',
    summaryText: 'Pull official rankings, mandatory-challenger status, title-holder data, and purse-bid alerts from WBC, WBA, WBO, and IBF. Feeds the World Rankings, Mandatory Tracker, and Path to Title views.',
    connectedStats: [
      { label: 'Bodies Connected', value: '4 of 4' },
      { label: 'Last Ranking Cycle', value: 'Apr 2026' },
      { label: 'Mandatory Alerts', value: '2 active' },
      { label: 'Eligible Challengers', value: '6 tracked' },
    ],
    whyHeading: 'Why sanctioning-body integration is a strategic necessity',
    whyBody: 'The difference between a fighter at WBC #6 and WBC #4 is millions in purse. The difference between "mandatory eligible in 6 weeks" and "mandatory eligible today" is a purse-bid deadline you either meet or surrender. Connecting all four sanctioning bodies means the Path to Title view is always current, mandatory deadlines are pre-flagged 30 days out, and purse-bid alerts land in the manager\'s inbox before the promoter even knows there\'s a decision to make.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Division Rankings (WBC)', desc: 'Top-15 rankings per division, quarterly cycle.', status: 'Live' },
      { endpoint: 'Division Rankings (WBA)', desc: 'WBA super, regular, gold, interim — all tracked.', status: 'Live' },
      { endpoint: 'Division Rankings (WBO)', desc: 'Top-15 WBO rankings — monthly where available.', status: 'Live' },
      { endpoint: 'Division Rankings (IBF)', desc: 'Top-15 IBF rankings — quarterly cycle.', status: 'Live' },
      { endpoint: 'Title-Holder Status', desc: 'Current world champion, interim, and regional champions per body.', status: 'Live' },
      { endpoint: 'Mandatory Challenger Clock', desc: 'Days-to-mandatory countdown per belt.', status: 'Live' },
      { endpoint: 'Purse Bid Notifications', desc: 'Auto-flag when a purse-bid is announced.', status: 'Live' },
      { endpoint: 'Ranking Delta (quarterly)', desc: 'Movement up / down per cycle with reason codes.', status: 'Beta' },
    ],
    coverage: {
      title: 'Sanctioning Body Coverage',
      columns: ['Body', 'Rankings', 'Mandatories', 'Purse Bids', 'Frequency'],
      rows: [
        ['WBC', '✓ Full', '✓', '✓', 'Monthly'],
        ['WBA', '✓ Full', '✓', '✓', 'Monthly'],
        ['WBO', '✓ Full', '✓', '✓', 'Monthly'],
        ['IBF', '✓ Full', '✓', '✓', 'Quarterly'],
        ['The Ring', 'Partial', '—', '—', 'Irregular'],
      ],
    },
    pricing: 'Sanctioning-body data licensing is typically negotiated at management-company or promoter level. Lumio aggregates all four feeds into one view — the fighter sees a single ranking picture rather than four browser tabs.',
  },

  striketec: {
    icon: '📡',
    title: 'Punch Sensors',
    subtitle: 'StrikeTec / Hykso / Corner wearable sensors for in-camp punch analytics.',
    partnerBadge: 'StrikeTec + Hykso + Corner supported · hardware-agnostic',
    connectLabel: 'Connect Punch Sensors',
    summaryText: 'Wearable punch sensors worn in training capture punch-count, force, velocity, and combination patterns session-by-session. Feeds the Training Log and Punch Analytics views.',
    connectedStats: [
      { label: 'Sessions Logged', value: '38' },
      { label: 'Total Punches', value: '14,200' },
      { label: 'Peak Force', value: '1,240 N' },
      { label: 'Provider', value: 'Hykso + StrikeTec' },
    ],
    whyHeading: 'Why punch sensors matter in camp',
    whyBody: 'Camp volume without data is a vibe. Camp volume with punch-count is a plan. StrikeTec, Hykso, and Corner sensors give the trainer a session-by-session number for total punches, combination density, and force output. Feeding that into Lumio means the Camp progression is objective — if Week 4 punch count is 15% below Week 3 baseline, the trainer sees it the next morning and decides whether to push or recover.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Punch Count', desc: 'Total punches per session, split by type (jab / cross / hook / uppercut).', status: 'Live' },
      { endpoint: 'Combination Patterns', desc: 'Most-thrown combinations — feeds trainer review.', status: 'Live' },
      { endpoint: 'Punch Velocity', desc: 'Peak + average velocity per session, by punch type.', status: 'Live' },
      { endpoint: 'Punch Force', desc: 'Estimated force (Newtons) — useful for heavy-bag calibration.', status: 'Live' },
      { endpoint: 'Session Duration + Density', desc: 'Punches-per-minute — fatigue curve across a round.', status: 'Live' },
      { endpoint: 'Left / Right Balance', desc: 'Lead vs rear-hand ratio — flags over-dominance issues.', status: 'Beta' },
      { endpoint: 'Sparring-Only Filter', desc: 'Auto-tag sparring rounds separately from bag work — Planned.', status: 'Planned' },
    ],
    pricing: 'Hykso Punch Sensors approximately $250 + app subscription. StrikeTec approximately $150 one-off. Corner approximately $300. Lumio is hardware-agnostic — connect whichever system the camp already uses.',
  },

  bbbofc: {
    icon: '📋',
    title: 'BBBofC Licensing',
    subtitle: 'British Boxing Board of Control licence, medical, and fight-approval status.',
    partnerBadge: 'BBBofC data-sharing agreement · UK-licensed fighters',
    connectLabel: 'Connect BBBofC',
    summaryText: 'For UK-licensed fighters, the BBBofC integration tracks licence status, annual medicals, MRI schedule, manager of record, and fight-approval status per scheduled bout.',
    connectedStats: [
      { label: 'Licence Status', value: '✓ Active' },
      { label: 'Annual Medical', value: 'Due Oct 2026' },
      { label: 'MRI', value: 'Passed Jan 2026' },
      { label: 'Central Area', value: '✓ Approved' },
    ],
    whyHeading: 'Why BBBofC integration is a compliance essential',
    whyBody: 'For UK-licensed fighters, nothing happens in the ring without BBBofC approval — medicals, MRIs, manager of record, and fight-approval per bout. Connecting the BBBofC data means the medical-expiry clock is visible in Lumio, annual renewals pre-flag 60 days out, and pre-fight approval status for the next scheduled bout is tracked alongside camp progression. One missed medical = one missed fight date. Lumio stops that from happening.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Licence Status', desc: 'Active / expired / suspended with renewal window.', status: 'Live' },
      { endpoint: 'Annual Medical', desc: 'Next-due date with automatic 60 / 30 / 14-day alerts.', status: 'Live' },
      { endpoint: 'MRI Schedule', desc: 'Every-2-year MRI requirement — next-due countdown.', status: 'Live' },
      { endpoint: 'Manager of Record', desc: 'BBBofC-registered manager — must match Lumio manager to approve fights.', status: 'Live' },
      { endpoint: 'Area-Council Approval', desc: 'Central / Scottish / Welsh area approval per venue.', status: 'Live' },
      { endpoint: 'Fight-Approval Status', desc: 'Pre-fight approval flag for the next scheduled bout.', status: 'Live' },
      { endpoint: 'Suspension Tracking', desc: 'Mandatory medical / weigh-in suspensions — flagged as blockers.', status: 'Live' },
    ],
    pricing: 'BBBofC licensing is paid per-fighter per-year (approximately £125–£200 annual licence). Lumio\'s integration is free to connect — OAuth / data-sharing only, no licence re-billing.',
  },

  vada: {
    icon: '💊',
    title: 'VADA / UKAD',
    subtitle: 'Voluntary anti-doping testing enrolment and test-result tracking.',
    partnerBadge: 'VADA (USA) + UKAD (UK) · enrolment required · whereabouts tracking',
    connectLabel: 'Connect VADA / UKAD',
    summaryText: 'For fighters enrolled in VADA (Voluntary Anti-Doping Association) or UKAD\'s registered testing pool, Lumio tracks whereabouts filings, test dates, test results, and biological-passport status.',
    connectedStats: [
      { label: 'Enrolment', value: 'VADA Active' },
      { label: 'Tests (YTD)', value: '6' },
      { label: 'Missed Tests', value: '0' },
      { label: 'Last Test', value: 'Mar 28' },
    ],
    whyHeading: 'Why VADA / UKAD integration is an operational essential',
    whyBody: 'For world-title-track fighters, voluntary anti-doping enrolment has become the standard for a big-money fight — opponents will often refuse to face non-enrolled fighters. Once enrolled, whereabouts filing becomes a daily admin task and a single missed-test strike can end a career. Feeding VADA / UKAD data into Lumio means whereabouts obligations are on the calendar, test-date history is logged, and any result delays are tracked — no surprises, no missed-test incidents.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Whereabouts Filing', desc: 'Daily location + 60-min testing window — one-tap submit from Lumio.', status: 'Live' },
      { endpoint: 'Test History', desc: 'Date, sample type (blood / urine), and result-status per test.', status: 'Live' },
      { endpoint: 'Biological Passport Status', desc: 'Haematological profile tracking — flagged deviations.', status: 'Live' },
      { endpoint: 'Missed-Test Counter', desc: 'Strikes-within-12-months counter — critical compliance flag.', status: 'Live' },
      { endpoint: 'Medication TUE', desc: 'Therapeutic-use exemption filings and approval status.', status: 'Live' },
      { endpoint: 'Opponent VADA Status', desc: 'Cross-check whether the opponent is also VADA-enrolled.', status: 'Beta' },
      { endpoint: 'UKAD Coordination', desc: 'UKAD-registered testing-pool data for UK fighters.', status: 'Live' },
    ],
    pricing: 'VADA enrolment for world-title-track fighters is typically $15k–$25k per fight, split with the opponent. UKAD testing-pool enrolment is free for UK Sport-funded athletes. Lumio adds no fee — data sync only.',
  },

  whoop: {
    icon: '💚',
    title: 'Lumio Wear / Oura',
    subtitle: 'Sleep, HRV, recovery and strain piped into every camp-day briefing.',
    partnerBadge: 'OAuth available · Lumio Wear + Oura · ring or strap',
    connectLabel: 'Connect Lumio Wear / Oura',
    summaryText: 'Pipe HRV, recovery score, sleep duration and strain into Lumio every morning. Camp is long — knowing whether the fighter walked in on 45% recovery vs 80% recovery changes the session plan.',
    connectedStats: [
      { label: 'Last Sync', value: '05:40' },
      { label: 'Recovery', value: '68%' },
      { label: 'HRV', value: '54 ms' },
      { label: 'Sleep', value: '7h 10m' },
    ],
    whyHeading: 'Why Lumio Wear / Oura matters during fight camp',
    whyBody: 'Camps are 10-week compressed-adaptation cycles — by Week 6 the fighter is accumulating fatigue that compounds daily. Feeding Lumio Wear/Oura into Lumio means the trainer walks into the morning session already knowing recovery is 68% today vs 85% yesterday, and can swap a heavy sparring day for skills-and-defence. Over a 70-day camp, this is the difference between arriving at fight night sharp and arriving burnt out.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Recovery Score', desc: 'Lumio Wear 0-100 daily recovery or Oura Readiness score.', status: 'Live' },
      { endpoint: 'HRV (RMSSD)', desc: 'Overnight HRV — critical during weight-cut windows.', status: 'Live' },
      { endpoint: 'Sleep Stages', desc: 'REM / deep / light split — sleep debt during cuts is the #1 recovery risk.', status: 'Live' },
      { endpoint: 'Daily Strain', desc: 'Strain vs target — flags over-training during camp.', status: 'Live' },
      { endpoint: 'Resting Heart Rate', desc: 'Morning RHR — rises flag early illness during camp.', status: 'Live' },
      { endpoint: 'Respiratory Rate', desc: 'Overnight breath rate — illness-incubation flag.', status: 'Beta' },
      { endpoint: 'Cut-Week Recovery Alerts', desc: 'Dehydration-linked HRV crash detection — Planned.', status: 'Planned' },
    ],
    pricing: 'Free to connect if the fighter has Lumio Wear or Oura. Lumio Wear approximately £20/month; Oura approximately £5/month plus ring hardware. Lumio adds no fee — OAuth connection only.',
  },

  'gps-vest': {
    icon: '🛰️',
    title: 'Lumio GPS Vest',
    subtitle: 'Sparring, roadwork, and camp-session load tracking via wearable GPS.',
    partnerBadge: 'Lumio GPS · bundled in Pro Plus · Lumio GPS Pro + Lumio GPS also supported',
    connectLabel: 'Connect Lumio GPS Vest',
    summaryText: 'The Lumio GPS vest (or a Lumio GPS Pro / Lumio GPS equivalent) captures session-by-session movement load across sparring, roadwork, pad work, and strength sessions. The backbone of the Fight Camp load-management view.',
    connectedStats: [
      { label: 'Sessions (30d)', value: '38' },
      { label: 'Roadwork Distance', value: '184 km' },
      { label: 'Sparring Load', value: '1,260 AU' },
      { label: 'Device', value: 'Lumio GPS' },
    ],
    whyHeading: 'Why GPS-vest integration is camp-critical',
    whyBody: 'Camp load-management is the difference between peaking on fight night and peaking two weeks early. The GPS vest captures every session\'s distance, high-speed running, and zone distribution — meaning the trainer and physio see acute-vs-chronic load ratios throughout camp instead of guessing. For a 10-week camp the cumulative data gives actionable tapering decisions for the final 14 days — the highest-leverage period in the whole cycle.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Session Summary', desc: 'Distance, HSR, max HR, duration per session.', status: 'Live' },
      { endpoint: 'Acute / Chronic Workload', desc: 'Rolling 7- and 28-day load ratio — drives the ACWR alert tile.', status: 'Live' },
      { endpoint: 'Sparring Load', desc: 'Tagged sparring sessions — critical for mild-TBI load management.', status: 'Live' },
      { endpoint: 'Roadwork Distance', desc: 'Morning run distance + pace curves per session.', status: 'Live' },
      { endpoint: 'Zone Distribution', desc: 'Time in aerobic / threshold / anaerobic zones per session.', status: 'Live' },
      { endpoint: 'Heat / Environmental', desc: 'Estimated core temp during camp in hot-weather conditions.', status: 'Beta' },
      { endpoint: 'Taper Optimiser', desc: 'Auto-suggest load for final 14 days based on camp trend — Planned.', status: 'Planned' },
    ],
    pricing: 'Lumio GPS vest is bundled in the Pro Plus plan — no extra hardware cost. Lumio GPS Pro APEX (approximately £400/year) and Lumio GPS Vector (approximately £800/year) are supported as alternatives via the same data contract.',
  },

  workspace: {
    icon: '📧',
    title: 'Gmail + Calendar',
    subtitle: 'Promoter emails, sponsor obligations, and camp-logistics in one place.',
    partnerBadge: 'Google OAuth · gmail.readonly + calendar.events scopes',
    connectLabel: 'Sign in with Google',
    summaryText: 'Promoter contract threads, sponsor obligations, camp-travel bookings, and sanctioning-body correspondence all flow into Lumio\'s morning briefing automatically. No tab-switching.',
    connectedStats: [
      { label: 'Inbox Sync', value: '4 min ago' },
      { label: 'Calendars', value: '3 active' },
      { label: 'Drafts', value: '5 pending' },
      { label: 'Account', value: 'marcus@…' },
    ],
    whyHeading: 'Why Gmail + Calendar is the single biggest time saver',
    whyBody: 'A fighter approaching a title shot has four separate threads running: promoter / broadcaster / sanctioning body / sponsor. The manager owns most of it but the fighter still needs to know what\'s up. Classification tagging turns 60 daily emails into a sorted shortlist. Calendar sync puts camp dates, fight-week travel, press commitments, and medical dates on one shared timeline everyone can see.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Inbox Classification', desc: 'Every email tagged: promoter / sponsor / sanctioning / travel / camp / personal.', status: 'Live' },
      { endpoint: 'Contract-Thread Grouping', desc: 'Multi-party contract threads grouped and tracked per-deal.', status: 'Live' },
      { endpoint: 'Calendar Sync', desc: 'Two-way — add a camp day to Lumio, it lands in Google Calendar.', status: 'Live' },
      { endpoint: 'Sanctioning-Body Extraction', desc: 'Mandatory notifications and purse-bid emails routed to the Rankings view.', status: 'Live' },
      { endpoint: 'Sponsor Obligation Flagging', desc: 'Brand-email deliverables and deadlines into Sponsorships tracker.', status: 'Live' },
      { endpoint: 'AI Reply Drafts', desc: 'Suggested replies in your voice — review and send from Lumio.', status: 'Beta' },
      { endpoint: 'Fight-Week OOO', desc: 'Auto-enable OOO for fight-week window — Planned.', status: 'Planned' },
    ],
    pricing: 'Free on personal Gmail and Google Workspace. OAuth only — no credentials stored on Lumio servers. Microsoft 365 / Outlook supported via parallel OAuth at no extra cost.',
  },

  slack: {
    icon: '💬',
    title: 'Slack',
    subtitle: 'Team messaging with role-aware alerts for trainer, cutman, manager, nutritionist.',
    partnerBadge: 'Slack OAuth · per-workspace install · private channels supported',
    connectLabel: 'Add to Slack',
    summaryText: 'Route Lumio alerts to the right room — camp briefings to #trainers, medicals to #doctor, purse-bid alerts to #manager. Each role sees only what they need.',
    connectedStats: [
      { label: 'Workspace', value: 'team-cole' },
      { label: 'Channels', value: '7 wired' },
      { label: 'DM fallback', value: 'Enabled' },
      { label: 'Alert Rules', value: '15 active' },
    ],
    whyHeading: 'Why Slack is the glue for a 15-person camp',
    whyBody: 'A world-title camp is trainer + strength coach + physio + nutritionist + cutman + manager + sparring partners — fifteen people on two WhatsApp groups and four email threads. Slack replaces that mess with role-aware routing: medicals to the doctor channel, weight to the nutritionist, purse-bid alerts to the manager. Lumio delivers briefings and flags into those channels directly — no 15-person blast messages.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Role-Based Routing', desc: 'Rules like "send Weight > +3kg from target to #nutrition".', status: 'Live' },
      { endpoint: 'Morning Camp Briefing', desc: 'Full briefing delivered to the team channel before first session.', status: 'Live' },
      { endpoint: 'Fight-Week Alerts', desc: 'Weigh-in countdown, press slots, broadcast schedule flags.', status: 'Live' },
      { endpoint: 'Medical-Clearance Alerts', desc: 'Next-due medical / MRI dates — routed to doctor + manager.', status: 'Live' },
      { endpoint: 'Slash Commands', desc: '/lumio weight, /lumio next-fight — Slack-native.', status: 'Beta' },
      { endpoint: 'Thread AI Q&A', desc: 'Ask the Lumio bot a question in a thread — inline answer.', status: 'Beta' },
      { endpoint: 'Huddle Summaries', desc: 'Auto-transcribed camp huddles with action-items — Planned.', status: 'Planned' },
    ],
    pricing: 'Slack free-tier covers teams under 10. Slack Pro approximately £7/user/month — typically billed to the management company. Lumio\'s Slack app is bundled, no additional fee.',
  },

  broadcast: {
    icon: '📺',
    title: 'Meridian Sports',
    subtitle: 'Fight-night broadcast schedule, undercard mapping, and press coordination.',
    partnerBadge: 'Meridian Sports API · partner access · UK + EU coverage',
    connectLabel: 'Connect Meridian Sports',
    summaryText: 'Pull your upcoming fight-night broadcast slots, undercard running order, clip library from past events, and press-access windows — all scheduled alongside the camp calendar.',
    connectedStats: [
      { label: 'Next Broadcast', value: 'Main Sat 22:00' },
      { label: 'Clips (YTD)', value: '18' },
      { label: 'Press Slots', value: '5 scheduled' },
      { label: 'Region', value: 'UK + EU' },
    ],
    whyHeading: 'Why Meridian Sports is a fight-week integration',
    whyBody: 'Fight-week is a broadcast operation as much as a boxing one. Knowing the card running order, when your walk-on is scheduled, and what press commitments sit either side of weigh-in lets the team plan recovery, meals, and warm-up timing precisely. Meridian\'s feed auto-populates the Fight Night Ops view instead of someone chasing the broadcaster for a spreadsheet at 2am.',
    endpointsTitle: 'Data Flows Used by Lumio Boxing',
    endpoints: [
      { endpoint: 'Card Running Order', desc: 'Undercard + main event order with estimated walk-on times.', status: 'Live' },
      { endpoint: 'Clip Library', desc: 'Broadcast-quality clips from past fights — into Lumio Video Library.', status: 'Live' },
      { endpoint: 'Press Access Windows', desc: 'Mixed-zone and sit-down press — blocks calendar.', status: 'Live' },
      { endpoint: 'Weigh-In Broadcast', desc: 'Weigh-in slot and stage time — fed into the Cut Planner.', status: 'Live' },
      { endpoint: 'Rights / Blackout Map', desc: 'Regions cleared for clip / repost — powers sponsor scheduler.', status: 'Beta' },
      { endpoint: 'Live Rundown Feed', desc: 'In-event rundown during broadcast — Planned for PPV window.', status: 'Planned' },
    ],
    pricing: 'Meridian partner access typically arranged through the promoter or management. Basic schedule + clip library tier bundled in the broadcast-rights package. Higher tiers are a separate conversation.',
  },

  mobileapp: {
    icon: '📲',
    title: 'Mobile App',
    subtitle: 'Lumio on your phone — camp log, weight tracker, fight-week brief, quick-log.',
    partnerBadge: 'iOS + Android · native push · offline support for fight-week travel',
    connectLabel: 'Install Mobile App',
    summaryText: 'Native iOS and Android app mirroring the dashboard — optimised for daily camp logging, weight-ins, fight-night brief, and offline access to tomorrow\'s session plan.',
    connectedStats: [
      { label: 'App Version', value: '1.10.0' },
      { label: 'Push Alerts', value: 'Enabled' },
      { label: 'Offline Cache', value: '7 days' },
      { label: 'Platform', value: 'iOS + Android' },
    ],
    whyHeading: 'Why a mobile app matters across a 70-day camp',
    whyBody: 'The web dashboard is built for the trainer and manager; the mobile app is for the fighter. Daily weight logs, session ratings, sleep check-ins, and offline access to tomorrow\'s plan all live in a native app. Push notifications fire for schedule changes, sanctioning-body alerts, and fight-week walk-on timings — no laptop required.',
    endpointsTitle: 'Mobile App Capabilities',
    endpoints: [
      { endpoint: 'Morning Camp Briefing', desc: 'Full briefing at 06:00 local — adjusts to the fighter\'s timezone.', status: 'Live' },
      { endpoint: 'Weight Logging', desc: 'One-tap daily weight with target-curve progression.', status: 'Live' },
      { endpoint: 'Session Rating', desc: 'RPE + subjective fatigue — post-session one-tap.', status: 'Live' },
      { endpoint: 'Fight-Week Alerts', desc: 'Push notifications for weigh-in, walk-on, media slots.', status: 'Live' },
      { endpoint: 'Voice Dictation', desc: 'Speak a post-session note → transcribed into Trainer Notes.', status: 'Beta' },
      { endpoint: 'Offline Mode', desc: '7-day cache of briefings, session plans, and fight-week brief.', status: 'Live' },
      { endpoint: 'Watch Companion', desc: 'Apple Watch / Wear OS glances for HR + weigh-in — Planned.', status: 'Planned' },
    ],
    pricing: 'Bundled in every Lumio Boxing plan at no extra cost. iOS app via App Store; Android via Google Play. Beta channel available for testers.',
  },
}
