import type { IntegrationConfig } from './integration-detail-view'

export const DARTS_INTEGRATIONS: Record<string, IntegrationConfig> = {
  'pdc-api': {
    icon: '🏆',
    title: 'PDC Tour API',
    subtitle: 'Rankings, fixtures, live scores, averages, and checkout data.',
    partnerBadge: 'PDC official data partner · API key required · commercial licence',
    connectLabel: 'Connect PDC API',
    summaryText: 'The canonical source for PDC Order of Merit, Pro Tour fixtures, televised events, Players Championship results, and point-level match data. Powers the rankings tracker, forecaster, and live-score view.',
    connectedStats: [
      { label: 'API Status', value: '✓ Connected' },
      { label: 'OoM Updated', value: 'Mon 00:00 GMT' },
      { label: 'Events', value: '128 in 2026' },
      { label: 'Players Indexed', value: '140+' },
    ],
    whyHeading: 'Why the PDC API is the highest-priority darts integration',
    whyBody: 'Without the PDC API the Order of Merit tracker is manual entry — unusable for a tour pro. With it, every Monday Lumio recomputes the live ranking, flags points rolling off the 2-year Order of Merit window, updates the Premier League scenario model, and feeds the prize-forecaster. Pro Tour schedules, European Tour qualifier cut-offs, and the TV Major draw sheets all flow from this single connection.',
    endpointsTitle: 'API Endpoints Used by Lumio Darts',
    endpoints: [
      { endpoint: 'Order of Merit', desc: 'Live OoM ranking recomputed every Monday — 2-year rolling window.', status: 'Live' },
      { endpoint: 'Points Decay Calendar', desc: 'Prize money falling off in each forward quarter — powers the expiry view.', status: 'Live' },
      { endpoint: 'Tour Card Status', desc: 'Top 64 + Q-School graduates — feeds the Tour Card view.', status: 'Live' },
      { endpoint: 'Pro Tour Fixtures', desc: 'Players Championship + European Tour qualifier schedule.', status: 'Live' },
      { endpoint: 'Televised Events Draw', desc: 'World Matchplay, Grand Prix, Grand Slam, Worlds draw sheets.', status: 'Live' },
      { endpoint: 'Live Scores', desc: 'Leg-by-leg live scores during any PDC-sanctioned match.', status: 'Live' },
      { endpoint: 'Match Averages', desc: 'Per-match 3-dart average, first-9, checkout % by opponent.', status: 'Live' },
      { endpoint: 'Checkout Statistics', desc: 'Attempts, hits, and finish-leg conversion per player.', status: 'Live' },
      { endpoint: 'Premier League Standings', desc: 'Round-by-round league standings during the PL window.', status: 'Live' },
      { endpoint: 'Prize Money Breakdown', desc: 'Per-round prize money per event — feeds forecaster.', status: 'Live' },
    ],
    coverage: {
      title: 'Tour Coverage — PDC API',
      columns: ['Tier', 'Events', 'Live Scores', 'OoM', 'Averages', 'Draws'],
      rows: [
        ['TV Majors', '12', '✓ Leg-level', '✓ Full', '✓ Full', '✓'],
        ['Premier League', '17', '✓ Leg-level', '✓ Full', '✓ Full', '✓'],
        ['World Championship', '1', '✓ Leg-level', '✓ Full', '✓ Full', '✓'],
        ['Pro Tour (Players Champ.)', '30', '✓ Leg-level', '✓ Full', '✓ Full', '✓'],
        ['European Tour', '13', '✓ Leg-level', '✓ Full', '✓ Full', '✓'],
        ['Development / Challenge Tour', '~60', 'Partial', '✓ Full', 'Partial', '✓'],
      ],
    },
    pricing: 'PDC API licensing varies by call volume and data depth — typical range approximately $400–$1,500/month for a product like Lumio. Backend cost absorbed by Lumio, not charged to players. TV-rights data (broadcast slots, exclusive clips) is a separate negotiation per-event.',
  },

  'wdf-api': {
    icon: '🌍',
    title: 'WDF Data Feed',
    subtitle: 'Amateur + youth rankings, BDO legacy events, and international qualifiers.',
    partnerBadge: 'WDF data-sharing agreement · ranked events only',
    connectLabel: 'Connect WDF Feed',
    summaryText: 'Complements the PDC API with amateur-tier rankings, youth series results, and the WDF World Masters / Lakeside events. Useful for players transitioning from amateur or entering via Q-School.',
    connectedStats: [
      { label: 'Rankings', value: '✓ Weekly' },
      { label: 'Events', value: '260+ tracked' },
      { label: 'Regions', value: '40+ federations' },
      { label: 'Youth Series', value: '✓' },
    ],
    whyHeading: 'Why the WDF feed matters for transition-tier players',
    whyBody: 'The PDC API is the tour feed — but a player in Q-School or the first year off a Tour Card often has half their competitive calendar in WDF-sanctioned events. Without the WDF feed those results are invisible to Lumio. With it, amateur rankings, international qualifying events, and youth-series results all flow into one place — useful for agents scouting and for players building a full season-view.',
    endpointsTitle: 'Data Flows Used by Lumio Darts',
    endpoints: [
      { endpoint: 'WDF Rankings', desc: 'Weekly-updated amateur rankings per federation.', status: 'Live' },
      { endpoint: 'World Masters / Lakeside', desc: 'Draws, results, and prize money for WDF TV events.', status: 'Live' },
      { endpoint: 'International Qualifiers', desc: 'PDC qualifier events run outside the PDC tour structure.', status: 'Live' },
      { endpoint: 'Youth Series Results', desc: 'Junior + youth rankings — used by agents scouting next-gen talent.', status: 'Live' },
      { endpoint: 'Federation Mapping', desc: 'Player-to-federation lookup (JDC, DPNZ, DCA, etc.).', status: 'Beta' },
      { endpoint: 'Historical Amateur Results', desc: 'Pre-tour-card career history — useful for Q-School prep.', status: 'Beta' },
    ],
    pricing: 'WDF data-sharing is typically free or low-cost — the federation releases rankings publicly. Lumio runs a sync job nightly. No player-level cost.',
  },

  dartconnect: {
    icon: '🎯',
    title: 'DartConnect',
    subtitle: 'On-oche digital scorekeeping with live streaming and session analytics.',
    partnerBadge: 'DartConnect Pro API · tablet-based scoring · venue + home use',
    connectLabel: 'Connect DartConnect',
    summaryText: 'Pull every practice session, venue match, and league night into Lumio automatically. DartConnect is the on-oche scorekeeping app used across the tour — connecting it gives Lumio shot-level granularity without manual entry.',
    connectedStats: [
      { label: 'Sessions Synced', value: '247' },
      { label: 'Matches', value: '128' },
      { label: 'Practice Logs', value: '119' },
      { label: 'Latest Sync', value: '3 min ago' },
    ],
    whyHeading: 'Why DartConnect is the performance-critical integration',
    whyBody: 'Every practice session averaged, every checkout attempted, every leg played at a venue or league — DartConnect captures them all on a tablet at the oche. Without the integration, Lumio relies on post-session manual entry (the thing pro players never actually do). With it, the 3-dart average trend line is real, the checkout % is live, and the dart-cam analytics have context. It\'s the darts equivalent of a golf shot-tracker.',
    endpointsTitle: 'Data Flows Used by Lumio Darts',
    endpoints: [
      { endpoint: 'Session Summary', desc: '3-dart average, first-9 average, checkout % per session.', status: 'Live' },
      { endpoint: 'Match Results', desc: 'Leg-by-leg match scorecards with opponent metadata.', status: 'Live' },
      { endpoint: 'Practice Metrics', desc: 'Drill-specific analytics — doubles practice, combo drills, bogey numbers.', status: 'Live' },
      { endpoint: 'Historical Archive', desc: 'Overnight sync of the full session history when first connected.', status: 'Live' },
      { endpoint: 'Live Streaming Link', desc: 'DartConnect-streamed matches auto-tagged for review.', status: 'Beta' },
      { endpoint: 'Opponent Tagging', desc: 'Match opponent data sync — feeds head-to-head view.', status: 'Beta' },
      { endpoint: 'Dart-by-Dart Log', desc: 'Individual dart scores per leg for heatmap — Planned.', status: 'Planned' },
    ],
    pricing: 'DartConnect Pro is approximately £8–£15/month per account. Lumio-connected players usually already have the subscription via a venue or home set-up. OAuth connection is free on Lumio\'s side — no data stored without consent.',
  },

  dartfish: {
    icon: '📹',
    title: 'Lumio Vision Video',
    subtitle: 'High-frame video capture and motion analysis for throw breakdown.',
    partnerBadge: 'Lumio Vision Live · 240fps iOS capture · coach video platform',
    connectLabel: 'Connect Lumio Vision',
    summaryText: 'Sync every coached throw breakdown, slow-mo comparison, and annotated session into the Lumio video library. The standard for technical throw analysis across the sport.',
    connectedStats: [
      { label: 'Clips Synced', value: '486' },
      { label: 'Annotated', value: '126' },
      { label: 'Latest Capture', value: '12 Apr' },
      { label: 'Storage', value: '6.8 GB' },
    ],
    whyHeading: 'Why Lumio Vision is a complementary (high-impact) integration',
    whyBody: 'Lumio Vision is the de-facto video tool used by coaches breaking down throw mechanics — stance, release point, follow-through. Connecting it means annotated comparison clips from your coach flow straight into Lumio\'s video library, tagged and searchable. Without it, the coach\'s work sits in a parallel app and the player has to switch contexts every time they want to review.',
    endpointsTitle: 'Data Flows Used by Lumio Darts',
    endpoints: [
      { endpoint: 'Video Library', desc: 'Every captured throw clip with metadata (session, angle, distance).', status: 'Live' },
      { endpoint: 'Coach Annotations', desc: 'Lumio Vision overlay drawings and voice-notes preserved on import.', status: 'Live' },
      { endpoint: 'Side-by-Side Comparisons', desc: 'Two-clip comparisons from the coach — imported with both clips.', status: 'Live' },
      { endpoint: 'Frame-Level Markers', desc: 'Release-point and impact markers — powers slow-mo scrubber.', status: 'Live' },
      { endpoint: 'Session Tagging', desc: 'Practice / match / exhibition tags flow into Lumio filters.', status: 'Beta' },
      { endpoint: 'AI Release-Point Detection', desc: 'Auto-flag release-point drift vs baseline — Planned for Q3.', status: 'Planned' },
    ],
    pricing: 'Lumio Vision Live is approximately £50/year for individuals. Coach tiers start at approximately £200/year. Lumio-connected players typically have the subscription via their coach — OAuth connection is free.',
  },

  whoop: {
    icon: '💚',
    title: 'Lumio Wear / Oura',
    subtitle: 'Sleep, HRV, recovery and strain piped into every morning briefing.',
    partnerBadge: 'OAuth available · Lumio Wear + Oura · ring or strap',
    connectLabel: 'Connect Lumio Wear / Oura',
    summaryText: 'Pipe HRV, recovery score, sleep duration and strain into Lumio every morning. The difference between a fresh practice session and a foggy one — now visible before you pick up the darts.',
    connectedStats: [
      { label: 'Last Sync', value: '07:02' },
      { label: 'Recovery', value: '74%' },
      { label: 'HRV', value: '60 ms' },
      { label: 'Sleep', value: '7h 34m' },
    ],
    whyHeading: 'Why Lumio Wear / Oura matters for TV-event pacing',
    whyBody: 'Televised darts nights are late-finishing, high-adrenaline, high-alcohol-exposure environments. A player on a run can play three matches in one evening and not fall asleep until 4am. Feeding Lumio Wear/Oura into Lumio means the morning after a late night, the practice plan is pre-calibrated to a 60% recovery score — not a generic "full day" block. Cumulative sleep debt across a 14-day Worlds run is the single biggest driver of late-tournament average drop.',
    endpointsTitle: 'Data Flows Used by Lumio Darts',
    endpoints: [
      { endpoint: 'Recovery Score', desc: 'Lumio Wear 0-100 daily recovery or Oura Readiness score.', status: 'Live' },
      { endpoint: 'HRV (RMSSD)', desc: 'Overnight HRV — leading indicator of fatigue carryover.', status: 'Live' },
      { endpoint: 'Sleep Stages', desc: 'REM / deep / light split — feeds the sleep-debt tile.', status: 'Live' },
      { endpoint: 'Daily Strain', desc: 'Strain vs target — useful for quantifying adrenaline-heavy match nights.', status: 'Live' },
      { endpoint: 'Resting Heart Rate', desc: 'Morning RHR — detects travel fatigue and illness incubation.', status: 'Live' },
      { endpoint: 'Respiratory Rate', desc: 'Overnight breath rate — early illness flag on the winter TV circuit.', status: 'Beta' },
      { endpoint: 'Alcohol-Impact Flag', desc: 'Recovery-drop pattern detection — Planned for Q3.', status: 'Planned' },
    ],
    pricing: 'Free to connect if the player has Lumio Wear or Oura. Lumio Wear approximately £20/month; Oura approximately £5/month plus ring hardware. Lumio adds no fee — OAuth connection only.',
  },

  johansports: {
    icon: '🛰️',
    title: 'Johan Sports',
    subtitle: 'Step count, walk-on HR, and hydration-adjusted strain for TV-week pacing.',
    partnerBadge: 'OAuth · 10Hz GPS + IMU · CSV import for any other vendor',
    connectLabel: 'Connect Johan Sports',
    summaryText: 'Step count, walk-on HR spike, hydration-adjusted strain. Essential for TV-event weeks where practice-room pacing and green-room waits affect in-match sharpness.',
    connectedStats: [
      { label: 'Session (today)', value: '8,420 steps' },
      { label: 'Walk-on HR peak', value: '142 bpm' },
      { label: 'Load 7-day', value: '1,220 AU' },
      { label: 'Device', value: 'Johan Sports' },
    ],
    whyHeading: 'Why GPS load tracking matters on TV-week',
    whyBody: 'Darts looks static but a TV night is four hours on your feet — practice room, walk-on lane, green room, stage, back to practice. The total step count and HR-zone distribution during a TV day is a meaningful load number that correlates with late-match average drop. Feeding the GPS-vest data into the platform lets the physio see hydration-adjusted strain in near-real-time and intervene between matches.',
    endpointsTitle: 'Data Flows Used by Lumio Darts',
    endpoints: [
      { endpoint: 'Step Count', desc: 'Daily step count with practice / match / off-stage breakdown.', status: 'Live' },
      { endpoint: 'Walk-on HR Spike', desc: 'Peak HR during walk-on and first leg — adrenaline benchmark.', status: 'Live' },
      { endpoint: 'Session Duration', desc: 'Time on feet during a venue night — practice + stage time.', status: 'Live' },
      { endpoint: 'HR Zone Distribution', desc: 'Time in resting / elevated / peak zones across the day.', status: 'Live' },
      { endpoint: 'Hydration-Adjusted Strain', desc: 'Strain normalised for estimated fluid balance — TV-week only.', status: 'Beta' },
      { endpoint: 'Green-Room Recovery Window', desc: 'Between-match recovery HR curve — flags under-recovery.', status: 'Beta' },
      { endpoint: 'Tremor Proxy', desc: 'Accelerometer steadiness score during warm-ups — Planned.', status: 'Planned' },
    ],
    pricing: 'Johan Sports licences are quoted per unit on a per-team basis — speak to the Johan Sports sales team for current pricing. CSV upload is always available as a fallback if you use a different vendor.',
  },

  workspace: {
    icon: '📧',
    title: 'Gmail + Calendar',
    subtitle: 'Tournament entries, sponsor emails, and team meetings in one place.',
    partnerBadge: 'Google OAuth · gmail.readonly + calendar.events scopes',
    connectLabel: 'Sign in with Google',
    summaryText: 'Sponsor obligations, tournament confirmations, TV-event briefing packs, and exhibition enquiries all flow into Lumio\'s morning briefing automatically. No tab-switching, no missed threads.',
    connectedStats: [
      { label: 'Inbox Sync', value: '2 min ago' },
      { label: 'Calendars', value: '2 active' },
      { label: 'Drafts', value: '3 pending' },
      { label: 'Account', value: 'jake@…' },
    ],
    whyHeading: 'Why Gmail + Calendar is the single biggest time saver',
    whyBody: 'A pro darts player with sponsorship deals, exhibition enquiries, tour admin, and a management company easily fields 50+ emails a day. Classification tagging turns that into a sorted list the player actually reads. Calendar sync means exhibition dates, practice sessions, media slots, and tournament fixtures all sit on one timeline — visible to the manager, agent, and coach.',
    endpointsTitle: 'Data Flows Used by Lumio Darts',
    endpoints: [
      { endpoint: 'Inbox Classification', desc: 'Every email tagged: tournament / sponsor / exhibition / travel / personal.', status: 'Live' },
      { endpoint: 'Exhibition Enquiry Detection', desc: 'Promoter emails auto-extracted into the Exhibitions view.', status: 'Live' },
      { endpoint: 'Calendar Sync', desc: 'Two-way — add a match to Lumio, it lands in Google Calendar.', status: 'Live' },
      { endpoint: 'Tour-Admin Extraction', desc: 'Entry confirmations, qualifier cut-offs, Q-School dates.', status: 'Live' },
      { endpoint: 'Sponsor Obligation Flagging', desc: 'Brand-email deliverables and deadlines into Sponsorship tracker.', status: 'Live' },
      { endpoint: 'AI Reply Drafts', desc: 'Suggested replies in your voice — review and send from Lumio.', status: 'Beta' },
      { endpoint: 'OOO for TV Weeks', desc: 'Auto-set OOO for World Championship / Worlds windows — Planned.', status: 'Planned' },
    ],
    pricing: 'Free on personal Gmail and Google Workspace. OAuth only — no credentials stored on Lumio servers. Microsoft 365 / Outlook supported via parallel OAuth at no extra cost.',
  },

  slack: {
    icon: '💬',
    title: 'Slack',
    subtitle: 'Team messaging with role-aware alerts for manager, coach, sponsor.',
    partnerBadge: 'Slack OAuth · per-workspace install · private channels supported',
    connectLabel: 'Add to Slack',
    summaryText: 'Route Lumio alerts to the right room — briefings to #coaching, sponsor obligations to #manager, exhibition enquiries to #agent. Each role only sees what they need.',
    connectedStats: [
      { label: 'Workspace', value: 'team-morrison' },
      { label: 'Channels', value: '4 wired' },
      { label: 'DM fallback', value: 'Enabled' },
      { label: 'Alert Rules', value: '9 active' },
    ],
    whyHeading: 'Why Slack is the glue for a travelling team',
    whyBody: 'A pro darts team — manager, agent, coach, maybe a physio — is a small distributed operation. Slack is already where messaging happens. Lumio slots in as another bot: morning briefings to the team channel, sponsor flags to the manager, exhibition enquiries to the agent. No email noise, no missed pings, role-aware routing means nobody gets spammed about what isn\'t theirs.',
    endpointsTitle: 'Data Flows Used by Lumio Darts',
    endpoints: [
      { endpoint: 'Role-Based Routing', desc: '"Send Exhibition enquiries over £10k to #manager" — configured in Settings.', status: 'Live' },
      { endpoint: 'Morning Briefing Push', desc: 'Full briefing delivered to the team channel before first practice.', status: 'Live' },
      { endpoint: 'Match-Night Alerts', desc: 'Draw updates, opponent swaps, and live-score flags during TV events.', status: 'Live' },
      { endpoint: 'Exhibition Enquiry Alerts', desc: 'New promoter emails routed to the agent channel with context.', status: 'Live' },
      { endpoint: 'Slash Commands', desc: '/lumio recovery, /lumio next-event — Slack-native.', status: 'Beta' },
      { endpoint: 'Thread AI Q&A', desc: 'Ask the Lumio bot a question in a thread — inline answer.', status: 'Beta' },
      { endpoint: 'Huddle Summaries', desc: 'Auto-transcribed team huddles with action-items — Planned.', status: 'Planned' },
    ],
    pricing: 'Slack free-tier covers teams under 10. Slack Pro approximately £7/user/month — typically billed to the management company. Lumio\'s Slack app is bundled, no additional fee.',
  },

  broadcast: {
    icon: '📺',
    title: 'Meridian Sports',
    subtitle: 'TV broadcast schedule, clip library, and press-access coordination.',
    partnerBadge: 'Meridian Sports API · partner access · UK + EU coverage',
    connectLabel: 'Connect Meridian Sports',
    summaryText: 'Pull your upcoming TV slots, clip library from past events, and press-access windows — all scheduled alongside tournaments in the Media module.',
    connectedStats: [
      { label: 'Next Broadcast', value: 'QF Fri 20:00' },
      { label: 'Clips (YTD)', value: '22' },
      { label: 'Press Slots', value: '3 scheduled' },
      { label: 'Region', value: 'UK + EU' },
    ],
    whyHeading: 'Why Meridian Sports is a commercial integration',
    whyBody: 'TV broadcast schedule is where the commercial week lives. Knowing exactly when you\'re on air lets sponsors pre-plan social posts, the manager stagger press, and the player decline last-minute calls that clash with a featured match. Meridian\'s feed auto-populates the Media module instead of someone chasing the broadcast office each Sunday night.',
    endpointsTitle: 'Data Flows Used by Lumio Darts',
    endpoints: [
      { endpoint: 'Broadcast Schedule', desc: 'Featured-match slots and main-stage coverage windows.', status: 'Live' },
      { endpoint: 'Clip Library', desc: 'Broadcast-quality clips from past events — into Lumio Video Library.', status: 'Live' },
      { endpoint: 'Press Access Windows', desc: 'Mixed-zone and sit-down press commitments — blocks calendar.', status: 'Live' },
      { endpoint: 'Featured-Match Flags', desc: '48h lead alert for featured slots.', status: 'Live' },
      { endpoint: 'Rights / Blackout Map', desc: 'Regions cleared for clip / repost — powers sponsor social scheduler.', status: 'Beta' },
      { endpoint: 'Live Rundown Feed', desc: 'In-event rundown during broadcast — Planned for Worlds window.', status: 'Planned' },
    ],
    pricing: 'Meridian partner access typically arranged through management. Basic schedule + clip library tier is bundled in the broadcast-rights package. Higher tiers are a separate commercial conversation.',
  },

  mobileapp: {
    icon: '📲',
    title: 'Mobile App',
    subtitle: 'Lumio on your phone — briefings, match-day view, quick shot-logging.',
    partnerBadge: 'iOS + Android · native push · offline support for travel',
    connectLabel: 'Install Mobile App',
    summaryText: 'Native iOS and Android app mirroring the dashboard — optimised for pre-match briefings, quick session logging, and offline viewing of tomorrow\'s match-prep brief.',
    connectedStats: [
      { label: 'App Version', value: '1.12.0' },
      { label: 'Push Alerts', value: 'Enabled' },
      { label: 'Offline Cache', value: '7 days' },
      { label: 'Platform', value: 'iOS + Android' },
    ],
    whyHeading: 'Why a mobile app matters on a TV-heavy circuit',
    whyBody: 'The web dashboard is built for the management team; the mobile app is for the player. Pre-match briefings, opponent scout cards, quick-log of practice sessions, and offline access to tomorrow\'s prep all live in a native app. Push notifications fire for draw changes, exhibition enquiries, and TV-schedule swaps — without needing the laptop.',
    endpointsTitle: 'Mobile App Capabilities',
    endpoints: [
      { endpoint: 'Morning Briefing Push', desc: 'Full briefing at 08:00 local — adjusts to the player\'s timezone.', status: 'Live' },
      { endpoint: 'Match-Prep Brief', desc: 'Pre-match scout card — cached offline for warm-up reading.', status: 'Live' },
      { endpoint: 'Quick Session Log', desc: 'One-tap practice logging — duration, drills, average.', status: 'Live' },
      { endpoint: 'Draw / Opponent Alerts', desc: 'Push when the draw changes or a qualifier lands in your section.', status: 'Live' },
      { endpoint: 'Voice Dictation', desc: 'Speak a practice note → transcribed to the practice log.', status: 'Beta' },
      { endpoint: 'Offline Mode', desc: '7-day cache of briefings, match prep, and video clips.', status: 'Live' },
      { endpoint: 'Watch Companion', desc: 'Apple Watch / Wear OS glances — Planned for Q4.', status: 'Planned' },
    ],
    pricing: 'Bundled in every Lumio Darts plan at no extra cost. iOS app via App Store; Android via Google Play. Beta channel available for testers.',
  },
}
