import type { IntegrationConfig } from './integration-detail-view'

export const GOLF_INTEGRATIONS: Record<string, IntegrationConfig> = {
  whoop: {
    icon: '💚',
    title: 'Lumio Wear / Oura',
    subtitle: 'Sleep, HRV, recovery and strain piped into every morning briefing.',
    partnerBadge: 'OAuth available · Lumio Wear + Oura · ring or strap',
    connectLabel: 'Connect Lumio Wear / Oura',
    summaryText: 'Pipe HRV, recovery score, sleep duration and strain into Lumio every morning — so your coach sees red-flag recovery scores before you walk onto the range.',
    connectedStats: [
      { label: 'Last Sync', value: '06:12' },
      { label: 'Recovery', value: '78%' },
      { label: 'HRV', value: '62 ms' },
      { label: 'Sleep', value: '7h 48m' },
    ],
    whyHeading: 'Why Lumio Wear / Oura is a complementary integration',
    whyBody: 'Physical recovery is the single biggest predictor of short-game feel on tour. Piping recovery scores into the morning briefing lets Lumio pre-empt deterioration — if HRV is 20% below baseline the day before Round 3, the briefing flags it, your physio sees it, and the practice plan gets dialled back before anyone has to ask.',
    endpointsTitle: 'Data Flows Used by Lumio Golf',
    endpoints: [
      { endpoint: 'Recovery Score (Lumio Wear)', desc: 'Daily 0-100 score blending HRV, RHR, sleep and respiratory rate.', status: 'Live' },
      { endpoint: 'Readiness Score (Oura)', desc: 'Oura Ring equivalent of recovery — pulled via OAuth in the same flow.', status: 'Live' },
      { endpoint: 'HRV (RMSSD)', desc: 'Overnight heart-rate variability — the leading indicator of parasympathetic recovery.', status: 'Live' },
      { endpoint: 'Sleep Stages', desc: 'REM / deep / light split plus total sleep vs. target — powers the sleep debt tile.', status: 'Live' },
      { endpoint: 'Strain / Activity', desc: 'Daily strain (Lumio Wear) or activity (Oura) — cross-referenced with round/practice load.', status: 'Live' },
      { endpoint: 'Respiratory Rate', desc: 'Overnight breath rate — an early illness flag during travel-heavy swings.', status: 'Beta' },
      { endpoint: 'Strain Coach Alerts', desc: 'Suggested target strain given yesterday\'s recovery — delivered into the morning briefing.', status: 'Planned' },
    ],
    pricing: 'Free if the player already has a Lumio Wear or Oura subscription (both consumer wearables). No additional cost to Lumio — OAuth connection only. If neither is connected, the morning briefing hides the Recovery tile rather than showing a placeholder.',
  },

  catapult: {
    icon: '🛰️',
    title: 'Lumio GPS / Lumio GPS Pro',
    subtitle: 'Per-session load tracking across range, course walks, and gym work.',
    partnerBadge: 'API key required · Lumio GPS Vector + Lumio GPS Pro APEX / EDGE supported',
    connectLabel: 'Connect Lumio GPS / Lumio GPS Pro',
    summaryText: 'Track per-session load across range, course walks, and gym work. Critical for multi-week Majors stretches where cumulative fatigue impacts short-game feel.',
    connectedStats: [
      { label: 'Sessions (30d)', value: '42' },
      { label: 'Avg Distance', value: '9.2 km' },
      { label: 'Load 7-day', value: '1,840 AU' },
      { label: 'Provider', value: 'Lumio GPS Vector' },
    ],
    whyHeading: 'Why Lumio GPS / Lumio GPS Pro matters on tour',
    whyBody: 'Golf looks low-intensity but 72 holes of competitive walking plus range and gym sessions stacks real cumulative load — especially on hilly links or in heat. Feeding the GPS vest data into Lumio lets the fitness coach see if the player is cumulatively trending into a strain bracket that historically correlates with short-game dropoff. It\'s the difference between "he felt off on Sunday" and "Sunday was inevitable from Wednesday".',
    endpointsTitle: 'Data Flows Used by Lumio Golf',
    endpoints: [
      { endpoint: 'Session Summary', desc: 'Total distance, high-speed running, max HR, duration — one row per session.', status: 'Live' },
      { endpoint: 'Zone Distribution', desc: 'Time-in-zone for HR and speed bands — useful for heat-stress flagging.', status: 'Live' },
      { endpoint: 'Acute / Chronic Workload', desc: 'Rolling 7- and 28-day load — the ACWR ratio drives the fitness/fatigue tile.', status: 'Live' },
      { endpoint: 'Player Load (AU)', desc: 'Proprietary arbitrary-units load metric — maps across provider boundaries.', status: 'Live' },
      { endpoint: 'Heat / Environmental', desc: 'Core temp estimate and ambient — powers the hydration-adjusted strain tile.', status: 'Beta' },
      { endpoint: 'Gym Sessions', desc: 'Indoor IMU sessions for strength work — tagged separately from range / course.', status: 'Beta' },
      { endpoint: 'Sleep + Load Correlation', desc: 'Cross-references wearable sleep data to flag under-recovery before an acute spike.', status: 'Planned' },
    ],
    pricing: 'Lumio GPS Vector licences run approximately £800–£1,400/year per unit. Lumio GPS Pro APEX/EDGE is approximately £400–£700/year. Lumio is hardware-agnostic — whichever vendor the player\'s fitness coach uses, the same dashboard shows the data.',
  },

  v1golf: {
    icon: '🎥',
    title: 'V1 Golf Video',
    subtitle: 'Swing capture, frame-by-frame analysis, and coach annotation.',
    partnerBadge: 'V1 Pro API · V1 Sports · iOS + Android capture apps',
    connectLabel: 'Connect V1 Golf',
    summaryText: 'Pull every V1 Pro swing capture, annotation, and coach comparison clip directly into the Lumio video library — synced overnight with tags intact.',
    connectedStats: [
      { label: 'Clips Synced', value: '1,247' },
      { label: 'Coach Notes', value: '186' },
      { label: 'Latest Capture', value: '14 Apr' },
      { label: 'Library Size', value: '18.4 GB' },
    ],
    whyHeading: 'Why V1 Golf is a core swing-capture integration',
    whyBody: 'Most tour coaches already live in V1 Pro — swing clips, frame-by-frame annotations, and side-by-side comparisons are already stored there. Connecting Lumio means the Video Library stops being a parallel universe and starts being the same content, just surfaced alongside the round data. Every annotated clip your coach makes shows up tagged and searchable in under 12 hours.',
    endpointsTitle: 'Data Flows Used by Lumio Golf',
    endpoints: [
      { endpoint: 'Swing Library', desc: 'Every captured clip with metadata (club, date, angle, face-on/down-line).', status: 'Live' },
      { endpoint: 'Coach Annotations', desc: 'V1 overlay drawings and voice-over notes — preserved on import.', status: 'Live' },
      { endpoint: 'Side-by-Side Comparisons', desc: 'Two-clip comparisons the coach built — the most-watched swing learning format.', status: 'Live' },
      { endpoint: 'Session Tagging', desc: 'Range / course / gym tags flow into Lumio\'s category pills automatically.', status: 'Live' },
      { endpoint: 'Frame-Level Timestamps', desc: 'Top-of-backswing, impact, and finish markers — powers the slow-mo scrubber.', status: 'Beta' },
      { endpoint: 'Voice Memo Transcripts', desc: 'Coach voice-over auto-transcribed and searchable — Planned for Q3.', status: 'Planned' },
    ],
    pricing: 'V1 Golf Academy subscription starts at approximately $30/month per coach. V1 Pro API access is bundled in the coaching tier. If your coach already uses V1, connection is an OAuth click; if they don\'t, no data loss — Lumio\'s native Video Library still works standalone.',
  },

  workspace: {
    icon: '📧',
    title: 'Gmail + Calendar',
    subtitle: 'Tournament entries, sponsor emails, and coach meetings in one place.',
    partnerBadge: 'Google OAuth · gmail.readonly + calendar.events scopes',
    connectLabel: 'Sign in with Google',
    summaryText: 'Stop switching tabs. Sponsor obligations, tournament entry confirmations, travel bookings, and coach meetings all flow into Lumio\'s morning briefing automatically.',
    connectedStats: [
      { label: 'Inbox Sync', value: '2 min ago' },
      { label: 'Calendars', value: '3 active' },
      { label: 'Drafts', value: '4 pending' },
      { label: 'Account', value: 'amargeison@…' },
    ],
    whyHeading: 'Why connecting Gmail + Calendar is the single biggest time saver',
    whyBody: 'On tour, the 30 minutes spent every morning scrolling email for what actually matters is 30 minutes of mental energy not spent on the round. Lumio\'s Gmail integration runs overnight classification — tournament admin, sponsor obligation, coach meeting, travel booking, personal — and only surfaces what needs the player\'s attention. Calendar sync puts tee times, physio slots, and sponsor commitments on a single timeline the whole team can see.',
    endpointsTitle: 'Data Flows Used by Lumio Golf',
    endpoints: [
      { endpoint: 'Inbox Classification', desc: 'Every inbound email tagged: tournament / sponsor / travel / coach / personal.', status: 'Live' },
      { endpoint: 'Tournament Entry Detection', desc: 'Auto-extracts event, date, entry fee from tour email confirmations.', status: 'Live' },
      { endpoint: 'Calendar Sync', desc: 'Two-way sync — add a tee time in Lumio and it lands in Google Calendar.', status: 'Live' },
      { endpoint: 'Coach Meeting Extraction', desc: 'Detects video-call links in meeting invites and surfaces them in morning briefing.', status: 'Live' },
      { endpoint: 'Sponsor Obligation Flagging', desc: 'Pulls deliverables and deadlines out of brand emails into Sponsorship tracker.', status: 'Live' },
      { endpoint: 'Reply Drafting (AI)', desc: 'Suggested replies drafted in your voice — review and send without leaving Lumio.', status: 'Beta' },
      { endpoint: 'Out-of-Office Auto-Set', desc: 'Auto-enable OOO for Majors weeks based on tournament schedule — Planned.', status: 'Planned' },
    ],
    pricing: 'Free for Google Workspace personal and Workspace accounts. No charge from Lumio — OAuth only, no credentials stored. Microsoft 365 / Outlook support mirrors the same capability and is available via the parallel OAuth flow.',
  },

  slack: {
    icon: '💬',
    title: 'Slack',
    subtitle: 'Team messaging with role-aware alerts for coach, physio, manager, agent.',
    partnerBadge: 'Slack OAuth · per-workspace install · private channels supported',
    connectLabel: 'Add to Slack',
    summaryText: 'Route Lumio alerts to the right room — morning briefings to #coaching, physio flags to #medical, sponsor obligations to #manager. Each role sees only what they need.',
    connectedStats: [
      { label: 'Workspace', value: 'team-halton' },
      { label: 'Channels', value: '6 wired' },
      { label: 'DM fallback', value: 'Enabled' },
      { label: 'Alert Rules', value: '14 active' },
    ],
    whyHeading: 'Why Slack is the glue for a travelling team',
    whyBody: 'A touring golf team is four people on three continents running a business in two time zones. Slack is already where the team lives — so Lumio slots in as another well-behaved app, routing the right alert to the right room. Physio sees recovery flags; the manager sees sponsor obligations; the coach sees practice-load trends. Nobody gets pinged about stuff that isn\'t their job.',
    endpointsTitle: 'Data Flows Used by Lumio Golf',
    endpoints: [
      { endpoint: 'Role-Based Routing', desc: 'Rules like "send Recovery < 60% alerts to #physio" — configured in Settings.', status: 'Live' },
      { endpoint: 'Morning Briefing Push', desc: 'Full briefing delivered to the team channel before first tee, replacing mass email.', status: 'Live' },
      { endpoint: 'Sponsor Obligation Alerts', desc: 'Upcoming deliverables flagged 48h ahead — routed to manager.', status: 'Live' },
      { endpoint: 'DM Fallback', desc: 'If a channel goes silent, escalation DMs the primary owner automatically.', status: 'Live' },
      { endpoint: 'Two-Way Commands', desc: '/lumio recovery, /lumio next-event — triggered from Slack directly.', status: 'Beta' },
      { endpoint: 'Thread-Based AI Q&A', desc: 'Ask the Lumio bot a question in a thread — answer inline with the data.', status: 'Beta' },
      { endpoint: 'Huddle Summaries', desc: 'Auto-transcribed team huddles posted back with action-item extraction — Planned.', status: 'Planned' },
    ],
    pricing: 'Free on Slack\'s free tier for teams under 10. Slack Pro is approximately £7/user/month — typically billed to the player\'s management company as a standard tool. Lumio\'s Slack app itself is bundled — no extra fee.',
  },

  broadcast: {
    icon: '📺',
    title: 'Meridian Sports',
    subtitle: 'Broadcast schedule, clip library, and press-access coordination.',
    partnerBadge: 'Meridian Sports API · partner access required · UK + EU coverage',
    connectLabel: 'Connect Meridian Sports',
    summaryText: 'Pull your upcoming broadcast slots, clip library from past events, and press-access windows — all scheduled alongside tournaments in the Media module.',
    connectedStats: [
      { label: 'Next Broadcast', value: 'R3 Sat 14:30' },
      { label: 'Clips (YTD)', value: '47' },
      { label: 'Press Slots', value: '6 scheduled' },
      { label: 'Region', value: 'UK + EU' },
    ],
    whyHeading: 'Why Meridian Sports is a complementary integration',
    whyBody: 'Broadcast schedule is where the commercial week actually lives. Knowing when the player is on air lets sponsors pre-plan social posts, the manager stagger press commitments, and the player decline calls that clash with a featured-group window. Meridian\'s API makes the schedule auto-populate the Media module instead of someone chasing the broadcast office for a spreadsheet every Sunday night.',
    endpointsTitle: 'Data Flows Used by Lumio Golf',
    endpoints: [
      { endpoint: 'Broadcast Schedule', desc: 'Player-specific featured-group slots and leaderboard cut-ins.', status: 'Live' },
      { endpoint: 'Clip Library', desc: 'Broadcast-quality clips from past events — synced into Lumio Video Library.', status: 'Live' },
      { endpoint: 'Press Access Windows', desc: 'Mixed-zone and sit-down press commitments — blocks calendar automatically.', status: 'Live' },
      { endpoint: 'Featured-Group Flags', desc: 'Early alert when a featured-group slot is confirmed — 48h lead time.', status: 'Live' },
      { endpoint: 'Rights / Blackout Map', desc: 'Which regions can clip / repost — feeds the sponsor social scheduler.', status: 'Beta' },
      { endpoint: 'Broadcast Rundown Feed', desc: 'Live rundown during coverage — Planned for Ryder Cup window.', status: 'Planned' },
    ],
    pricing: 'Meridian Sports partner access is typically negotiated at management-company level. For Lumio-connected players, the basic schedule + clip-library tier is included in the player\'s broadcast-rights package. Higher tiers (live rundown, region-specific rights) are a separate commercial conversation.',
  },
}
