import type { IntegrationConfig } from './integration-detail-view'

export const TENNIS_INTEGRATIONS: Record<string, IntegrationConfig> = {
  'atp-api': {
    icon: '🏆',
    title: 'ATP Tour API',
    subtitle: 'Rankings, draws, results, and live scoring across the men\'s tour.',
    partnerBadge: 'ATP official data partner · API key required · commercial licence',
    connectLabel: 'Connect ATP API',
    summaryText: 'The canonical source for ATP singles and doubles rankings, entry lists, main-draw brackets, and live scores. Powers the rankings tracker, forecaster, and draw view.',
    connectedStats: [
      { label: 'API Status', value: '✓ Connected' },
      { label: 'Rankings Updated', value: 'Mon 02:00 GMT' },
      { label: 'Tournaments', value: '62 in 2026' },
      { label: 'Players Indexed', value: '2,400+' },
    ],
    whyHeading: 'Why the ATP API is the highest-priority tennis integration',
    whyBody: 'Without the ATP API the rankings tracker relies on manual entry — useless for a professional. With it, every Monday morning Lumio recomputes your live ranking, flags points dropping from the 52-week window, updates the race-to-finals standings, and feeds the scenario model for the week\'s tournament. Draw-sheets, prize-money breakdowns, and head-to-heads all flow from this one connection.',
    endpointsTitle: 'API Endpoints Used by Lumio Tennis',
    endpoints: [
      { endpoint: 'Live Rankings', desc: 'Weekly ATP singles + doubles ranking recomputed every Monday.', status: 'Live' },
      { endpoint: '52-Week Points Decay', desc: 'Points expiring next week, in 4 weeks, in 12 weeks — powers the expiry calendar.', status: 'Live' },
      { endpoint: 'Entry Lists', desc: 'Main-draw and qualifying entry lists with cut-offs and WC slots.', status: 'Live' },
      { endpoint: 'Draw Sheets', desc: 'Live brackets per tournament — updates as rounds complete.', status: 'Live' },
      { endpoint: 'Head-to-Head', desc: 'Career and surface-specific H2H records against any opponent.', status: 'Live' },
      { endpoint: 'Live Scores', desc: 'Point-by-point live scoring for every ATP-level main-draw match.', status: 'Live' },
      { endpoint: 'Prize Money Breakdown', desc: 'Per-round prize money per tournament — feeds the forecaster.', status: 'Live' },
      { endpoint: 'Match Stats', desc: 'Serve speed, winner/UE counts, break-point conversion per match.', status: 'Beta' },
      { endpoint: 'Race to Finals', desc: 'ATP Race standings + scenario projection to Finals qualification.', status: 'Live' },
    ],
    coverage: {
      title: 'Tour Coverage — ATP API',
      columns: ['Tier', 'Events', 'Live Scores', 'Rankings', 'Draws', 'Stats'],
      rows: [
        ['Grand Slams', '4', '✓ Point-level', '✓ Full', '✓', '✓ Full'],
        ['ATP Masters 1000', '9', '✓ Point-level', '✓ Full', '✓', '✓ Full'],
        ['ATP 500', '13', '✓ Point-level', '✓ Full', '✓', '✓ Full'],
        ['ATP 250', '36', '✓ Point-level', '✓ Full', '✓', 'Partial'],
        ['ATP Finals', '1', '✓ Point-level', '✓ Full', '✓', '✓ Full'],
        ['Challenger Tour', '~180', 'Partial', '✓ Full', '✓', 'Partial'],
      ],
    },
    pricing: 'ATP API commercial licensing varies by call volume and data depth — typical range is approximately $500–$2,500/month for a product like Lumio. This is a backend cost absorbed by Lumio, not charged to players. Grand Slam integration is a separate rights conversation handled via Tennis Australia, Roland-Garros, AELTC, and USTA.',
  },

  'wta-api': {
    icon: '🎾',
    title: 'WTA Tour API',
    subtitle: 'Rankings, draws, results, and live scoring across the women\'s tour.',
    partnerBadge: 'WTA official data partner · API key required · commercial licence',
    connectLabel: 'Connect WTA API',
    summaryText: 'Women\'s tour equivalent of the ATP feed. Rankings, entry lists, draw sheets, live scores and prize money for WTA 1000, 500, 250 and Finals.',
    connectedStats: [
      { label: 'API Status', value: '✓ Connected' },
      { label: 'Rankings Updated', value: 'Mon 02:00 GMT' },
      { label: 'Tournaments', value: '54 in 2026' },
      { label: 'Players Indexed', value: '2,100+' },
    ],
    whyHeading: 'Why the WTA API is a tour-critical integration',
    whyBody: 'Lumio\'s women\'s-tour mode runs on the WTA API end-to-end — same weekly ranking recompute, same 52-week decay calendar, same draw sheets and live scoring. Without it, every WTA-side feature (rankings tracker, forecaster, entry manager) degrades to manual entry. With it, the coach + agent + player all see the same numbers the tour itself publishes, updated within minutes.',
    endpointsTitle: 'API Endpoints Used by Lumio Tennis',
    endpoints: [
      { endpoint: 'Live Rankings', desc: 'Weekly WTA singles + doubles ranking recomputed every Monday.', status: 'Live' },
      { endpoint: '52-Week Points Decay', desc: 'Expiring points per opponent week — drives the defense-required projections.', status: 'Live' },
      { endpoint: 'Entry Lists', desc: 'Main-draw and qualifying entry lists for every WTA event.', status: 'Live' },
      { endpoint: 'Draw Sheets', desc: 'Live brackets updated round-by-round.', status: 'Live' },
      { endpoint: 'Head-to-Head', desc: 'Career + surface H2H records for every WTA-ranked player.', status: 'Live' },
      { endpoint: 'Live Scores', desc: 'Point-level live scoring during WTA-level matches.', status: 'Live' },
      { endpoint: 'Prize Money Breakdown', desc: 'Per-round prize money — feeds forecaster and agent reconciliation.', status: 'Live' },
      { endpoint: 'Match Stats', desc: 'Serve speed, winners, break points per WTA match.', status: 'Beta' },
      { endpoint: 'Race to Finals', desc: 'WTA Race standings + Finals qualification scenario projection.', status: 'Live' },
    ],
    coverage: {
      title: 'Tour Coverage — WTA API',
      columns: ['Tier', 'Events', 'Live Scores', 'Rankings', 'Draws', 'Stats'],
      rows: [
        ['Grand Slams', '4', '✓ Point-level', '✓ Full', '✓', '✓ Full'],
        ['WTA 1000', '10', '✓ Point-level', '✓ Full', '✓', '✓ Full'],
        ['WTA 500', '13', '✓ Point-level', '✓ Full', '✓', '✓ Full'],
        ['WTA 250', '27', '✓ Point-level', '✓ Full', '✓', 'Partial'],
        ['WTA Finals + Elite Trophy', '2', '✓ Point-level', '✓ Full', '✓', '✓ Full'],
        ['ITF World Tennis Tour', '~150', 'Partial', '✓ Full', '✓', 'Partial'],
      ],
    },
    pricing: 'Similar commercial licensing to the ATP API — approximately $500–$2,500/month depending on call volume. Backend cost absorbed by Lumio. Grand Slam data flows through the same per-Slam rights agreements.',
  },

  lumioVision: {
    icon: '🎬',
    title: 'Lumio Vision',
    subtitle: 'Upload your match video. Lumio Vision timestamps it against your GPS session so you can review any moment in one click.',
    partnerBadge: 'Coming Soon · Rolling out through 2026',
    connectLabel: 'Coming Soon',
    summaryText: 'Lumio-built video analysis, aligned with the GPS session timeline — upload match footage and review any point in one click. Shot detection and serve analytics rolling out through 2026.',
    connectedStats: [
      { label: 'Sessions', value: '—' },
      { label: 'Rallies', value: '—' },
      { label: 'Clips Tagged', value: '—' },
      { label: 'Storage', value: '—' },
    ],
    whyHeading: 'Why Lumio Vision is our in-house video layer',
    whyBody: 'Lumio Vision is Lumio-built video analysis designed to align cleanly with the GPS session timeline — upload, tag, and review any point in one click. Shot detection and serve analytics are rolling out through 2026; until then, the portal keeps your match footage indexed against your movement data so coaches and players always have a shared reference. No third-party account required when it launches.',
    endpointsTitle: 'Planned Data Flows',
    endpoints: [
      { endpoint: 'Video Upload + GPS Timestamp Sync', desc: 'Match video aligned with GPS session timeline.', status: 'Beta' },
      { endpoint: 'Point-by-Point Clips', desc: 'Full-length rallies auto-clipped from uploaded video.', status: 'Beta' },
      { endpoint: 'Shot Detection', desc: 'Stroke-level metadata (type, outcome, placement).', status: 'Planned' },
      { endpoint: 'Serve Analytics', desc: 'Serve speed, placement, and spin estimation.', status: 'Planned' },
      { endpoint: 'Heatmap Export', desc: 'Shot-placement heatmap PNGs — embedded in Scout Reports.', status: 'Planned' },
    ],
    pricing: 'Included with Lumio Tour Pro and Pro+ at launch. No third-party subscription required.',
  },

  hawkeye: {
    icon: '👁️',
    title: 'Hawk-Eye',
    subtitle: 'Ball-tracking data from Grand Slams and Masters 1000 venues.',
    partnerBadge: 'Hawk-Eye Innovations · per-tournament rights · enterprise tier',
    connectLabel: 'Connect Hawk-Eye',
    summaryText: 'Ball-tracking, serve speed, spin, and placement data from venues where Hawk-Eye is installed. The gold standard for competitive-match analytics — feeds the rally deconstruction view.',
    connectedStats: [
      { label: 'Matches Indexed', value: '62' },
      { label: 'Tournaments', value: '14' },
      { label: 'Rallies', value: '8,400+' },
      { label: 'Access', value: 'Player tier' },
    ],
    whyHeading: 'Why Hawk-Eye is a tier-one integration for competitive analysis',
    whyBody: 'Hawk-Eye is the only system producing millimetre-accurate ball-tracking in the pro game — which means every serve bounce location, every baseline depth, and every cross-court spin rate comes from it. Piping Hawk-Eye into Lumio closes the loop between live broadcast stats and the player\'s own post-match review. If your Sunday second-serve placement was 40cm shorter than your tournament average, Hawk-Eye is the only source that can tell you with that precision.',
    endpointsTitle: 'Data Flows Used by Lumio Tennis',
    endpoints: [
      { endpoint: 'Serve Placement Heatmap', desc: 'Exact bounce coordinates for every serve — singles + doubles.', status: 'Live' },
      { endpoint: 'Rally Depth', desc: 'Baseline-to-ball distance distribution per rally segment.', status: 'Live' },
      { endpoint: 'Spin Rate', desc: 'RPM data per stroke — serve, topspin forehand, kick serve, etc.', status: 'Live' },
      { endpoint: 'Shot Speed', desc: 'mph / kph for every struck ball — second-serve speed is a key diagnostic.', status: 'Live' },
      { endpoint: 'Net Clearance', desc: 'Ball height at net crossing — tracks risk-vs-reward tuning.', status: 'Live' },
      { endpoint: 'Court Positioning', desc: 'Player x/y during every shot — powers the Pressure Analysis view.', status: 'Beta' },
      { endpoint: 'Point-Level Replays', desc: '3D replay data for any point — Planned integration for scout prep.', status: 'Planned' },
    ],
    coverage: {
      title: 'Venue Coverage — Hawk-Eye',
      columns: ['Tier', 'Installed', 'Depth', 'Heatmaps', 'Historical'],
      rows: [
        ['Grand Slams', '✓ All 4', '✓ Full', '✓', '✓ 2015+'],
        ['ATP Masters 1000', '✓ All 9', '✓ Full', '✓', '✓ 2018+'],
        ['WTA 1000', '✓ All 10', '✓ Full', '✓', '✓ 2019+'],
        ['ATP/WTA 500', '✓ 20 of 26', 'Partial', '✓', 'Partial'],
        ['ATP/WTA 250', 'Partial', 'Partial', 'Partial', '—'],
        ['Challenger / ITF', 'N/A', 'N/A', 'N/A', 'N/A'],
      ],
    },
    pricing: 'Hawk-Eye match data is licensed per-tournament — access is typically negotiated through the player\'s federation or management company as part of the rights package. Lumio absorbs the aggregation / hosting cost; the player sees their own historical Hawk-Eye data in one place.',
  },

  playsight: {
    icon: '🎥',
    title: 'PlaySight',
    subtitle: 'Academy-installed multi-camera tracking and auto-generated highlights.',
    partnerBadge: 'PlaySight SmartCourt · academy-installed · 7-camera rig',
    connectLabel: 'Connect PlaySight',
    summaryText: 'For players training at a PlaySight-equipped academy, every practice session and exhibition match is auto-captured with multi-camera coverage, auto-clipped by point.',
    connectedStats: [
      { label: 'Academy', value: 'Lumio Madrid' },
      { label: 'Sessions (30d)', value: '22' },
      { label: 'Auto Highlights', value: '148' },
      { label: 'Storage', value: '28 GB' },
    ],
    whyHeading: 'Why PlaySight is complementary (not a core integration)',
    whyBody: 'PlaySight is only useful if the academy has installed it — but where it is installed, it delivers broadcast-quality 7-camera coverage with auto-generated point-by-point highlights. For players doing block training at PlaySight venues, the integration saves coaches 3-4 hours of post-session clipping per week. Outside those venues, it\'s dark — hence complementary rather than critical.',
    endpointsTitle: 'Data Flows Used by Lumio Tennis',
    endpoints: [
      { endpoint: 'Match Recording', desc: 'Full-match capture with 7-camera angles, synced time codes.', status: 'Live' },
      { endpoint: 'Auto Highlight Reel', desc: 'Winners + match points auto-clipped into a shareable reel.', status: 'Live' },
      { endpoint: 'Practice Session Tagging', desc: 'Training blocks tagged (serves, groundstrokes, drills).', status: 'Live' },
      { endpoint: 'Line-Calling Playback', desc: 'Automated challenge replays embedded in match video.', status: 'Live' },
      { endpoint: 'Player Analytics', desc: 'Per-session movement load and court coverage heatmaps.', status: 'Beta' },
      { endpoint: 'Clip Sharing', desc: 'One-tap share-to-Lumio for any segment — Planned.', status: 'Planned' },
    ],
    pricing: 'PlaySight SmartCourt installations are paid-for by the academy or club (typically $15k+ install + annual fee). For players, access is free through the academy account — OAuth connection brings the historical session archive into Lumio.',
  },

  johansports: {
    icon: '🛰️',
    title: 'Johan Sports',
    subtitle: 'Court-coverage, movement load, and distance per match.',
    partnerBadge: 'OAuth · 10Hz GPS + IMU · CSV import for any other vendor',
    connectLabel: 'Connect Johan Sports',
    summaryText: 'GPS vest data from practice and match sessions. Tracks total distance, high-speed running, court coverage, and accumulated movement load week-over-week.',
    connectedStats: [
      { label: 'Last Session', value: 'Today 09:40' },
      { label: 'Distance (match)', value: '4.2 km' },
      { label: 'Load 7-day', value: '1,640 AU' },
      { label: 'Device', value: 'Johan Sports' },
    ],
    whyHeading: 'Why GPS load tracking is performance-critical',
    whyBody: 'Best-of-five Grand Slam tennis is one of the highest-load match formats in pro sport. Accumulated load across a 14-day Slam — plus practice before each match — is a proven predictor of late-tournament injury. Feeding the GPS-vest data into Lumio means the physio sees the cumulative strain metric every morning and can throttle practice before the load enters red-flag territory.',
    endpointsTitle: 'Data Flows Used by Lumio Tennis',
    endpoints: [
      { endpoint: 'Match Summary', desc: 'Per-match distance, HSR, max HR, duration — one row per match.', status: 'Live' },
      { endpoint: 'Zone Distribution', desc: 'Time in HR zones and speed zones — heat-stress flagging.', status: 'Live' },
      { endpoint: 'Acute / Chronic Workload', desc: 'Rolling 7- and 28-day load ratio — the ACWR alert tile.', status: 'Live' },
      { endpoint: 'Court Coverage', desc: 'Spatial heatmap of where the player moved on court.', status: 'Live' },
      { endpoint: 'Change-of-Direction Count', desc: 'Sharp CoD events per set — proxy for lateral-load strain.', status: 'Beta' },
      { endpoint: 'Heat / Environmental', desc: 'Ambient temp, humidity, estimated core temp during match.', status: 'Beta' },
      { endpoint: 'Gym Load Sync', desc: 'Indoor strength sessions tagged separately from on-court work.', status: 'Planned' },
    ],
    pricing: 'Johan Sports licences are quoted per unit on a per-team basis — speak to the Johan Sports sales team for current pricing. Lumio is hardware-agnostic — drop a CSV from any other vendor and the same dashboards backfill.',
  },

  whoop: {
    icon: '💚',
    title: 'Lumio Wear / Oura',
    subtitle: 'Sleep, HRV, recovery and strain piped into every morning briefing.',
    partnerBadge: 'OAuth available · Lumio Wear + Oura · ring or strap',
    connectLabel: 'Connect Lumio Wear / Oura',
    summaryText: 'Pipe HRV, recovery score, sleep duration and strain into Lumio every morning — so your coach and physio see recovery flags before you walk onto the practice court.',
    connectedStats: [
      { label: 'Last Sync', value: '06:14' },
      { label: 'Recovery', value: '71%' },
      { label: 'HRV', value: '58 ms' },
      { label: 'Sleep', value: '7h 22m' },
    ],
    whyHeading: 'Why Lumio Wear / Oura is a complementary integration',
    whyBody: 'Recovery is the single clearest predictor of a decision-making day on court. Feeding Lumio Wear/Oura data into the morning briefing lets Lumio pre-empt under-recovery: if HRV is 25% below baseline and REM sleep was below 90 minutes, the briefing flags it, the physio sees it, and the practice plan dials back without anyone having to ask.',
    endpointsTitle: 'Data Flows Used by Lumio Tennis',
    endpoints: [
      { endpoint: 'Recovery Score', desc: 'Lumio Wear 0-100 daily recovery or Oura Readiness score.', status: 'Live' },
      { endpoint: 'HRV (RMSSD)', desc: 'Overnight heart-rate variability — leading indicator of parasympathetic recovery.', status: 'Live' },
      { endpoint: 'Sleep Stages', desc: 'REM / deep / light split plus total vs target.', status: 'Live' },
      { endpoint: 'Daily Strain', desc: 'Lumio Wear strain or Oura activity — cross-referenced with match load.', status: 'Live' },
      { endpoint: 'Resting Heart Rate', desc: 'Morning RHR — rises flag travel fatigue or illness incubation.', status: 'Live' },
      { endpoint: 'Respiratory Rate', desc: 'Overnight breath rate — early illness flag during busy swings.', status: 'Beta' },
      { endpoint: 'Strain-Coach Alerts', desc: 'Suggested target strain for the day — Planned for Q3.', status: 'Planned' },
    ],
    pricing: 'Free to connect if the player already has a Lumio Wear or Oura subscription. Lumio Wear: approximately £20/month. Oura: approximately £5/month plus ring hardware. No additional Lumio fee — OAuth connection only.',
  },

  workspace: {
    icon: '📧',
    title: 'Gmail + Calendar',
    subtitle: 'Tournament entries, sponsor emails, and coach meetings in one place.',
    partnerBadge: 'Google OAuth · gmail.readonly + calendar.events scopes',
    connectLabel: 'Sign in with Google',
    summaryText: 'Stop switching tabs. Sponsor obligations, tournament entry confirmations, travel bookings, and coach meetings all flow into Lumio\'s morning briefing automatically.',
    connectedStats: [
      { label: 'Inbox Sync', value: '3 min ago' },
      { label: 'Calendars', value: '2 active' },
      { label: 'Drafts', value: '6 pending' },
      { label: 'Account', value: 'alex@…' },
    ],
    whyHeading: 'Why Gmail + Calendar is the single biggest time saver',
    whyBody: 'On a 30-tournament season, the hours lost every week scrolling through email is measurable. Lumio\'s Gmail classification tags every email — tournament admin, sponsor obligation, coach meeting, travel, personal — and only surfaces what needs a reply. Calendar sync puts practice slots, match times, and sponsor commitments on one shared timeline the whole team sees.',
    endpointsTitle: 'Data Flows Used by Lumio Tennis',
    endpoints: [
      { endpoint: 'Inbox Classification', desc: 'Every email tagged: tournament / sponsor / travel / coach / personal.', status: 'Live' },
      { endpoint: 'Tournament Entry Extraction', desc: 'Auto-pulls event, date, entry fee from tour confirmations.', status: 'Live' },
      { endpoint: 'Calendar Sync', desc: 'Two-way — add a practice slot in Lumio, it lands in Google Calendar.', status: 'Live' },
      { endpoint: 'Coach Meeting Detection', desc: 'Detects video-call links in invites — surfaced in morning briefing.', status: 'Live' },
      { endpoint: 'Sponsor Obligation Flagging', desc: 'Pulls deliverables/deadlines from brand emails into Sponsorship tracker.', status: 'Live' },
      { endpoint: 'AI Reply Drafts', desc: 'Suggested replies in your voice — review and send without leaving Lumio.', status: 'Beta' },
      { endpoint: 'OOO Auto-Set', desc: 'Auto-enable OOO for Slam weeks from tournament schedule — Planned.', status: 'Planned' },
    ],
    pricing: 'Free for personal Gmail and Google Workspace accounts. OAuth only — no credentials stored on Lumio servers. Microsoft 365 / Outlook support is available via the parallel OAuth flow at no extra cost.',
  },

  slack: {
    icon: '💬',
    title: 'Slack',
    subtitle: 'Team messaging with role-aware alerts for coach, physio, manager, agent.',
    partnerBadge: 'Slack OAuth · per-workspace install · private channels supported',
    connectLabel: 'Add to Slack',
    summaryText: 'Route Lumio alerts to the right room — morning briefings to #coaching, physio flags to #medical, sponsor obligations to #manager. Each role sees only what they need.',
    connectedStats: [
      { label: 'Workspace', value: 'team-rivera' },
      { label: 'Channels', value: '5 wired' },
      { label: 'DM fallback', value: 'Enabled' },
      { label: 'Alert Rules', value: '12 active' },
    ],
    whyHeading: 'Why Slack is the glue for a travelling team',
    whyBody: 'A pro tennis team — coach, hitting partner, physio, agent — is a small distributed company. Slack is where that company already lives, so Lumio slots in as another well-behaved bot. Physio sees recovery flags; the agent sees sponsor obligations; the coach sees practice-load trends. Each role only gets pinged about what\'s theirs.',
    endpointsTitle: 'Data Flows Used by Lumio Tennis',
    endpoints: [
      { endpoint: 'Role-Based Routing', desc: 'Rules like "send Recovery < 60% alerts to #physio".', status: 'Live' },
      { endpoint: 'Morning Briefing Push', desc: 'Full briefing delivered to the team channel before first practice.', status: 'Live' },
      { endpoint: 'Match-Day Alerts', desc: 'Draw updates, opponent changes, and live-score flags.', status: 'Live' },
      { endpoint: 'Sponsor Obligation Alerts', desc: 'Upcoming deliverables flagged 48h ahead — routed to agent.', status: 'Live' },
      { endpoint: 'Slash Commands', desc: '/lumio recovery, /lumio next-match — direct from Slack.', status: 'Beta' },
      { endpoint: 'Thread AI Q&A', desc: 'Ask the Lumio bot a question in a thread — inline answer.', status: 'Beta' },
      { endpoint: 'Huddle Summaries', desc: 'Auto-transcribed team huddles with action-items — Planned.', status: 'Planned' },
    ],
    pricing: 'Free on Slack\'s free tier for teams under 10. Slack Pro is approximately £7/user/month — typically billed to the player\'s management company. Lumio\'s Slack app is bundled, no additional fee.',
  },

  broadcast: {
    icon: '📺',
    title: 'Meridian Sports',
    subtitle: 'Broadcast schedule, clip library, and press-access coordination.',
    partnerBadge: 'Meridian Sports API · partner access · UK + EU coverage',
    connectLabel: 'Connect Meridian Sports',
    summaryText: 'Pull your upcoming broadcast slots, clip library from past events, and press-access windows — all scheduled alongside tournaments in the Media module.',
    connectedStats: [
      { label: 'Next Broadcast', value: 'QF Fri 19:00' },
      { label: 'Clips (YTD)', value: '38' },
      { label: 'Press Slots', value: '4 scheduled' },
      { label: 'Region', value: 'UK + EU' },
    ],
    whyHeading: 'Why Meridian Sports is a commercially-useful integration',
    whyBody: 'Broadcast schedule is where the commercial week lives. Knowing when the player is on show-court with main-channel coverage lets sponsors pre-plan social posts, the agent stagger press, and the player decline calls that clash with a featured match. Meridian\'s feed auto-populates the Media module instead of someone chasing the broadcast office by email every Sunday night.',
    endpointsTitle: 'Data Flows Used by Lumio Tennis',
    endpoints: [
      { endpoint: 'Broadcast Schedule', desc: 'Featured-court slots and match-of-the-day flags.', status: 'Live' },
      { endpoint: 'Clip Library', desc: 'Broadcast-quality clips from past matches — into Lumio Video Library.', status: 'Live' },
      { endpoint: 'Press Access Windows', desc: 'Mixed-zone and sit-down press commitments — blocks calendar.', status: 'Live' },
      { endpoint: 'Featured-Match Flags', desc: 'Early alert when featured-match slot is confirmed — 48h lead.', status: 'Live' },
      { endpoint: 'Rights / Blackout Map', desc: 'Regions cleared for clip / repost — powers sponsor social scheduler.', status: 'Beta' },
      { endpoint: 'Live Rundown Feed', desc: 'In-match rundown during broadcast — Planned for Slam windows.', status: 'Planned' },
    ],
    pricing: 'Meridian Sports partner access is typically arranged through management. For Lumio-connected players, the basic schedule + clip library tier is bundled in the broadcast-rights package. Higher tiers are a separate commercial conversation.',
  },

  mobileapp: {
    icon: '📲',
    title: 'Mobile App',
    subtitle: 'Lumio on your phone — briefings, match-day view, and quick-log shortcuts.',
    partnerBadge: 'iOS + Android · native push · offline support for travel',
    connectLabel: 'Install Mobile App',
    summaryText: 'Native iOS and Android app mirroring the dashboard — optimised for pre-match briefings, quick shot-logging, and in-flight offline viewing of tomorrow\'s match-prep brief.',
    connectedStats: [
      { label: 'App Version', value: '1.14.0' },
      { label: 'Push Alerts', value: 'Enabled' },
      { label: 'Offline Cache', value: '7 days' },
      { label: 'Platform', value: 'iOS + Android' },
    ],
    whyHeading: 'Why a mobile app matters for a travelling tour',
    whyBody: 'The web dashboard is built for the coach and manager; the mobile app is for the player. Pre-match briefings, opponent scout cards, quick-log of practice notes, and offline access to the next match\'s prep all live in a single native app. Push notifications fire for draw changes, opponent swaps, and sponsor obligations — the player doesn\'t have to think about the laptop.',
    endpointsTitle: 'Mobile App Capabilities',
    endpoints: [
      { endpoint: 'Morning Briefing Push', desc: 'Full briefing at 06:30 local time — adjusts to the player\'s timezone.', status: 'Live' },
      { endpoint: 'Match-Prep Brief', desc: 'Pre-match scout card — cached offline for in-flight / warm-up reading.', status: 'Live' },
      { endpoint: 'Quick Shot Log', desc: 'One-tap practice logging — serves, groundstrokes, drill times.', status: 'Live' },
      { endpoint: 'Draw / Opponent Alerts', desc: 'Push when the draw changes or a qualifier lands in your section.', status: 'Live' },
      { endpoint: 'Voice Dictation', desc: 'Speak a practice note → transcribed to the practice log.', status: 'Beta' },
      { endpoint: 'Offline Mode', desc: '7-day cache of briefings, match prep, and video clips for travel days.', status: 'Live' },
      { endpoint: 'Watch Companion', desc: 'Apple Watch / Wear OS glanceable complications — Planned for Q4.', status: 'Planned' },
    ],
    pricing: 'Bundled in every Lumio Tennis plan at no extra cost. iOS app is distributed via the App Store; Android via Google Play. Beta channel available for testers.',
  },
}
