'use client'

import Link from 'next/link'
import SportRoleTabs from '../components/SportRoleTabs'
import { BOXING_ROLES } from '../components/sportRoles'

const RED = '#C41E3A'
const RED_LIGHT = '#EF4455'
const BG = '#07080F'
const CARD = '#0D1117'
const CARD_ALT = '#111827'
const BORDER = '#1E293B'
const BORDER_ALT = '#1F2937'
const TEXT = '#F9FAFB'
const MUTED = '#9CA3AF'

const STAT_PILLS = ['40+ features', 'GPS vest ready', 'AI powered', 'ElevenLabs voice', 'CompuBox ready']

const FEATURES: Array<{ icon: string; title: string; desc: string }> = [
  { icon: '🏕️', title: 'Fight Camp Management', desc: "Camp dashboard with phase timeline, daily sessions, sparring schedule, and GPS ring heatmap as the centrepiece. Everything Jim Bevan needs before the first session." },
  { icon: '📡', title: 'GPS Ring Heatmap', desc: "Lumio Fight Vest + 4 UWB beacons track your movement in the ring at 10Hz. Centre ring time, ropes exposure, corner time — the first quantitative measure of ring generalship ever built." },
  { icon: '⚖️', title: 'ACWR Load Monitoring', desc: "Acute:Chronic Workload Ratio for boxing camp. 28-day rolling load vs 7-day acute — prevents overtraining injuries before they happen. The data Jim has always wanted, quantified." },
  { icon: '🌍', title: 'World Rankings & Mandatory', desc: "Live WBC, WBA, WBO, IBF rankings, mandatory challenger timelines, purse bid calculator, and undisputed tracker. Know your path to the title every morning." },
  { icon: '🤖', title: 'AI Morning Briefing', desc: "Camp day briefing generated by Claude AI — includes yesterday's GPS session summary, weight trajectory, sparring focus, sponsor obligations, and opponent intel. Voice-delivered before first session." },
  { icon: '💰', title: 'Financial Dashboard', desc: "Purse simulator, fight earnings ledger, camp cost tracker, multi-jurisdiction tax dashboard. One place for everything you need before you talk to your accountant." },
]

const TIERS = [
  { name: 'Professional Fighter', desc: 'Camp dashboard, GPS ring heatmaps, ACWR load monitoring, weight cut tracker, and AI morning briefing. Everything you need to arrive at the gym ready.' },
  { name: 'Trainer / Corner Team', desc: "Trainer Notes view, sparring planner, GPS load data, corner sheet PDF generator, and session-by-session ring heatmap review. Jim Bevan's complete digital toolkit." },
  { name: 'Manager / Agent', desc: 'Manager dashboard, world rankings, mandatory tracker, purse bid calculator, sponsorship pipeline, and fight earnings ledger. The business side of boxing, organised.' },
]

const PRICING = [
  { name: 'Lumio Fight Pro', price: '£199/mo', features: ['Fight camp management', 'World rankings + mandatory tracker', 'Weight cut tracker', 'AI morning briefing', 'Up to 3 team accounts'] },
  { name: 'Lumio Fight Elite', price: '£499/mo', highlight: true, features: ['Everything in Pro', 'GPS Vest integration (vest sold separately)', 'Ring heatmap + ACWR monitoring', 'Purse bid calculator + undisputed tracker', 'Punch analytics + GPS fusion', 'Priority account manager + Jim Bevan onboarding'] },
]

// ── Mockup chrome ───────────────────────────────────────────────────────────
function MockupFrame({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ backgroundColor: CARD_ALT, border: `1px solid ${BORDER_ALT}`, borderRadius: 12, overflow: 'hidden', boxShadow: `0 30px 80px ${RED}22` }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 14px', borderBottom: `1px solid ${BORDER_ALT}`, backgroundColor: '#0B1020' }}>
        <div style={{ display: 'flex', gap: 6 }}>
          <div style={{ width: 10, height: 10, borderRadius: '50%', backgroundColor: '#EF4444' }} />
          <div style={{ width: 10, height: 10, borderRadius: '50%', backgroundColor: '#F59E0B' }} />
          <div style={{ width: 10, height: 10, borderRadius: '50%', backgroundColor: '#10B981' }} />
        </div>
        <div style={{ flex: 1, height: 18, borderRadius: 5, backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}` }} />
      </div>
      <div style={{ padding: 18 }}>{children}</div>
    </div>
  )
}

function Badge({ children, color, bg }: { children: React.ReactNode; color: string; bg: string }) {
  return (
    <span style={{ fontSize: 9, fontWeight: 800, padding: '3px 8px', borderRadius: 999, color, backgroundColor: bg, border: `1px solid ${color}55`, letterSpacing: '0.05em', textTransform: 'uppercase' }}>
      {children}
    </span>
  )
}

function KPI({ value, label, sub, color }: { value: string; label: string; sub?: string; color: string }) {
  return (
    <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${color}55`, borderRadius: 10, padding: 12 }}>
      <div style={{ fontSize: 16, fontWeight: 900, color }}>{value}</div>
      <div style={{ fontSize: 9, fontWeight: 700, color: TEXT, marginTop: 2, textTransform: 'uppercase', letterSpacing: '0.05em' }}>{label}</div>
      {sub && <div style={{ fontSize: 9, color: MUTED, marginTop: 2 }}>{sub}</div>}
    </div>
  )
}

// ── Mockups ─────────────────────────────────────────────────────────────────
function CampDashboardMockup() {
  return (
    <MockupFrame>
      <div style={{ background: `linear-gradient(135deg, ${RED}, ${RED_LIGHT})`, borderRadius: 10, padding: 10, marginBottom: 10, color: '#fff' }}>
        <div style={{ fontSize: 10, fontWeight: 900 }}>Camp Day 22/70 · vs Viktor Petrov · 48 days</div>
        <div style={{ fontSize: 8, marginTop: 4, opacity: 0.9 }}>Good morning, Marcus. Specific phase — 8 rounds sparring today.</div>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6, marginBottom: 10 }}>
        <KPI value="48" label="Days to Fight" color={RED} />
        <KPI value="22/70" label="Camp Day" color={RED_LIGHT} />
        <KPI value="97.8→92.7" label="Weight kg" color="#F59E0B" />
        <KPI value="81%" label="Recovery" color="#10B981" />
      </div>
      <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 10 }}>
        <svg width="220" height="80" viewBox="0 0 220 80">
          <rect x="10" y="6" width="200" height="68" rx="4" fill="#1a1a0a" stroke="#8B4513" strokeWidth="1.5" />
          <rect x="20" y="14" width="180" height="52" rx="2" fill="none" stroke="#8B4513" strokeWidth="1" opacity="0.6" />
          <line x1="10" y1="40" x2="210" y2="40" stroke="rgba(255,255,255,0.15)" strokeDasharray="3,3" />
          <circle cx="110" cy="40" r="22" fill={RED} opacity="0.7" style={{ filter: 'blur(6px)' }} />
          <circle cx="110" cy="40" r="14" fill={RED_LIGHT} opacity="0.6" style={{ filter: 'blur(4px)' }} />
          <circle cx="60" cy="40" r="10" fill={RED} opacity="0.4" style={{ filter: 'blur(5px)' }} />
          <circle cx="160" cy="40" r="10" fill={RED} opacity="0.4" style={{ filter: 'blur(5px)' }} />
        </svg>
      </div>
      <div style={{ backgroundColor: 'rgba(245,158,11,0.1)', border: '1px solid rgba(245,158,11,0.45)', borderRadius: 8, padding: 8, marginBottom: 6 }}>
        <div style={{ fontSize: 10, color: '#F59E0B', fontWeight: 800 }}>⚠ ACWR 1.25 — Monitor carefully</div>
      </div>
      <div style={{ backgroundColor: 'rgba(16,185,129,0.08)', border: '1px solid rgba(16,185,129,0.35)', borderRadius: 8, padding: 8 }}>
        <div style={{ fontSize: 10, color: '#10B981', fontWeight: 800 }}>⚖️ Weight cut: -0.18kg/day target · On track</div>
      </div>
    </MockupFrame>
  )
}

function RingHeatmapMockup() {
  return (
    <MockupFrame>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
        <div style={{ fontSize: 11, fontWeight: 800, color: TEXT }}>Ring Heatmap — Day 22 Sparring</div>
        <Badge color="#EF4444" bg="rgba(239,68,68,0.2)">● LUMIO VEST LIVE</Badge>
      </div>
      <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 12 }}>
        <svg width="260" height="180" viewBox="0 0 260 180">
          <rect x="10" y="10" width="240" height="160" rx="6" fill="#1a1a0a" stroke="#8B4513" strokeWidth="2" />
          {[0.92, 0.84, 0.76].map((f, i) => (
            <rect key={i} x={10 + (240 * (1 - f) / 2)} y={10 + (160 * (1 - f) / 2)} width={240 * f} height={160 * f} rx="3" fill="none" stroke="#8B4513" strokeWidth="1.2" opacity="0.55" />
          ))}
          <line x1="10" y1="90" x2="250" y2="90" stroke="rgba(255,255,255,0.15)" strokeDasharray="4,4" />
          <circle cx="130" cy="90" r="40" fill={RED} opacity="0.72" style={{ filter: 'blur(8px)' }} />
          <circle cx="125" cy="92" r="28" fill={RED_LIGHT} opacity="0.6" style={{ filter: 'blur(6px)' }} />
          <circle cx="50" cy="90" r="22" fill={RED} opacity="0.5" style={{ filter: 'blur(8px)' }} />
          <circle cx="210" cy="90" r="22" fill={RED} opacity="0.5" style={{ filter: 'blur(8px)' }} />
          <circle cx="130" cy="30" r="16" fill={RED} opacity="0.42" style={{ filter: 'blur(7px)' }} />
          <circle cx="130" cy="150" r="14" fill={RED} opacity="0.38" style={{ filter: 'blur(7px)' }} />
          <text x="130" y="94" textAnchor="middle" fontSize="12" fontWeight="700" fill="rgba(255,255,255,0.85)">40%</text>
        </svg>
      </div>
      <div style={{ marginBottom: 12 }}>
        {[{ l: 'Centre', v: 40, c: '#EF4444' }, { l: 'Ropes', v: 35, c: '#F97316' }, { l: 'Corners', v: 25, c: '#EAB308' }].map(z => (
          <div key={z.l} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
            <div style={{ fontSize: 9, color: MUTED, width: 50 }}>{z.l}</div>
            <div style={{ flex: 1, height: 5, backgroundColor: '#1F2937', borderRadius: 3 }}>
              <div style={{ width: `${z.v}%`, height: '100%', backgroundColor: z.c, borderRadius: 3 }} />
            </div>
            <div style={{ fontSize: 9, color: TEXT, width: 30, textAlign: 'right', fontWeight: 700 }}>{z.v}%</div>
          </div>
        ))}
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6 }}>
        <KPI value="1.25" label="ACWR" color="#F59E0B" />
        <KPI value="4.9km" label="Distance" color={RED} />
        <KPI value="358" label="Load AU" color={RED_LIGHT} />
        <KPI value="75m" label="Duration" color="#10B981" />
      </div>
    </MockupFrame>
  )
}

function RankingsMockup() {
  return (
    <MockupFrame>
      <div style={{ fontSize: 11, fontWeight: 800, color: TEXT, marginBottom: 2 }}>🌍 Marcus Cole — World Rankings</div>
      <div style={{ fontSize: 9, color: MUTED, marginBottom: 10 }}>Heavyweight · 22-1 (18 KO) · Updated hourly</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6, marginBottom: 10 }}>
        <KPI value="#5" label="WBC" color={RED} />
        <KPI value="#9" label="WBA" color="#A855F7" />
        <KPI value="#5" label="WBO" color="#3B82F6" />
        <KPI value="#12" label="IBF" color="#F59E0B" />
      </div>
      <div style={{ backgroundColor: 'rgba(16,185,129,0.08)', border: '1px solid rgba(16,185,129,0.35)', borderRadius: 8, padding: 10, marginBottom: 8 }}>
        <div style={{ fontSize: 10, fontWeight: 800, color: '#10B981' }}>✓ Mandatory Ordered</div>
        <div style={{ fontSize: 9, color: MUTED, marginTop: 2 }}>WBC eliminator #3 vs #5 — Q4 2026</div>
      </div>
      <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}`, borderRadius: 8, padding: 10, marginBottom: 8 }}>
        <div style={{ fontSize: 10, fontWeight: 800, color: TEXT, marginBottom: 4 }}>Purse Simulator</div>
        <div style={{ fontSize: 9, color: MUTED }}>£5M total → Marcus gross: <span style={{ color: RED_LIGHT, fontWeight: 700 }}>£1.25M</span> → Net est: <span style={{ color: '#10B981', fontWeight: 700 }}>£836k</span></div>
      </div>
      <div style={{ backgroundColor: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.35)', borderRadius: 8, padding: 10 }}>
        <div style={{ fontSize: 10, fontWeight: 800, color: '#F59E0B', marginBottom: 4 }}>🏆 Undisputed Path</div>
        <div style={{ fontSize: 9, color: MUTED, lineHeight: 1.6 }}>Step 1: Beat Petrov → WBC #3 · Step 3: WBO Title Shot 2027 · Step 5: Undisputed 2028-29</div>
      </div>
    </MockupFrame>
  )
}

function BriefingMockup() {
  return (
    <MockupFrame>
      <div style={{ fontSize: 11, fontWeight: 800, color: TEXT, marginBottom: 2 }}>🥊 AI Morning Briefing — Camp Day 22</div>
      <div style={{ fontSize: 9, color: MUTED, marginBottom: 10 }}>Generated 06:30 · GPS session included · DAZN shoot in 8 days</div>
      <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${RED}55`, borderRadius: 10, padding: 12, marginBottom: 10 }}>
        <p style={{ fontSize: 10, color: TEXT, lineHeight: 1.65, margin: 0, fontStyle: 'italic' }}>
          &ldquo;Camp Day 22. ACWR at 1.25 — manage today&apos;s load carefully. Yesterday&apos;s sparring showed 38% ropes time — Jim&apos;s jab-to-centre drill is the priority. Weight on track. Petrov camp: new body shot work observed. Make it count.&rdquo;
        </p>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 6 }}>
        <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}`, borderRadius: 8, padding: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 800, color: '#10B981', marginBottom: 3 }}>✓ GPS SUMMARY</div>
          <div style={{ fontSize: 9, color: MUTED }}>Load 358 AU · ACWR 1.25 · 40% centre</div>
        </div>
        <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}`, borderRadius: 8, padding: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 800, color: '#F59E0B', marginBottom: 3 }}>⚖️ WEIGHT</div>
          <div style={{ fontSize: 9, color: MUTED }}>97.8kg · -0.18kg/day · on track</div>
        </div>
        <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}`, borderRadius: 8, padding: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 800, color: RED_LIGHT, marginBottom: 3 }}>🎯 SPARRING FOCUS</div>
          <div style={{ fontSize: 9, color: MUTED }}>Pull counter right hand · body work on break</div>
        </div>
        <div style={{ backgroundColor: '#0A0B10', border: `1px solid ${BORDER_ALT}`, borderRadius: 8, padding: 8 }}>
          <div style={{ fontSize: 9, fontWeight: 800, color: '#3B82F6', marginBottom: 3 }}>🤝 OBLIGATIONS</div>
          <div style={{ fontSize: 9, color: MUTED }}>DAZN shoot in 8 days · Apex Performance post due</div>
        </div>
      </div>
      <button style={{ width: '100%', marginTop: 10, fontSize: 10, fontWeight: 800, padding: '8px 12px', borderRadius: 8, backgroundColor: RED, color: '#fff', border: 'none' }}>▶ Play voice briefing (1m 58s)</button>
    </MockupFrame>
  )
}

// ── Spotlight wrapper ────────────────────────────────────────────────────────
function Spotlight({ eyebrow, title, body, bullets, mockup, reverse, altBg }: {
  eyebrow: string; title: string; body: string; bullets: string[]; mockup: React.ReactNode; reverse?: boolean; altBg?: boolean
}) {
  return (
    <section style={{ padding: '96px 24px', backgroundColor: altBg ? '#0A0C14' : BG }}>
      <div style={{ maxWidth: 1200, margin: '0 auto', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 64, alignItems: 'center' }}>
        <div style={{ order: reverse ? 2 : 1 }}>
          <div style={{ fontSize: 12, fontWeight: 800, color: RED_LIGHT, letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: 12 }}>{eyebrow}</div>
          <h2 style={{ fontSize: 40, fontWeight: 900, color: TEXT, marginBottom: 16, lineHeight: 1.1 }}>{title}</h2>
          <p style={{ fontSize: 16, color: MUTED, lineHeight: 1.6, marginBottom: 24 }}>{body}</p>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 10 }}>
            {bullets.map(b => (
              <li key={b} style={{ display: 'flex', alignItems: 'flex-start', gap: 10, fontSize: 15, color: TEXT }}>
                <span style={{ color: RED_LIGHT, fontWeight: 900, flexShrink: 0 }}>✓</span>
                <span>{b}</span>
              </li>
            ))}
          </ul>
        </div>
        <div style={{ order: reverse ? 1 : 2 }}>{mockup}</div>
      </div>
    </section>
  )
}

// ── Page ─────────────────────────────────────────────────────────────────────
export default function BoxingLandingPage() {
  return (
    <div style={{ backgroundColor: BG, color: TEXT, minHeight: '100vh' }}>
      {/* ── HERO ── */}
      <section style={{ minHeight: '100vh', padding: '120px 24px 80px', position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', inset: 0, background: `radial-gradient(circle at 20% 10%, ${RED}33, transparent 50%), radial-gradient(circle at 80% 60%, ${RED_LIGHT}22, transparent 55%)`, pointerEvents: 'none' }} />
        <div style={{ position: 'relative', maxWidth: 1200, margin: '0 auto', textAlign: 'center' }}>
          <div style={{ fontSize: 13, fontWeight: 800, letterSpacing: '0.2em', color: RED_LIGHT, textTransform: 'uppercase', marginBottom: 24 }}>
            LUMIO FIGHT · BOXING
          </div>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, background: 'rgba(239,68,68,0.12)', border: '1px solid rgba(239,68,68,0.4)', borderRadius: 999, padding: '6px 16px', marginBottom: 20 }}>
            <span style={{ fontSize: 14 }}>🛰️</span>
            <span style={{ color: '#ef4444', fontSize: 12, fontWeight: 800, letterSpacing: '0.05em', textTransform: 'uppercase' }}>World First — GPS Ring Movement Tracking</span>
          </div>
          <h1 style={{ fontSize: 'clamp(44px, 7vw, 80px)', fontWeight: 900, lineHeight: 1.05, color: TEXT, marginBottom: 24, maxWidth: 1000, marginLeft: 'auto', marginRight: 'auto' }}>
            The complete platform for professional boxers.
          </h1>
          <p style={{ fontSize: 20, color: MUTED, lineHeight: 1.6, maxWidth: 860, margin: '0 auto 16px' }}>
            GPS ring heatmaps that track your movement at 10Hz. Fight camp management, ACWR load monitoring, world rankings, weight tracking, sponsorship and AI morning briefings — with GPS ring tracking no other platform has built.
          </p>
          <p style={{ fontSize: 14, color: RED_LIGHT, fontWeight: 700, marginBottom: 40, letterSpacing: '0.02em' }}>
            No tool like this exists for professional boxing anywhere else.
          </p>
          <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap', marginBottom: 48 }}>
            <Link href="/sports-signup?sport=boxing" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '18px 32px', borderRadius: 12, backgroundColor: RED, color: '#fff', fontSize: 16, fontWeight: 800, textDecoration: 'none', boxShadow: `0 20px 50px ${RED}66` }}>
              Apply for founding access →
            </Link>
            <Link href="/boxing/boxing-demo" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '18px 32px', borderRadius: 12, backgroundColor: 'transparent', color: TEXT, fontSize: 16, fontWeight: 800, textDecoration: 'none', border: `1px solid ${BORDER}` }}>
              Try the demo
            </Link>
          </div>
          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            {STAT_PILLS.map(p => (
              <span key={p} style={{ padding: '10px 18px', borderRadius: 999, backgroundColor: 'rgba(196,30,58,0.1)', border: `1px solid ${RED}66`, color: RED_LIGHT, fontSize: 13, fontWeight: 700 }}>{p}</span>
            ))}
          </div>
        </div>
      </section>

      {/* ── FEATURE GRID ── */}
      <section id="features" style={{ padding: '96px 24px', backgroundColor: '#0A0C14' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <h2 style={{ fontSize: 44, fontWeight: 900, color: TEXT, textAlign: 'center', marginBottom: 16, lineHeight: 1.1 }}>
            Everything a professional boxer needs.<br />
            <span style={{ color: RED_LIGHT }}>In one place.</span>
          </h2>
          <p style={{ fontSize: 16, color: MUTED, textAlign: 'center', marginBottom: 56, maxWidth: 760, marginLeft: 'auto', marginRight: 'auto' }}>
            40+ portal features across 8 sections — fight camp, rankings, weight management, financials, team, commercial, career, and AI intelligence.
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 20 }}>
            {FEATURES.map(f => (
              <div key={f.title} style={{ backgroundColor: CARD, border: `1px solid ${BORDER}`, borderRadius: 16, padding: 24 }}>
                <div style={{ fontSize: 32, marginBottom: 12 }}>{f.icon}</div>
                <h3 style={{ fontSize: 18, fontWeight: 800, color: TEXT, marginBottom: 8 }}>{f.title}</h3>
                <p style={{ fontSize: 14, color: MUTED, lineHeight: 1.6 }}>{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <SportRoleTabs sport="boxing" demoHref="/boxing/boxing-demo" accentColor="#EF4444" accentColorDim="rgba(239,68,68,0.15)" roles={BOXING_ROLES} />

      {/* ── SPOTLIGHTS ── */}
      <Spotlight
        eyebrow="SPOTLIGHT · CAMP DASHBOARD"
        title="Your entire camp. One view."
        body="The Lumio Fight camp dashboard gives your trainer the GPS ring heatmap, weight trajectory, ACWR load status, and today's sessions — all before Marcus arrives at the gym."
        bullets={['GPS ring heatmap replaces subjective coaching notes with quantified ring generalship', 'ACWR load monitoring — green / amber / red zone alerts before each session', 'Weight cut trajectory — GPS-adjusted daily target alongside cut progress', 'Sponsor and media obligations flagged automatically every morning']}
        mockup={<CampDashboardMockup />}
      />

      <Spotlight
        altBg reverse
        eyebrow="SPOTLIGHT · GPS RING HEATMAP"
        title="Quantify ring generalship. For the first time."
        body="The Lumio Fight GPS Vest and four UWB beacons track movement inside the ring at 10Hz — 10cm accuracy. Aggregate into Centre, Ropes, and Corners zones. For the first time, a trainer can say 'you spent 38% of round 3 on the ropes' with data."
        bullets={['UWB local positioning — works indoors where GPS cannot', 'Centre / Ropes / Corners zone breakdown per session and per round', 'Multi-session overlay — compare camp week 1 vs week 8 side-by-side', "One-click Camp Load Report PDF — Jim's most-requested feature"]}
        mockup={<RingHeatmapMockup />}
      />

      <Spotlight
        eyebrow="SPOTLIGHT · WORLD RANKINGS"
        title="Know your path to the title every morning."
        body="Live WBC, WBA, WBO, and IBF rankings updated after every result. Mandatory challenger timelines, purse bid floor calculator, and the Undisputed Tracker — every step on the path from contender to champion, mapped out."
        bullets={['Rankings across all four sanctioning bodies in one view', 'Mandatory proceeding tracker — when the order drops, you know immediately', "Purse bid simulator — input any total purse, get Marcus's 25% floor instantly", 'Undisputed tracker — 5-step path from contender to all four belts']}
        mockup={<RankingsMockup />}
      />

      <Spotlight
        altBg reverse
        eyebrow="SPOTLIGHT · AI MORNING BRIEFING"
        title="Before the first session. Every morning."
        body="Lumio reads yesterday's GPS session, today's weight, HRV recovery score, opponent intel, and sponsor obligations — then generates a structured briefing for Marcus, Jim, Danny, and Liam. Voice-powered by ElevenLabs."
        bullets={["GPS session summary — yesterday's load, ring zone analysis, ACWR status", 'Weight trajectory — daily cut target adjusted for session load', 'Sparring focus — one specific drill based on ring heatmap data', 'Sponsor and media obligations flagged for today']}
        mockup={<BriefingMockup />}
      />

      {/* ── WHO IT'S FOR ── */}
      <section style={{ padding: '96px 24px', backgroundColor: BG }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <h2 style={{ fontSize: 40, fontWeight: 900, color: TEXT, textAlign: 'center', marginBottom: 16, lineHeight: 1.1 }}>
            Built for every corner of the camp.
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 24, marginTop: 56 }}>
            {TIERS.map(t => (
              <div key={t.name} style={{ backgroundColor: CARD, border: `1px solid ${RED}55`, borderRadius: 16, padding: 32 }}>
                <div style={{ fontSize: 13, fontWeight: 800, color: RED_LIGHT, letterSpacing: '0.15em', textTransform: 'uppercase', marginBottom: 12 }}>ROLE</div>
                <h3 style={{ fontSize: 22, fontWeight: 900, color: TEXT, marginBottom: 12 }}>{t.name}</h3>
                <p style={{ fontSize: 14, color: MUTED, lineHeight: 1.6 }}>{t.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── PRICING ── */}
      <section style={{ padding: '96px 24px', backgroundColor: '#0A0C14' }}>
        <div style={{ maxWidth: 900, margin: '0 auto' }}>
          <h2 style={{ fontSize: 40, fontWeight: 900, color: TEXT, textAlign: 'center', marginBottom: 16, lineHeight: 1.1 }}>
            Simple pricing. Two tiers.
          </h2>
          <p style={{ fontSize: 16, color: MUTED, textAlign: 'center', marginBottom: 48 }}>Pick the tier that fits your camp. Upgrade when you&apos;re ready.</p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 24 }}>
            {PRICING.map(p => (
              <div key={p.name} style={{ backgroundColor: CARD, border: p.highlight ? `2px solid ${RED}` : `1px solid ${BORDER}`, borderRadius: 16, padding: 32, position: 'relative' }}>
                {p.highlight && (
                  <div style={{ position: 'absolute', top: -12, left: '50%', transform: 'translateX(-50%)', padding: '4px 12px', borderRadius: 999, backgroundColor: RED, color: '#fff', fontSize: 10, fontWeight: 900, letterSpacing: '0.1em', textTransform: 'uppercase' }}>Most popular</div>
                )}
                <h3 style={{ fontSize: 20, fontWeight: 900, color: TEXT, marginBottom: 8 }}>{p.name}</h3>
                <div style={{ fontSize: 32, fontWeight: 900, color: RED_LIGHT, marginBottom: 20 }}>{p.price}</div>
                <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 10 }}>
                  {p.features.map(f => (
                    <li key={f} style={{ display: 'flex', gap: 10, fontSize: 14, color: '#D1D5DB' }}>
                      <span style={{ color: RED_LIGHT, fontWeight: 900, flexShrink: 0 }}>✓</span>
                      <span>{f}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── BOTTOM CTA ── */}
      <section style={{ padding: '120px 24px', backgroundColor: BG, borderTop: `1px solid ${BORDER}` }}>
        <div style={{ maxWidth: 900, margin: '0 auto', textAlign: 'center' }}>
          <h2 style={{ fontSize: 48, fontWeight: 900, color: TEXT, marginBottom: 20, lineHeight: 1.1 }}>
            The complete platform for professional boxers.
          </h2>
          <p style={{ fontSize: 17, color: MUTED, lineHeight: 1.6, marginBottom: 40 }}>
            Try the demo with the Marcus Cole sample profile, or set up your own portal in 5 steps.
          </p>
          <div style={{ display: 'flex', gap: 16, justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link href="/boxing/boxing-demo" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '18px 32px', borderRadius: 12, backgroundColor: RED, color: '#fff', fontSize: 16, fontWeight: 800, textDecoration: 'none', boxShadow: `0 20px 50px ${RED}66` }}>
              Try the live demo →
            </Link>
            <Link href="/boxing/onboarding" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '18px 32px', borderRadius: 12, backgroundColor: 'transparent', color: TEXT, fontSize: 16, fontWeight: 800, textDecoration: 'none', border: `1px solid ${BORDER}` }}>
              Set up your portal →
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}
