'use client'

// Live funder outputs — opens a print-ready branded document in a new tab.
// Built client-side from demo data; the production version renders the same
// templates from real registers/surveys (tp_funder_reports stores snapshots).

import { INSIGHTS, FUNNEL, SCHOOLS, CAMPAIGN, IMPACT_AREAS, SCHOOL_STATS } from '@/data/tenproject/demo-data'

export type FunderDocKind = 'term-report' | 'funder-pack' | 'bid-narrative' | 'governor-pack' | 'newsletter-snippet'

const RED = '#D7262C'
const DARK = '#1B1B21'

export function esc(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

export function shell(title: string, body: string, copyText?: string) {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>${esc(title)}</title>
<link rel="icon" href="/tenproject-favicon-32.png">
<style>
  * { box-sizing: border-box; margin: 0; }
  body { font-family: system-ui, -apple-system, sans-serif; color: ${DARK}; background: #F7F5F2; }
  .toolbar { position: sticky; top: 0; background: ${DARK}; padding: 10px 18px; display: flex; gap: 10px; align-items: center; justify-content: space-between; }
  .toolbar span { color: #C9C4BE; font-size: 12px; font-weight: 600; }
  .toolbar div { display: flex; gap: 8px; }
  .toolbar button { background: ${RED}; color: #fff; border: none; border-radius: 8px; padding: 9px 16px; font-size: 13px; font-weight: 800; cursor: pointer; }
  .toolbar button.alt { background: #fff; color: ${DARK}; }
  .page { max-width: 760px; margin: 22px auto; background: #fff; padding: 44px 48px; border-radius: 4px; box-shadow: 0 8px 30px #00000014; }
  .brand { display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid ${RED}; padding-bottom: 16px; margin-bottom: 22px; }
  .brand img { height: 44px; }
  .brand .doc { text-align: right; font-size: 11px; color: #6B6560; font-weight: 700; letter-spacing: 1px; }
  h1 { font-size: 24px; font-weight: 900; margin: 0 0 4px; }
  .sub { color: #6B6560; font-size: 13px; margin-bottom: 20px; }
  h2 { font-size: 15px; font-weight: 900; color: ${RED}; margin: 22px 0 8px; letter-spacing: .4px; }
  p, li { font-size: 13px; line-height: 1.65; color: #33302C; }
  ul { padding-left: 18px; }
  table { width: 100%; border-collapse: collapse; font-size: 12.5px; margin: 8px 0; }
  th { background: ${DARK}; color: #fff; text-align: left; padding: 7px 10px; font-size: 11.5px; }
  td { padding: 7px 10px; border-bottom: 1px solid #EFEBE6; }
  .tiles { display: flex; flex-wrap: wrap; gap: 10px; margin: 10px 0; }
  .tile { flex: 1 1 140px; background: #F7F5F2; border-radius: 10px; padding: 12px 14px; }
  .tile b { display: block; font-size: 21px; font-weight: 900; color: ${RED}; }
  .tile span { font-size: 10.5px; color: #6B6560; font-weight: 700; }
  .quote { background: #FDE8E8; border-radius: 10px; padding: 12px 14px; font-style: italic; font-size: 12.5px; margin: 8px 0; }
  .quote b { display: block; font-style: normal; color: ${RED}; font-size: 11px; margin-top: 5px; }
  .foot { margin-top: 26px; padding-top: 12px; border-top: 1px solid #EFEBE6; font-size: 10.5px; color: #8A847E; }
  @media print { .toolbar { display: none; } body { background: #fff; } .page { box-shadow: none; margin: 0; max-width: none; border-radius: 0; } }
</style></head>
<body>
<div class="toolbar">
  <span>Generated by the Ten Project Portal · demo data</span>
  <div>
    ${copyText ? '<button class="alt" onclick="copyDoc()">Copy text</button>' : ''}
    <button onclick="window.print()">Print / Save as PDF</button>
  </div>
</div>
<div class="page">${body}</div>
${copyText ? `<script>function copyDoc(){navigator.clipboard.writeText(${JSON.stringify(copyText)}).then(()=>{document.querySelector('.toolbar button.alt').textContent='Copied!';setTimeout(()=>{document.querySelector('.toolbar button.alt').textContent='Copy text'},1500)})}</script>` : ''}
</body></html>`
}

export function brandHeader(docLabel: string) {
  return `<div class="brand">
    <img src="/tenproject_logo.png" alt="Ten Project">
    <div class="doc">${esc(docLabel)}<br>${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
  </div>`
}

const tiles = (items: { label: string; value: string | number }[]) =>
  `<div class="tiles">${items.map(t => `<div class="tile"><b>${esc(String(t.value))}</b><span>${esc(t.label)}</span></div>`).join('')}</div>`

// ─── 1. Term report (AI-drafted) ────────────────────────────────────────────
function termReport() {
  const body = `
    ${brandHeader('TERM REPORT · AUTUMN 2026')}
    <h1>Ten Project — Term Report</h1>
    <div class="sub">Autumn term 2026 · prepared for schools, boroughs and trust partners · AI-drafted from registers, QR check-ins and family surveys</div>

    <h2>THE TERM IN NUMBERS</h2>
    ${tiles(INSIGHTS.headline)}

    <h2>NARRATIVE SUMMARY</h2>
    <p>This term Ten Project reached ${INSIGHTS.headline[0].value} children each week in curriculum time across our partner schools, with an average attendance of 91% — every figure drawn from named-child digital registers rather than estimates. Weekend family sessions grew from ${INSIGHTS.weekendTrend[0]} family visits in week 1 to ${INSIGHTS.weekendTrend[INSIGHTS.weekendTrend.length - 1]} by week 10, as families reached in school converted to community participation.</p>
    <p>Of the ${FUNNEL[0].n} children reached in school this term, ${FUNNEL[1].n} families activated the parent app (${FUNNEL[1].pct}%), ${FUNNEL[3].n} attended a weekend community session (${FUNNEL[3].pct}%), and ${FUNNEL[4].n} became regular attendees. This school-to-community conversion is the programme's core outcome — school as the hub, family activity as the result.</p>

    <h2>SCHOOL BY SCHOOL</h2>
    <table><tr><th>School</th><th>Status</th><th>Children</th><th>Parent activation</th></tr>
    ${SCHOOLS.map(s => `<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.status.toUpperCase())}</td><td>${s.children ?? '—'}</td><td>${s.activation ? s.activation + '%' : '—'}</td></tr>`).join('')}
    </table>

    <h2>WHAT FAMILIES TOLD US</h2>
    <p>Families surveyed cited the following areas of improvement: ${IMPACT_AREAS.join(', ')}. The three most-cited were Confidence (88%), Exercise (84%) and Family (81%).</p>

    <h2>SAFEGUARDING & COMPLIANCE</h2>
    <p>All delivering coaches hold current DBS checks, LTA Safeguarding & Protection training, First Aid certification and £5m insurance, tracked with automatic expiry alerts in the portal. Photography and data consent is recorded per family and enforced at every session.</p>

    <div class="foot">Ten Project Ltd · Morden, London · tenproject.org.uk · Generated by the Ten Project Portal (demo data — live version draws from real registers)</div>
  `
  return shell('Ten Project — Term Report', body)
}

// ─── 2. Funder pack ─────────────────────────────────────────────────────────
function funderPack() {
  const maxT = Math.max(...INSIGHTS.termGrowth.map(t => t.children))
  const body = `
    ${brandHeader('FUNDER PACK · 2026')}
    <h1>The case for Ten Project</h1>
    <div class="sub">Participation, impact and reach — the evidence pack for boroughs, trusts and sponsors</div>

    <h2>HEADLINES</h2>
    ${tiles(INSIGHTS.headline)}

    <h2>PARTICIPATION GROWTH</h2>
    <table><tr><th>Term</th>${INSIGHTS.termGrowth.map(t => `<th>${esc(t.term)}</th>`).join('')}</tr>
    <tr><td><b>Children / week</b></td>${INSIGHTS.termGrowth.map(t => `<td>${t.children.toLocaleString()}${t.children === maxT ? ' ◀' : ''}</td>`).join('')}</tr></table>
    <p>3.3× growth in five terms. Every figure is backed by named-child registers captured at the point of delivery.</p>

    <h2>SCHOOL → COMMUNITY CONVERSION</h2>
    <table><tr><th>Funnel stage</th><th>Children / families</th><th>%</th></tr>
    ${FUNNEL.map(f => `<tr><td>${esc(f.stage)}</td><td>${f.n}</td><td>${f.pct}%</td></tr>`).join('')}
    </table>

    <h2>REPORTED IMPACT</h2>
    <table><tr><th>Area</th><th>% of families citing</th></tr>
    ${INSIGHTS.impactSurvey.map(a => `<tr><td>${esc(a.area)}</td><td>${a.pct}%</td></tr>`).join('')}
    </table>

    <h2>REACH & INCLUSION</h2>
    <ul>
      <li>${INSIGHTS.inclusion.freeSessions} of sessions free to families; ${INSIGHTS.inclusion.girls} of participants are girls.</li>
      <li>${INSIGHTS.inclusion.inclusiveVenuePct}% of community venues run inclusive sessions designed for children and adults with learning, sensory and physical disabilities.</li>
      <li>Active in ${INSIGHTS.inclusion.boroughs} boroughs and growing, delivered through primary schools and public community courts.</li>
    </ul>

    <h2>HOW FUNDING UNLOCKS SCHOOLS</h2>
    <p>With PE &amp; Sport Premium direct payments ending, unfunded schools now fundraise through the portal — for example ${esc(CAMPAIGN.school)} has raised £${(CAMPAIGN.raised).toLocaleString()} of its £${CAMPAIGN.target.toLocaleString()} target across ${CAMPAIGN.supporters} supporters. Match-funding a school campaign is the most direct way a partner can put a named school over the line.</p>

    <div class="foot">Ten Project Ltd · Morden, London · tenproject.org.uk · Generated by the Ten Project Portal (demo data — live version draws from real registers)</div>
  `
  return shell('Ten Project — Funder Pack', body)
}

// ─── 3. Bid narrative (copyable) ────────────────────────────────────────────
function bidNarrative() {
  const paras = [
    `Ten Project delivers free, game-based tennis to children aged 4–10 through a 10-week programme embedded in primary-school curriculum time, supplemented by free weekend parent-and-child sessions on public community courts. This term the programme reached 2,140 children per week across our partner schools, with 91% average attendance — every figure evidenced by named-child digital registers captured at the point of delivery.`,
    `The programme's distinctive outcome is school-to-community conversion: of 214 children reached at a typical school, 57% of families activate the programme's parent app, 21% attend a free weekend family session, and 14% become regular attendees. Weekend participation grew from 14 family visits in week one to 44 by week ten. Families surveyed report improvements across Confidence (88%), Exercise (84%) and Family life (81%), alongside Socialising, Well-Being, Focus and Academic Attainment — with 100% saying they would recommend the programme.`,
    `Delivery is fully safeguarded: LTA Level 2/3 accredited coaches with enhanced DBS checks, LTA Safeguarding training, First Aid certification and £5m insurance, all tracked with automatic expiry alerts. All sessions are free to families; 48% of participants are girls, and a third of community venues run sessions designed to include children and adults with learning, sensory and physical disabilities.`,
    `Grant funding directly unlocks named schools: with PE & Sport Premium direct payments ending, unfunded schools now raise their programme cost through supervised fundraising campaigns with transparent, per-pound tracking. A funder can sponsor a school outright or match-fund its campaign — and receives termly impact reporting generated from the same registers and surveys quoted above, per school, per borough or whole-programme.`,
  ]
  const body = `
    ${brandHeader('BID NARRATIVE · DRAFT')}
    <h1>AI-drafted bid narrative</h1>
    <div class="sub">Drop-in copy for grant applications and partner proposals — edit to fit the funder's word limit and priorities</div>
    ${paras.map(p => `<p style="margin-bottom:12px">${esc(p)}</p>`).join('')}
    <div class="foot">Ten Project Ltd · Generated by the Ten Project Portal (demo data — live version draws from real registers) · Use the Copy text button above to paste into a bid</div>
  `
  return shell('Ten Project — Bid Narrative', body, paras.join('\n\n'))
}

// ─── 4. Governor pack (school-facing results, print/PDF) ────────────────────
function governorPack() {
  const s = SCHOOL_STATS
  const body = `
    ${brandHeader('GOVERNOR PACK · ST CLEMENT’S PRIMARY')}
    <h1>Ten Project at St Clement’s Primary</h1>
    <div class="sub">${esc(s.term)} · results pack for governors and sponsors · generated from the programme’s digital registers</div>

    <h2>THE TERM IN NUMBERS</h2>
    ${tiles(s.headline.map(h => ({ label: h.label, value: h.value })))}

    <h2>ATTENDANCE, WEEK BY WEEK</h2>
    <table><tr><th></th>${s.weeklyAttendance.map((_, i) => `<th>W${i + 1}</th>`).join('')}</tr>
    <tr><td><b>Attendance</b></td>${s.weeklyAttendance.map(v => `<td>${v}%</td>`).join('')}</tr></table>
    <p>Attendance held above 90% for the whole programme — week 10, the Ten Project Festival, was the best-attended session of the year. Participation: ${s.yearGroups.map(y => `${y.year} — ${y.children} children`).join(' · ')}.</p>

    <h2>WHAT THE CHILDREN LEARNT</h2>
    <table><tr><th>Skill area (Activity Booklet)</th><th>% of children achieving</th></tr>
    ${s.stickerAreas.map(a => `<tr><td>${esc(a.area)}</td><td>${a.pct}%</td></tr>`).join('')}
    </table>
    <p>Curriculum alignment: ${s.outcomes.join(' · ')}.</p>

    <h2>WHAT FAMILIES SAID</h2>
    ${s.quotes.map(q => `<div class="quote">“${esc(q.q)}”<b>— ${esc(q.who)}</b></div>`).join('')}

    <h2>BRINGING IT BACK FOR 2026/27</h2>
    <p>With PE &amp; Sport Premium direct payments ending, the school is fundraising the programme cost for 2026/27. The campaign has raised £${CAMPAIGN.raised.toLocaleString()} of its £${CAMPAIGN.target.toLocaleString()} target across ${CAMPAIGN.supporters} supporters, with match-funding secured for the final stretch. Governors and sponsors can view or share the live campaign at tenproject.org.uk/fundraise.</p>

    <div class="foot">Ten Project Ltd · tenproject.org.uk · Generated by the Ten Project Portal (demo data — live version draws from real registers)</div>
  `
  return shell('Ten Project — Governor Pack', body)
}

// ─── 5. Parent newsletter snippet (copyable) ────────────────────────────────
function newsletterSnippet() {
  const text = [
    `TEN PROJECT AT ST CLEMENT'S — WHAT A TERM! 🎾`,
    ``,
    `This ${SCHOOL_STATS.term.replace(' (completed)', '')}, ${SCHOOL_STATS.headline[0].value} children across Y2–Y4 took part in Ten Project — ten weeks of free, game-based tennis in school, learning the forehand, backhand, volley and serve, and earning ${SCHOOL_STATS.headline[2].value} Success Stickers along the way. Attendance was ${SCHOOL_STATS.headline[1].value}, and ${SCHOOL_STATS.headline[3].value} children completed all ten weeks and received their certificate at the Ten Project Festival.`,
    ``,
    `It doesn't stop there: free weekend Family Sessions run on local community courts, where parents and children play together — 11 of our families already go. Every family is welcome, all equipment is provided, and it's completely free.`,
    ``,
    `HELP BRING TEN PROJECT BACK FOR 2026/27 — with school sports funding changing, we're raising the programme cost ourselves. We're already at £${CAMPAIGN.raised.toLocaleString()} of £${CAMPAIGN.target.toLocaleString()}! Look out for the Sponsored Ball Hit on 10 October, and you can donate any time via the school's Ten Project fundraising page.`,
    ``,
    `LEARN. PLAY. TOGETHER.`,
  ].join('\n')
  const body = `
    ${brandHeader('PARENT NEWSLETTER SNIPPET')}
    <h1>Parent newsletter snippet</h1>
    <div class="sub">Drop-in copy for the school newsletter or parent app — use the Copy text button above, then paste and edit freely</div>
    ${text.split('\n\n').map(p2 => `<p style="margin-bottom:12px; white-space: pre-line">${esc(p2)}</p>`).join('')}
    <div class="foot">Ten Project Ltd · Generated by the Ten Project Portal (demo data)</div>
  `
  return shell('Ten Project — Newsletter Snippet', body, text)
}

export function openFunderDoc(kind: FunderDocKind) {
  const html =
    kind === 'term-report' ? termReport()
    : kind === 'funder-pack' ? funderPack()
    : kind === 'governor-pack' ? governorPack()
    : kind === 'newsletter-snippet' ? newsletterSnippet()
    : bidNarrative()
  const w = window.open('', '_blank')
  if (!w) return
  w.document.open()
  w.document.write(html)
  w.document.close()
}

export function openDocWindow(html: string) {
  const w = window.open('', '_blank')
  if (!w) return
  w.document.open()
  w.document.write(html)
  w.document.close()
}
