'use client'

// Coach resource library docs + printable TENOR session card.
// Week-4 plans render from the real session-plan data; other resources get
// structured branded documents. Production serves these from coach_resources.

import { shell, brandHeader, esc, openDocWindow } from './funder-docs'
import { WEEK4_SESSION_PLAN, CURRICULUM, STICKER_AREAS } from '@/data/tenproject/demo-data'

const table = (head: [string, string], rows: [string, string][]) =>
  `<table><tr><th>${esc(head[0])}</th><th>${esc(head[1])}</th></tr>${rows.map(r => `<tr><td><b>${esc(r[0])}</b></td><td>${esc(r[1])}</td></tr>`).join('')}</table>`

const ul = (items: string[]) => `<ul>${items.map(i => `<li style="margin-bottom:6px">${esc(i)}</li>`).join('')}</ul>`

function sessionPlanBody(variant: 'school' | 'family') {
  const p2 = WEEK4_SESSION_PLAN
  return `
    ${brandHeader(`SESSION PLAN · WEEK ${p2.week} · ${variant.toUpperCase()}`)}
    <h1>Week ${p2.week} — ${p2.skill} (${variant === 'school' ? 'in-school session' : 'weekend family session'})</h1>
    <div class="sub">${esc(p2.duration)} · ${variant === 'school' ? 'coach-led, teacher assisting' : 'TENOR-led with coach support — parent + child pairs'}</div>
    ${table(['Time', 'Block'], p2.blocks.map(b => [`${b.time} (${b.mins}m)`, `${b.title} — ${b.detail}`] as [string, string]))}
    <h2>COACHING POINTS</h2>
    ${ul(p2.coachingPoints)}
    <h2>EQUIPMENT</h2>
    ${ul(p2.equipment)}
    <h2>SAFETY & SAFEGUARDING</h2>
    ${ul(p2.safety)}
    <h2>THIS WEEK’S VIDEOS</h2>
    ${ul(p2.videos.map(v => `${v.title} (${v.length})`))}
    <div class="foot">Ten Project Ltd · Generated by the Ten Project Portal</div>
  `
}

const GENERIC_DOCS: Record<string, { title: string; sub: string; body: string }> = {
  'Scheme of work — all 10 weeks': {
    title: 'Scheme of work — the full 10 weeks',
    sub: 'The Ten Project curriculum, week by week, with progressions for ages 4–10',
    body: `
      ${table(['Weeks', 'Focus'], CURRICULUM.map(c => [c.weeks, `${c.skill} — ${c.tip}`] as [string, string]))}
      <h2>THE SIX SUCCESS STICKER AREAS</h2>
      ${ul(STICKER_AREAS.map(a => `${a.label} — ${a.desc}`))}
      <h2>DIFFERENTIATION (STEP)</h2>
      ${ul(['Space — bigger/smaller target areas by age and confidence', 'Task — balloon → beach ball → red felt ball progressions', 'Equipment — 19"–23" rackets, mini nets, cones', 'People — 1:1 parent pairs, small teams, whole-group games'])}
    `,
  },
  'Festival pack — Week 10': {
    title: 'Festival pack — Week 10',
    sub: 'The celebration finale — stations, certificates, families invited',
    body: `
      ${table(['Station', 'What happens'], [['Rally corner', 'Family rally challenge — longest rally on the board'], ['Target town', 'Forehand/backhand target hitting, stickers for every hit'], ['Speed serve', 'Fastest serve of the day (soft balls)'], ['Game court', 'Mini match play with coach umpires'], ['Presentation', 'Every child receives their Ten Project certificate']])}
      <h2>CHECKLIST</h2>
      ${ul(['Certificates printed + signed (portal generates from the roster)', 'Family invites out via the app 2 weeks ahead', 'Photography consent flags checked BEFORE the day', 'Stickers: Festival sticker for every completing child', 'Talent-pathway leaflets for keen families'])}
    `,
  },
  'LTA Youth alignment map': {
    title: 'LTA Youth alignment map',
    sub: 'How booklet skills map to the LTA pathway — for talent-spotting conversations',
    body: `
      ${table(['Booklet area', 'LTA Youth equivalent'], [['Warm Up & ABC’s', 'Fundamental movement (Blue/Red foundations)'], ['The Shots', 'Red ball technique strands'], ['Game Play / Scoring', 'Red ball match play + scoring'], ['Fun Games & Competition', 'Festival + team competition formats'], ['Teamwork & Respect', 'LTA Youth values strand']])}
      <p>A child comfortable across all six areas by week 10 is ready for a club Red-ball session — use the pathway referral in the portal so HQ can track the hand-off.</p>
    `,
  },
  'CPD: coaching 4–7s': {
    title: 'CPD — coaching 4–7 year olds',
    sub: 'Video series companion notes',
    body: ul(['Movement before technique — ABC games first, always', 'Instructions in 10 seconds or less; demonstrate, don’t describe', 'Every child active every 30 seconds — no queues', 'Parents are equipment: use them as feeders, targets and partners', 'Praise effort loudly, correct technique quietly']),
  },
  'Talent pathway referral guide': {
    title: 'Talent pathway referral guide',
    sub: 'When and how to refer a child onwards',
    body: ul(['Signals: rally consistency ahead of the group, asks for more, family keen', 'Talk to the family first — the portal referral captures their interest', 'Refer via the portal (Pathways) so HQ can make the club introduction', 'Follow up at week 10 — the Festival is the natural hand-off moment']),
  },
  'Safeguarding: quick reference': {
    title: 'Safeguarding — quick reference',
    sub: 'What to do, what not to do',
    body: ul(['Concern raised or observed: do NOT investigate — record facts, report same day', 'HQ safeguarding lead: 07700 900789 (always answered on session days)', 'Never be alone with a child out of sight of others', 'Photos: check the family consent flag in the register FIRST', 'Record anything unusual in the portal — time, place, facts only']),
  },
  'Kit & equipment checklist': {
    title: 'Kit & equipment checklist',
    sub: 'Per-venue inventory and damage reporting',
    body: ul(['24 rackets (19"–23") — check grips and frames weekly', '40 red felt balls — bin any that have gone soft', '4 mini nets, 20 cones, balloon drill bag', 'Report damage in the portal — replacements auto-requested', 'First-aid kit sealed and in date — check monthly']),
  },
  'Photography & Filming policy': {
    title: 'Photography & Filming policy — courtside rules',
    sub: 'The consent flags and what they mean',
    body: ul(['GREEN flag: photo/filming consent given — OK for programme use', 'AMBER/no flag: NO photos of this child, including group shots they appear in', 'Parents may photograph their OWN child only', 'All programme photos via the portal media upload — never personal camera rolls', 'Full policy: tenproject.org.uk/photography-and-filming-policy']),
  },
}

export function openResourceDoc(title: string) {
  if (title.includes('Week 4') && title.includes('school')) {
    openDocWindow(shell('Week 4 session plan — school', sessionPlanBody('school')))
    return
  }
  if (title.includes('Week 4') && title.includes('family')) {
    openDocWindow(shell('Week 4 session plan — family', sessionPlanBody('family')))
    return
  }
  if (title.includes('Session cards')) {
    // All 10 weeks — reuse the scheme of work
    const d = GENERIC_DOCS['Scheme of work — all 10 weeks']
    openDocWindow(shell(d.title, `${brandHeader('SESSION CARDS · ALL 10 WEEKS')}<h1>${esc(d.title)}</h1><div class="sub">${esc(d.sub)}</div>${d.body}<div class="foot">Ten Project Ltd · Generated by the Ten Project Portal</div>`))
    return
  }
  if (title.includes('TENOR handbook')) {
    openDocWindow(shell('TENOR handbook', `${brandHeader('TENOR HANDBOOK')}<h1>The TENOR handbook</h1><div class="sub">Everything about running a family session — the short version</div>${ul(['Arrive 20 minutes early — setup, court sweep, QR sign on the gate', 'Families scan themselves in; tap in anyone without a phone', 'Follow the week’s session card — warm-up, drills, games, together time', 'Minimum two inducted TENORs for a session to run', 'Any safeguarding concern: call the HQ lead, never investigate yourself', 'Register auto-submits at 3pm — check the live count before you leave', 'Pack down: kit counted back into the store, damage reported in the app'])}<div class="foot">Ten Project Ltd · Generated by the Ten Project Portal</div>`))
    return
  }
  if (title.includes('Safeguarding basics')) {
    const d = GENERIC_DOCS['Safeguarding: quick reference']
    openDocWindow(shell(d.title, `${brandHeader('SAFEGUARDING · VOLUNTEERS')}<h1>${esc(d.title)}</h1><div class="sub">${esc(d.sub)}</div>${d.body}<div class="foot">Ten Project Ltd · Generated by the Ten Project Portal</div>`))
    return
  }
  const d = GENERIC_DOCS[title]
  const doc = d ?? { title, sub: 'Resource', body: '<p>Full content lands here from the portal resource library.</p>' }
  openDocWindow(shell(doc.title, `${brandHeader('RESOURCE')}<h1>${esc(doc.title)}</h1><div class="sub">${esc(doc.sub)}</div>${doc.body}<div class="foot">Ten Project Ltd · Generated by the Ten Project Portal</div>`))
}

export function openSessionCardDoc() {
  openDocWindow(shell('Session card — Week 4', sessionPlanBody('family')))
}
