'use client'

import { useState, useEffect } from 'react'
import { createBrowserClient } from '@supabase/ssr'
import {
  BookOpen, Plus, X, Loader2, CheckCircle2, AlertTriangle,
  ChevronRight, ChevronLeft, Sparkles, Edit3, Send,
  Printer, FileText, Clock, Users, Brain, Copy, Check,
} from 'lucide-react'
import { PageShell, SectionCard, StatCard } from '@/components/page-ui'
import { ChartSection, parseNum } from '@/components/chart-ui'
import Link from 'next/link'

// ─── Supabase ──────────────────────────────────────────────────────────────────

function useSupabase() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  )
}

// ─── Types ─────────────────────────────────────────────────────────────────────

interface CoverWorkRecord {
  id: string
  teacher_name: string
  year_group: string
  subject: string
  topic: string
  duration: string
  sent_to_cover_teacher: boolean
  created_at: string
}

interface GeneratedDoc {
  status: string
  id: string | null
  teacher_name: string
  year_group: string
  subject: string
  topic: string
  duration: string
  cover_teacher_instructions: string
  pupil_task_sheet: string
  extension_activities: string
  marking_guide: string
  tokens_used: number
}

// ─── Constants ─────────────────────────────────────────────────────────────────

const YEAR_GROUPS = [
  'Reception', 'Year 1', 'Year 2', 'Year 3', 'Year 4', 'Year 5', 'Year 6',
  'Year 7', 'Year 8', 'Year 9', 'Year 10', 'Year 11',
]

const SUBJECTS = [
  'English', 'Maths', 'Science', 'History', 'Geography', 'RE', 'PSHE',
  'Art', 'Design & Technology', 'Music', 'PE', 'Computing', 'MFL', 'Drama', 'Other',
]

const DURATIONS = ['1 lesson', 'Half day', 'Full day']

const SAMPLE_STAFF = [
  'Mrs A. Johnson', 'Mr B. Patel', 'Miss C. Williams', 'Mr D. Evans', 'Mrs E. Thompson',
  'Mr F. Clarke', 'Miss G. Roberts', 'Mr H. Wilson', 'Mrs I. Davies', 'Mr J. Stephens',
]

// ─── Copy button helper ────────────────────────────────────────────────────────

function CopyButton({ text, label }: { text: string; label: string }) {
  const [copied, setCopied] = useState(false)
  function handleCopy() {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }
  return (
    <button type="button" onClick={handleCopy}
      className="flex items-center gap-1 text-xs transition-colors"
      style={{ color: copied ? '#0D9488' : '#6B7280' }}>
      {copied ? <Check size={11} /> : <Copy size={11} />}
      {copied ? 'Copied' : label}
    </button>
  )
}

// ─── Generated Document Viewer ────────────────────────────────────────────────

interface DocViewerProps {
  doc: GeneratedDoc
  onClose: () => void
  onSaved: (record: CoverWorkRecord) => void
}

function DocViewer({ doc, onClose, onSaved }: DocViewerProps) {
  const [activeTab, setActiveTab] = useState<'teacher' | 'pupils' | 'extension' | 'marking'>('teacher')
  const [editing, setEditing]     = useState(false)
  const [teacherInstr, setTeacherInstr]   = useState(doc.cover_teacher_instructions)
  const [pupilTask, setPupilTask]         = useState(doc.pupil_task_sheet)
  const [extension, setExtension]         = useState(doc.extension_activities)
  const [marking, setMarking]             = useState(doc.marking_guide)
  const [sendEmail, setSendEmail]         = useState('')
  const [sending, setSending]             = useState(false)
  const [sent, setSent]                   = useState(false)

  const tabs = [
    { id: 'teacher' as const, label: 'Cover Teacher', count: null },
    { id: 'pupils' as const, label: 'Pupil Task Sheet', count: null },
    { id: 'extension' as const, label: 'Extension', count: null },
    { id: 'marking' as const, label: 'Marking Guide', count: null },
  ]

  const currentContent = {
    teacher: teacherInstr,
    pupils: pupilTask,
    extension: extension,
    marking: marking,
  }[activeTab]

  const setCurrentContent = {
    teacher: setTeacherInstr,
    pupils: setPupilTask,
    extension: setExtension,
    marking: setMarking,
  }[activeTab]

  function handlePrint() {
    const content = `
COVER WORK — ${doc.teacher_name}
${doc.year_group} · ${doc.subject} · ${doc.topic}
Duration: ${doc.duration}
Generated by Lumio AI
${'='.repeat(60)}

COVER TEACHER INSTRUCTIONS
${teacherInstr}

${'='.repeat(60)}
PUPIL TASK SHEET
${pupilTask}

${'='.repeat(60)}
EXTENSION ACTIVITIES
${extension}

${'='.repeat(60)}
MARKING GUIDE
${marking}
`
    const w = window.open('', '_blank')
    if (w) {
      w.document.write(`<pre style="font-family:Arial;font-size:13px;padding:24px;max-width:750px">${content}</pre>`)
      w.document.close()
      w.print()
    }
  }

  async function handleSend() {
    if (!sendEmail) return
    setSending(true)
    // In a real app this would call an API — for demo we just mark as sent
    await new Promise(r => setTimeout(r, 800))
    setSent(true)
    setSending(false)
    onSaved({
      id: doc.id ?? crypto.randomUUID(),
      teacher_name: doc.teacher_name,
      year_group: doc.year_group,
      subject: doc.subject,
      topic: doc.topic,
      duration: doc.duration,
      sent_to_cover_teacher: true,
      created_at: new Date().toISOString(),
    })
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(0,0,0,0.7)' }}>
      <div className="w-full max-w-3xl rounded-2xl flex flex-col" style={{ backgroundColor: '#111318', border: '1px solid #1F2937', maxHeight: '90vh' }}>
        {/* Header */}
        <div className="flex items-center justify-between border-b px-6 py-4 shrink-0" style={{ borderColor: '#1F2937' }}>
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5 rounded-full px-3 py-1"
              style={{ backgroundColor: 'rgba(139,92,246,0.12)', border: '1px solid rgba(139,92,246,0.2)' }}>
              <Sparkles size={12} style={{ color: '#A855F7' }} />
              <span className="text-xs font-semibold" style={{ color: '#A855F7' }}>AI Generated</span>
            </div>
            <div>
              <p className="text-sm font-semibold" style={{ color: '#F9FAFB' }}>
                {doc.year_group} · {doc.subject} · {doc.topic}
              </p>
              <p className="text-xs" style={{ color: '#9CA3AF' }}>
                {doc.teacher_name} · {doc.duration} · {doc.tokens_used.toLocaleString()} tokens
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button type="button" onClick={() => setEditing(v => !v)}
              className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors"
              style={{
                backgroundColor: editing ? 'rgba(245,158,11,0.15)' : 'rgba(55,65,81,0.4)',
                color: editing ? '#F59E0B' : '#9CA3AF',
                border: `1px solid ${editing ? '#F59E0B' : '#374151'}`,
              }}>
              <Edit3 size={11} /> {editing ? 'Editing' : 'Edit'}
            </button>
            <button type="button" onClick={handlePrint}
              className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors"
              style={{ backgroundColor: 'rgba(55,65,81,0.4)', color: '#9CA3AF', border: '1px solid #374151' }}>
              <Printer size={11} /> Print
            </button>
            <button onClick={onClose} className="rounded-lg p-1.5 transition-colors hover:bg-gray-800">
              <X size={16} style={{ color: '#9CA3AF' }} />
            </button>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex border-b shrink-0" style={{ borderColor: '#1F2937' }}>
          {tabs.map(tab => (
            <button key={tab.id} type="button"
              onClick={() => setActiveTab(tab.id)}
              className="px-5 py-3 text-xs font-semibold transition-colors"
              style={{
                color: activeTab === tab.id ? '#F9FAFB' : '#6B7280',
                borderBottom: activeTab === tab.id ? '2px solid #A855F7' : '2px solid transparent',
              }}>
              {tab.label}
            </button>
          ))}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {editing ? (
            <textarea
              value={currentContent}
              onChange={e => setCurrentContent(e.target.value)}
              className="w-full h-full min-h-[300px] resize-none rounded-lg px-4 py-3 text-sm outline-none font-mono leading-relaxed"
              style={{ backgroundColor: '#07080F', border: '1px solid #374151', color: '#F9FAFB' }}
            />
          ) : (
            <div className="relative">
              <div className="absolute top-0 right-0">
                <CopyButton text={currentContent} label="Copy section" />
              </div>
              <pre className="whitespace-pre-wrap text-sm leading-relaxed"
                style={{ color: '#D1D5DB', fontFamily: 'inherit' }}>
                {currentContent || <span style={{ color: '#4B5563' }}>No content in this section</span>}
              </pre>
            </div>
          )}
        </div>

        {/* Send panel */}
        <div className="border-t px-6 py-4 shrink-0" style={{ borderColor: '#1F2937' }}>
          {sent ? (
            <div className="flex items-center gap-2">
              <CheckCircle2 size={14} style={{ color: '#0D9488' }} />
              <span className="text-sm" style={{ color: '#0D9488' }}>Sent to cover teacher at {sendEmail}</span>
            </div>
          ) : (
            <div className="flex items-center gap-2">
              <input
                value={sendEmail}
                onChange={e => setSendEmail(e.target.value)}
                type="email"
                placeholder="cover.teacher@school.example"
                className="flex-1 rounded-lg px-3 py-2 text-sm outline-none"
                style={{ backgroundColor: '#07080F', border: '1px solid #374151', color: '#F9FAFB' }} />
              <button type="button" onClick={handleSend} disabled={!sendEmail || sending}
                className="flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold shrink-0"
                style={{
                  backgroundColor: sendEmail ? '#0D9488' : 'rgba(55,65,81,0.4)',
                  color: sendEmail ? '#F9FAFB' : '#6B7280',
                }}>
                {sending ? <Loader2 size={13} className="animate-spin" /> : <Send size={13} />}
                Send to cover teacher
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ─── Generator Modal ──────────────────────────────────────────────────────────

interface GenModalProps {
  prefilledTeacher?: string
  onClose: () => void
  onGenerated: (doc: GeneratedDoc, record: CoverWorkRecord) => void
}

function GeneratorModal({ prefilledTeacher, onClose, onGenerated }: GenModalProps) {
  const [teacherName, setTeacherName]     = useState(prefilledTeacher ?? '')
  const [suggestions, setSuggestions]     = useState<string[]>([])
  const [yearGroup, setYearGroup]         = useState('')
  const [subject, setSubject]             = useState('')
  const [topic, setTopic]                 = useState('')
  const [duration, setDuration]           = useState('1 lesson')
  const [instructions, setInstructions]   = useState('')
  const [generating, setGenerating]       = useState(false)
  const [error, setError]                 = useState('')

  function handleTeacherInput(val: string) {
    setTeacherName(val)
    if (val.length < 2) { setSuggestions([]); return }
    setSuggestions(SAMPLE_STAFF.filter(s => s.toLowerCase().includes(val.toLowerCase())))
  }

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault()
    if (!teacherName.trim()) { setError('Teacher name required.'); return }
    if (!yearGroup) { setError('Year group required.'); return }
    if (!subject) { setError('Subject required.'); return }
    if (!topic.trim()) { setError('Topic required.'); return }

    setGenerating(true)
    setError('')
    try {
      const res = await fetch('/api/workflows/school/cover-work', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          teacher_name: teacherName.trim(),
          year_group: yearGroup,
          subject,
          topic: topic.trim(),
          duration,
          instructions: instructions || undefined,
        }),
      })
      const data = await res.json()
      if (!res.ok) { setError(data.error ?? 'Generation failed.'); return }

      const doc = data as GeneratedDoc
      const record: CoverWorkRecord = {
        id: doc.id ?? crypto.randomUUID(),
        teacher_name: doc.teacher_name,
        year_group: doc.year_group,
        subject: doc.subject,
        topic: doc.topic,
        duration: doc.duration,
        sent_to_cover_teacher: false,
        created_at: new Date().toISOString(),
      }
      onGenerated(doc, record)
    } catch {
      setError('Network error. Please try again.')
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(0,0,0,0.6)' }}>
      <div className="w-full max-w-lg rounded-2xl" style={{ backgroundColor: '#111318', border: '1px solid #1F2937' }}>
        <div className="flex items-center justify-between border-b px-6 py-4" style={{ borderColor: '#1F2937' }}>
          <div className="flex items-center gap-2">
            <Brain size={18} style={{ color: '#A855F7' }} />
            <h2 className="text-base font-semibold" style={{ color: '#F9FAFB' }}>AI Cover Work Generator</h2>
          </div>
          <button onClick={onClose} className="rounded-lg p-1.5 transition-colors hover:bg-gray-800">
            <X size={16} style={{ color: '#9CA3AF' }} />
          </button>
        </div>

        <form onSubmit={handleGenerate} className="flex flex-col gap-4 px-6 py-5">
          {/* Teacher */}
          <div className="relative">
            <label className="block text-xs font-semibold mb-1.5" style={{ color: '#9CA3AF' }}>Absent Teacher *</label>
            <input
              value={teacherName}
              onChange={e => handleTeacherInput(e.target.value)}
              placeholder="Type name…"
              className="w-full rounded-lg px-3 py-2.5 text-sm outline-none"
              style={{ backgroundColor: '#07080F', border: '1px solid #374151', color: '#F9FAFB' }} />
            {suggestions.length > 0 && (
              <div className="absolute z-10 w-full mt-1 rounded-lg overflow-hidden shadow-lg"
                style={{ backgroundColor: '#1C1F26', border: '1px solid #374151' }}>
                {suggestions.map(s => (
                  <button key={s} type="button"
                    className="w-full text-left px-3 py-2 text-sm hover:bg-gray-700 transition-colors"
                    style={{ color: '#F9FAFB' }}
                    onClick={() => { setTeacherName(s); setSuggestions([]) }}>
                    {s}
                  </button>
                ))}
              </div>
            )}
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold mb-1.5" style={{ color: '#9CA3AF' }}>Year Group *</label>
              <select value={yearGroup} onChange={e => setYearGroup(e.target.value)}
                className="w-full rounded-lg px-3 py-2.5 text-sm outline-none"
                style={{ backgroundColor: '#07080F', border: '1px solid #374151', color: '#F9FAFB' }}>
                <option value="">Select…</option>
                {YEAR_GROUPS.map(y => <option key={y} value={y}>{y}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-xs font-semibold mb-1.5" style={{ color: '#9CA3AF' }}>Subject *</label>
              <select value={subject} onChange={e => setSubject(e.target.value)}
                className="w-full rounded-lg px-3 py-2.5 text-sm outline-none"
                style={{ backgroundColor: '#07080F', border: '1px solid #374151', color: '#F9FAFB' }}>
                <option value="">Select…</option>
                {SUBJECTS.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold mb-1.5" style={{ color: '#9CA3AF' }}>Topic / Unit *</label>
            <input value={topic} onChange={e => setTopic(e.target.value)}
              placeholder="What were they covering this week? (e.g. Fractions, WW2 causes, photosynthesis…)"
              className="w-full rounded-lg px-3 py-2.5 text-sm outline-none"
              style={{ backgroundColor: '#07080F', border: '1px solid #374151', color: '#F9FAFB' }} />
          </div>

          <div>
            <label className="block text-xs font-semibold mb-2" style={{ color: '#9CA3AF' }}>Duration *</label>
            <div className="flex gap-2">
              {DURATIONS.map(d => {
                const sel = duration === d
                return (
                  <button key={d} type="button" onClick={() => setDuration(d)}
                    className="rounded-lg px-3 py-1.5 text-xs font-medium transition-colors"
                    style={{
                      backgroundColor: sel ? 'rgba(139,92,246,0.2)' : 'rgba(55,65,81,0.4)',
                      color: sel ? '#A855F7' : '#9CA3AF',
                      border: `1px solid ${sel ? '#8B5CF6' : '#374151'}`,
                    }}>
                    {d}
                  </button>
                )
              })}
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold mb-1.5" style={{ color: '#9CA3AF' }}>Special Instructions</label>
            <textarea value={instructions} onChange={e => setInstructions(e.target.value)}
              rows={2}
              placeholder="SEN considerations, group work preferred, avoid writing tasks, use textbook pp.45-50…"
              className="w-full resize-none rounded-lg px-3 py-2.5 text-sm outline-none"
              style={{ backgroundColor: '#07080F', border: '1px solid #374151', color: '#F9FAFB' }} />
          </div>

          {error && (
            <div className="flex items-center gap-2 rounded-lg px-3 py-2.5"
              style={{ backgroundColor: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.25)' }}>
              <AlertTriangle size={14} style={{ color: '#EF4444' }} />
              <p className="text-xs" style={{ color: '#FCA5A5' }}>{error}</p>
            </div>
          )}

          <div className="flex gap-3 pt-1">
            <button type="button" onClick={onClose}
              className="rounded-lg px-4 py-2.5 text-sm font-medium"
              style={{ backgroundColor: 'rgba(55,65,81,0.4)', color: '#9CA3AF', border: '1px solid #374151' }}>
              Cancel
            </button>
            <button type="submit" disabled={generating}
              className="flex-1 flex items-center justify-center gap-2 rounded-lg py-2.5 text-sm font-semibold"
              style={{ backgroundColor: generating ? '#4B5563' : '#7C3AED', color: '#F9FAFB' }}>
              {generating ? (
                <><Loader2 size={14} className="animate-spin" /> Generating with Claude AI…</>
              ) : (
                <><Sparkles size={14} /> Generate Cover Work</>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

// ─── Page ──────────────────────────────────────────────────────────────────────

export default function CoverWorkPage() {
  const supabase = useSupabase()
  const [showModal, setShowModal]         = useState(false)
  const [generatedDoc, setGeneratedDoc]   = useState<GeneratedDoc | null>(null)
  const [records, setRecords]             = useState<CoverWorkRecord[]>([])
  const [loading, setLoading]             = useState(true)
  const [totalCount, setTotalCount]       = useState(0)
  const [sentCount, setSentCount]         = useState(0)

  useEffect(() => {
    async function load() {
      try {
        const { data } = await supabase
          .from('school_cover_work')
          .select('id, teacher_name, year_group, subject, topic, duration, sent_to_cover_teacher, created_at')
          .order('created_at', { ascending: false })
          .limit(30)

        if (data) {
          const records = data as CoverWorkRecord[]
          setRecords(records)
          setTotalCount(records.length)
          setSentCount(records.filter(r => r.sent_to_cover_teacher).length)
        }
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [supabase])

  function handleGenerated(doc: GeneratedDoc, record: CoverWorkRecord) {
    setShowModal(false)
    setGeneratedDoc(doc)
    setRecords(prev => [record, ...prev])
    setTotalCount(c => c + 1)
  }

  function handleSaved(updatedRecord: CoverWorkRecord) {
    setRecords(prev => prev.map(r => r.id === updatedRecord.id ? updatedRecord : r))
    if (updatedRecord.sent_to_cover_teacher) setSentCount(c => c + 1)
  }

  const stats = [
    {
      label: 'Cover Work Generated',
      value: String(loading ? '…' : totalCount),
      trend: 'using Claude AI',
      trendDir: 'up' as const,
      trendGood: true,
      icon: Brain,
      sub: 'all time',
    },
    {
      label: 'Sent to Cover Teachers',
      value: String(sentCount),
      trend: sentCount > 0 ? 'delivered' : 'none yet',
      trendDir: 'up' as const,
      trendGood: true,
      icon: Send,
      sub: 'emailed directly',
    },
    {
      label: 'Subjects Covered',
      value: String(new Set(records.map(r => r.subject)).size),
      trend: 'across curriculum',
      trendDir: 'up' as const,
      trendGood: true,
      icon: BookOpen,
      sub: 'different subjects',
    },
    {
      label: 'Staff Covered',
      value: String(new Set(records.map(r => r.teacher_name)).size),
      trend: 'different teachers',
      trendDir: 'up' as const,
      trendGood: true,
      icon: Users,
      sub: 'unique staff',
    },
  ]

  return (
    <PageShell>
      {/* Sub-navigation */}
      <div className="flex items-center gap-2 flex-wrap">
        <Link href="/school-office"
          className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors"
          style={{ backgroundColor: 'rgba(107,114,128,0.1)', color: '#9CA3AF', border: '1px solid #374151' }}>
          <ChevronLeft size={11} /> School Office
        </Link>
        <ChevronRight size={12} style={{ color: '#374151' }} />
        <Link href="/school-office/cover"
          className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors"
          style={{ backgroundColor: 'rgba(107,114,128,0.1)', color: '#9CA3AF', border: '1px solid #374151' }}>
          Supply Cover
        </Link>
        <ChevronRight size={12} style={{ color: '#374151' }} />
        <span className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium"
          style={{ backgroundColor: 'rgba(139,92,246,0.08)', color: '#A855F7', border: '1px solid rgba(139,92,246,0.2)' }}>
          <Brain size={12} /> AI Cover Work
        </span>
      </div>

      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold" style={{ color: '#F9FAFB' }}>AI Cover Work Generator</h2>
          <p className="text-xs mt-0.5" style={{ color: '#9CA3AF' }}>
            Claude AI generates cover teacher instructions, pupil task sheets, extension activities and marking guides in seconds
          </p>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold transition-colors"
          style={{ backgroundColor: '#7C3AED', color: '#F9FAFB' }}
          onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.backgroundColor = '#6D28D9' }}
          onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.backgroundColor = '#7C3AED' }}>
          <Sparkles size={15} />
          Generate Cover Work
        </button>
      </div>

      {/* Stats */}
      <ChartSection points={stats.map(s => ({ label: s.label, value: parseNum(s.value) }))}>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {stats.map(s => <StatCard key={s.label} {...s} />)}
        </div>
      </ChartSection>

      {/* How it works */}
      <div className="rounded-xl px-5 py-4" style={{ backgroundColor: 'rgba(139,92,246,0.06)', border: '1px solid rgba(139,92,246,0.15)' }}>
        <div className="flex items-start gap-3">
          <Sparkles size={16} className="shrink-0 mt-0.5" style={{ color: '#A855F7' }} />
          <div>
            <p className="text-sm font-semibold" style={{ color: '#F9FAFB' }}>Powered by Claude AI</p>
            <p className="text-xs mt-0.5" style={{ color: '#9CA3AF' }}>
              Enter the teacher, year group, subject, and topic — Claude generates a complete cover work pack in seconds including pupil-facing task sheets, cover teacher instructions, extension activities for early finishers, and a simple marking guide.
            </p>
          </div>
        </div>
      </div>

      {/* History */}
      <SectionCard title="Generated Cover Work">
        {loading ? (
          <div className="flex items-center justify-center py-10">
            <Loader2 size={20} className="animate-spin" style={{ color: '#9CA3AF' }} />
          </div>
        ) : records.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-3 py-10">
            <Brain size={32} style={{ color: '#374151' }} />
            <p className="text-sm" style={{ color: '#9CA3AF' }}>No cover work generated yet</p>
            <button onClick={() => setShowModal(true)}
              className="flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold"
              style={{ backgroundColor: 'rgba(139,92,246,0.15)', color: '#A855F7', border: '1px solid rgba(139,92,246,0.3)' }}>
              <Sparkles size={13} /> Generate your first cover work pack
            </button>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr style={{ borderBottom: '1px solid #1F2937' }}>
                  {['Teacher', 'Year', 'Subject', 'Topic', 'Duration', 'Status', 'Created'].map(h => (
                    <th key={h} className="pb-3 text-left text-xs font-semibold uppercase tracking-wider"
                      style={{ color: '#6B7280' }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y" style={{ borderColor: '#1F2937' }}>
                {records.map(r => (
                  <tr key={r.id}>
                    <td className="py-3 pr-4 text-sm font-medium" style={{ color: '#F9FAFB' }}>{r.teacher_name}</td>
                    <td className="py-3 pr-4 text-xs" style={{ color: '#9CA3AF' }}>{r.year_group}</td>
                    <td className="py-3 pr-4 text-xs" style={{ color: '#9CA3AF' }}>{r.subject}</td>
                    <td className="py-3 pr-4 text-xs max-w-[180px] truncate" style={{ color: '#D1D5DB' }}>{r.topic}</td>
                    <td className="py-3 pr-4 text-xs" style={{ color: '#6B7280' }}>{r.duration}</td>
                    <td className="py-3 pr-4">
                      {r.sent_to_cover_teacher ? (
                        <span className="flex items-center gap-1 text-xs" style={{ color: '#0D9488' }}>
                          <CheckCircle2 size={11} /> Sent
                        </span>
                      ) : (
                        <span className="flex items-center gap-1 text-xs" style={{ color: '#6B7280' }}>
                          <FileText size={11} /> Saved
                        </span>
                      )}
                    </td>
                    <td className="py-3 text-xs" style={{ color: '#6B7280' }}>
                      {new Date(r.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </SectionCard>

      {/* What Claude generates */}
      <SectionCard title="What's Included in Every Pack">
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {[
            { icon: FileText, title: 'Cover Teacher Instructions', desc: 'Step-by-step lesson guide, timing, and classroom management notes.' },
            { icon: BookOpen, title: 'Pupil Task Sheet', desc: 'Ready-to-use activity written directly to pupils with clear objectives.' },
            { icon: Plus, title: 'Extension Activities', desc: '2-3 additional tasks for early finishers, appropriately challenging.' },
            { icon: CheckCircle2, title: 'Marking Guide', desc: 'Simple guide so work can be quickly assessed on the teacher\'s return.' },
          ].map(({ icon: Icon, title, desc }) => (
            <div key={title} className="rounded-xl p-4" style={{ backgroundColor: '#07080F', border: '1px solid #1F2937' }}>
              <Icon size={16} className="mb-2" style={{ color: '#A855F7' }} />
              <p className="text-sm font-semibold mb-1" style={{ color: '#F9FAFB' }}>{title}</p>
              <p className="text-xs leading-relaxed" style={{ color: '#9CA3AF' }}>{desc}</p>
            </div>
          ))}
        </div>
      </SectionCard>

      {showModal && (
        <GeneratorModal
          onClose={() => setShowModal(false)}
          onGenerated={handleGenerated}
        />
      )}

      {generatedDoc && (
        <DocViewer
          doc={generatedDoc}
          onClose={() => setGeneratedDoc(null)}
          onSaved={handleSaved}
        />
      )}
    </PageShell>
  )
}
