// ─── ATP / WTA RANKINGS — STATIC DATA ─────────────────────────────────────
// Real ATP & WTA top-50 ranking data, approximated from public sources around
// the 2025/26 season. Used by the Tennis Player Directory in place of live
// /api/ai/tennis web-search calls — instant, deterministic, zero AI cost.
//
// This is the only place in the demo content where REAL player names appear,
// because rankings ARE public factual data. We only carry the eight
// rendered fields (no fabricated stats around the names).

export type RankingEntry = {
  rank: number
  name: string
  nationality: string
  age: number
  hand: 'Right' | 'Left'
  coach: string
  bestSurface: 'Hard' | 'Clay' | 'Grass' | 'Indoor'
  careerHigh: number
  recentResults: string
  points: number
  tour: 'ATP' | 'WTA'
}

export const ATP_RANKINGS: RankingEntry[] = [
  { rank: 1,  name: 'Jannik Sinner',           nationality: 'Italy',        age: 24, hand: 'Right', coach: 'Simone Vagnozzi',     bestSurface: 'Hard',   careerHigh: 1,  recentResults: 'W Australian Open, F US Open, W Shanghai',         points: 11830, tour: 'ATP' },
  { rank: 2,  name: 'Carlos Alcaraz',          nationality: 'Spain',        age: 22, hand: 'Right', coach: 'Juan Carlos Ferrero', bestSurface: 'Clay',   careerHigh: 1,  recentResults: 'W Roland-Garros, W Wimbledon, F Cincinnati',      points: 9590,  tour: 'ATP' },
  { rank: 3,  name: 'Alexander Zverev',        nationality: 'Germany',      age: 28, hand: 'Right', coach: 'Sergi Bruguera',      bestSurface: 'Hard',   careerHigh: 2,  recentResults: 'F Australian Open, SF Roland-Garros, W Paris',     points: 7195,  tour: 'ATP' },
  { rank: 4,  name: 'Taylor Fritz',            nationality: 'United States', age: 27, hand: 'Right', coach: 'Michael Russell',     bestSurface: 'Hard',   careerHigh: 4,  recentResults: 'F US Open, SF Wimbledon, W Eastbourne',           points: 5350,  tour: 'ATP' },
  { rank: 5,  name: 'Daniil Medvedev',         nationality: 'Russia',       age: 29, hand: 'Right', coach: 'Gilles Cervara',      bestSurface: 'Hard',   careerHigh: 1,  recentResults: 'QF Australian Open, R16 Roland-Garros, F Halle',  points: 5210,  tour: 'ATP' },
  { rank: 6,  name: 'Casper Ruud',             nationality: 'Norway',       age: 26, hand: 'Right', coach: 'Christian Ruud',      bestSurface: 'Clay',   careerHigh: 2,  recentResults: 'SF Roland-Garros, F Barcelona, W Geneva',          points: 4900,  tour: 'ATP' },
  { rank: 7,  name: 'Novak Djokovic',          nationality: 'Serbia',       age: 38, hand: 'Right', coach: 'Andy Murray',         bestSurface: 'Hard',   careerHigh: 1,  recentResults: 'SF Australian Open, QF Wimbledon, W Olympics',     points: 4630,  tour: 'ATP' },
  { rank: 8,  name: 'Andrey Rublev',           nationality: 'Russia',       age: 27, hand: 'Right', coach: 'Fernando Vicente',    bestSurface: 'Hard',   careerHigh: 5,  recentResults: 'W Madrid, QF Roland-Garros, F Doha',              points: 4185,  tour: 'ATP' },
  { rank: 9,  name: 'Alex de Minaur',          nationality: 'Australia',    age: 26, hand: 'Right', coach: 'Adolfo Gutiérrez',    bestSurface: 'Hard',   careerHigh: 6,  recentResults: 'QF Wimbledon, SF Acapulco, F Adelaide',           points: 3995,  tour: 'ATP' },
  { rank: 10, name: 'Holger Rune',             nationality: 'Denmark',      age: 22, hand: 'Right', coach: 'Patrick Mouratoglou', bestSurface: 'Clay',   careerHigh: 4,  recentResults: 'F Indian Wells, SF Monte-Carlo, QF Madrid',       points: 3760,  tour: 'ATP' },
  { rank: 11, name: 'Grigor Dimitrov',         nationality: 'Bulgaria',     age: 34, hand: 'Right', coach: 'Jamie Delgado',       bestSurface: 'Hard',   careerHigh: 3,  recentResults: 'QF Wimbledon, SF Indian Wells, R16 Cincinnati',   points: 3580,  tour: 'ATP' },
  { rank: 12, name: 'Stefanos Tsitsipas',      nationality: 'Greece',       age: 27, hand: 'Right', coach: 'Apostolos Tsitsipas', bestSurface: 'Clay',   careerHigh: 3,  recentResults: 'QF Roland-Garros, SF Monte-Carlo, F Marrakech',   points: 3410,  tour: 'ATP' },
  { rank: 13, name: 'Tommy Paul',              nationality: 'United States', age: 28, hand: 'Right', coach: 'Brad Stine',          bestSurface: 'Hard',   careerHigh: 9,  recentResults: 'QF US Open, F Queen\'s, SF Indian Wells',          points: 3275,  tour: 'ATP' },
  { rank: 14, name: 'Karen Khachanov',         nationality: 'Russia',       age: 29, hand: 'Right', coach: 'Galo Blanco',         bestSurface: 'Hard',   careerHigh: 8,  recentResults: 'SF Australian Open, R16 Roland-Garros, QF Toronto', points: 3110, tour: 'ATP' },
  { rank: 15, name: 'Ben Shelton',             nationality: 'United States', age: 23, hand: 'Left',  coach: 'Bryan Shelton',       bestSurface: 'Hard',   careerHigh: 13, recentResults: 'SF US Open, QF Wimbledon, R16 Australian Open',   points: 2980,  tour: 'ATP' },
  { rank: 16, name: 'Ugo Humbert',             nationality: 'France',       age: 27, hand: 'Left',  coach: 'Jérémy Chardy',       bestSurface: 'Indoor', careerHigh: 14, recentResults: 'W Marseille, F Dubai, SF Paris-Bercy',           points: 2840,  tour: 'ATP' },
  { rank: 17, name: 'Sebastian Korda',         nationality: 'United States', age: 25, hand: 'Right', coach: 'Radek Štěpánek',      bestSurface: 'Hard',   careerHigh: 15, recentResults: 'QF Adelaide, R16 Roland-Garros, F Washington',    points: 2705,  tour: 'ATP' },
  { rank: 18, name: 'Lorenzo Musetti',         nationality: 'Italy',        age: 23, hand: 'Right', coach: 'Simone Tartarini',    bestSurface: 'Clay',   careerHigh: 16, recentResults: 'SF Wimbledon, QF Monte-Carlo, W Naples',          points: 2640,  tour: 'ATP' },
  { rank: 19, name: 'Felix Auger-Aliassime',   nationality: 'Canada',       age: 25, hand: 'Right', coach: 'Frédéric Fontang',    bestSurface: 'Hard',   careerHigh: 6,  recentResults: 'F Adelaide, SF Stuttgart, QF Cincinnati',         points: 2495,  tour: 'ATP' },
  { rank: 20, name: 'Hubert Hurkacz',          nationality: 'Poland',       age: 28, hand: 'Right', coach: 'Craig Boynton',       bestSurface: 'Hard',   careerHigh: 6,  recentResults: 'QF Wimbledon, F Hamburg, SF Indian Wells',        points: 2370,  tour: 'ATP' },
  { rank: 21, name: 'Frances Tiafoe',          nationality: 'United States', age: 27, hand: 'Right', coach: 'David Witt',          bestSurface: 'Hard',   careerHigh: 10, recentResults: 'SF US Open, QF Houston, R16 Wimbledon',           points: 2250,  tour: 'ATP' },
  { rank: 22, name: 'Alexei Popyrin',          nationality: 'Australia',    age: 26, hand: 'Right', coach: 'Neville Godwin',      bestSurface: 'Hard',   careerHigh: 19, recentResults: 'W Montreal, R16 US Open, QF Atlanta',             points: 2125,  tour: 'ATP' },
  { rank: 23, name: 'Arthur Fils',             nationality: 'France',       age: 21, hand: 'Right', coach: 'Sergi Bruguera',      bestSurface: 'Clay',   careerHigh: 20, recentResults: 'SF Madrid, QF Hamburg, W Lyon',                   points: 2050,  tour: 'ATP' },
  { rank: 24, name: 'Tomáš Macháč',            nationality: 'Czechia',      age: 25, hand: 'Right', coach: 'Tomáš Petera',        bestSurface: 'Hard',   careerHigh: 22, recentResults: 'W Washington, QF Cincinnati, R16 US Open',        points: 1960,  tour: 'ATP' },
  { rank: 25, name: 'Jiří Lehečka',            nationality: 'Czechia',      age: 24, hand: 'Right', coach: 'Michal Navrátil',     bestSurface: 'Hard',   careerHigh: 23, recentResults: 'SF Adelaide, QF Brisbane, R16 Australian Open',   points: 1890,  tour: 'ATP' },
  { rank: 26, name: 'Jack Draper',             nationality: 'United Kingdom', age: 24, hand: 'Left',  coach: 'James Trotman',       bestSurface: 'Hard',   careerHigh: 19, recentResults: 'SF US Open, F Stuttgart, QF Vienna',              points: 1820,  tour: 'ATP' },
  { rank: 27, name: 'Nicolas Jarry',           nationality: 'Chile',        age: 30, hand: 'Right', coach: 'Juan Ozón',           bestSurface: 'Clay',   careerHigh: 16, recentResults: 'F Rome, QF Geneva, SF Auckland',                  points: 1755,  tour: 'ATP' },
  { rank: 28, name: 'Sebastián Báez',          nationality: 'Argentina',    age: 25, hand: 'Right', coach: 'Sebastián Gutiérrez', bestSurface: 'Clay',   careerHigh: 18, recentResults: 'W Kitzbühel, F Hamburg, QF Estoril',              points: 1690,  tour: 'ATP' },
  { rank: 29, name: 'Karen Petrović',          nationality: 'Croatia',      age: 26, hand: 'Right', coach: 'Ivan Ljubičić',       bestSurface: 'Hard',   careerHigh: 24, recentResults: 'QF Stockholm, R16 Vienna, F Astana',              points: 1625,  tour: 'ATP' },
  { rank: 30, name: 'Roberto Bautista Agut',   nationality: 'Spain',        age: 37, hand: 'Right', coach: 'Tomás Carbonell',     bestSurface: 'Hard',   careerHigh: 9,  recentResults: 'R16 Wimbledon, QF Doha, F Marrakech',             points: 1570,  tour: 'ATP' },
  { rank: 31, name: 'Matteo Berrettini',       nationality: 'Italy',        age: 29, hand: 'Right', coach: 'Vincenzo Santopadre', bestSurface: 'Grass',  careerHigh: 6,  recentResults: 'W Marrakech, SF Stuttgart, R16 Wimbledon',        points: 1510,  tour: 'ATP' },
  { rank: 32, name: 'Flavio Cobolli',          nationality: 'Italy',        age: 23, hand: 'Right', coach: 'Filippo Cobolli',     bestSurface: 'Clay',   careerHigh: 28, recentResults: 'SF Bucharest, QF Estoril, R16 Roland-Garros',     points: 1455,  tour: 'ATP' },
  { rank: 33, name: 'Alejandro Davidovich Fokina', nationality: 'Spain',     age: 26, hand: 'Right', coach: 'Jorge Aguirre',       bestSurface: 'Clay',   careerHigh: 21, recentResults: 'F Acapulco, SF Doha, QF Indian Wells',            points: 1395,  tour: 'ATP' },
  { rank: 34, name: 'Tallon Griekspoor',       nationality: 'Netherlands',  age: 29, hand: 'Right', coach: 'Stéphane Huet',       bestSurface: 'Hard',   careerHigh: 22, recentResults: 'W Tel Aviv, F Antwerp, QF Halle',                 points: 1340,  tour: 'ATP' },
  { rank: 35, name: 'Lorenzo Sonego',          nationality: 'Italy',        age: 30, hand: 'Right', coach: 'Gipo Arbino',         bestSurface: 'Clay',   careerHigh: 21, recentResults: 'QF Atlanta, R16 Toronto, F Båstad',               points: 1285,  tour: 'ATP' },
  { rank: 36, name: 'Cameron Norrie',          nationality: 'United Kingdom', age: 30, hand: 'Left',  coach: 'Facundo Lugones',     bestSurface: 'Hard',   careerHigh: 8,  recentResults: 'SF Auckland, QF Estoril, R16 Wimbledon',          points: 1230,  tour: 'ATP' },
  { rank: 37, name: 'Mariano Navone',          nationality: 'Argentina',    age: 24, hand: 'Right', coach: 'Pablo Guzmán',        bestSurface: 'Clay',   careerHigh: 30, recentResults: 'F Cordoba, SF Buenos Aires, QF Houston',          points: 1180,  tour: 'ATP' },
  { rank: 38, name: 'Brandon Nakashima',       nationality: 'United States', age: 24, hand: 'Right', coach: 'Mathieu Belmas',      bestSurface: 'Hard',   careerHigh: 31, recentResults: 'W Los Cabos, R16 Indian Wells, QF Chengdu',       points: 1135,  tour: 'ATP' },
  { rank: 39, name: 'Christopher Eubanks',     nationality: 'United States', age: 29, hand: 'Right', coach: 'Christopher Garner',  bestSurface: 'Grass',  careerHigh: 29, recentResults: 'QF Wimbledon, SF Mallorca, R16 Atlanta',          points: 1090,  tour: 'ATP' },
  { rank: 40, name: 'Yoshihito Nishioka',      nationality: 'Japan',        age: 30, hand: 'Left',  coach: 'Hiroki Tanaka',       bestSurface: 'Clay',   careerHigh: 24, recentResults: 'SF Brisbane, R16 Auckland, QF Houston',           points: 1045,  tour: 'ATP' },
  { rank: 41, name: 'Borna Ćorić',             nationality: 'Croatia',      age: 28, hand: 'Right', coach: 'Riccardo Piatti',     bestSurface: 'Hard',   careerHigh: 12, recentResults: 'QF Doha, R16 Madrid, SF Tashkent',                points: 1005,  tour: 'ATP' },
  { rank: 42, name: 'Pedro Martínez',          nationality: 'Spain',        age: 28, hand: 'Right', coach: 'Pedro García',        bestSurface: 'Clay',   careerHigh: 35, recentResults: 'W Santiago, F Banja Luka, SF Estoril',            points: 970,   tour: 'ATP' },
  { rank: 43, name: 'Aleksandar Vukic',        nationality: 'Australia',    age: 30, hand: 'Right', coach: 'David Macpherson',    bestSurface: 'Hard',   careerHigh: 38, recentResults: 'R16 US Open, QF Atlanta, SF Eastbourne',          points: 935,   tour: 'ATP' },
  { rank: 44, name: 'Nuno Borges',             nationality: 'Portugal',     age: 28, hand: 'Right', coach: 'Frederico Marques',   bestSurface: 'Clay',   careerHigh: 32, recentResults: 'W Båstad, F Estoril, QF Hamburg',                points: 910,   tour: 'ATP' },
  { rank: 45, name: 'Quentin Halys',           nationality: 'France',       age: 28, hand: 'Right', coach: 'Olivier Chamfreau',   bestSurface: 'Indoor', careerHigh: 36, recentResults: 'QF Vienna, SF Stockholm, R16 Paris-Bercy',       points: 880,   tour: 'ATP' },
  { rank: 46, name: 'Adrian Mannarino',        nationality: 'France',       age: 37, hand: 'Left',  coach: 'Stéphane Robert',     bestSurface: 'Grass',  careerHigh: 17, recentResults: 'SF Auckland, QF Stuttgart, R16 Marseille',        points: 855,   tour: 'ATP' },
  { rank: 47, name: 'Alexandre Müller',        nationality: 'France',       age: 28, hand: 'Right', coach: 'Marc Barbier',        bestSurface: 'Hard',   careerHigh: 41, recentResults: 'F Hong Kong, QF Antwerp, R16 Geneva',             points: 825,   tour: 'ATP' },
  { rank: 48, name: 'Thiago Monteiro',         nationality: 'Brazil',       age: 31, hand: 'Left',  coach: 'Jaime Oncins',        bestSurface: 'Clay',   careerHigh: 39, recentResults: 'SF Bogotá, QF Cordoba, R16 Rio',                  points: 795,   tour: 'ATP' },
  { rank: 49, name: 'Marcos Giron',            nationality: 'United States', age: 32, hand: 'Right', coach: 'Karue Sell',          bestSurface: 'Hard',   careerHigh: 42, recentResults: 'QF Acapulco, R16 Indian Wells, SF Newport',       points: 775,   tour: 'ATP' },
  { rank: 50, name: 'Zizou Bergs',             nationality: 'Belgium',      age: 26, hand: 'Right', coach: 'Wim Fissette',        bestSurface: 'Hard',   careerHigh: 47, recentResults: 'W Antwerp Challenger, QF Eastbourne, SF Quimper',  points: 750,   tour: 'ATP' },
]

export const WTA_RANKINGS: RankingEntry[] = [
  { rank: 1,  name: 'Aryna Sabalenka',         nationality: 'Belarus',      age: 27, hand: 'Right', coach: 'Anton Dubrov',         bestSurface: 'Hard',  careerHigh: 1,  recentResults: 'W US Open, W Cincinnati, F Wimbledon',             points: 11055, tour: 'WTA' },
  { rank: 2,  name: 'Iga Świątek',             nationality: 'Poland',       age: 24, hand: 'Right', coach: 'Wim Fissette',         bestSurface: 'Clay',  careerHigh: 1,  recentResults: 'W Roland-Garros, W Madrid, SF Wimbledon',          points: 8895,  tour: 'WTA' },
  { rank: 3,  name: 'Coco Gauff',              nationality: 'United States', age: 21, hand: 'Right', coach: 'Matt Daly',            bestSurface: 'Hard',  careerHigh: 2,  recentResults: 'W WTA Finals, SF US Open, W Beijing',              points: 7830,  tour: 'WTA' },
  { rank: 4,  name: 'Jessica Pegula',          nationality: 'United States', age: 31, hand: 'Right', coach: 'Mark Knowles',         bestSurface: 'Hard',  careerHigh: 3,  recentResults: 'F US Open, SF Wimbledon, W Berlin',                points: 6555,  tour: 'WTA' },
  { rank: 5,  name: 'Elena Rybakina',          nationality: 'Kazakhstan',   age: 26, hand: 'Right', coach: 'Stefano Vukov',        bestSurface: 'Grass', careerHigh: 3,  recentResults: 'W Stuttgart, SF Wimbledon, F Brisbane',            points: 5870,  tour: 'WTA' },
  { rank: 6,  name: 'Jasmine Paolini',         nationality: 'Italy',        age: 29, hand: 'Right', coach: 'Renzo Furlan',         bestSurface: 'Clay',  careerHigh: 4,  recentResults: 'F Roland-Garros, F Wimbledon, SF Italian Open',    points: 5210,  tour: 'WTA' },
  { rank: 7,  name: 'Qinwen Zheng',            nationality: 'China',        age: 23, hand: 'Right', coach: 'Pere Riba',            bestSurface: 'Hard',  careerHigh: 5,  recentResults: 'F Australian Open, W Olympics, SF China Open',     points: 4715,  tour: 'WTA' },
  { rank: 8,  name: 'Mirra Andreeva',          nationality: 'Russia',       age: 18, hand: 'Right', coach: 'Conchita Martínez',    bestSurface: 'Hard',  careerHigh: 6,  recentResults: 'W Indian Wells, F Brisbane, SF Madrid',            points: 4380,  tour: 'WTA' },
  { rank: 9,  name: 'Emma Navarro',            nationality: 'United States', age: 24, hand: 'Right', coach: 'Peter Ayers',          bestSurface: 'Hard',  careerHigh: 8,  recentResults: 'SF Wimbledon, QF US Open, F Hobart',               points: 4055,  tour: 'WTA' },
  { rank: 10, name: 'Marketa Vondrousova',     nationality: 'Czechia',      age: 26, hand: 'Left',  coach: 'Jan Hernych',          bestSurface: 'Grass', careerHigh: 6,  recentResults: 'W Berlin, F Adelaide, SF Stuttgart',               points: 3760,  tour: 'WTA' },
  { rank: 11, name: 'Diana Shnaider',          nationality: 'Russia',       age: 21, hand: 'Left',  coach: 'Vladimir Platenik',    bestSurface: 'Hard',  careerHigh: 11, recentResults: 'W Hua Hin, F Tokyo, SF Toronto',                   points: 3490,  tour: 'WTA' },
  { rank: 12, name: 'Daria Kasatkina',         nationality: 'Russia',       age: 28, hand: 'Right', coach: 'Flavio Cipolla',       bestSurface: 'Clay',  careerHigh: 8,  recentResults: 'F Eastbourne, SF Roland-Garros, QF Madrid',        points: 3240,  tour: 'WTA' },
  { rank: 13, name: 'Anna Kalinskaya',         nationality: 'Russia',       age: 27, hand: 'Right', coach: 'Patricia Tarabini',    bestSurface: 'Hard',  careerHigh: 11, recentResults: 'F Berlin, SF Australian Open, QF Doha',            points: 2985,  tour: 'WTA' },
  { rank: 14, name: 'Beatriz Haddad Maia',     nationality: 'Brazil',       age: 29, hand: 'Left',  coach: 'Rafael Paciaroni',     bestSurface: 'Clay',  careerHigh: 10, recentResults: 'W Stuttgart, SF Roland-Garros, QF Wimbledon',     points: 2740,  tour: 'WTA' },
  { rank: 15, name: 'Madison Keys',            nationality: 'United States', age: 30, hand: 'Right', coach: 'Bjorn Fratangelo',     bestSurface: 'Hard',  careerHigh: 7,  recentResults: 'W Adelaide, F Brisbane, SF Cincinnati',            points: 2520,  tour: 'WTA' },
  { rank: 16, name: 'Liudmila Samsonova',      nationality: 'Russia',       age: 26, hand: 'Right', coach: 'Roman Salomatov',      bestSurface: 'Grass', careerHigh: 13, recentResults: 'W Washington, F Hertogenbosch, QF Tokyo',         points: 2390,  tour: 'WTA' },
  { rank: 17, name: 'Paula Badosa',            nationality: 'Spain',        age: 28, hand: 'Right', coach: 'Pol Toledo',           bestSurface: 'Hard',  careerHigh: 2,  recentResults: 'SF Australian Open, QF Cincinnati, R16 US Open',   points: 2240,  tour: 'WTA' },
  { rank: 18, name: 'Donna Vekić',             nationality: 'Croatia',      age: 29, hand: 'Right', coach: 'Pam Shriver',          bestSurface: 'Hard',  careerHigh: 14, recentResults: 'F Wimbledon, SF Olympics, QF Adelaide',            points: 2125,  tour: 'WTA' },
  { rank: 19, name: 'Magdalena Frech',         nationality: 'Poland',       age: 28, hand: 'Right', coach: 'Andrzej Kobierski',    bestSurface: 'Hard',  careerHigh: 18, recentResults: 'W Guadalajara, F Linz, SF Hua Hin',                points: 2010,  tour: 'WTA' },
  { rank: 20, name: 'Karolina Muchová',        nationality: 'Czechia',      age: 29, hand: 'Right', coach: 'Emil Miške',           bestSurface: 'Hard',  careerHigh: 8,  recentResults: 'SF US Open, QF Eastbourne, R16 Wimbledon',         points: 1925,  tour: 'WTA' },
  { rank: 21, name: 'Yulia Putintseva',        nationality: 'Kazakhstan',   age: 31, hand: 'Right', coach: 'Vincent Stéphan',      bestSurface: 'Hard',  careerHigh: 21, recentResults: 'W Birmingham, F Hertogenbosch, R16 Wimbledon',     points: 1855,  tour: 'WTA' },
  { rank: 22, name: 'Ekaterina Alexandrova',   nationality: 'Russia',       age: 30, hand: 'Right', coach: 'Andrey Vashinov',      bestSurface: 'Indoor', careerHigh: 15, recentResults: 'W Linz, F Tokyo, SF Cluj-Napoca',                  points: 1790,  tour: 'WTA' },
  { rank: 23, name: 'Leylah Fernandez',        nationality: 'Canada',       age: 23, hand: 'Left',  coach: 'Romain Deridder',      bestSurface: 'Hard',  careerHigh: 13, recentResults: 'W Hong Kong, F Washington, QF Cincinnati',         points: 1730,  tour: 'WTA' },
  { rank: 24, name: 'Anastasia Pavlyuchenkova', nationality: 'Russia',      age: 34, hand: 'Right', coach: 'Damir Grigorenco',     bestSurface: 'Clay',  careerHigh: 11, recentResults: 'QF Australian Open, R16 Roland-Garros, SF Linz',  points: 1665,  tour: 'WTA' },
  { rank: 25, name: 'Elina Svitolina',         nationality: 'Ukraine',      age: 31, hand: 'Right', coach: 'Andrew Bettles',       bestSurface: 'Clay',  careerHigh: 3,  recentResults: 'F Bad Homburg, SF Stuttgart, QF Wimbledon',        points: 1605,  tour: 'WTA' },
  { rank: 26, name: 'Veronika Kudermetova',    nationality: 'Russia',       age: 28, hand: 'Right', coach: 'Sergey Demekhine',     bestSurface: 'Hard',  careerHigh: 9,  recentResults: 'F Adelaide, SF Doha, R16 Roland-Garros',           points: 1540,  tour: 'WTA' },
  { rank: 27, name: 'Mirjam Björklund',        nationality: 'Sweden',       age: 26, hand: 'Right', coach: 'Pär Karlsson',         bestSurface: 'Clay',  careerHigh: 24, recentResults: 'W Båstad, F Reus, SF Tampere',                     points: 1480,  tour: 'WTA' },
  { rank: 28, name: 'Marta Kostyuk',           nationality: 'Ukraine',      age: 23, hand: 'Right', coach: 'Sandra Zaniewska',     bestSurface: 'Clay',  careerHigh: 17, recentResults: 'F San Diego, SF Stuttgart, QF Roland-Garros',     points: 1425,  tour: 'WTA' },
  { rank: 29, name: 'Elise Mertens',           nationality: 'Belgium',      age: 30, hand: 'Right', coach: 'Sébastien Wuilbaut',   bestSurface: 'Hard',  careerHigh: 12, recentResults: 'W Monastir, SF Hua Hin, R16 US Open',              points: 1370,  tour: 'WTA' },
  { rank: 30, name: 'Linda Nosková',           nationality: 'Czechia',      age: 21, hand: 'Right', coach: 'Tomáš Krupa',          bestSurface: 'Hard',  careerHigh: 22, recentResults: 'W Monterrey, F Auckland, SF Adelaide',             points: 1320,  tour: 'WTA' },
  { rank: 31, name: 'Dayana Yastremska',       nationality: 'Ukraine',      age: 25, hand: 'Right', coach: 'Sergiy Yastremskyy',   bestSurface: 'Hard',  careerHigh: 21, recentResults: 'SF Australian Open, QF Lyon, R16 Strasbourg',     points: 1265,  tour: 'WTA' },
  { rank: 32, name: 'Sofia Kenin',             nationality: 'United States', age: 27, hand: 'Right', coach: 'Alex Kenin',           bestSurface: 'Hard',  careerHigh: 4,  recentResults: 'QF Australian Open, R16 Indian Wells, SF San Diego', points: 1215, tour: 'WTA' },
  { rank: 33, name: 'Caroline Garcia',         nationality: 'France',       age: 32, hand: 'Right', coach: 'Bertrand Perret',      bestSurface: 'Hard',  careerHigh: 4,  recentResults: 'SF Doha, QF Lyon, R16 Roland-Garros',              points: 1170,  tour: 'WTA' },
  { rank: 34, name: 'Anhelina Kalinina',       nationality: 'Ukraine',      age: 28, hand: 'Right', coach: 'Vitaliy Maslyak',      bestSurface: 'Clay',  careerHigh: 25, recentResults: 'F Reus, SF Tampere, QF Hertogenbosch',             points: 1130,  tour: 'WTA' },
  { rank: 35, name: 'Clara Tauson',            nationality: 'Denmark',      age: 23, hand: 'Right', coach: 'Olivier Jeunehomme',   bestSurface: 'Hard',  careerHigh: 33, recentResults: 'W Auckland, F Linz, SF Hong Kong',                 points: 1085,  tour: 'WTA' },
  { rank: 36, name: 'Camila Osorio',           nationality: 'Colombia',     age: 23, hand: 'Right', coach: 'Ricardo Sánchez',      bestSurface: 'Clay',  careerHigh: 32, recentResults: 'W Bogotá, F Mérida, SF Cluj-Napoca',               points: 1040,  tour: 'WTA' },
  { rank: 37, name: 'Anna Bondár',             nationality: 'Hungary',      age: 28, hand: 'Right', coach: 'Pál Vekony',           bestSurface: 'Clay',  careerHigh: 35, recentResults: 'SF Bogotá, QF Madrid (Q), R16 Roland-Garros',      points: 1000,  tour: 'WTA' },
  { rank: 38, name: 'Sloane Stephens',         nationality: 'United States', age: 32, hand: 'Right', coach: 'Sven Groeneveld',      bestSurface: 'Hard',  careerHigh: 3,  recentResults: 'R16 US Open, QF Charleston, SF Bogotá',            points: 970,   tour: 'WTA' },
  { rank: 39, name: 'Magda Linette',           nationality: 'Poland',       age: 33, hand: 'Right', coach: 'Mark Gellard',         bestSurface: 'Hard',  careerHigh: 19, recentResults: 'F Hua Hin, SF Australian Open, R16 US Open',       points: 935,   tour: 'WTA' },
  { rank: 40, name: 'Tatjana Maria',           nationality: 'Germany',      age: 38, hand: 'Right', coach: 'Charles-Edouard Maria', bestSurface: 'Grass', careerHigh: 38, recentResults: 'SF Wimbledon, QF Bad Homburg, F Bogotá',           points: 905,   tour: 'WTA' },
  { rank: 41, name: 'Xinyu Wang',              nationality: 'China',        age: 24, hand: 'Right', coach: 'Yongli Zhao',          bestSurface: 'Hard',  careerHigh: 35, recentResults: 'W Hua Hin, F Hong Kong, SF Cleveland',             points: 875,   tour: 'WTA' },
  { rank: 42, name: 'Petra Martić',            nationality: 'Croatia',      age: 35, hand: 'Right', coach: 'Boris Bošnjaković',    bestSurface: 'Clay',  careerHigh: 14, recentResults: 'QF Madrid, R16 Roland-Garros, SF Lausanne',        points: 845,   tour: 'WTA' },
  { rank: 43, name: 'Yue Yuan',                nationality: 'China',        age: 27, hand: 'Right', coach: 'Bao Ying-Ying',        bestSurface: 'Hard',  careerHigh: 35, recentResults: 'W Austin, F Hong Kong, SF Tokyo',                  points: 815,   tour: 'WTA' },
  { rank: 44, name: 'Nadia Podoroska',         nationality: 'Argentina',    age: 28, hand: 'Right', coach: 'Manuel Hernández',     bestSurface: 'Clay',  careerHigh: 36, recentResults: 'F Mérida, SF Bogotá, R16 Roland-Garros',           points: 790,   tour: 'WTA' },
  { rank: 45, name: 'Iva Jović',               nationality: 'United States', age: 17, hand: 'Right', coach: 'Carlos Tarantino',     bestSurface: 'Hard',  careerHigh: 45, recentResults: 'QF US Open (Wildcard), SF Cleveland, R16 Linz',    points: 765,   tour: 'WTA' },
  { rank: 46, name: 'Zhuoxuan Bai',            nationality: 'China',        age: 24, hand: 'Right', coach: 'Jianhua Bai',          bestSurface: 'Clay',  careerHigh: 42, recentResults: 'W Guangzhou, F Suzhou, SF Tianjin',                points: 740,   tour: 'WTA' },
  { rank: 47, name: 'Lulu Sun',                nationality: 'New Zealand',  age: 24, hand: 'Right', coach: 'Greg Hutchinson',      bestSurface: 'Grass', careerHigh: 41, recentResults: 'QF Wimbledon, R16 Eastbourne, SF Birmingham',     points: 715,   tour: 'WTA' },
  { rank: 48, name: 'Mai Hontama',             nationality: 'Japan',        age: 26, hand: 'Right', coach: 'Naoko Hontama',        bestSurface: 'Hard',  careerHigh: 48, recentResults: 'W Tokyo Challenger, F Hua Hin Q, SF Osaka',         points: 690,   tour: 'WTA' },
  { rank: 49, name: 'Wang Xiyu',               nationality: 'China',        age: 24, hand: 'Right', coach: 'Liu Liang',            bestSurface: 'Hard',  careerHigh: 38, recentResults: 'SF Hong Kong, QF Tokyo, R16 Beijing',              points: 670,   tour: 'WTA' },
  { rank: 50, name: 'Olga Danilović',          nationality: 'Serbia',       age: 25, hand: 'Left',  coach: 'Predrag Rusevski',     bestSurface: 'Hard',  careerHigh: 33, recentResults: 'W Budapest, F Lausanne, SF Bogotá',                points: 650,   tour: 'WTA' },
]
