// NELI Pupils Data — extracted from neli-portal.jsx
export interface Pupil {
  id: number; name: string; dob: string; g: string; eal: boolean; fsm: boolean; is: number; es: number; neli: boolean;
  sen: { status: string; category: string; plan: string; ehcp: boolean; agencies: string[]; adjustments: string[] };
  attendance: number; neliWeek?: number; neliSessions?: number; neliExpected?: number; interventionist?: string;
  class: string; subscores?: { recVocab: number; expVocab: number; grammar: number; listening: number };
  notes: string; nextSteps?: string[];
}

export const PUPILS = [
  {id:1,  name:"Amara Johnson",    dob:"15/04/2020", g:"F", eal:false, fsm:true,  is:62,  es:80,  neli:true,
    sen:{status:"SEN Support", category:"Communication & Interaction", plan:"Speech & Language Referral in progress", ehcp:false, agencies:["SALT referral pending"], adjustments:["Visual timetable","Reduced group sizes","TA support in sessions"]},
    elgs:{la:["E","E"],psed:["E","E","E"],pd:["E","E"],lit:["E","E","E"],maths:["E","E"],utw:["E","E","E"],ead:["E","E"]},
    attendance:82, leuven:{wellbeing:2, involvement:2},
    subscores:{recVocab:58, expVocab:61, grammar:64, listening:65},
    notes:"Amara has made significant progress through the NELI intervention. She is growing in confidence but still requires targeted support in expressive language. Parents are engaged and supportive. SALT referral submitted October 2024.",
    nextSteps:["Continue NELI programme to Week 20","Follow up SALT referral","Introduce visual sentence starters","Weekly 1:1 reading with class teacher"],
    neliWeek:17, neliSessions:78, neliExpected:85, interventionist:"Mrs S. Mitchell",
    senDetail:{strategies:["SALT weekly sessions","Visual supports for tasks","Simplified instructions","Extra processing time"], saltReferral:true, saltDate:"Oct 2024", nextReview:"Apr 2025"},
    attendanceDetail:{missed:12, notes:"Several medical absences"},
    wellbeingDetail:{notes:"Settles better with familiar adults"},
    neliDetail:{sessionsThisWeek:2, expectedCompletion:"Jul 2025"},
    class:"A"},
  {id:2,  name:"Leon Carter",      dob:"02/09/2019", g:"M", eal:false, fsm:true,  is:71,  es:85,  neli:true,
    sen:{status:"Monitoring", category:"Communication & Interaction", plan:"Class-based monitoring", ehcp:false, agencies:[], adjustments:["Additional verbal prompts","Preferential seating"]},
    elgs:{la:["E","E"],psed:["E","E","E"],pd:["E","Ex"],lit:["E","E","E"],maths:["E","E"],utw:["Ex","E","E"],ead:["E","Ex"]},
    attendance:91, leuven:{wellbeing:3, involvement:3},
    subscores:{recVocab:68, expVocab:70, grammar:73, listening:74},
    notes:"Leon has shown steady improvement in group sessions. His listening skills have developed well. Behaviour in class has improved since starting NELI (teacher report).",
    nextSteps:["Monitor transition to Year 1","Consolidate vocabulary gains","Encourage story-telling at home (parent newsletter)"],
    neliWeek:17, neliSessions:82, neliExpected:85, interventionist:"Mrs S. Mitchell",
    senDetail:{strategies:["Check-ins at start of day","Quiet corner access","Emotion coaching"], saltReferral:false, nextReview:"May 2025"},
    attendanceDetail:{missed:5, notes:""},
    wellbeingDetail:{notes:""},
    neliDetail:{sessionsThisWeek:3, expectedCompletion:"Jul 2025"},
    class:"A"},
  {id:3,  name:"Fatima Al-Hassan", dob:"20/01/2020", g:"F", eal:true,  fsm:true,  is:74,  es:90,  neli:true,
    sen:{status:"EAL Monitoring", category:"EAL", plan:"EAL support plan", ehcp:false, agencies:["EAL Advisory Service"], adjustments:["Bilingual resources","Pre-teaching key vocabulary","Home-school language link"]},
    elgs:{la:["E","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","E"],lit:["E","E","E"],maths:["Ex","Ex"],utw:["Ex","Ex","E"],ead:["Ex","Ex"]},
    attendance:95, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:72, expVocab:71, grammar:76, listening:78},
    notes:"Fatima speaks Arabic at home (Moroccan dialect). Her English has developed remarkably well through NELI and strong family engagement. Her vocabulary acquisition rate is outstanding for an EAL learner.",
    nextSteps:["Celebrate progress with family","Monitor ELG outcomes in summer term","Continue bilingual story resources"],
    neliWeek:17, neliSessions:84, neliExpected:85, interventionist:"Mrs S. Mitchell", homeLanguage:"Arabic (Moroccan)", ealStage:"Developing",
    senDetail:{strategies:["Bilingual glossary","Peer buddy system","Pre-teaching vocabulary"], saltReferral:false, nextReview:"Jun 2025"},
    attendanceDetail:{missed:3, notes:""},
    wellbeingDetail:{notes:"Thriving, gaining confidence"},
    neliDetail:{sessionsThisWeek:3, expectedCompletion:"Jul 2025"},
    class:"A"},
  {id:4,  name:"Kai Murphy",       dob:"11/06/2020", g:"M", eal:false, fsm:true,  is:78,  es:89,  neli:true,
    sen:{status:"Monitoring", category:"Social, Emotional & Mental Health", plan:"Nurture group referral", ehcp:false, agencies:[], adjustments:["Calm corner access","Check-in/check-out","Consistent adult"]},
    elgs:{la:["E","E"],psed:["E","E","E"],pd:["Ex","Ex"],lit:["E","E","E"],maths:["E","Ex"],utw:["Ex","E","Ex"],ead:["Ex","Ex"]},
    attendance:88, leuven:{wellbeing:3, involvement:3},
    subscores:{recVocab:75, expVocab:77, grammar:79, listening:81},
    notes:"Kai has made good progress. SEMH monitoring in place following some early-year behaviour concerns. Nurture group has been beneficial. Language gains through NELI are strong.",
    nextSteps:["Continue nurture group","Transition planning with Y1 teacher","Parent review meeting in May"],
    neliWeek:17, neliSessions:76, neliExpected:85, interventionist:"Mr J. Okafor",
    senDetail:{strategies:["Chunked tasks","Concrete manipulatives","Reduced written demands"], saltReferral:false, nextReview:"May 2025"},
    attendanceDetail:{missed:7, notes:"Persistent lateness noted"},
    wellbeingDetail:{notes:""},
    neliDetail:{sessionsThisWeek:3, expectedCompletion:"Jul 2025"},
    class:"A"},
  {id:5,  name:"Zahra Patel",      dob:"03/03/2020", g:"F", eal:true,  fsm:false, is:79,  es:90,  neli:true,
    sen:{status:"None", category:"", plan:"", ehcp:false, agencies:[], adjustments:["Bilingual dictionaries available"]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["E","Ex","E"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:97, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:78, expVocab:76, grammar:81, listening:82},
    notes:"Zahra is a capable, confident learner. Gujarati spoken at home. Her English has developed strongly this year. NELI has helped consolidate narrative skills.",
    nextSteps:["Transition to Year 1 with positive profile","Share end-of-year data with parents"],
    neliWeek:17, neliSessions:83, neliExpected:85, interventionist:"Mr J. Okafor", homeLanguage:"Gujarati", ealStage:"Competent",
    senDetail:{strategies:[], saltReferral:false, nextReview:null},
    attendanceDetail:{missed:1, notes:""},
    wellbeingDetail:{notes:"Excellent engagement"},
    neliDetail:{sessionsThisWeek:3, expectedCompletion:"Jul 2025"},
    class:"A"},
  {id:6,  name:"Oliver Barnes",    dob:"18/08/2019", g:"M", eal:false, fsm:false, is:82,  es:87,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","E"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:94, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:80, expVocab:82, grammar:83, listening:83},
    notes:"Oliver is a confident communicator. Making good progress across all areas.",
    nextSteps:["Monitor end-of-year ELG outcomes"],
    class:"A"},
  {id:7,  name:"Priya Sharma",     dob:"22/11/2019", g:"F", eal:true,  fsm:false, is:85,  es:89,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:96, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:84, expVocab:83, grammar:86, listening:87},
    notes:"Priya is a highly capable learner. Punjabi spoken at home.",
    nextSteps:["End-of-year EYFS profile"],
    homeLanguage:"Punjabi", ealStage:"Fluent",
    class:"A"},
  {id:8,  name:"Mohammed Idris",   dob:"07/05/2020", g:"M", eal:true,  fsm:true,  is:86,  es:90,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","E"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:93, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:84, expVocab:85, grammar:87, listening:88},
    notes:"Mohammed is making excellent progress. Arabic and Somali spoken at home.",
    nextSteps:["End-of-year EYFS profile"],
    homeLanguage:"Arabic & Somali", ealStage:"Competent",
    class:"A"},
  {id:9,  name:"Imogen Clarke",    dob:"30/07/2020", g:"F", eal:false, fsm:false, is:87,  es:91,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:98, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:86, expVocab:87, grammar:88, listening:88},
    notes:"Imogen is a confident, articulate learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"A"},
  {id:10, name:"Samuel Green",     dob:"14/12/2019", g:"M", eal:false, fsm:false, is:88,  es:92,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:95, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:87, expVocab:87, grammar:89, listening:90},
    notes:"Samuel is making strong progress in all areas.",
    nextSteps:["End-of-year EYFS profile"],
    class:"A"},
  {id:11, name:"Isla Reid",        dob:"09/02/2020", g:"F", eal:false, fsm:false, is:89,  es:93,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:96, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:88, expVocab:89, grammar:90, listening:90},
    notes:"Isla is flourishing across all areas of the EYFS.",
    nextSteps:["End-of-year EYFS profile"],
    class:"A"},
  {id:12, name:"Noah Williams",    dob:"25/06/2020", g:"M", eal:false, fsm:false, is:90,  es:93,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:93, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:89, expVocab:90, grammar:91, listening:91},
    notes:"Noah is a confident communicator with strong literacy foundations.",
    nextSteps:["End-of-year EYFS profile"],
    class:"A"},
  {id:13, name:"Ruby Taylor",      dob:"18/04/2020", g:"F", eal:false, fsm:false, is:91,  es:95,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:97, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:90, expVocab:91, grammar:92, listening:92},
    notes:"Ruby is a highly motivated learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:14, name:"Aiden Walsh",      dob:"03/10/2019", g:"M", eal:false, fsm:false, is:92,  es:95,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:94, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:91, expVocab:91, grammar:93, listening:93},
    notes:"Aiden is making excellent all-round progress.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:15, name:"Sophia Patel",     dob:"12/01/2020", g:"F", eal:false, fsm:false, is:93,  es:96,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:98, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:92, expVocab:93, grammar:94, listening:94},
    notes:"Sophia is a highly capable learner making strong progress.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:16, name:"Ethan Brown",      dob:"28/07/2020", g:"M", eal:false, fsm:false, is:94,  es:97,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:95, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:93, expVocab:94, grammar:95, listening:95},
    notes:"Ethan is making strong progress across all areas.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:17, name:"Ananya Singh",     dob:"14/03/2020", g:"F", eal:true,  fsm:false, is:95,  es:98,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:97, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:94, expVocab:95, grammar:96, listening:96},
    notes:"Ananya is a high-attaining learner. Hindi spoken at home.",
    nextSteps:["End-of-year EYFS profile"],
    homeLanguage:"Hindi", ealStage:"Fluent",
    class:"B"},
  {id:18, name:"Joshua Adams",     dob:"05/11/2019", g:"M", eal:false, fsm:false, is:96,  es:99,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:96, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:95, expVocab:96, grammar:97, listening:97},
    notes:"Joshua is an enthusiastic and capable learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:19, name:"Lily Thompson",    dob:"22/08/2020", g:"F", eal:false, fsm:false, is:97,  es:100, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:98, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:96, expVocab:97, grammar:98, listening:98},
    notes:"Lily is flourishing and on track for GLD.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:20, name:"Dylan Morris",     dob:"11/05/2020", g:"M", eal:false, fsm:false, is:98,  es:101, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:94, leuven:{wellbeing:4, involvement:5},
    subscores:{recVocab:97, expVocab:98, grammar:99, listening:99},
    notes:"Dylan is making excellent progress.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:21, name:"Freya Jenkins",    dob:"16/02/2020", g:"F", eal:false, fsm:false, is:99,  es:102, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:97, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:98, expVocab:99, grammar:100, listening:100},
    notes:"Freya is an outstanding learner across all areas.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:22, name:"Thomas Evans",     dob:"08/09/2019", g:"M", eal:false, fsm:false, is:100, es:103, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:93, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:99, expVocab:100, grammar:101, listening:101},
    notes:"Thomas is a capable, well-rounded learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:23, name:"Mia Cooper",       dob:"27/06/2020", g:"F", eal:false, fsm:false, is:101, es:104, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:96, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:100, expVocab:101, grammar:102, listening:102},
    notes:"Mia is a confident and creative learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:24, name:"Hamza Osman",      dob:"19/04/2020", g:"M", eal:true,  fsm:false, is:103, es:106, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:95, leuven:{wellbeing:4, involvement:5},
    subscores:{recVocab:102, expVocab:103, grammar:104, listening:104},
    notes:"Hamza is making excellent progress. Somali spoken at home.",
    nextSteps:["End-of-year EYFS profile"],
    homeLanguage:"Somali", ealStage:"Developing",
    class:"B"},
  {id:25, name:"Grace Wilson",     dob:"30/10/2019", g:"F", eal:false, fsm:false, is:105, es:108, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:97, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:104, expVocab:105, grammar:106, listening:106},
    notes:"Grace is an outstanding communicator and learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:26, name:"Callum Fraser",    dob:"13/01/2020", g:"M", eal:false, fsm:false, is:108, es:111, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:96, leuven:{wellbeing:4, involvement:5},
    subscores:{recVocab:107, expVocab:108, grammar:109, listening:109},
    notes:"Callum is a highly capable learner with strong language skills.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:27, name:"Charlotte Davies", dob:"24/08/2020", g:"F", eal:false, fsm:false, is:112, es:115, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:98, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:111, expVocab:112, grammar:113, listening:113},
    notes:"Charlotte is an exceptional learner — top of the cohort.",
    nextSteps:["End-of-year EYFS profile","Discuss Year 1 enrichment provision"],
    class:"B"},
  {id:28, name:"Rory MacDonald",   dob:"17/03/2020", g:"M", eal:false, fsm:false, is:116, es:118, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:95, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:115, expVocab:116, grammar:117, listening:117},
    notes:"Rory has exceptional language skills — well above age-expected outcomes.",
    nextSteps:["End-of-year EYFS profile","Consider gifted & talented provision in Year 1"],
    class:"B"},
];
