'use client';

export const T = {
  sidebar:"#0C1A2E", sidebarHover:"#162540", sidebarActive:"#1E3561",
  sidebarText:"#8BA4C7",
  bg:"#F0EDE5", card:"#FFFFFF", border:"#E2DDD4",
  navy:"#1B3060", gold:"#C8960C", goldLight:"#FEF3C7",
  green:"#15803D", greenBg:"#DCFCE7",
  amber:"#B45309", amberBg:"#FFFBEB",
  red:"#B91C1C", redBg:"#FEF2F2",
  blue:"#1D4ED8", blueBg:"#EFF6FF",
  purple:"#7C3AED", purpleBg:"#F5F3FF",
  text:"#111827", muted:"#6B7280", light:"#F9FAFB",
};

// ─── DATA ─────────────────────────────────────────────

export const PUPILS = [
  {id:1,  name:"Amara Johnson",    dob:"15/04/2020", g:"F", eal:false, fsm:true,  is:62,  es:80,  neli:true,
    sen:{status:"SEN Support", category:"Communication & Interaction", plan:"Speech & Language Referral in progress", ehcp:false, agencies:["SALT referral pending"], adjustments:["Visual timetable","Reduced group sizes","TA support in sessions"]},
    elgs:{la:["E","E"],psed:["E","E","E"],pd:["E","E"],lit:["E","E","E"],maths:["E","E"],utw:["E","E","E"],ead:["E","E"]},
    attendance:82, leuven:{wellbeing:2, involvement:2},
    subscores:{recVocab:58, expVocab:61, grammar:64, listening:65},
    notes:"Amara has made significant progress through the NELI intervention. She is growing in confidence but still requires targeted support in expressive language. Parents are engaged and supportive. SALT referral submitted October 2024.",
    nextSteps:["Continue NELI programme to Week 20","Follow up SALT referral","Introduce visual sentence starters","Weekly 1:1 reading with class teacher"],
    neliWeek:17, neliSessions:78, neliExpected:85, interventionist:"Mrs S. Mitchell",
    senDetail:{strategies:["SALT weekly sessions","Visual supports for tasks","Simplified instructions","Extra processing time"], saltReferral:true, saltDate:"Oct 2024", nextReview:"Apr 2025"},
    attendanceDetail:{missed:12, notes:"Several medical absences"},
    wellbeingDetail:{notes:"Settles better with familiar adults"},
    neliDetail:{sessionsThisWeek:2, expectedCompletion:"Jul 2025"},
    class:"A"},
  {id:2,  name:"Leon Carter",      dob:"02/09/2019", g:"M", eal:false, fsm:true,  is:71,  es:85,  neli:true,
    sen:{status:"Monitoring", category:"Communication & Interaction", plan:"Class-based monitoring", ehcp:false, agencies:[], adjustments:["Additional verbal prompts","Preferential seating"]},
    elgs:{la:["E","E"],psed:["E","E","E"],pd:["E","Ex"],lit:["E","E","E"],maths:["E","E"],utw:["Ex","E","E"],ead:["E","Ex"]},
    attendance:91, leuven:{wellbeing:3, involvement:3},
    subscores:{recVocab:68, expVocab:70, grammar:73, listening:74},
    notes:"Leon has shown steady improvement in group sessions. His listening skills have developed well. Behaviour in class has improved since starting NELI (teacher report).",
    nextSteps:["Monitor transition to Year 1","Consolidate vocabulary gains","Encourage story-telling at home (parent newsletter)"],
    neliWeek:17, neliSessions:82, neliExpected:85, interventionist:"Mrs S. Mitchell",
    senDetail:{strategies:["Check-ins at start of day","Quiet corner access","Emotion coaching"], saltReferral:false, nextReview:"May 2025"},
    attendanceDetail:{missed:5, notes:""},
    wellbeingDetail:{notes:""},
    neliDetail:{sessionsThisWeek:3, expectedCompletion:"Jul 2025"},
    class:"A"},
  {id:3,  name:"Fatima Al-Hassan", dob:"20/01/2020", g:"F", eal:true,  fsm:true,  is:74,  es:90,  neli:true,
    sen:{status:"EAL Monitoring", category:"EAL", plan:"EAL support plan", ehcp:false, agencies:["EAL Advisory Service"], adjustments:["Bilingual resources","Pre-teaching key vocabulary","Home-school language link"]},
    elgs:{la:["E","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","E"],lit:["E","E","E"],maths:["Ex","Ex"],utw:["Ex","Ex","E"],ead:["Ex","Ex"]},
    attendance:95, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:72, expVocab:71, grammar:76, listening:78},
    notes:"Fatima speaks Arabic at home (Moroccan dialect). Her English has developed remarkably well through NELI and strong family engagement. Her vocabulary acquisition rate is outstanding for an EAL learner.",
    nextSteps:["Celebrate progress with family","Monitor ELG outcomes in summer term","Continue bilingual story resources"],
    neliWeek:17, neliSessions:84, neliExpected:85, interventionist:"Mrs S. Mitchell", homeLanguage:"Arabic (Moroccan)", ealStage:"Developing",
    senDetail:{strategies:["Bilingual glossary","Peer buddy system","Pre-teaching vocabulary"], saltReferral:false, nextReview:"Jun 2025"},
    attendanceDetail:{missed:3, notes:""},
    wellbeingDetail:{notes:"Thriving, gaining confidence"},
    neliDetail:{sessionsThisWeek:3, expectedCompletion:"Jul 2025"},
    class:"A"},
  {id:4,  name:"Kai Murphy",       dob:"11/06/2020", g:"M", eal:false, fsm:true,  is:78,  es:89,  neli:true,
    sen:{status:"Monitoring", category:"Social, Emotional & Mental Health", plan:"Nurture group referral", ehcp:false, agencies:[], adjustments:["Calm corner access","Check-in/check-out","Consistent adult"]},
    elgs:{la:["E","E"],psed:["E","E","E"],pd:["Ex","Ex"],lit:["E","E","E"],maths:["E","Ex"],utw:["Ex","E","Ex"],ead:["Ex","Ex"]},
    attendance:88, leuven:{wellbeing:3, involvement:3},
    subscores:{recVocab:75, expVocab:77, grammar:79, listening:81},
    notes:"Kai has made good progress. SEMH monitoring in place following some early-year behaviour concerns. Nurture group has been beneficial. Language gains through NELI are strong.",
    nextSteps:["Continue nurture group","Transition planning with Y1 teacher","Parent review meeting in May"],
    neliWeek:17, neliSessions:76, neliExpected:85, interventionist:"Mr J. Okafor",
    senDetail:{strategies:["Chunked tasks","Concrete manipulatives","Reduced written demands"], saltReferral:false, nextReview:"May 2025"},
    attendanceDetail:{missed:7, notes:"Persistent lateness noted"},
    wellbeingDetail:{notes:""},
    neliDetail:{sessionsThisWeek:3, expectedCompletion:"Jul 2025"},
    class:"A"},
  {id:5,  name:"Zahra Patel",      dob:"03/03/2020", g:"F", eal:true,  fsm:false, is:79,  es:90,  neli:true,
    sen:{status:"None", category:"", plan:"", ehcp:false, agencies:[], adjustments:["Bilingual dictionaries available"]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["E","Ex","E"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:97, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:78, expVocab:76, grammar:81, listening:82},
    notes:"Zahra is a capable, confident learner. Gujarati spoken at home. Her English has developed strongly this year. NELI has helped consolidate narrative skills.",
    nextSteps:["Transition to Year 1 with positive profile","Share end-of-year data with parents"],
    neliWeek:17, neliSessions:83, neliExpected:85, interventionist:"Mr J. Okafor", homeLanguage:"Gujarati", ealStage:"Competent",
    senDetail:{strategies:[], saltReferral:false, nextReview:null},
    attendanceDetail:{missed:1, notes:""},
    wellbeingDetail:{notes:"Excellent engagement"},
    neliDetail:{sessionsThisWeek:3, expectedCompletion:"Jul 2025"},
    class:"A"},
  {id:6,  name:"Oliver Barnes",    dob:"18/08/2019", g:"M", eal:false, fsm:false, is:82,  es:87,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","E"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:94, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:80, expVocab:82, grammar:83, listening:83},
    notes:"Oliver is a confident communicator. Making good progress across all areas.",
    nextSteps:["Monitor end-of-year ELG outcomes"],
    class:"A"},
  {id:7,  name:"Priya Sharma",     dob:"22/11/2019", g:"F", eal:true,  fsm:false, is:85,  es:89,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:96, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:84, expVocab:83, grammar:86, listening:87},
    notes:"Priya is a highly capable learner. Punjabi spoken at home.",
    nextSteps:["End-of-year EYFS profile"],
    homeLanguage:"Punjabi", ealStage:"Fluent",
    class:"A"},
  {id:8,  name:"Mohammed Idris",   dob:"07/05/2020", g:"M", eal:true,  fsm:true,  is:86,  es:90,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","E"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:93, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:84, expVocab:85, grammar:87, listening:88},
    notes:"Mohammed is making excellent progress. Arabic and Somali spoken at home.",
    nextSteps:["End-of-year EYFS profile"],
    homeLanguage:"Arabic & Somali", ealStage:"Competent",
    class:"A"},
  {id:9,  name:"Imogen Clarke",    dob:"30/07/2020", g:"F", eal:false, fsm:false, is:87,  es:91,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:98, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:86, expVocab:87, grammar:88, listening:88},
    notes:"Imogen is a confident, articulate learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"A"},
  {id:10, name:"Samuel Green",     dob:"14/12/2019", g:"M", eal:false, fsm:false, is:88,  es:92,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:95, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:87, expVocab:87, grammar:89, listening:90},
    notes:"Samuel is making strong progress in all areas.",
    nextSteps:["End-of-year EYFS profile"],
    class:"A"},
  {id:11, name:"Isla Reid",        dob:"09/02/2020", g:"F", eal:false, fsm:false, is:89,  es:93,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:96, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:88, expVocab:89, grammar:90, listening:90},
    notes:"Isla is flourishing across all areas of the EYFS.",
    nextSteps:["End-of-year EYFS profile"],
    class:"A"},
  {id:12, name:"Noah Williams",    dob:"25/06/2020", g:"M", eal:false, fsm:false, is:90,  es:93,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:93, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:89, expVocab:90, grammar:91, listening:91},
    notes:"Noah is a confident communicator with strong literacy foundations.",
    nextSteps:["End-of-year EYFS profile"],
    class:"A"},
  {id:13, name:"Ruby Taylor",      dob:"18/04/2020", g:"F", eal:false, fsm:false, is:91,  es:95,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:97, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:90, expVocab:91, grammar:92, listening:92},
    notes:"Ruby is a highly motivated learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:14, name:"Aiden Walsh",      dob:"03/10/2019", g:"M", eal:false, fsm:false, is:92,  es:95,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:94, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:91, expVocab:91, grammar:93, listening:93},
    notes:"Aiden is making excellent all-round progress.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:15, name:"Sophia Patel",     dob:"12/01/2020", g:"F", eal:false, fsm:false, is:93,  es:96,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:98, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:92, expVocab:93, grammar:94, listening:94},
    notes:"Sophia is a highly capable learner making strong progress.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:16, name:"Ethan Brown",      dob:"28/07/2020", g:"M", eal:false, fsm:false, is:94,  es:97,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:95, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:93, expVocab:94, grammar:95, listening:95},
    notes:"Ethan is making strong progress across all areas.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:17, name:"Ananya Singh",     dob:"14/03/2020", g:"F", eal:true,  fsm:false, is:95,  es:98,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:97, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:94, expVocab:95, grammar:96, listening:96},
    notes:"Ananya is a high-attaining learner. Hindi spoken at home.",
    nextSteps:["End-of-year EYFS profile"],
    homeLanguage:"Hindi", ealStage:"Fluent",
    class:"B"},
  {id:18, name:"Joshua Adams",     dob:"05/11/2019", g:"M", eal:false, fsm:false, is:96,  es:99,  neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:96, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:95, expVocab:96, grammar:97, listening:97},
    notes:"Joshua is an enthusiastic and capable learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:19, name:"Lily Thompson",    dob:"22/08/2020", g:"F", eal:false, fsm:false, is:97,  es:100, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:98, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:96, expVocab:97, grammar:98, listening:98},
    notes:"Lily is flourishing and on track for GLD.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:20, name:"Dylan Morris",     dob:"11/05/2020", g:"M", eal:false, fsm:false, is:98,  es:101, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:94, leuven:{wellbeing:4, involvement:5},
    subscores:{recVocab:97, expVocab:98, grammar:99, listening:99},
    notes:"Dylan is making excellent progress.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:21, name:"Freya Jenkins",    dob:"16/02/2020", g:"F", eal:false, fsm:false, is:99,  es:102, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:97, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:98, expVocab:99, grammar:100, listening:100},
    notes:"Freya is an outstanding learner across all areas.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:22, name:"Thomas Evans",     dob:"08/09/2019", g:"M", eal:false, fsm:false, is:100, es:103, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:93, leuven:{wellbeing:4, involvement:4},
    subscores:{recVocab:99, expVocab:100, grammar:101, listening:101},
    notes:"Thomas is a capable, well-rounded learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:23, name:"Mia Cooper",       dob:"27/06/2020", g:"F", eal:false, fsm:false, is:101, es:104, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:96, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:100, expVocab:101, grammar:102, listening:102},
    notes:"Mia is a confident and creative learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:24, name:"Hamza Osman",      dob:"19/04/2020", g:"M", eal:true,  fsm:false, is:103, es:106, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:95, leuven:{wellbeing:4, involvement:5},
    subscores:{recVocab:102, expVocab:103, grammar:104, listening:104},
    notes:"Hamza is making excellent progress. Somali spoken at home.",
    nextSteps:["End-of-year EYFS profile"],
    homeLanguage:"Somali", ealStage:"Developing",
    class:"B"},
  {id:25, name:"Grace Wilson",     dob:"30/10/2019", g:"F", eal:false, fsm:false, is:105, es:108, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:97, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:104, expVocab:105, grammar:106, listening:106},
    notes:"Grace is an outstanding communicator and learner.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:26, name:"Callum Fraser",    dob:"13/01/2020", g:"M", eal:false, fsm:false, is:108, es:111, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:96, leuven:{wellbeing:4, involvement:5},
    subscores:{recVocab:107, expVocab:108, grammar:109, listening:109},
    notes:"Callum is a highly capable learner with strong language skills.",
    nextSteps:["End-of-year EYFS profile"],
    class:"B"},
  {id:27, name:"Charlotte Davies", dob:"24/08/2020", g:"F", eal:false, fsm:false, is:112, es:115, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:98, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:111, expVocab:112, grammar:113, listening:113},
    notes:"Charlotte is an exceptional learner — top of the cohort.",
    nextSteps:["End-of-year EYFS profile","Discuss Year 1 enrichment provision"],
    class:"B"},
  {id:28, name:"Rory MacDonald",   dob:"17/03/2020", g:"M", eal:false, fsm:false, is:116, es:118, neli:false,
    sen:{status:"None",category:"",plan:"",ehcp:false,agencies:[],adjustments:[]},
    elgs:{la:["Ex","Ex"],psed:["Ex","Ex","Ex"],pd:["Ex","Ex"],lit:["Ex","Ex","Ex"],maths:["Ex","Ex"],utw:["Ex","Ex","Ex"],ead:["Ex","Ex"]},
    attendance:95, leuven:{wellbeing:5, involvement:5},
    subscores:{recVocab:115, expVocab:116, grammar:117, listening:117},
    notes:"Rory has exceptional language skills — well above age-expected outcomes.",
    nextSteps:["End-of-year EYFS profile","Consider gifted & talented provision in Year 1"],
    class:"B"},
];

export const CLASSES = [
  {id:"A", name:"Reception A", teacher:"Miss H. Thompson", ta:"Mrs J. Okafor", room:"Room 1"},
  {id:"B", name:"Reception B", teacher:"Mrs S. Ahmed", ta:"Mr D. Chen", room:"Room 2"},
];

export const TRUST = [
  {id:1, name:"Parkside Primary",       short:"PP", pupils:28, neli:5, avgI:91.2, avgE:96.8, assessed:100, weeks:16, status:"good"},
  {id:2, name:"Riverside Academy",      short:"RA", pupils:31, neli:6, avgI:88.7, avgE:94.8, assessed:100, weeks:15, status:"good"},
  {id:3, name:"Greenfields Primary",    short:"GP", pupils:24, neli:5, avgI:90.4, avgE:null,  assessed:83,  weeks:16, status:"warning"},
  {id:4, name:"Hillside Infant School", short:"HI", pupils:19, neli:5, avgI:86.1, avgE:null,  assessed:100, weeks:8,  status:"alert"},
];

export const STAFF = [
  {name:"Sarah Mitchell", role:"TA – NELI Lead",    c1:true,  c2:true,  c3:true},
  {name:"James Okafor",   role:"Teaching Assistant", c1:true,  c2:true,  c3:false},
  {name:"Hannah Brooks",  role:"Reception Teacher",  c1:true,  c2:false, c3:false},
  {name:"David Chen",     role:"SENCO",              c1:true,  c2:true,  c3:true},
];

export const ELG_AREAS = [
  {key:"la",  label:"Communication & Language", short:"C&L", prime:true,  goals:["Listening, Attention & Understanding","Speaking"]},
  {key:"psed",label:"Personal, Social & Emotional", short:"PSED", prime:true, goals:["Self-Regulation","Managing Self","Building Relationships"]},
  {key:"pd",  label:"Physical Development", short:"PD", prime:true,  goals:["Gross Motor Skills","Fine Motor Skills"]},
  {key:"lit", label:"Literacy",          short:"Lit", prime:false, goals:["Comprehension","Word Reading","Writing"]},
  {key:"maths",label:"Mathematics",     short:"Maths",prime:false, goals:["Number","Numerical Patterns"]},
  {key:"utw", label:"Understanding the World",short:"UTW",prime:false, goals:["Past & Present","People, Culture & Communities","The Natural World"]},
  {key:"ead", label:"Expressive Arts & Design",short:"EAD",prime:false, goals:["Creating with Materials","Being Imaginative & Expressive"]},
];

export const ALERTS = [
  {msg:"Hillside Infant at week 8 — behind schedule",type:"red"},
  {msg:"Greenfields: 4 pupils not yet assessed",type:"amber"},
  {msg:"End-year reassessment due in 8 weeks",type:"amber"},
  {msg:"Course 3 outstanding for James Okafor",type:"amber"},
];

// ─── HELPERS ──────────────────────────────────────────

export const getLight = (s: number) => s < 85 ? "red" : s < 96 ? "amber" : "green";
export const lc = (l: string) => l==="red" ? T.red : l==="amber" ? T.amber : T.green;
export const lb = (l: string) => l==="red" ? T.redBg : l==="amber" ? T.amberBg : T.greenBg;
export const ll = (l: string) => l==="red" ? "Needs Support" : l==="amber" ? "Monitor" : "On Track";

export const neliPupils = PUPILS.filter(p => p.neli);
export const neliAvgGain = Math.round(neliPupils.reduce((s,p)=>s+(p.es-p.is),0)/neliPupils.length*10)/10;
export const classAvgI = Math.round(PUPILS.reduce((s,p)=>s+p.is,0)/PUPILS.length*10)/10;
export const classAvgE = Math.round(PUPILS.reduce((s,p)=>s+p.es,0)/PUPILS.length*10)/10;
export const redC = PUPILS.filter(p=>getLight(p.is)==="red").length;
export const ambC = PUPILS.filter(p=>getLight(p.is)==="amber").length;
export const grnC = PUPILS.filter(p=>getLight(p.is)==="green").length;

export const elgScore = (p: any) => {
  const all = [...p.elgs.la,...p.elgs.psed,...p.elgs.pd,...p.elgs.lit,...p.elgs.maths,...p.elgs.utw,...p.elgs.ead];
  const exp = all.filter((v: string)=>v==="Ex").length;
  return {total:all.length, expected:exp, gld: [...p.elgs.la,...p.elgs.psed,...p.elgs.pd,...p.elgs.lit,...p.elgs.maths].every((v: string)=>v==="Ex")};
};

export const LeuvLabel = (n: number) => ["","Very Low","Low","Moderate","High","Very High"][n];
export const LeuvColor = (n: number) => [T.red,T.red,T.amber,T.amber,T.green,T.green][n];

export const FL_COURSES = [
  {
    id:1,
    title:"NELI Course 1: Language Fundamentals",
    provider:"OxEd and Assessment",
    providerLogo:"OxEd",
    desc:"Enhance your understanding of oral language, why good language skills are so important and how NELI supports their development.",
    duration:"4–5 hours",
    weeks:3,
    level:"Introductory",
    type:"Course",
    status:"in-progress",
    progress:60,
    required:true,
    reqFor:"All NELI staff",
    url:"https://www.futurelearn.com/courses/neli-language-fundamentals",
    topics:["What is oral language?","Why language skills matter","How NELI was developed","The evidence behind NELI","Language development milestones","Identifying language difficulties"],
    imgBg:"#1B5E20",
    imgEmoji:"\u{1F469}\u200D\u{1F467}\u200D\u{1F466}",
  },
  {
    id:2,
    title:"NELI Course 2: Delivering the Programme",
    provider:"OxEd and Assessment",
    providerLogo:"OxEd",
    desc:"Presents details of the NELI programme structure — how to plan and deliver group and individual sessions, and key strategies to support language skills.",
    duration:"4–5 hours",
    weeks:3,
    level:"Intermediate",
    type:"Course",
    status:"not-started",
    progress:0,
    required:true,
    reqFor:"All NELI staff",
    url:"https://www.futurelearn.com/courses/neli-delivering-programme",
    topics:["Programme structure & timeline","Group session delivery","Individual session delivery","Special Words vocabulary","Narrative & storytelling skills","Using the Ted puppet"],
    imgBg:"#1A237E",
    imgEmoji:"\u{1F4DA}",
  },
  {
    id:3,
    title:"NELI Course 3: Phonics & Phonological Awareness",
    provider:"OxEd and Assessment",
    providerLogo:"OxEd",
    desc:"Essential training for delivering the second 10 weeks of NELI, covering phonological awareness and early letter-sound knowledge.",
    duration:"2–3 hours",
    weeks:2,
    level:"Intermediate",
    type:"Course",
    status:"not-started",
    progress:0,
    required:false,
    reqFor:"NELI TAs only",
    url:"https://www.futurelearn.com/courses/neli-phonics",
    topics:["What is phonological awareness?","Rhyme & alliteration activities","Phoneme identification","Letter-sound knowledge","Blending & segmenting","Links to early reading"],
    imgBg:"#B71C1C",
    imgEmoji:"\u{1F524}",
  },
  {
    id:4,
    title:"The Nuffield Early Language Intervention: Language Fundamentals — Training Course 1 of 3",
    provider:"The Department of Education, University of Oxford",
    providerLogo:"UoO",
    desc:"Enhance your understanding of oral language, why good language skills are so important and how NELI supports their development.",
    duration:"4–5 hours",
    weeks:3,
    level:"Introductory",
    type:"Course",
    status:"in-progress",
    progress:45,
    required:false,
    reqFor:"Oxford version",
    url:"https://www.futurelearn.com/courses/nuffield-early-language-intervention",
    topics:["University of Oxford research context","Language development science","NELI's evidence base","Oral language & literacy","Randomised controlled trials","Programme outcomes"],
    imgBg:"#004B87",
    imgEmoji:"\u{1F393}",
  },
  {
    id:5,
    title:"Language Fundamentals (US)",
    provider:"OxEd and Assessment",
    providerLogo:"OxEd",
    desc:"Enhance your understanding of oral language, why good language skills are so important and how TEL Ted supports their development.",
    duration:"4–5 hours",
    weeks:3,
    level:"Introductory",
    type:"Course",
    status:"not-started",
    progress:0,
    required:false,
    reqFor:"US schools",
    url:"https://www.futurelearn.com/courses/language-fundamentals-us",
    topics:["Oral language in US schools","Language development research","TEL Ted programme structure","Adapting NELI for US context","Assessment approaches","Family engagement strategies"],
    imgBg:"#1B3060",
    imgEmoji:"\u{1F1FA}\u{1F1F8}",
  },
  {
    id:6,
    title:"TEL Ted Support Hub",
    provider:"OxEd and Assessment",
    providerLogo:"OxEd",
    desc:"Look for information, ask questions, share tips and discuss TEL Ted with your fellow practitioners. A community space for NELI practitioners.",
    duration:"Ongoing",
    weeks:0,
    level:"All levels",
    type:"Community Hub",
    status:"enrolled",
    progress:100,
    required:false,
    reqFor:"All staff",
    url:"https://www.futurelearn.com/courses/tel-ted-support-hub",
    topics:["Community discussions","Practitioner Q&A","Sharing best practice","Expert mentor support","Weekly webinars","Resource library"],
    imgBg:"#E65100",
    imgEmoji:"\u{1F9F8}",
  },
  {
    id:7,
    title:"NELI Delivery Support Hub",
    provider:"OxEd and Assessment",
    providerLogo:"OxEd",
    desc:"Access additional materials, ask questions and connect with mentors throughout your NELI delivery. Available throughout the programme.",
    duration:"Ongoing",
    weeks:0,
    level:"All levels",
    type:"Support Hub",
    status:"enrolled",
    progress:100,
    required:true,
    reqFor:"All NELI staff",
    url:"https://www.futurelearn.com/courses/neli-delivery-support",
    topics:["Programme FAQ","Mentor support","Peer discussion forums","Webinar recordings","Midpoint review guidance","End-of-year guidance"],
    imgBg:"#4A148C",
    imgEmoji:"\u{1F4AC}",
  },
];

export const statusStyles: Record<string, {label:string, color:string, bg:string}> = {
  "in-progress": {label:"In Progress",   color:"#1D4ED8", bg:"#EFF6FF"},
  "not-started": {label:"Not Started",   color:"#6B7280", bg:"#F9FAFB"},
  "enrolled":    {label:"Enrolled",      color:"#15803D", bg:"#DCFCE7"},
  "completed":   {label:"Completed",     color:"#15803D", bg:"#DCFCE7"},
};

export const NAV = [
  {id:"dashboard",     label:"Dashboard"},
  {id:"languagescreen",label:"LanguageScreen"},
  {id:"intervention",  label:"NELI Tracker"},
  {id:"classes",       label:"Classes"},
  {id:"insights",      label:"Insights"},
  {id:"trust",         label:"Trust View"},
  {id:"training",      label:"Training"},
  {id:"telted",        label:"TEL TED Training"},
  {id:"resources",     label:"Resources"},
];

export const STEPS: any[][] = [
  // Week 1
  [
    {title:"Welcome to the Course",type:"Article",content:[
      {type:"text",value:"Welcome to Course 1 of the NELI training programme, developed by Professor Charles Hulme and Dr Gillian West at the University of Oxford."},
      {type:"text",value:"This course will take approximately 4\u20135 hours to complete across three weeks. You can work through it at your own pace \u2014 it will always pick up where you left off."},
      {type:"heading",value:"By the end of this course you will:"},
      {type:"list",items:["Understand why oral language skills are critical for children's development","Know how to identify children who need language support using LanguageScreen","Be ready to support the NELI programme in your school"]},
      {type:"text",value:"This course has been certified by the CPD Certification Service."},
      {type:"video",caption:"Dr Gillian West, NELI Developer, introduces Course 1 (3 mins)"},
    ]},
    {title:"Why Oral Language Matters",type:"Article",content:[
      {type:"heading",value:"Why Oral Language Skills Are So Important"},
      {type:"text",value:"Oral language skills form the foundation of all learning. Children who start school with language weaknesses are at significant risk of:"},
      {type:"list",items:["Reading and writing difficulties","Maths underperformance","Social and emotional difficulties","Lower educational attainment overall"]},
      {type:"text",value:"Research from the University of Oxford shows that 1 in 5 children starts school with language skills below age-expected levels. For children from disadvantaged backgrounds, this rises to 1 in 3."},
      {type:"text",value:"The good news? Language skills are highly responsive to targeted intervention. The NELI programme has been shown in four randomised controlled trials to produce significant improvements \u2014 with children making 3\u20135 months additional progress in just 20 weeks."},
      {type:"discussion",prompt:"\uD83D\uDCAC Discussion: Think about your Reception class. How many children do you think might have language weaknesses? Share your thoughts with your fellow practitioners."},
    ]},
    {title:"The Components of Oral Language",type:"Article",content:[
      {type:"heading",value:"What Is Language?"},
      {type:"text",value:"Language is made up of several interconnected components. LanguageScreen assesses four key areas:"},
      {type:"diagram",items:[
        {name:"Receptive Vocabulary",desc:"Understanding the meaning of words. Children hear a word and identify the correct picture.",icon:"\uD83D\uDD35",color:T.blue},
        {name:"Expressive Vocabulary",desc:"Using words to express ideas. Children name objects or describe pictures.",icon:"\uD83D\uDFE1",color:T.gold},
        {name:"Grammar",desc:"Understanding and using sentence structure. Children repeat sentences of increasing complexity.",icon:"\uD83D\uDFE2",color:T.green},
        {name:"Listening Comprehension",desc:"Understanding spoken language in context. Children listen to a passage and answer questions.",icon:"\uD83D\uDFE3",color:T.purple},
      ]},
      {type:"text",value:"Children who score below 85 on LanguageScreen are identified as potentially needing additional language support."},
    ]},
    {title:"Quiz: Week 1 Check",type:"Quiz",quiz:[
      {q:"What proportion of children start school with language skills below age-expected levels?",options:["1 in 10","1 in 5","1 in 3","1 in 2"],correct:1,explanation:"Research shows 1 in 5 children (20%) start school with below-expected language skills."},
      {q:"Which of the following is NOT assessed by LanguageScreen?",options:["Receptive vocabulary","Phonological awareness","Grammar","Listening comprehension"],correct:1,explanation:"LanguageScreen assesses receptive vocab, expressive vocab, grammar, and listening. Phonological awareness is covered in NELI Part 2."},
      {q:"How many weeks does the NELI programme last?",options:["10 weeks","15 weeks","20 weeks","30 weeks"],correct:2,explanation:"NELI is a 20-week programme split into Part 1 (weeks 1\u201310) and Part 2 (weeks 11\u201320)."},
      {q:"What LanguageScreen score indicates a child may need additional support?",options:["Below 100","Below 90","Below 85","Below 80"],correct:2,explanation:"A standard score below 85 (1 SD below the mean) indicates a child who may benefit from additional language support."},
    ]},
  ],
  // Week 2
  [
    {title:"What is LanguageScreen?",type:"Article",content:[
      {type:"heading",value:"Introducing LanguageScreen"},
      {type:"text",value:"LanguageScreen is an app-based language assessment developed by OxEd & Assessment, a University of Oxford spinout company. It was standardised on approximately 350,000 children aged 3;6 to 8;11."},
      {type:"heading",value:"Key features:"},
      {type:"list",items:["Takes 10\u201312 minutes per child","Administered by any school adult \u2014 no specialist training required","Automatically scored \u2014 no manual marking","Four subtests: Receptive Vocab, Expressive Vocab, Grammar, Listening","Provides a standardised score (average = 100, typical range 85\u2013115)","Scores below 85 indicate children who may benefit from NELI"]},
      {type:"text",value:"LanguageScreen has excellent reliability (Cronbach\u2019s \u03b1 = .92) and has been validated against established clinical language assessments."},
      {type:"video",caption:"Demonstration of LanguageScreen in use (5 mins)"},
    ]},
    {title:"Administering LanguageScreen",type:"Article",content:[
      {type:"heading",value:"Step by Step"},
      {type:"steps",items:[
        {icon:"\uD83D\uDCF1",text:"Open the LanguageScreen app on a tablet or computer"},
        {icon:"\uD83D\uDC64",text:"Log in with your school credentials"},
        {icon:"\uD83D\uDCCB",text:"Select the child from your class list"},
        {icon:"\uD83C\uDFAF",text:"Ensure the child can see the screen clearly"},
        {icon:"\uD83D\uDDE3\uFE0F",text:"Read the instructions aloud as prompted by the app"},
        {icon:"\u2705",text:"The app scores automatically \u2014 no action needed"},
        {icon:"\uD83D\uDCCA",text:"Review results in the portal immediately after"},
      ]},
      {type:"tips",title:"\uD83D\uDCA1 Tips for a successful assessment:",items:["Find a quiet space away from distractions","Sit beside the child, not opposite","Reassure the child \u2014 'there are no wrong answers'","Allow plenty of time \u2014 don't rush","Assess each child individually, not in groups"]},
    ]},
    {title:"Understanding Scores",type:"Article",content:[
      {type:"heading",value:"Interpreting LanguageScreen Scores"},
      {type:"table",headers:["Score","Band","Meaning"],rows:[
        ["115+","Well above average","Exceeds age expectations"],
        ["100\u2013114","Above average","Meeting expectations comfortably"],
        ["85\u201399","Average","Within typical range"],
        ["75\u201384","Below average","May benefit from Whole Class NELI"],
        ["Below 75","Well below average","Strong candidate for NELI intervention"],
      ]},
      {type:"slider"},
    ]},
    {title:"Quiz: Week 2 Check",type:"Quiz",quiz:[
      {q:"How long does a LanguageScreen assessment take per child?",options:["5 minutes","10\u201312 minutes","20 minutes","30 minutes"],correct:1,explanation:"LanguageScreen takes approximately 10\u201312 minutes per child."},
      {q:"Who can administer LanguageScreen?",options:["Only qualified SaLTs","Only class teachers","Any trained school adult","Only NELI leads"],correct:2,explanation:"Any school adult can administer LanguageScreen \u2014 no specialist training is required."},
      {q:"A child scores 78 on LanguageScreen. What does this indicate?",options:["Well above average","Average","Below average \u2014 may benefit from Whole Class NELI","Well below average \u2014 strong candidate for NELI"],correct:2,explanation:"A score of 78 falls in the 75\u201384 band: below average, may benefit from Whole Class NELI."},
      {q:"Approximately how many children was LanguageScreen standardised on?",options:["10,000","50,000","350,000","1,000,000"],correct:2,explanation:"LanguageScreen was standardised on approximately 350,000 children."},
    ]},
  ],
  // Week 3
  [
    {title:"The NELI Programme",type:"Article",content:[
      {type:"heading",value:"NELI: What, Who and How"},
      {type:"text",value:"NELI is a 20-week oral language intervention programme delivered by trained teaching assistants to small groups of Reception children who have been identified as having language weaknesses."},
      {type:"heading",value:"Programme structure:"},
      {type:"list",items:["Part 1 (Weeks 1\u201310): Group and individual sessions, vocabulary and narrative","Part 2 (Weeks 11\u201320): Adds letter sounds and phonological awareness"]},
      {type:"heading",value:"Each week includes:"},
      {type:"list",items:["3 \u00d7 Group Sessions (20 minutes each) \u2014 up to 6 children","1\u20132 \u00d7 Individual Sessions (10 minutes each) \u2014 one child at a time"]},
      {type:"heading",value:"Key activities each week:"},
      {type:"list",items:["\uD83D\uDCDA Special Words \u2014 3\u20134 new vocabulary words introduced and practised","\uD83E\uDD81 Story activities \u2014 narrative skills through picture books and story cards","\uD83D\uDC42 Listening activities \u2014 attention and listening exercises","\uD83D\uDD24 Part 2: Letter sounds and phonological awareness activities"]},
      {type:"video",caption:"Overview of a NELI Group Session (4 mins)"},
    ]},
    {title:"Supporting Children in NELI",type:"Article",content:[
      {type:"heading",value:"How to Support NELI Children Effectively"},
      {type:"text",value:"As a NELI practitioner, your relationship with the children is key. Here are the principles that underpin effective NELI delivery:"},
      {type:"list",items:[
        "\uD83C\uDF1F Positive reinforcement \u2014 Use the Best Listener Board and stickers. Children thrive on encouragement.",
        "\uD83D\uDDE3\uFE0F Modelling language \u2014 Always model Special Words in full sentences. Expand: 'dog run' \u2192 'The dog is running fast!'",
        "\uD83D\uDCD6 Repeated exposure \u2014 Words are revisited across sessions. Children need 10\u201315 exposures to acquire a new word.",
        "\uD83D\uDC68\u200D\uD83D\uDC69\u200D\uD83D\uDC67 Involving parents \u2014 Share Special Words weekly so children hear them at home too.",
        "\u23F1\uFE0F Consistency \u2014 Deliver sessions consistently \u2014 same time, same place each week.",
      ]},
    ]},
    {title:"Final Assessment",type:"Quiz",quiz:[
      {q:"How many weeks does the NELI programme run?",options:["10 weeks","15 weeks","20 weeks","30 weeks"],correct:2,explanation:"NELI runs for 20 weeks."},
      {q:"How many children can be in a NELI group session?",options:["2","Up to 6","Up to 10","The whole class"],correct:1,explanation:"NELI group sessions have up to 6 children."},
      {q:"When does Part 2 of NELI begin?",options:["Week 5","Week 8","Week 11","Week 15"],correct:2,explanation:"Part 2 begins at Week 11."},
      {q:"What are 'Special Words' in NELI?",options:["Sight words for reading","New vocabulary words introduced each week","Phonics sounds","Spelling words"],correct:1,explanation:"Special Words are 3\u20134 new vocabulary words introduced and practised each week."},
      {q:"Which of the following is NOT a core activity in NELI?",options:["Vocabulary activities","Narrative/story activities","Silent reading","Listening activities"],correct:2,explanation:"Silent reading is not part of NELI. The programme focuses on oral language: vocabulary, narrative, and listening."},
    ]},
    {title:"Certificate of Completion",type:"Article",certificate:true,content:[]},
  ],
];
