export type SportFeature = {
  id: string
  label: string
  icon: string
  group: string
  defaultOn: boolean
}

export const SPORT_FEATURES: Record<string, SportFeature[]> = {
  darts: [
    { id: 'dashboard', label: 'Dashboard', icon: '📊', group: 'OVERVIEW', defaultOn: true },
    { id: 'morning', label: 'Morning Briefing', icon: '☀️', group: 'OVERVIEW', defaultOn: true },
    { id: 'performance', label: 'Performance', icon: '📈', group: 'PERFORMANCE', defaultOn: true },
    { id: 'dartcam', label: 'Dart Cam & Analytics', icon: '🎥', group: 'PERFORMANCE', defaultOn: false },
    { id: 'practice', label: 'Practice Tracker', icon: '🎯', group: 'PERFORMANCE', defaultOn: true },
    { id: 'schedule', label: 'Tournament Schedule', icon: '📅', group: 'MATCH', defaultOn: true },
    { id: 'live-scores', label: 'Live Scores', icon: '🔴', group: 'MATCH', defaultOn: true },
    { id: 'draw-bracket', label: 'Draw & Bracket', icon: '🏆', group: 'MATCH', defaultOn: false },
    { id: 'match-prep', label: 'Match Prep', icon: '🧠', group: 'MATCH', defaultOn: true },
    { id: 'opponentintel', label: 'Opponent Intel', icon: '🔍', group: 'MATCH', defaultOn: true },
    { id: 'teamhub', label: 'Team Hub', icon: '👥', group: 'TEAM', defaultOn: true },
    { id: 'physio-recovery', label: 'Physio', icon: '🏥', group: 'TEAM', defaultOn: true },
    { id: 'mental', label: 'Mental Performance', icon: '🧘', group: 'TEAM', defaultOn: false },
    { id: 'walk-on-music', label: 'Walk-on Music', icon: '🎵', group: 'TEAM', defaultOn: false },
    { id: 'nutrition-log', label: 'Nutrition', icon: '🥗', group: 'TEAM', defaultOn: false },
    { id: 'team-comms', label: 'Team Comms', icon: '💬', group: 'TEAM', defaultOn: true },
    { id: 'fan-engagement', label: 'Fan Engagement', icon: '⭐', group: 'TEAM', defaultOn: false },
    { id: 'sponsorship', label: 'Sponsorship', icon: '💼', group: 'COMMERCIAL', defaultOn: true },
    { id: 'exhibitions', label: 'Exhibitions', icon: '🎪', group: 'COMMERCIAL', defaultOn: false },
    { id: 'media', label: 'Media Manager', icon: '📱', group: 'COMMERCIAL', defaultOn: false },
    { id: 'financial', label: 'Financial', icon: '💰', group: 'COMMERCIAL', defaultOn: true },
    { id: 'agent', label: 'Agent Pipeline', icon: '🤝', group: 'COMMERCIAL', defaultOn: false },
    { id: 'travel', label: 'Smart Flights & Hotels', icon: '✈️', group: 'TOOLS', defaultOn: true },
    { id: 'tourcard', label: 'Tour Card', icon: '🃏', group: 'TOOLS', defaultOn: true },
    { id: 'equipment', label: 'Equipment', icon: '🎯', group: 'TOOLS', defaultOn: false },
    { id: 'career', label: 'Career Planning', icon: '🗺️', group: 'TOOLS', defaultOn: true },
    { id: 'datahub', label: 'Data Hub', icon: '📊', group: 'TOOLS', defaultOn: false },
    { id: 'findpro', label: 'Find a Pro', icon: '🔍', group: 'TOOLS', defaultOn: false },
  ],
  tennis: [
    { id: 'dashboard', label: 'Dashboard', icon: '📊', group: 'OVERVIEW', defaultOn: true },
    { id: 'morning', label: 'Morning Briefing', icon: '☀️', group: 'OVERVIEW', defaultOn: true },
    { id: 'performance', label: 'Performance', icon: '📈', group: 'PERFORMANCE', defaultOn: true },
    { id: 'gpsvideo', label: 'GPS & Video', icon: '🎥', group: 'PERFORMANCE', defaultOn: false },
    { id: 'schedule', label: 'Tournament Schedule', icon: '📅', group: 'MATCH', defaultOn: true },
    { id: 'livescores', label: 'Live Scores', icon: '🔴', group: 'MATCH', defaultOn: true },
    { id: 'matchprep', label: 'Match Prep', icon: '🧠', group: 'MATCH', defaultOn: true },
    { id: 'scout', label: 'Opponent Scout', icon: '🔍', group: 'MATCH', defaultOn: true },
    { id: 'draw', label: 'Draw & Bracket', icon: '🏆', group: 'MATCH', defaultOn: false },
    { id: 'team', label: 'Team Hub', icon: '👥', group: 'TEAM', defaultOn: true },
    { id: 'physio', label: 'Physio', icon: '🏥', group: 'TEAM', defaultOn: true },
    { id: 'nutrition', label: 'Nutrition', icon: '🥗', group: 'TEAM', defaultOn: false },
    { id: 'racket', label: 'Racket & Strings', icon: '🎾', group: 'TEAM', defaultOn: false },
    { id: 'mental', label: 'Mental Performance', icon: '🧘', group: 'TEAM', defaultOn: false },
    { id: 'travel', label: 'Travel', icon: '✈️', group: 'TEAM', defaultOn: true },
    { id: 'partners', label: 'Playing Partners', icon: '🤝', group: 'TEAM', defaultOn: false },
    { id: 'doubles', label: 'Doubles', icon: '👫', group: 'TEAM', defaultOn: false },
    { id: 'teamcomms', label: 'Team Comms', icon: '💬', group: 'TEAM', defaultOn: true },
    { id: 'sponsorship', label: 'Sponsorship', icon: '💼', group: 'COMMERCIAL', defaultOn: true },
    { id: 'financial', label: 'Financial', icon: '💰', group: 'COMMERCIAL', defaultOn: true },
    { id: 'media', label: 'Media Manager', icon: '📱', group: 'COMMERCIAL', defaultOn: false },
    { id: 'exhibition', label: 'Exhibitions', icon: '🎪', group: 'COMMERCIAL', defaultOn: false },
    { id: 'pipeline', label: 'Agent Pipeline', icon: '🤝', group: 'COMMERCIAL', defaultOn: false },
    { id: 'prizeforecast', label: 'Prize Forecaster', icon: '🏆', group: 'COMMERCIAL', defaultOn: false },
    { id: 'entries', label: 'Entry Manager', icon: '📋', group: 'TOOLS', defaultOn: true },
    { id: 'career', label: 'Career Planning', icon: '🗺️', group: 'TOOLS', defaultOn: true },
    { id: 'academy', label: 'Academy', icon: '🎓', group: 'TOOLS', defaultOn: false },
    { id: 'datahub', label: 'Data Hub', icon: '📊', group: 'TOOLS', defaultOn: false },
    { id: 'courtbooking', label: 'Court Booking', icon: '🏟️', group: 'TOOLS', defaultOn: false },
    { id: 'federation', label: 'Federation', icon: '🏛️', group: 'TOOLS', defaultOn: false },
    { id: 'accreditations', label: 'Accreditations', icon: '📜', group: 'TOOLS', defaultOn: false },
    { id: 'playerdirectory', label: 'Player Directory', icon: '👥', group: 'TOOLS', defaultOn: false },
    { id: 'coachfinder', label: 'Coach Finder', icon: '🎓', group: 'TOOLS', defaultOn: false },
  ],
  golf: [
    { id: 'dashboard', label: 'Dashboard', icon: '📊', group: 'OVERVIEW', defaultOn: true },
    { id: 'morning', label: 'Morning Briefing', icon: '☀️', group: 'OVERVIEW', defaultOn: true },
    { id: 'owgr', label: 'OWGR Ranking', icon: '🏆', group: 'PERFORMANCE', defaultOn: true },
    { id: 'schedule', label: 'Tournament Schedule', icon: '📅', group: 'PERFORMANCE', defaultOn: true },
    { id: 'strokes', label: 'Strokes Gained', icon: '📈', group: 'PERFORMANCE', defaultOn: true },
    { id: 'coursefit', label: 'Course Fit', icon: '⛳', group: 'PERFORMANCE', defaultOn: true },
    { id: 'matchprep', label: 'Round Prep', icon: '🧠', group: 'PERFORMANCE', defaultOn: true },
    { id: 'practicelog', label: 'Practice Log', icon: '📝', group: 'PERFORMANCE', defaultOn: false },
    { id: 'team', label: 'Team Hub', icon: '👥', group: 'TEAM', defaultOn: true },
    { id: 'caddie', label: 'Caddie', icon: '🎒', group: 'TEAM', defaultOn: true },
    { id: 'physio', label: 'Physio', icon: '🏥', group: 'TEAM', defaultOn: true },
    { id: 'equipment', label: 'Equipment', icon: '🏌️', group: 'TEAM', defaultOn: false },
    { id: 'mental', label: 'Mental Performance', icon: '🧘', group: 'TEAM', defaultOn: false },
    { id: 'sponsorship', label: 'Sponsorship', icon: '💼', group: 'COMMERCIAL', defaultOn: true },
    { id: 'media', label: 'Media Manager', icon: '📱', group: 'COMMERCIAL', defaultOn: false },
    { id: 'financial', label: 'Financial', icon: '💰', group: 'COMMERCIAL', defaultOn: true },
    { id: 'proam', label: 'Pro-Am', icon: '🤝', group: 'COMMERCIAL', defaultOn: false },
    { id: 'agent', label: 'Agent Pipeline', icon: '🤝', group: 'COMMERCIAL', defaultOn: false },
    { id: 'travel', label: 'Smart Flights & Hotels', icon: '✈️', group: 'TOOLS', defaultOn: true },
    { id: 'exemptions', label: 'Exemptions', icon: '📋', group: 'TOOLS', defaultOn: false },
    { id: 'qualifying', label: 'Q-School', icon: '🎓', group: 'TOOLS', defaultOn: false },
    { id: 'career', label: 'Career Planning', icon: '🗺️', group: 'TOOLS', defaultOn: true },
    { id: 'video', label: 'Video Library', icon: '🎥', group: 'TOOLS', defaultOn: false },
    { id: 'findpro', label: 'Find a Pro', icon: '🔍', group: 'TOOLS', defaultOn: false },
    { id: 'arccos', label: 'Arccos', icon: '📡', group: 'INTEGRATIONS', defaultOn: false },
    { id: 'datagolf', label: 'DataGolf', icon: '📊', group: 'INTEGRATIONS', defaultOn: false },
    { id: 'trackman', label: 'TrackMan', icon: '📡', group: 'INTEGRATIONS', defaultOn: false },
  ],
  boxing: [
    { id: 'camp', label: 'Camp Dashboard', icon: '📊', group: 'OVERVIEW', defaultOn: true },
    { id: 'training', label: 'Training Log', icon: '📝', group: 'FIGHT CAMP', defaultOn: true },
    { id: 'sparring', label: 'Sparring', icon: '🥊', group: 'FIGHT CAMP', defaultOn: true },
    { id: 'opposition', label: 'Opposition Scout', icon: '🔍', group: 'FIGHT CAMP', defaultOn: true },
    { id: 'fight-night', label: 'Fight Night', icon: '🌙', group: 'FIGHT CAMP', defaultOn: true },
    { id: 'punchanalytics', label: 'Punch Analytics', icon: '📊', group: 'FIGHT CAMP', defaultOn: false },
    { id: 'gpsringheatmap', label: 'GPS Ring Heatmap', icon: '🗺️', group: 'FIGHT CAMP', defaultOn: false },
    { id: 'fightcamp', label: 'Fight Camp Mode', icon: '⚡', group: 'FIGHT CAMP', defaultOn: true },
    { id: 'weight', label: 'Weight Tracker', icon: '⚖️', group: 'WEIGHT & HEALTH', defaultOn: true },
    { id: 'cut', label: 'Cut Planner', icon: '📉', group: 'WEIGHT & HEALTH', defaultOn: true },
    { id: 'recovery', label: 'Recovery & HRV', icon: '❤️', group: 'WEIGHT & HEALTH', defaultOn: false },
    { id: 'medical', label: 'Medical Record', icon: '🏥', group: 'WEIGHT & HEALTH', defaultOn: true },
    { id: 'teamoverview', label: 'Team Overview', icon: '👥', group: 'TEAM HUB', defaultOn: true },
    { id: 'briefing', label: 'Fighter Briefing', icon: '📋', group: 'TEAM HUB', defaultOn: true },
    { id: 'trainernotes', label: 'Trainer Notes', icon: '📝', group: 'TEAM HUB', defaultOn: false },
    { id: 'managerdash', label: 'Manager Dashboard', icon: '💼', group: 'TEAM HUB', defaultOn: false },
    { id: 'rankings', label: 'World Rankings', icon: '🏆', group: 'RANKINGS', defaultOn: true },
    { id: 'mandatory', label: 'Mandatory Challengers', icon: '⚠️', group: 'RANKINGS', defaultOn: false },
    { id: 'pathtotitle', label: 'Path to Title', icon: '🗺️', group: 'RANKINGS', defaultOn: true },
    { id: 'pursebid', label: 'Purse Bid', icon: '💰', group: 'RANKINGS', defaultOn: false },
    { id: 'career', label: 'Career Planning', icon: '🗺️', group: 'RANKINGS', defaultOn: true },
    { id: 'sponsorships', label: 'Sponsorships', icon: '💼', group: 'COMMERCIAL', defaultOn: true },
    { id: 'media', label: 'Media', icon: '📱', group: 'COMMERCIAL', defaultOn: false },
    { id: 'appearances', label: 'Appearances', icon: '🎪', group: 'COMMERCIAL', defaultOn: false },
    { id: 'contracts', label: 'Contract Tracker', icon: '📄', group: 'COMMERCIAL', defaultOn: true },
    { id: 'pursesim', label: 'Purse Simulator', icon: '💰', group: 'FINANCIALS', defaultOn: true },
    { id: 'earnings', label: 'Fight Earnings', icon: '💵', group: 'FINANCIALS', defaultOn: true },
    { id: 'campcosts', label: 'Camp Costs', icon: '📊', group: 'FINANCIALS', defaultOn: false },
    { id: 'tax', label: 'Tax Tracker', icon: '🧾', group: 'FINANCIALS', defaultOn: false },
    { id: 'fightrecord', label: 'Fight Record', icon: '📜', group: 'CAREER', defaultOn: true },
    { id: 'careerstats', label: 'Career Stats', icon: '📊', group: 'CAREER', defaultOn: true },
    { id: 'promoterpipeline', label: 'Promoter Pipeline', icon: '🤝', group: 'CAREER', defaultOn: false },
    { id: 'agentintel', label: 'Agent Intel', icon: '🕵️', group: 'CAREER', defaultOn: false },
    { id: 'aibriefing', label: 'AI Morning Briefing', icon: '☀️', group: 'INTEL', defaultOn: true },
    { id: 'opscout', label: 'Opposition Scout', icon: '🎯', group: 'INTEL', defaultOn: false },
    { id: 'broadcast', label: 'Broadcast Tracker', icon: '📺', group: 'INTEL', defaultOn: false },
    { id: 'news', label: 'Industry News', icon: '📰', group: 'INTEL', defaultOn: false },
    { id: 'gps', label: 'GPS Load Monitor', icon: '📡', group: 'INTEGRATIONS', defaultOn: false },
    { id: 'gpsvest', label: 'GPS Vest', icon: '🦺', group: 'INTEGRATIONS', defaultOn: false },
    { id: 'findpro', label: 'Find a Pro', icon: '🔍', group: 'INTEGRATIONS', defaultOn: false },
  ],
}

export const ALWAYS_ON = ['dashboard', 'camp', 'settings']
